// This file is generated by dmc. DO NOT EDIT.

export interface TocItem { title: string; url: string; items: TocItem[] }
export interface Metadata { readingTime: number; wordCount: number }
export interface BaseCollection {
  body: string
  content: string
  excerpt: string
  metadata: Metadata
  toc: TocItem[]
  contentType: string
  flattenedPath: string
  permalink: string
  slug: string
  sourceFileDir: string
  sourceFileName: string
  sourceFilePath: string
  html?: string
}
export interface DocCollection extends BaseCollection { [frontmatterField: string]: unknown }

export interface DocsCollection extends BaseCollection {
  title: string
  description?: string
  date?: string
  draft?: boolean
  tags?: string[]
  author?: {
    name: string
    url?: string
  }
}
export declare const docs: DocsCollection[]

