/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function compile(source: string): any
/**
 * Render a LaTeX fragment to KaTeX HTML via the embedded KaTeX engine.
 * Output matches the JS chain `rehype-katex` byte-for-byte. Pair with
 * the standard `katex.min.css` for glyph rendering.
 */
export declare function latexToHtml(latex: string, display: boolean): string
export declare function compileMany(sources: Array<string>): Array<any>
export interface CollectionInput {
  name: string
  pattern: string
  baseDir: string
  schema?: any
  single?: boolean
}
export interface BuildInput {
  outputDir: string
  collections: Array<CollectionInput>
  root?: string
  strict?: boolean
  clean?: boolean
  outputAssets?: string
  outputBase?: string
  outputName?: string
  outputFormat?: string
  markdownRemarkPlugins?: any
  markdownRehypePlugins?: any
  mdxRemarkPlugins?: any
  mdxRehypePlugins?: any
  copyLinkedFiles?: boolean
  mdxOutputFormat?: string
  mdxMinify?: boolean
  markdownGfm?: boolean
  includeHtml?: boolean
  cacheEnabled?: boolean
  /**
   * Bypass the plugin gate for every plugin: every JS plugin runs
   * in the sidecar, every native transformer is dropped.
   */
  forceSidecar?: boolean
  /**
   * Per-plugin sidecar preference. Names listed here run in the
   * sidecar; the matching native transformer is dropped from the
   * pipeline. Names dmc recognises:
   *   "remark-gfm", "remark-math", "remark-emoji",
   *   "rehype-pretty-code", "shiki",
   *   "rehype-katex", "rehype-mathjax",
   *   "rehype-slug", "rehype-autolink-headings"
   */
  preferSidecar?: Array<string>
}
export interface BuildReport {
  diagnostics: Array<string>
}
export declare function build(input: BuildInput): BuildReport
