/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function compile(source: string): any
/**
 * Render a LaTeX fragment to KaTeX HTML via the embedded KaTeX engine.
 * Output matches the JS chain `rehype-katex` byte-for-byte. Pair with
 * the standard `katex.min.css` for glyph rendering.
 */
export declare function latexToHtml(latex: string, display: boolean): string
export declare function compileMany(sources: Array<string>): Array<any>
export interface CollectionInput {
  name: string
  pattern: string
  baseDir: string
  schema?: any
  single?: boolean
}
export interface BuildInput {
  outputDir: string
  collections: Array<CollectionInput>
  root?: string
  strict?: boolean
  clean?: boolean
  outputAssets?: string
  outputBase?: string
  outputName?: string
  outputFormat?: string
  markdownRemarkPlugins?: any
  markdownRehypePlugins?: any
  mdxRemarkPlugins?: any
  mdxRehypePlugins?: any
  copyLinkedFiles?: boolean
  mdxOutputFormat?: string
  mdxMinify?: boolean
  markdownGfm?: boolean
  includeHtml?: boolean
  cacheEnabled?: boolean
}
export interface BuildReport {
  diagnostics: Array<string>
}
export declare function build(input: BuildInput): BuildReport
