/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function compile(source: string): any
export declare function compileMany(sources: Array<string>): Array<any>
export interface CollectionInput {
  name: string
  pattern: string
  baseDir: string
  schema?: any
  single?: boolean
}
export interface BuildInput {
  outputDir: string
  collections: Array<CollectionInput>
  root?: string
  strict?: boolean
  clean?: boolean
  outputAssets?: string
  outputBase?: string
  outputName?: string
  outputFormat?: string
  markdownRemarkPlugins?: any
  markdownRehypePlugins?: any
  mdxRemarkPlugins?: any
  mdxRehypePlugins?: any
}
export interface BuildCollectionReport {
  name: string
  records: number
  outputPath: string
}
export interface BuildErrorReport {
  file: string
  message: string
}
export interface BuildReport {
  collections: Array<BuildCollectionReport>
  errors: Array<BuildErrorReport>
}
export declare function build(input: BuildInput): BuildReport
