/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compile a single MDX source string. Returns the full CompileOutput as a JS object:
 * { body, content, html, excerpt, metadata, toc, frontmatter, frontmatter_raw, imports, exports }
 * Field names are snake_case (matching serde Serialize on the Rust struct).
 */
export declare function compile(source: string): any
export interface CollectionInput {
  name: string
  pattern: string
  baseDir: string
}
export interface BuildInput {
  outputDir: string
  collections: Array<CollectionInput>
}
export interface BuildCollectionReport {
  name: string
  records: number
  outputPath: string
}
export interface BuildReport {
  collections: Array<BuildCollectionReport>
}
/**
 * Run the full engine: walk globs, compile each MDX file, write velite-shape JSON.
 * Equivalent to `duck-md build` CLI but driven by a JS object — no toml needed.
 */
export declare function build(input: BuildInput): BuildReport
