<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectTo</key>
    <array>
      <string>text.html.derivative</string>
      <string>text.html.derivative.ng</string>
      <string>source.ts.ng</string>
    </array>
    <key>injectionSelector</key>
    <string>L:text.html -comment</string>
    <key>name</key>
    <string>angular-template</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#interpolation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>interpolation</key>
      <dict>
        <key>begin</key>
        <string>\{\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.ts</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>expression.ng</string>
        <key>end</key>
        <string>}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>template.ng</string>
  </dict>
</plist>