<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectTo</key>
    <array>
      <string>text.html.derivative</string>
      <string>text.html.derivative.ng</string>
      <string>source.ts.ng</string>
    </array>
    <key>injectionSelector</key>
    <string>L:text.html -comment -expression.ng -meta.tag -source.css -source.js</string>
    <key>name</key>
    <string>angular-let-declaration</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#letDeclaration</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>letDeclaration</key>
      <dict>
        <key>begin</key>
        <string>(@let)\s+([$_[:alpha:]][$_[:alnum:]]*)\s*(=)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.ng</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.ng</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ng</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=;)</string>
        <key>name</key>
        <string>meta.definition.variable.ng</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#letInitializer</string>
          </dict>
        </array>
      </dict>
      <key>letInitializer</key>
      <dict>
        <key>begin</key>
        <string>\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ng</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>meta.definition.variable.initializer.ng</string>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.ng</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>template.let.ng</string>
  </dict>
</plist>