<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectTo</key>
    <array>
      <string>source.ts.ng</string>
    </array>
    <key>injectionSelector</key>
    <string>L:meta.decorator.ts -comment -text.html</string>
    <key>name</key>
    <string>angular-inline-template</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#inlineTemplate</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>inlineTemplate</key>
      <dict>
        <key>begin</key>
        <string>(template)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.object-literal.key.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.object-literal.key.ts punctuation.separator.key-value.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[,}])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tsParenExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ngTemplate</string>
          </dict>
        </array>
      </dict>
      <key>ngTemplate</key>
      <dict>
        <key>begin</key>
        <string>\G\s*(["'`|])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.html.derivative.ng</string>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.html.derivative.ng</string>
          </dict>
          <dict>
            <key>include</key>
            <string>template.ng</string>
          </dict>
        </array>
      </dict>
      <key>tsParenExpression</key>
      <dict>
        <key>begin</key>
        <string>\G\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tsParenExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ngTemplate</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>inline-template.ng</string>
  </dict>
</plist>