<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectTo</key>
    <array>
      <string>text.html.derivative</string>
      <string>text.html.derivative.ng</string>
      <string>source.ts.ng</string>
    </array>
    <key>injectionSelector</key>
    <string>L:text.html -comment -expression.ng -meta.tag -source.css -source.js</string>
    <key>name</key>
    <string>angular-template-blocks</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#block</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>block</key>
      <dict>
        <key>begin</key>
        <string>(@)(if|else if|else|defer|placeholder|loading|error|switch|case|default|for|empty)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.block.kind.ng</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>name</key>
        <string>control.block.ng</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blockExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockBody</string>
          </dict>
        </array>
      </dict>
      <key>blockBody</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.ts</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>control.block.body.ng</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.html.derivative.ng</string>
          </dict>
          <dict>
            <key>include</key>
            <string>template.ng</string>
          </dict>
        </array>
      </dict>
      <key>blockExpression</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>control.block.expression.ng</string>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blockExpressionOfClause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockExpressionLetBinding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockExpressionTrackClause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
      <key>blockExpressionLetBinding</key>
      <dict>
        <key>begin</key>
        <string>\blet\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>storage.type.ng</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[$)])|(?&lt;=;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
      <key>blockExpressionOfClause</key>
      <dict>
        <key>begin</key>
        <string>([$_[:alpha:]][$_[:alnum:]]*)\s+(of)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.ng</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.expression.of.ng</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[$)])|(?&lt;=;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
      <key>blockExpressionTrackClause</key>
      <dict>
        <key>begin</key>
        <string>\btrack\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.track.ng</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[$)])|(?&lt;=;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>expression.ng</string>
          </dict>
        </array>
      </dict>
      <key>transition</key>
      <dict>
        <key>match</key>
        <string>@</string>
        <key>name</key>
        <string>keyword.control.block.transition.ng</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>template.blocks.ng</string>
  </dict>
</plist>