<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>conf</string>
      <string>CONF</string>
      <string>envvars</string>
      <string>htaccess</string>
      <string>HTACCESS</string>
      <string>htgroups</string>
      <string>HTGROUPS</string>
      <string>htpasswd</string>
      <string>HTPASSWD</string>
      <string>.htaccess</string>
      <string>.HTACCESS</string>
      <string>.htgroups</string>
      <string>.HTGROUPS</string>
      <string>.htpasswd</string>
      <string>.HTPASSWD</string>
    </array>
    <key>name</key>
    <string>apache</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(\s)*(#).*$\n?</string>
        <key>name</key>
        <string>comment.line.hash.ini</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.apacheconf</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.tag.apacheconf</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>string.value.apacheconf</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(&lt;)(Proxy|ProxyMatch|IfVersion|Directory|DirectoryMatch|Files|FilesMatch|IfDefine|IfModule|Limit|LimitExcept|Location|LocationMatch|VirtualHost|Macro|If|Else|ElseIf)(\s(.+?))?(&gt;)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.apacheconf</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.tag.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(&lt;/)(Proxy|ProxyMatch|IfVersion|Directory|DirectoryMatch|Files|FilesMatch|IfDefine|IfModule|Limit|LimitExcept|Location|LocationMatch|VirtualHost|Macro|If|Else|ElseIf)(&gt;)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.regexp.apacheconf</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>string.replacement.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;=(Rewrite(Rule|Cond)))\s+(.+?)\s+(.+?)($|\s)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.status.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.regexp.apacheconf</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;=RedirectMatch)(\s+(\d\d\d|permanent|temp|seeother|gone))?\s+(.+?)\s+((.+?)($|\s))?</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.status.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;=Redirect)(\s+(\d\d\d|permanent|temp|seeother|gone))?\s+(.+?)\s+((.+?)($|\s))?</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.regexp.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;=(?:Script|)AliasMatch)\s+(.+?)\s+((.+?)\s)?</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.path.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;=RedirectPermanent|RedirectTemp|ScriptAlias|Alias)\s+(.+?)\s+((.+?)($|\s))?</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.core.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AcceptPathInfo|AccessFileName|AddDefaultCharset|AddOutputFilterByType|AllowEncodedSlashes|AllowOverride|AuthName|AuthType|CGIMapExtension|ContentDigest|DefaultType|Define|DocumentRoot|EnableMMAP|EnableSendfile|ErrorDocument|ErrorLog|FileETag|ForceType|HostnameLookups|IdentityCheck|Include(Optional)?|KeepAlive|KeepAliveTimeout|LimitInternalRecursion|LimitRequestBody|LimitRequestFields|LimitRequestFieldSize|LimitRequestLine|LimitXMLRequestBody|LogLevel|MaxKeepAliveRequests|Mutex|NameVirtualHost|Options|Require|RLimitCPU|RLimitMEM|RLimitNPROC|Satisfy|ScriptInterpreterSource|ServerAdmin|ServerAlias|ServerName|ServerPath|ServerRoot|ServerSignature|ServerTokens|SetHandler|SetInputFilter|SetOutputFilter|Time([Oo])ut|TraceEnable|UseCanonicalName|Use|ErrorLogFormat|GlobalLog|PHPIniDir|SSLHonorCipherOrder|SSLCompression|SSLUseStapling|SSLStapling\w+|SSLCARevocationCheck|SSLSRPVerifierFile|SSLSessionTickets|RequestReadTimeout|ProxyHTML\w+|MaxRanges)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.mpm.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AcceptMutex|AssignUserID|BS2000Account|ChildPerUserID|CoreDumpDirectory|EnableExceptionHook|Group|Listen|ListenBacklog|LockFile|MaxClients|MaxConnectionsPerChild|MaxMemFree|MaxRequestsPerChild|MaxRequestsPerThread|MaxRequestWorkers|MaxSpareServers|MaxSpareThreads|MaxThreads|MaxThreadsPerChild|MinSpareServers|MinSpareThreads|NumServers|PidFile|ReceiveBufferSize|ScoreBoardFile|SendBufferSize|ServerLimit|StartServers|StartThreads|ThreadLimit|ThreadsPerChild|ThreadStackSize|User|Win32DisableAcceptEx)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.access.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Allow|Deny|Order)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.actions.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Action|Script)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.alias.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Alias|AliasMatch|Redirect|RedirectMatch|RedirectPermanent|RedirectTemp|ScriptAlias|ScriptAliasMatch)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.auth.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Auth(?:Authoritative|GroupFile|UserFile|BasicProvider|BasicFake|BasicAuthoritative|BasicUseDigestAlgorithm))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.auth_anon.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Anonymous(?:|_Authoritative|_LogEmail|_MustGiveEmail|_NoUserID|_VerifyEmail))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.auth_dbm.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AuthDBM(?:Authoritative|GroupFile|Type|UserFile))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.auth_digest.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AuthDigest(?:Algorithm|Domain|File|GroupFile|NcCheck|NonceFormat|NonceLifetime|Qop|ShmemSize|Provider))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.auth_ldap.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AuthLDAP(?:Authoritative|BindDN|BindPassword|CharsetConfig|CompareDNOnServer|DereferenceAliases|Enabled|FrontPageHack|GroupAttribute|GroupAttributeIsDN|RemoteUserIsDN|Url))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.autoindex.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AddAlt|AddAltByEncoding|AddAltByType|AddDescription|AddIcon|AddIconByEncoding|AddIconByType|DefaultIcon|HeaderName|IndexIgnore|IndexOptions|IndexOrderDefault|IndexStyleSheet|IndexHeadInsert|ReadmeName)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.filter.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Balancer(?:Member|Growth|Persist|Inherit))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.cache.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Cache(?:DefaultExpire|Disable|Enable|ForceCompletion|IgnoreCacheControl|IgnoreHeaders|IgnoreNoLastMod|LastModifiedFactor|MaxExpire))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.cern_meta.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Meta(?:Dir|Files|Suffix))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.cgi.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(ScriptLog(?:|Buffer|Length))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.cgid.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Script(?:Log|LogBuffer|LogLength|Sock))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.charset_lite.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Charset(?:Default|Options|SourceEnc))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.dav.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Dav(?:|DepthInfinity|MinTimeout|LockDB))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.deflate.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Deflate(?:BufferSize|CompressionLevel|FilterNote|MemLevel|WindowSize))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.dir.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(DirectoryIndex|DirectorySlash|FallbackResource)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.disk_cache.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Cache(?:DirLength|DirLevels|ExpiryCheck|GcClean|GcDaily|GcInterval|GcMemUsage|GcUnused|MaxFileSize|MinFileSize|Root|Size|TimeMargin))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.dumpio.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(DumpIO(?:In|Out)put)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.env.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((?:Pass|Set|Unset)Env)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.expires.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Expires(?:Active|ByType|Default))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.ext_filter.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(ExtFilter(?:Define|Options))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.file_cache.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((?:Cache|MMap)File)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.filter.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AddOutputFilterByType|FilterChain|FilterDeclare|FilterProtocol|FilterProvider|FilterTrace)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.headers.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((?:|Request)Header)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.imap.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Imap(?:Base|Default|Menu))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.include.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(SSIEndTag|SSIErrorMsg|SSIStartTag|SSITimeFormat|SSIUndefinedEcho|XBitHack)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.isapi.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(ISAPI(?:AppendLogToErrors|AppendLogToQuery|CacheFile|FakeAsync|LogNotSupported|ReadAheadBuffer))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.ldap.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(LDAP(?:CacheEntries|CacheTTL|ConnectionTimeout|OpCacheEntries|OpCacheTTL|SharedCacheFile|SharedCacheSize|TrustedCA|TrustedCAType))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.log.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(BufferedLogs|CookieLog|CustomLog|LogFormat|TransferLog|ForensicLog)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.mem_cache.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(MCache(?:MaxObjectCount|MaxObjectSize|MaxStreamingBuffer|MinObjectSize|RemovalAlgorithm|Size))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.mime.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AddCharset|AddEncoding|AddHandler|AddInputFilter|AddLanguage|AddOutputFilter|AddType|DefaultLanguage|ModMimeUsePathInfo|MultiviewsMatch|RemoveCharset|RemoveEncoding|RemoveHandler|RemoveInputFilter|RemoveLanguage|RemoveOutputFilter|RemoveType|TypesConfig)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.misc.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(ProtocolEcho|Example|AddModuleInfo|MimeMagicFile|CheckSpelling|ExtendedStatus|SuexecUserGroup|UserDir)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.negotiation.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(CacheNegotiatedDocs|ForceLanguagePriority|LanguagePriority)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.nw_ssl.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(NWSSLTrustedCerts|NWSSLUpgradeable|SecureListen)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.proxy.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(AllowCONNECT|NoProxy|ProxyBadHeader|ProxyBlock|ProxyDomain|ProxyErrorOverride|ProxyFtpDirCharset|ProxyIOBufferSize|ProxyMaxForwards|ProxyPass|ProxyPassMatch|ProxyPassReverse|ProxyPreserveHost|ProxyReceiveBufferSize|ProxyRemote|ProxyRemoteMatch|ProxyRequests|ProxyTimeout|ProxyVia)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.rewrite.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Rewrite(?:Base|Cond|Engine|Lock|Log|LogLevel|Map|Options|Rule))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.setenvif.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(BrowserMatch|BrowserMatchNoCase|SetEnvIf|SetEnvIfNoCase)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.so.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Load(?:File|Module))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.ssl.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(SSL(?:CACertificateFile|CACertificatePath|CARevocationFile|CARevocationPath|CertificateChainFile|CertificateFile|CertificateKeyFile|CipherSuite|Engine|Mutex|Options|PassPhraseDialog|Protocol|ProxyCACertificateFile|ProxyCACertificatePath|ProxyCARevocationFile|ProxyCARevocationPath|ProxyCipherSuite|ProxyEngine|ProxyMachineCertificateFile|ProxyMachineCertificatePath|ProxyProtocol|ProxyVerify|ProxyVerifyDepth|RandomSeed|Require|RequireSSL|SessionCache|SessionCacheTimeout|UserName|VerifyClient|VerifyDepth|InsecureRenegotiation|OpenSSLConfCmd))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.substitute.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Substitute(?:|InheritBefore|MaxLineLength))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.usertrack.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Cookie(?:Domain|Expires|Name|Style|Tracking))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.vhost_alias.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Virtual(?:DocumentRoot|DocumentRootIP|ScriptAlias|ScriptAliasIP))\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.php.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.property.apacheconf</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.value.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(php_(?:value|flag|admin_value|admin_flag))\b(\s+(.+?)(\s+(".+?"|.+?))?)?\s</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.variable.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.env.apacheconf</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.misc.apacheconf</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.variable.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(%\{)((HTTP_USER_AGENT|HTTP_REFERER|HTTP_COOKIE|HTTP_FORWARDED|HTTP_HOST|HTTP_PROXY_CONNECTION|HTTP_ACCEPT|REMOTE_ADDR|REMOTE_HOST|REMOTE_PORT|REMOTE_USER|REMOTE_IDENT|REQUEST_METHOD|SCRIPT_FILENAME|PATH_INFO|QUERY_STRING|AUTH_TYPE|DOCUMENT_ROOT|SERVER_ADMIN|SERVER_NAME|SERVER_ADDR|SERVER_PORT|SERVER_PROTOCOL|SERVER_SOFTWARE|TIME_YEAR|TIME_MON|TIME_DAY|TIME_HOUR|TIME_MIN|TIME_SEC|TIME_WDAY|TIME|API_VERSION|THE_REQUEST|REQUEST_URI|REQUEST_FILENAME|IS_SUBREQ|HTTPS)|(.*?))(})</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.mime-type.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((text|image|application|video|audio)/.+?)\s</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.helper.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(?i)(export|from|unset|set|on|off)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.decimal.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(\d+)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.flag.apacheconf</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.flag.apacheconf</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.flag.apacheconf</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s(\[)(.*?)(])\s</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.apacheconf</string>
  </dict>
</plist>