<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>conf</string>
      <string>bird</string>
      <string>bird2</string>
      <string>bird3</string>
      <string>bird.conf</string>
      <string>bird2.conf</string>
      <string>bird3.conf</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*}</string>
    <key>name</key>
    <string>bird2</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#ip-addresses</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#prefixes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#vpn-rd</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bytestrings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bgp-paths</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#print-statements</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#template-definitions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#filter-definitions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-definitions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#protocol-definitions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#next-hop-statements</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#neighbor-statements</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import-export-statements</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variable-declarations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#method-calls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-calls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#method-properties</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#route-attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#data-types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#structural-keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#protocol-phrases</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functional-keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#semantic-modifiers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#builtin-functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#filter-names</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#user-variables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#symbols</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#blocks</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>bgp-paths</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[=</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.bgp-path.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>=]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.bgp-path.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.bgp-path.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[*+?]</string>
                <key>name</key>
                <string>keyword.operator.wildcard.bird</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b[0-9]+\b</string>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#symbols</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>blocks</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.block.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.set.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.set.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.set.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tuple.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tuple.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.tuple.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.terminator.statement.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.bird</string>
          </dict>
        </array>
      </dict>
      <key>builtin-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:defined|unset|roa_check|aspa_check|aspa_check_downstream|aspa_check_upstream|from_hex|format|append|prepend|add|delete|empty|reset|bt_assert|bt_test_suite|bt_test_same)\b</string>
            <key>name</key>
            <string>support.function.builtin.bird</string>
          </dict>
        </array>
      </dict>
      <key>bytestrings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bhex:\h{2}(?:[-.:\s]*\h{2})*\b</string>
            <key>name</key>
            <string>constant.numeric.bytestring.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:\h{2}[-.:\s]*){15,}\h{2}\b</string>
            <key>name</key>
            <string>constant.numeric.bytestring.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\h{32,}\b</string>
            <key>name</key>
            <string>constant.numeric.bytestring.bird</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.number-sign.bird</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.bird</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:on|off|yes|no|true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:empty|unknown|generic|rt|ro|one|ten)\b</string>
            <key>name</key>
            <string>constant.language.special.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bSCOPE_(?:HOST|LINK|SITE|ORGANIZATION|UNIVERSE)\b</string>
            <key>name</key>
            <string>constant.language.scope.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bRTS_(?:STATIC|INHERIT|DEVICE|RIP|OSPF|OSPF_IA|OSPF_EXT1|OSPF_EXT2|BGP|PIPE|BABEL)\b</string>
            <key>name</key>
            <string>constant.language.source.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bRTD_(?:ROUTER|DEVICE|MULTIPATH|BLACKHOLE|UNREACHABLE|PROHIBIT)\b</string>
            <key>name</key>
            <string>constant.language.dest.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bROA_(?:UNKNOWN|INVALID|VALID)\b</string>
            <key>name</key>
            <string>constant.language.roa.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bASPA_(?:UNKNOWN|INVALID|VALID)\b</string>
            <key>name</key>
            <string>constant.language.aspa.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bNET_(?:IP4|IP6|IP6_SADR|VPN4|VPN6|ROA4|ROA6|FLOW4|FLOW6|MPLS)\b</string>
            <key>name</key>
            <string>constant.language.net-type.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bMPLS_POLICY_(?:NONE|STATIC|PREFIX|AGGREGATE|VRF)\b</string>
            <key>name</key>
            <string>constant.language.mpls.bird</string>
          </dict>
        </array>
      </dict>
      <key>data-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:(?:int|pair|quad|ip|prefix|ec|lc|rd|enum)\s+set|int|bool|ip|prefix|rd|pair|quad|ec|lc|string|bytestring|bgpmask|bgppath|clist|eclist|lclist|set|enum|route)\b</string>
            <key>name</key>
            <string>storage.type.bird</string>
          </dict>
        </array>
      </dict>
      <key>filter-definitions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(filter)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.filter.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.filter.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.filter-definition.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>filter-names</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z_a-z][0-9A-Z_a-z]*_filter\b</string>
            <key>name</key>
            <string>entity.name.function.filter.bird</string>
          </dict>
        </array>
      </dict>
      <key>function-calls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b([A-Z_a-z][0-9A-Z_a-z]*)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.call.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.function-call.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-definitions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(function)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')(?=\s*\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.function.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.user-defined.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-definition.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\(</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.bird</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.bird</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.function-parameters.bird</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#data-types</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#symbols</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>-&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.return-type.bird</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=\{)</string>
                <key>name</key>
                <string>meta.function-return-type.bird</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#data-types</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functional-keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:static|rip|ospf|bgp|babel|rpki|bfd|bmp|device|direct|kernel|pipe|perf|mrt|aggregator|l3vpn|radv)\b</string>
            <key>name</key>
            <string>keyword.control.protocol-type.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:graceful|restart|preference|disabled|hold|keepalive|connect|retry|start|delay|error|wait|forget|scan|randomize|router|id)\b</string>
            <key>name</key>
            <string>keyword.control.routing.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:interface|type|wired|wireless|tunnel|rxcost|limit|hello|update|interval|port|tx|class|dscp|priority|rx|buffer|length|check|link|rtt|cost|min|max|decay|send|timestamps)\b</string>
            <key>name</key>
            <string>keyword.other.interface.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:(?:refresh|retry|expire|transport|ssh|tcp|user|address|version|ignore|private|public|key)|(?:local\s+address|ignore\s+max\s+length|min\s+version|max\s+version|bird\s+private\s+key|remote\s+public\s+key))\b</string>
            <key>name</key>
            <string>keyword.other.rpki.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:authentication|none|mac|permissive|password|generate|accept|from|to|algorithm|hmac|sha1|sha256|sha384|sha512|blake2s128|blake2s256|blake2b256|blake2b512)\b</string>
            <key>name</key>
            <string>keyword.other.auth.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\btime\b</string>
            <key>name</key>
            <string>keyword.other.time.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:hostname|description|debug|log|syslog|stderr|bird|protocols|tables|channels|timeouts|passwords|bfd|confederation|cluster|stub|dead|neighbors|area|md5|multihop|passive|rfc1583compat|tick|ls|retransmit|transmit|ack|state|database|summary|external|nssa|translator|always|candidate|never|role|stability|election|action|warn|block|disable|keep|filtered|receive|modify|add|delete|withdraw|unreachable|blackhole|prohibit|unreach|igp_metric|localpref|med|origin|community|large_community|ext_community|as_path|prepend|weight|gateway|scope|onlink|recursive|multipath|igp|channel|sadr|src|learn|persist|via|ng)\b</string>
            <key>name</key>
            <string>keyword.other.config.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:flow4|flow6|dst|src|proto|header|dport|sport|icmp|code|tcp|flags|dscp|dont_fragment|is_fragment|first_fragment|last_fragment|fragment|label|offset)\b</string>
            <key>name</key>
            <string>keyword.other.flowspec.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:vpn4|vpn6|mpls|aspa|roa4|roa6)\b</string>
            <key>name</key>
            <string>keyword.other.address.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:all|none)\b</string>
            <key>name</key>
            <string>keyword.other.quick-declaration.bird</string>
          </dict>
        </array>
      </dict>
      <key>import-export-statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import-export.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.filter.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.filter.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(import)\s+(filter)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\b</string>
            <key>name</key>
            <string>meta.import-statement.bird</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(import)\s+(filter)\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import-export.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.filter.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.import-filter-inline.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(export)\s+(where)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import-export.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.where.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.terminator.statement.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.export-where-clause.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import-export.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.filter.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.filter.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(export)\s+(filter)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\b</string>
            <key>name</key>
            <string>meta.export-statement.bird</string>
          </dict>
        </array>
      </dict>
      <key>ip-addresses</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}(?:/[0-9]{1,2})?\b</string>
            <key>name</key>
            <string>constant.numeric.ip.ipv4.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:\h{0,4}:){2,7}\h{0,4}(?:/[0-9]{1,3})?\b</string>
            <key>name</key>
            <string>constant.numeric.ip.ipv6.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>::(?:\h{0,4}:){0,6}\h{0,4}(?:/[0-9]{1,3})?\b</string>
            <key>name</key>
            <string>constant.numeric.ip.ipv6.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:\h{0,4}:){1,6}::(?:\h{0,4}:){0,5}\h{0,4}(?:/[0-9]{1,3})?\b</string>
            <key>name</key>
            <string>constant.numeric.ip.ipv6.bird</string>
          </dict>
        </array>
      </dict>
      <key>method-calls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\.\s*([A-Z_a-z][0-9A-Z_a-z]*)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.method.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.method-call.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\.\s*([A-Z_a-z][0-9A-Z_a-z]*)</string>
            <key>name</key>
            <string>meta.method-access.bird</string>
          </dict>
        </array>
      </dict>
      <key>method-properties</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=\.)\s*(?:first|last|last_nonaggregated|len|asn|data1??|data2|is_v4|ip|src|dst|rd|maxlen|type|mask|min|max)\b(?!\s*\()</string>
            <key>name</key>
            <string>support.variable.property.bird</string>
          </dict>
        </array>
      </dict>
      <key>neighbor-statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.local.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.symbol.local-address.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.port.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.port.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(local)\s+([.:\h]+|[A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')(?:\s+(port)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*))?\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.local-as-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.local.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(local)\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.local-as-template-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.neighbor.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ip-address.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.interface-reference.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.interface.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.interface.bird</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>keyword.control.port.bird</string>
              </dict>
              <key>9</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.port.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(neighbor)\s+([.:\h]+)\s*(%\s*(?:'([-.0-:A-Z_a-z]+)'|([-.0-:A-Z_a-z]+)))?(?:\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*))?\s+(port)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.neighbor-port-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.neighbor.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.symbol.neighbor-address.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.interface-reference.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.interface.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.interface.bird</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>keyword.control.port.bird</string>
              </dict>
              <key>9</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.port.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(neighbor)\s+('[-.0-:A-Z_a-z]+'|(?!(?:as|range)\b)[A-Z_a-z][0-9A-Z_a-z]*)\s*(%\s*(?:'([-.0-:A-Z_a-z]+)'|([-.0-:A-Z_a-z]+)))?(?:\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*))?\s+(port)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.neighbor-port-symbolic-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.neighbor.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ip-address.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.interface-reference.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.interface.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.interface.bird</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(neighbor)\s+([.:\h]+)\s*(%\s*(?:'([-.0-:A-Z_a-z]+)'|([-.0-:A-Z_a-z]+)))?\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.neighbor-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.neighbor.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.symbol.neighbor-address.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.interface-reference.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.interface.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.interface.bird</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(neighbor)\s+('[-.0-:A-Z_a-z]+'|(?!(?:as|range)\b)[A-Z_a-z][0-9A-Z_a-z]*)\s*(%\s*(?:'([-.0-:A-Z_a-z]+)'|([-.0-:A-Z_a-z]+)))?\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.neighbor-symbolic-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.neighbor.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.asn.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(neighbor)\s+(as)\s+([0-9]+|[A-Z_a-z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.neighbor-template-statement.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.source.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ip-address.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(source address)\s+([.:\h]+)\b</string>
            <key>name</key>
            <string>meta.source-address-statement.bird</string>
          </dict>
        </array>
      </dict>
      <key>next-hop-statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.routing.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.ip-version.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ip-address.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(next hop)\s+(ipv4)\s+([.0-9]+)\b</string>
            <key>name</key>
            <string>meta.next-hop-ipv4.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.routing.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.ip-version.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.ip-address.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(next hop)\s+(ipv6)\s+([:\h]+)\b</string>
            <key>name</key>
            <string>meta.next-hop-ipv6.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.routing.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.semantic-modifier.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(next hop)\s+(self)\b</string>
            <key>name</key>
            <string>meta.next-hop-simple.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.routing.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.semantic-modifier.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(extended next hop)\s+(o(?:n|ff))\b</string>
            <key>name</key>
            <string>meta.extended-next-hop-statement.bird</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b0x\h+\b</string>
            <key>name</key>
            <string>constant.numeric.hex.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.bird</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.unit.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b[0-9]+\s*([mu]??s)\b</string>
            <key>name</key>
            <string>constant.numeric.time.bird</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>==|!=|&lt;=|&gt;=|!~|[&lt;=&gt;~]</string>
            <key>name</key>
            <string>keyword.operator.comparison.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;&amp;|\|\||!|-&gt;</string>
            <key>name</key>
            <string>keyword.operator.logical.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+\+</string>
            <key>name</key>
            <string>keyword.operator.concat.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-%*+/]</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>keyword.operator.range.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>keyword.operator.accessor.bird</string>
          </dict>
        </array>
      </dict>
      <key>prefixes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:(?:[0-9]{1,3}\.){3}[0-9]{1,3}|(?:\h{0,4}:)+\h{0,4})/[0-9]{1,3}(?:[-+]|\{[0-9]+,[0-9]+})?\b</string>
            <key>name</key>
            <string>constant.numeric.prefix.bird</string>
          </dict>
        </array>
      </dict>
      <key>print-statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(printn??)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.print.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.terminator.statement.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.print-statement.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>protocol-definitions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(protocol)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s+(from)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.protocol.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.protocol.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.control.template-reference.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.template.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.protocol-definition-with-template.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(protocol)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.protocol.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.protocol.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.protocol-definition-with-name.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(protocol)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.protocol.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.protocol-definition-anonymous.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>protocol-phrases</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:strict\s+bind|zero\s+udp6\s+checksum\s+rx|idle\s+tx\s+interval|multiplier|keyed|meticulous)\b</string>
            <key>name</key>
            <string>keyword.other.bfd.phrase.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:send\s+timestamps|rtt\s+(?:cost|min|max|decay)|next\s+hop\s+prefer|prefer|native)\b</string>
            <key>name</key>
            <string>keyword.other.babel.phrase.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:next\s+hop\s+(?:self|address|ibgp|ebgp)|link\s+local\s+next\s+hop\s+format|import\s+table|export\s+table|base\s+table|add\s+paths|aigp\s+originate|long\s+lived\s+graceful\s+restart|long\s+lived\s+stale\s+time|dynamic\s+name(?:\s+digits)?|free\s+bind|ttl\s+security|multihop\s+password|rr\s+client|rs\s+client|advertise\s+hostname|interpret\s+communities|deterministic\s+med|default\s+bgp_local_pref|default\s+bgp_med|med\s+metric|igp\s+metric|missing\s+lladdr|gateway\s+address|forwarding\s+addressed|gateway\s+recursive|allow\s+local\s+as|allow\s+bogus\s+as|originate\s+community|full\s+route\s+table|capabilities|primary)\b</string>
            <key>name</key>
            <string>keyword.other.bgp.phrase.bird</string>
          </dict>
        </array>
      </dict>
      <key>route-attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:net|scope|preference|from|gw|proto|source|dest|ifname|ifindex|weight|gw_mpls|gw_mpls_stack|onlink|igp_metric|mpls_label|mpls_policy|mpls_class|bgp_path|bgp_origin|bgp_next_hop|bgp_med|bgp_local_pref|bgp_community|bgp_ext_community|bgp_large_community|bgp_originator_id|bgp_cluster_list|ospf_metric1|ospf_metric2|ospf_tag|ospf_router_id|rip_metric|rip_tag|mypath|mylclist)\b</string>
            <key>name</key>
            <string>support.variable.route-attribute.bird</string>
          </dict>
        </array>
      </dict>
      <key>semantic-modifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:self|on|off|remote|extended)\b</string>
            <key>name</key>
            <string>keyword.other.semantic-modifier.bird</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\.</string>
                <key>name</key>
                <string>constant.character.escape.bird</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>'[-.0-:A-Z_a-z]+'</string>
            <key>name</key>
            <string>entity.name.symbol.quoted.bird</string>
          </dict>
        </array>
      </dict>
      <key>structural-keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:if|then|else|case|for|do|while|break|continue|return|in)\b</string>
            <key>name</key>
            <string>keyword.control.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\belse\s*:</string>
            <key>name</key>
            <string>keyword.control.case.else.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:accept|reject|error)\b</string>
            <key>name</key>
            <string>keyword.control.flow.bird</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:protocol|table|define|include|attribute|eval|ipv4|ipv6|local|as|from|where|cost|limit|action)\b</string>
            <key>name</key>
            <string>keyword.control.structure.bird</string>
          </dict>
        </array>
      </dict>
      <key>symbols</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z_a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.other.bird</string>
          </dict>
        </array>
      </dict>
      <key>template-definitions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(template)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s+(from)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.template.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.template.bird</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.control.template-reference.bird</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.template.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template-definition-with-from.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(template)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s+([A-Z_a-z][0-9A-Z_a-z]*|'[-.0-:A-Z_a-z]+')\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.template.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.template.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template-definition-with-name.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(template)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.template.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.protocol.bird</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.bird</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template-definition-anonymous.bird</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>user-variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.other.user-defined.bird</string>
          </dict>
        </array>
      </dict>
      <key>variable-declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.bird</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.declaration.bird</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b((?:int|pair|quad|ip|prefix|ec|lc|rd|enum)\s+set|int|bool|ip|prefix|rd|pair|quad|ec|lc|string|bytestring|bgpmask|bgppath|clist|eclist|lclist|set|enum|route)\s+([A-Z_a-z][0-9A-Z_a-z]*)(?:\s*=|;)</string>
            <key>name</key>
            <string>meta.variable-declaration.bird</string>
          </dict>
        </array>
      </dict>
      <key>vpn-rd</key>
      <dict>
        <key>match</key>
        <string>\b(?:[0-9]+:[0-9]+|[012]:[0-9]+:[0-9]+|(?:[0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]+)\b</string>
        <key>name</key>
        <string>constant.numeric.vpn-rd.bird</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.bird2</string>
  </dict>
</plist>