<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>cadence</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declarations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code-block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expressions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#composite</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#event</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>code-block</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.cadence</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\A^(#!).*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.cadence</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.documentation.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*:</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.documentation.playground.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\*/</string>
            <key>name</key>
            <string>invalid.illegal.unexpected-end-of-block-comment.cadence</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[\t ]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>///</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>comment.line.triple-slash.documentation.cadence</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>//:</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>comment.line.double-slash.documentation.cadence</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>comment.line.double-slash.cadence</string>
              </dict>
            </array>
          </dict>
        </array>
        <key>repository</key>
        <dict>
          <key>nested</key>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>composite</key>
      <dict>
        <key>begin</key>
        <string>\b((?:struct|resource|contract|attachment)(?:\s+interface)?|enum)\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.$1.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.$1.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?=\s*\Z)</string>
        <key>name</key>
        <string>meta.definition.type.composite.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#conformance-clause</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.type.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.type.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.type.body.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conformance-clause</key>
      <dict>
        <key>begin</key>
        <string>(:)(?=\s*\{)|(:)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.empty-conformance-clause.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.conformance-clause.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)$|(?=[={}])</string>
        <key>name</key>
        <string>meta.conformance-clause.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G</string>
            <key>end</key>
            <string>(?!\G)$|(?=[={}])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#var-let-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#initializer</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#prepare-execute</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#execute-phase</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#pre-post</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#transaction</string>
          </dict>
        </array>
      </dict>
      <key>event</key>
      <dict>
        <key>begin</key>
        <string>\b(event)\b\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.event.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.event.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>name</key>
        <string>meta.definition.type.event.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
        </array>
      </dict>
      <key>execute-phase</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(execute)\b\s*(?=\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.phase.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.transaction.phase.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.end.cadence</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expression-element-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.function-call.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.argument-label.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=[]),])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?![]),])(?=\S)</string>
            <key>end</key>
            <string>(?=[]),])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#language-variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#path-literals</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!\b(?:if|while|for|return|create|destroy|emit|as)\b)([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(&lt;)(?=[\&amp;(@\[_{\p{Lu}]|auth\b|\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type-arguments.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)(?!\s*[&lt;=&gt;])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type-arguments.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.type.arguments.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.type-argument.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.group.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression-element-list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\.)([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.method.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression-element-list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\.)[_\p{L}][_\p{L}\p{N}\p{M}]*</string>
            <key>name</key>
            <string>variable.other.member.cadence</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call-expression</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(?!(?:contract|struct|resource|event|enum|attachment|entitlement|import|fun|let|var|if|else|switch|case|default|while|for|in|break|continue|return|emit|as|create|destroy|attach|to|remove|from|pub|priv|access|all|self|view|auth|transaction|prepare|execute|pre|post|init|true|false|nil|Type|Int|UInt|Int8|Int16|Int32|Int64|Int128|Int256|UInt8|UInt16|UInt32|UInt64|UInt128|UInt256|Word8|Word16|Word32|Word64|Fix64|Fix128|UFix64|UFix128|String|Character|Bool|Address|Void|AnyStruct|AnyResource|Any|Never|mapping|include)\b)[_\p{L}][_\p{L}\p{N}\p{M}]*\b</string>
            <key>name</key>
            <string>variable.other.readwrite.cadence</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>begin</key>
        <string>\b(fun)\b\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|;|(?=}\s*$)|$</string>
        <key>name</key>
        <string>meta.definition.function.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-result</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.function.body.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-call-expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(?!set|init|transaction|prepare|execute|access|auth)([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression-element-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-expression</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(?:(view)\s+)?(fun)\b(?=\s*\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.view.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|$</string>
        <key>name</key>
        <string>meta.function.expression.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-result</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.function.body.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-result</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;![-!%\&amp;*+./&lt;=&gt;^|~])(:)(?![-!%\&amp;*+./&lt;=&gt;^|~])\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.function-result.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;![\&amp;&lt;@\[])(?!\G)(?=\s*\{)|(?=;|(?&lt;!\{)})|$</string>
        <key>name</key>
        <string>meta.function-result.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>initializer</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(init)\s*(?=[(&lt;])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|$</string>
        <key>name</key>
        <string>meta.definition.function.initializer.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.function.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.function.body.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\bvar\b</string>
            <key>name</key>
            <string>storage.type.var.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\blet\b</string>
            <key>name</key>
            <string>storage.type.let.cadence</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(entitlement)\s+(mapping)\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.entitlement.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.mapping.cadence</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.entitlement-mapping.cadence</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.entitlement-mapping.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\binclude\b</string>
                <key>name</key>
                <string>keyword.other.mapping.include.cadence</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.entitlement-mapping.cadence</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\binclude)\s+([_\p{L}][._\p{L}\p{N}\p{M}]*)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[_\p{L}][._\p{L}\p{N}\p{M}]*</string>
                <key>name</key>
                <string>entity.name.type.entitlement.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>-&gt;</string>
                <key>name</key>
                <string>punctuation.separator.mapping.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.entitlement.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.entitlement.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(entitlement)\b\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(access)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.access.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.access.modifier.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\bmapping\b</string>
                <key>name</key>
                <string>keyword.other.mapping.cadence</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.entitlement-mapping.cadence</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\bmapping)\s+([_\p{L}][._\p{L}\p{N}\p{M}]*)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(?:all|self|contract|account)\b</string>
                <key>name</key>
                <string>constant.language.access.audience.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.entitlement.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\|</string>
                <key>name</key>
                <string>punctuation.separator.entitlement.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[_\p{L}][._\p{L}\p{N}\p{M}]*</string>
                <key>name</key>
                <string>entity.name.type.entitlement.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(?:if|else|switch|case|default)\b</string>
            <key>name</key>
            <string>keyword.control.branch.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(?:return|continue|break)\b</string>
            <key>name</key>
            <string>keyword.control.transfer.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(?:while|for|in)\b</string>
            <key>name</key>
            <string>keyword.control.loop.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(?:create|destroy|emit|attach|to|remove|from)\b</string>
            <key>name</key>
            <string>keyword.other.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(p(?:ub|riv))\b</string>
            <key>name</key>
            <string>invalid.deprecated.keyword.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\bview\b</string>
            <key>name</key>
            <string>storage.modifier.view.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(auth)\b</string>
            <key>name</key>
            <string>keyword.other.auth.cadence</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(import)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$|//|/\*|;)</string>
            <key>name</key>
            <string>meta.import.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\bfrom\b</string>
                <key>name</key>
                <string>keyword.control.import.cadence</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#literals</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b[_\p{L}][_\p{L}\p{N}\p{M}]*\b</string>
                <key>name</key>
                <string>variable.other.readwrite.cadence</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>language-variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(self)\b</string>
            <key>name</key>
            <string>variable.language.cadence</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bnil\b</string>
            <key>name</key>
            <string>constant.language.nil.cadence</string>
          </dict>
        </array>
        <key>repository</key>
        <dict>
          <key>boolean</key>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.cadence</string>
          </dict>
          <key>numeric</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#binary</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#octal</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#hexadecimal</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#fixed-point</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#decimal</string>
              </dict>
            </array>
            <key>repository</key>
            <dict>
              <key>binary</key>
              <dict>
                <key>match</key>
                <string>(\B-|\b)0b[01]([01_]*[01])?\b</string>
                <key>name</key>
                <string>constant.numeric.integer.binary.cadence</string>
              </dict>
              <key>decimal</key>
              <dict>
                <key>match</key>
                <string>(\B-|\b)[0-9]([0-9_]*[0-9])?\b</string>
                <key>name</key>
                <string>constant.numeric.integer.decimal.cadence</string>
              </dict>
              <key>fixed-point</key>
              <dict>
                <key>match</key>
                <string>(\B-|\b)[0-9]([0-9_]*[0-9])?\.[0-9]([0-9_]*[0-9])?\b</string>
                <key>name</key>
                <string>constant.numeric.float.cadence</string>
              </dict>
              <key>hexadecimal</key>
              <dict>
                <key>match</key>
                <string>(\B-|\b)0x\h([_\h]*\h)?\b</string>
                <key>name</key>
                <string>constant.numeric.integer.hexadecimal.cadence</string>
              </dict>
              <key>octal</key>
              <dict>
                <key>match</key>
                <string>(\B-|\b)0o[0-7]([0-7_]*[0-7])?\b</string>
                <key>name</key>
                <string>constant.numeric.integer.octal.cadence</string>
              </dict>
            </dict>
          </dict>
          <key>string</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.cadence</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.single-line.cadence</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[\n\r]</string>
                    <key>name</key>
                    <string>invalid.illegal.returns-not-allowed.cadence</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>\\\(</string>
                    <key>beginCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.section.embedded.begin.cadence meta.embedded.cadence</string>
                      </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.embedded.line.cadence</string>
                    <key>end</key>
                    <string>\)</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.section.embedded.end.cadence meta.embedded.cadence</string>
                      </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.interpolation.cadence</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>begin</key>
                        <string>\(</string>
                        <key>beginCaptures</key>
                        <dict>
                          <key>0</key>
                          <dict>
                            <key>name</key>
                            <string>punctuation.section.group.begin.cadence</string>
                          </dict>
                        </dict>
                        <key>end</key>
                        <string>\)</string>
                        <key>endCaptures</key>
                        <dict>
                          <key>0</key>
                          <dict>
                            <key>name</key>
                            <string>punctuation.section.group.end.cadence</string>
                          </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#expressions</string>
                          </dict>
                        </array>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#expressions</string>
                      </dict>
                    </array>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#string-guts</string>
                  </dict>
                </array>
              </dict>
            </array>
            <key>repository</key>
            <dict>
              <key>string-guts</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\\["'0\\nrt]</string>
                    <key>name</key>
                    <string>constant.character.escape.cadence</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\\u\{\h{1,8}}</string>
                    <key>name</key>
                    <string>constant.character.escape.unicode.cadence</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </dict>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&lt;-&gt;</string>
            <key>name</key>
            <string>keyword.operator.swap.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?\.</string>
            <key>name</key>
            <string>keyword.operator.optional.chain.cadence</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(as(?:\?|!?))\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.cast.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$|;|//|/\\*|")|(?=[),}])|(?&lt;=&gt;)(?=\s*\{(?!\s*[_\p{L}][._\p{L}\p{N}\p{M}]*\s*:))|(?&lt;=[])&gt;?}\p{L}\p{N}])(?=\s*\{(?!\s*[_\p{L}][._\p{L}\p{N}\p{M}]*\s*:))|(?=\?\?)</string>
            <key>name</key>
            <string>meta.type.cast-target.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\{(?=\s*[_\p{L}][._\p{L}\p{N}\p{M}]*\s*:)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.type.dictionary.begin.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(})</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.type.dictionary.end.cadence</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.type.dictionary.cadence</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#comments</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#type</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>:</string>
                    <key>name</key>
                    <string>punctuation.separator.type.dictionary.cadence</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.type.dictionary.cadence</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>-</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.unary.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\))!</string>
            <key>name</key>
            <string>keyword.operator.force-unwrap.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!</string>
            <key>name</key>
            <string>keyword.operator.logical.not.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;-</string>
            <key>name</key>
            <string>keyword.operator.move.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;-!</string>
            <key>name</key>
            <string>keyword.operator.force-move.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-*+/]</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.remainder.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&gt;&gt;</string>
            <key>name</key>
            <string>keyword.operator.bitwise.shift.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&lt;</string>
            <key>name</key>
            <string>keyword.operator.bitwise.shift.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>==|!=|[&lt;&gt;]|&gt;=|&lt;=</string>
            <key>name</key>
            <string>keyword.operator.comparison.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?\?</string>
            <key>name</key>
            <string>keyword.operator.coalescing.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;&amp;|\|\|</string>
            <key>name</key>
            <string>keyword.operator.logical.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[!?]</string>
            <key>name</key>
            <string>keyword.operator.type.optional.cadence</string>
          </dict>
        </array>
      </dict>
      <key>parameter-clause</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.cadence</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.parameter-clause.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-list</string>
          </dict>
        </array>
      </dict>
      <key>parameter-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.unnamed-parameter.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(_)\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)(?=\s*:)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.label.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([_\p{L}][_\p{L}\p{N}\p{M}]*)\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)(?=\s*:)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([_\p{L}][_\p{L}\p{N}\p{M}]*)(?=\s*:)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:\s*(?!\s)</string>
            <key>end</key>
            <string>(?=[),])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>invalid.illegal.extra-colon-in-parameter-list.cadence</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>path-literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.path.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.other.path.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(/)((storage|public)(/[_\p{L}][_\p{L}\p{N}\p{M}]*)?)</string>
          </dict>
        </array>
      </dict>
      <key>pre-post</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(p(?:re|ost))\b\s*(?=\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.phase.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.transaction.phase.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.end.cadence</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>prepare-execute</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(prepare)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.phase.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.transaction.phase.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.phase.end.cadence</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>transaction</key>
      <dict>
        <key>begin</key>
        <string>\b(transaction)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.transaction.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))|(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.transaction.cadence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-clause</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.transaction.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.transaction.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.transaction.body.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(?:(view)\s+)?(fun)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.view.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.cadence</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=[]),&gt;}]|$)</string>
            <key>name</key>
            <string>meta.type.function.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\G</string>
                <key>end</key>
                <string>(\))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.cadence</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.parameter.cadence</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(:)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.function-result.cadence</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[]),&gt;}]|$)</string>
                <key>name</key>
                <string>meta.function-result.cadence</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)([_\p{L}][_\p{L}\p{N}\p{M}]*)\s*(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type-arguments.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type-arguments.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.type.arguments.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.type-argument.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\.)\b(auth)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.auth.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.auth.entitlements.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\bmapping\b</string>
                <key>name</key>
                <string>keyword.other.mapping.cadence</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.entitlement-mapping.cadence</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\bmapping)\s+([_\p{L}][._\p{L}\p{N}\p{M}]*)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.entitlement.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\|</string>
                <key>name</key>
                <string>punctuation.separator.entitlement.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[_\p{L}][._\p{L}\p{N}\p{M}]*</string>
                <key>name</key>
                <string>entity.name.type.entitlement.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{(?![^}]*:)(?!.*}\s*\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.intersection.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.intersection.end.cadence</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.type.intersection.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{(?=\s*[_\p{L}][._\p{L}\p{N}\p{M}]*\s*:)(?!.*}\s*\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.dictionary.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.dictionary.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.type.dictionary.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>punctuation.separator.type.dictionary.cadence</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.type.dictionary.cadence</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.array.begin.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.array.end.cadence</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.type.array.cadence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.reference.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([\&amp;@])(?=\s*\{)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.type.reference.cadence</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.cadence</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([\&amp;@])\s*([_\p{L}][._\p{L}\p{N}\p{M}]*)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([_\p{L}][_\p{L}\p{N}\p{M}]*)</string>
            <key>name</key>
            <string>entity.name.type.cadence</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[!?]</string>
            <key>name</key>
            <string>keyword.operator.type.optional.cadence</string>
          </dict>
        </array>
      </dict>
      <key>var-let-declaration</key>
      <dict>
        <key>begin</key>
        <string>\b(var|let)\b\s+([_\p{L}][_\p{L}\p{N}\p{M}]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.$1.cadence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.declaration.cadence</string>
          </dict>
        </dict>
        <key>end</key>
        <string>=|&lt;-!??|;|(?=//)|$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:\s*(?!\s)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.cadence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=//|=|&lt;-!??|;|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.cadence</string>
  </dict>
</plist>