<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>cairo</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>\b(if).*\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.if</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.condition</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cairo0</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.control.if</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cairo0</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(with)\s+(.+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.with</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.identifiers</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cairo0</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.control.with</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cairo0</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(with_attr)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s*[({]</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.with_attr</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cairo0</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.control.with_attr</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cairo0</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\belse\b</string>
        <key>name</key>
        <string>keyword.control.else</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(call|jmp|ret|abs|rel|if)\b</string>
        <key>name</key>
        <string>keyword.other.opcode</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([af]p)\b</string>
        <key>name</key>
        <string>keyword.other.register</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(const|let|local|tempvar|felt|as|from|import|static_assert|return|assert|cast|alloc_locals|with|with_attr|nondet|dw|codeoffset|new|using|and)\b</string>
        <key>name</key>
        <string>keyword.other.meta</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(SIZE(?:OF_LOCALS|))\b</string>
        <key>name</key>
        <string>markup.italic</string>
      </dict>
      <dict>
        <key>match</key>
        <string>//[^\n]*\n</string>
        <key>name</key>
        <string>comment.line.sharp</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z][0-9A-Z_a-z]*:\s*$</string>
        <key>name</key>
        <string>entity.name.function</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(func)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s*[({]</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cairo</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cairo0</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cairo</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function.cairo</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cairo0</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(struct|namespace)\s+([A-Z_a-z][0-9A-Z_a-z]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cairo</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cairo0</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.cairo</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function.cairo</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cairo0</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[-+]?[0-9]+\b</string>
        <key>name</key>
        <string>constant.numeric.decimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[-+]?0x\h+\b</string>
        <key>name</key>
        <string>constant.numeric.hexadecimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>'[^']*'</string>
        <key>name</key>
        <string>string.quoted.single</string>
      </dict>
      <dict>
        <key>match</key>
        <string>"[^"]*"</string>
        <key>name</key>
        <string>string.quoted.double</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>%\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.python</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.python</string>
        <key>end</key>
        <string>%}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.python</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>source.python</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.block.python</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.python</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.cairo0</string>
  </dict>
</plist>