<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>codeowners</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#pattern</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#owner</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*#</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.codeowners</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.codeowners</string>
          </dict>
        </array>
      </dict>
      <key>owner</key>
      <dict>
        <key>match</key>
        <string>\S*@\S+</string>
        <key>name</key>
        <string>storage.type.function.codeowners</string>
      </dict>
      <key>pattern</key>
      <dict>
        <key>match</key>
        <string>^\s*(\S+)</string>
        <key>name</key>
        <string>variable.other.codeowners</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.codeowners</string>
  </dict>
</plist>