<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>dotenv</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#line-comment</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s?(#.*)$\n</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#key</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.dotenv</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>property.value.dotenv</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#line-comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#double-quoted-string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#single-quoted-string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolation</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s?(.*?)\s?(=)(.*)$</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>double-quoted-string</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#escape-characters</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>"(.*)"</string>
        <key>name</key>
        <string>string.quoted.double.dotenv</string>
      </dict>
      <key>escape-characters</key>
      <dict>
        <key>match</key>
        <string>\\(?:["'\\bfnrt]|u[0-9A-F]{4})</string>
        <key>name</key>
        <string>constant.character.escape.dotenv</string>
      </dict>
      <key>interpolation</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.interpolation.begin.dotenv</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.interpolation.dotenv</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.interpolation.end.dotenv</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$\{)(.*)(})</string>
      </dict>
      <key>key</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.key.export.dotenv</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.key.dotenv</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(export\s)?(.*)</string>
      </dict>
      <key>line-comment</key>
      <dict>
        <key>match</key>
        <string>#.*$</string>
        <key>name</key>
        <string>comment.line.dotenv</string>
      </dict>
      <key>single-quoted-string</key>
      <dict>
        <key>match</key>
        <string>'(.*)'</string>
        <key>name</key>
        <string>string.quoted.single.dotenv</string>
      </dict>
      <key>variable</key>
      <dict>
        <key>match</key>
        <string>[A-Z_a-z]+[0-9A-Z_a-z]*</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.dotenv</string>
  </dict>
</plist>