<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>elm</string>
    </array>
    <key>name</key>
    <string>elm</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#debug</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(_)\b</string>
        <key>name</key>
        <string>keyword.unused.elm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-signature</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-alias-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string-triple</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string-quote</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#char</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([0-9]+\.[0-9]+([Ee][-+]?[0-9]+)?|[0-9]+[Ee][-+]?[0-9]+)\b</string>
        <key>name</key>
        <string>constant.numeric.float.elm</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([0-9]+)\b</string>
        <key>name</key>
        <string>constant.numeric.elm</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(0x\h+)\b</string>
        <key>name</key>
        <string>constant.numeric.elm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#glsl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#record-prefix</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module-prefix</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constructor</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>record.name.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.pipe.elm</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{)\s+([a-z][0-9A-Z_a-z]*)\s+(\|)\s+([a-z][0-9A-Z_a-z]*)</string>
        <key>name</key>
        <string>meta.record.field.update.elm</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.pipe.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\|)\s+([a-z][0-9A-Z_a-z]*)\s+(=)</string>
        <key>name</key>
        <string>meta.record.field.update.elm</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>record.name.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{)\s+([a-z][0-9A-Z_a-z]*)\s+$</string>
        <key>name</key>
        <string>meta.record.field.update.elm</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{)\s+([a-z][0-9A-Z_a-z]*)\s+(=)</string>
        <key>name</key>
        <string>meta.record.field.elm</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(,)\s+([a-z][0-9A-Z_a-z]*)\s+(=)</string>
        <key>name</key>
        <string>meta.record.field.elm</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([{}])</string>
        <key>name</key>
        <string>punctuation.bracket.elm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#unit</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comma</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#parens</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(-&gt;)</string>
        <key>name</key>
        <string>keyword.operator.arrow.elm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#infix_op</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([:=\\|])</string>
        <key>name</key>
        <string>keyword.other.elm</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(type|as|port|exposing|alias|infixl|infixr?)\s+</string>
        <key>name</key>
        <string>keyword.other.elm</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(if|then|else|case|of|let|in)\s+</string>
        <key>name</key>
        <string>keyword.control.elm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#record-accessor</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#top_level_value</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#period</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#square_brackets</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>block_comment</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\{-(?!#)</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>-}</string>
        <key>name</key>
        <string>comment.block.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
        </array>
      </dict>
      <key>char</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.char.begin.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.char.end.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|["\&amp;'\\abfnrtv]|x\h{1,5})</string>
            <key>name</key>
            <string>constant.character.escape.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^[@-_]</string>
            <key>name</key>
            <string>constant.character.escape.control.elm</string>
          </dict>
        </array>
      </dict>
      <key>comma</key>
      <dict>
        <key>match</key>
        <string>(,)</string>
        <key>name</key>
        <string>punctuation.separator.comma.elm</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>--</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.elm</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.double-dash.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
        </array>
      </dict>
      <key>constructor</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
        <key>name</key>
        <string>constant.type-constructor.elm</string>
      </dict>
      <key>debug</key>
      <dict>
        <key>match</key>
        <string>\b(Debug)\b</string>
        <key>name</key>
        <string>invalid.illegal.debug.elm</string>
      </dict>
      <key>glsl</key>
      <dict>
        <key>begin</key>
        <string>(\[)(glsl)(\|)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.glsl.bracket.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.glsl.name.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.glsl.bracket.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\|])</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.glsl.bracket.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.block.glsl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.glsl</string>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>begin</key>
        <string>^\b(import)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\n(?!\s)</string>
        <key>name</key>
        <string>meta.import.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(as|exposing)</string>
            <key>name</key>
            <string>keyword.control.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module_chunk</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#period</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-exports</string>
          </dict>
        </array>
      </dict>
      <key>infix_op</key>
      <dict>
        <key>match</key>
        <string>(&lt;/&gt;|&lt;\?&gt;|&lt;\||&lt;=|\|\||&amp;&amp;|&gt;=|\|&gt;|\|=|\|\.|\+\+|::|/=|==|//|&gt;&gt;|&lt;&lt;|[-*+/&lt;&gt;^])</string>
        <key>name</key>
        <string>keyword.operator.elm</string>
      </dict>
      <key>module</key>
      <dict>
        <key>begin</key>
        <string>^\b((port |effect )?module)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\n(?!\s)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.declaration.module.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#module_chunk</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#period</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(exposing)</string>
            <key>name</key>
            <string>keyword.other.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-exports</string>
          </dict>
        </array>
      </dict>
      <key>module-exports</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parens.module-export.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parens.module-export.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.declaration.exports.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[a-z]['0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>entity.name.function.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[A-Z]['0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(\.\.\)</string>
            <key>name</key>
            <string>punctuation.parens.ellipses.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>punctuation.parens.ellipses.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#infix_op</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(.*?\)</string>
            <key>name</key>
            <string>meta.other.unknown.elm</string>
          </dict>
        </array>
      </dict>
      <key>module-prefix</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.module.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.period.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([A-Z][0-9A-Z_a-z]*)(\.)</string>
        <key>name</key>
        <string>meta.module.name.elm</string>
      </dict>
      <key>module_chunk</key>
      <dict>
        <key>match</key>
        <string>[A-Z][0-9A-Z_a-z]*</string>
        <key>name</key>
        <string>support.module.elm</string>
      </dict>
      <key>parens</key>
      <dict>
        <key>match</key>
        <string>([()])</string>
        <key>name</key>
        <string>punctuation.parens.elm</string>
      </dict>
      <key>period</key>
      <dict>
        <key>match</key>
        <string>\.</string>
        <key>name</key>
        <string>keyword.other.period.elm</string>
      </dict>
      <key>record-accessor</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.period.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.accessor.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\.)([a-z][0-9A-Z_a-z]*)</string>
        <key>name</key>
        <string>meta.record.accessor</string>
      </dict>
      <key>record-prefix</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>record.name.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.period.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.record.field.accessor.elm</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([a-z][0-9A-Z_a-z]*)(\.)([a-z][0-9A-Z_a-z]*)</string>
        <key>name</key>
        <string>record.accessor.elm</string>
      </dict>
      <key>square_brackets</key>
      <dict>
        <key>match</key>
        <string>[]\[]</string>
        <key>name</key>
        <string>punctuation.definition.list.elm</string>
      </dict>
      <key>string-quote</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|["\&amp;'\\abfnrtv]|x\h{1,5})</string>
            <key>name</key>
            <string>constant.character.escape.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^[@-_]</string>
            <key>name</key>
            <string>constant.character.escape.control.elm</string>
          </dict>
        </array>
      </dict>
      <key>string-triple</key>
      <dict>
        <key>begin</key>
        <string>"""</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.elm</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|["\&amp;'\\abfnrtv]|x\h{1,5})</string>
            <key>name</key>
            <string>constant.character.escape.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^[@-_]</string>
            <key>name</key>
            <string>constant.character.escape.control.elm</string>
          </dict>
        </array>
      </dict>
      <key>top_level_value</key>
      <dict>
        <key>match</key>
        <string>^[a-z][0-9A-Z_a-z]*\b</string>
        <key>name</key>
        <string>entity.name.function.top_level.elm</string>
      </dict>
      <key>type-alias-declaration</key>
      <dict>
        <key>begin</key>
        <string>^(type\s+)(alias\s+)([A-Z]['0-9A-Z_a-z]*)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.type.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.type-alias.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?=\S)</string>
        <key>name</key>
        <string>meta.function.type-declaration.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\n\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-prefix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.type.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-record</string>
          </dict>
        </array>
      </dict>
      <key>type-declaration</key>
      <dict>
        <key>begin</key>
        <string>^(type\s+)([A-Z]['0-9A-Z_a-z]*)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.type.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?=\S)</string>
        <key>name</key>
        <string>meta.function.type-declaration.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.type-constructor.elm</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*([A-Z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.record.field.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.elm</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.type-constructor.elm</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([=|])\s+([A-Z][0-9A-Z_a-z]*)\b</string>
            <key>name</key>
            <string>meta.record.field.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-prefix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-record</string>
          </dict>
        </array>
      </dict>
      <key>type-record</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function.type-record.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.elm</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.record.field.elm</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.elm</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([a-z][0-9A-Z_a-z]*)\s+(:)</string>
            <key>name</key>
            <string>meta.record.field.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-prefix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-record</string>
          </dict>
        </array>
      </dict>
      <key>type-signature</key>
      <dict>
        <key>begin</key>
        <string>^(port\s+)?([_a-z]['0-9A-Z_a-z]*)\s+(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.port.elm</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.elm</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.colon.elm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(((?=[a-z]))|$)</string>
        <key>name</key>
        <string>meta.function.type-declaration.elm</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-signature-chunk</string>
          </dict>
        </array>
      </dict>
      <key>type-signature-chunk</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
            <key>name</key>
            <string>punctuation.spaces.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-prefix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[A-Z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>storage.type.elm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(\)</string>
            <key>name</key>
            <string>constant.unit.elm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-record</string>
          </dict>
        </array>
      </dict>
      <key>unit</key>
      <dict>
        <key>match</key>
        <string>\(\)</string>
        <key>name</key>
        <string>constant.unit.elm</string>
      </dict>
      <key>value</key>
      <dict>
        <key>match</key>
        <string>\b[a-z][0-9A-Z_a-z]*\b</string>
        <key>name</key>
        <string>meta.value.elm</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.elm</string>
  </dict>
</plist>