<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>js</string>
      <string>jsx</string>
      <string>ts</string>
      <string>tsx</string>
      <string>html</string>
      <string>vue</string>
      <string>svelte</string>
      <string>php</string>
      <string>res</string>
    </array>
    <key>injectTo</key>
    <array>
      <string>source.ts</string>
      <string>source.js</string>
    </array>
    <key>injectionSelector</key>
    <string>L:source.js -comment -string, L:source.js -comment -string, L:source.jsx -comment -string,  L:source.js.jsx -comment -string, L:source.ts -comment -string, L:source.tsx -comment -string, L:source.rescript -comment -string</string>
    <key>injections</key>
    <dict>
      <key>L:source</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&lt;</string>
            <key>name</key>
            <string>invalid.illegal.bad-angle-bracket.html</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>name</key>
    <string>es-tag-glsl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(?i)(\s?/\*\s?((?:|inline-)glsl)\s?\*/\s?)(`)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.block</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(`)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#template-substitution-element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.glsl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>inline.es6-htmlx#template</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?i)(\s*((?:|inline-)glsl))(`)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.block</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(`)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#template-substitution-element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.glsl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>inline.es6-htmlx#template</string>
          </dict>
          <dict>
            <key>include</key>
            <string>string.quoted.other.template.js</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?i)(?&lt;=[(,:=\s]|\$\()\s*(((/\*)|(//))\s?((?:|inline-)glsl) {0,1000}\*?/?) {0,1000}$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.line</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(`).*</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G()</string>
            <key>end</key>
            <string>(`)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts#template-substitution-element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.glsl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(\$\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#template-substitution-element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>scopeName</key>
    <string>inline.es6-glsl</string>
  </dict>
</plist>