<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>gdshader</string>
    </array>
    <key>name</key>
    <string>gdshader</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#any</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>any</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enclosed</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#classifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#separator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
        </array>
      </dict>
      <key>arraySize</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.gdshader</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>name</key>
        <string>meta.array-size.gdshader</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#element</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#separator</string>
          </dict>
        </array>
      </dict>
      <key>classifier</key>
      <dict>
        <key>begin</key>
        <string>(?=\b(?:shader_type|render_mode)\b)</string>
        <key>end</key>
        <string>(?&lt;=;)</string>
        <key>name</key>
        <string>meta.classifier.gdshader</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifierClassification</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#separator</string>
          </dict>
        </array>
      </dict>
      <key>classifierKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:shader_type|render_mode)\b</string>
        <key>name</key>
        <string>keyword.language.classifier.gdshader</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#commentLine</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#commentBlock</string>
          </dict>
        </array>
      </dict>
      <key>commentBlock</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.gdshader</string>
      </dict>
      <key>commentLine</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.gdshader</string>
      </dict>
      <key>constantFloat</key>
      <dict>
        <key>match</key>
        <string>\b(?:E|PI|TAU)\b</string>
        <key>name</key>
        <string>constant.language.float.gdshader</string>
      </dict>
      <key>constructor</key>
      <dict>
        <key>match</key>
        <string>\b(?:[A-Z_a-z]\w*(?=\s*\[\s*\w*\s*]\s*\()|[A-Z]\w*(?=\s*\())</string>
        <key>name</key>
        <string>entity.name.type.constructor.gdshader</string>
      </dict>
      <key>controlKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:if|else|do|while|for|continue|break|switch|case|default|return|discard)\b</string>
        <key>name</key>
        <string>keyword.control.gdshader</string>
      </dict>
      <key>definition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#structDefinition</string>
          </dict>
        </array>
      </dict>
      <key>element</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literalFloat</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literalInt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literalBool</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifierType</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constructor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#processorFunction</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifierFunction</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#swizzling</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifierField</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constantFloat</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#languageVariable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifierVariable</string>
          </dict>
        </array>
      </dict>
      <key>enclosed</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.gdshader</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>meta.parenthesis.gdshader</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#any</string>
          </dict>
        </array>
      </dict>
      <key>fieldDefinition</key>
      <dict>
        <key>begin</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#typeKeyword</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.+</string>
                <key>name</key>
                <string>entity.name.type.gdshader</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=;)</string>
        <key>name</key>
        <string>meta.definition.field.gdshader</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#arraySize</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fieldName</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#any</string>
          </dict>
        </array>
      </dict>
      <key>fieldName</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>name</key>
        <string>entity.name.variable.field.gdshader</string>
      </dict>
      <key>hintKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:source_color|hint_(?:color|range|(?:black_)?albedo|normal|(?:default_)?(?:white|black)|aniso|anisotropy|roughness_(?:[abgr]|normal|gray))|filter_(?:nearest|linear)(?:_mipmap(?:_anisotropic)?)?|repeat_(?:en|dis)able)\b</string>
        <key>name</key>
        <string>support.type.annotation.gdshader</string>
      </dict>
      <key>identifierClassification</key>
      <dict>
        <key>match</key>
        <string>\b[_a-z]+\b</string>
        <key>name</key>
        <string>entity.other.inherited-class.gdshader</string>
      </dict>
      <key>identifierField</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.gdshader</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.field.gdshader</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\.)\s*([A-Z_a-z]\w*)\b(?!\s*\()</string>
      </dict>
      <key>identifierFunction</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*(?=(?:\s|/\*(?:\*(?!/)|[^*])*\*/)*\()</string>
        <key>name</key>
        <string>entity.name.function.gdshader</string>
      </dict>
      <key>identifierType</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*(?=(?:\s*\[\s*\w*\s*])?\s+[A-Z_a-z]\w*\b)</string>
        <key>name</key>
        <string>entity.name.type.gdshader</string>
      </dict>
      <key>identifierVariable</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>name</key>
        <string>variable.name.gdshader</string>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#classifierKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#controlKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#modifierKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#precisionKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typeKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hintKeyword</string>
          </dict>
        </array>
      </dict>
      <key>languageVariable</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z][0-9A-Z_]*\b</string>
        <key>name</key>
        <string>variable.language.gdshader</string>
      </dict>
      <key>literalBool</key>
      <dict>
        <key>match</key>
        <string>\b(?:false|true)\b</string>
        <key>name</key>
        <string>constant.language.boolean.gdshader</string>
      </dict>
      <key>literalFloat</key>
      <dict>
        <key>match</key>
        <string>\b(?:\d+[Ee][-+]?\d+|(?:\d*\.\d+|\d+\.)(?:[Ee][-+]?\d+)?)[Ff]?</string>
        <key>name</key>
        <string>constant.numeric.float.gdshader</string>
      </dict>
      <key>literalInt</key>
      <dict>
        <key>match</key>
        <string>\b(?:0[Xx]\h+|\d+[Uu]?)\b</string>
        <key>name</key>
        <string>constant.numeric.integer.gdshader</string>
      </dict>
      <key>modifierKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:const|global|instance|uniform|varying|in|out|inout|flat|smooth)\b</string>
        <key>name</key>
        <string>storage.modifier.gdshader</string>
      </dict>
      <key>operator</key>
      <dict>
        <key>match</key>
        <string>&lt;&lt;=?|&gt;&gt;=?|[-!\&amp;*+/&lt;=&gt;|]=|&amp;&amp;|\|\||[-!%\&amp;*+/&lt;=&gt;^|~]</string>
        <key>name</key>
        <string>keyword.operator.gdshader</string>
      </dict>
      <key>precisionKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:low|medium|high)p\b</string>
        <key>name</key>
        <string>storage.type.built-in.primitive.precision.gdshader</string>
      </dict>
      <key>processorFunction</key>
      <dict>
        <key>match</key>
        <string>\b(?:vertex|fragment|light|start|process|sky|fog)(?=(?:\s|/\*(?:\*(?!/)|[^*])*\*/)*\()</string>
        <key>name</key>
        <string>support.function.gdshader</string>
      </dict>
      <key>separator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>punctuation.accessor.gdshader</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#separatorComma</string>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.terminator.statement.gdshader</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.operator.type.annotation.gdshader</string>
          </dict>
        </array>
      </dict>
      <key>separatorComma</key>
      <dict>
        <key>match</key>
        <string>,</string>
        <key>name</key>
        <string>punctuation.separator.comma.gdshader</string>
      </dict>
      <key>structDefinition</key>
      <dict>
        <key>begin</key>
        <string>(?=\bstruct\b)</string>
        <key>end</key>
        <string>(?&lt;=;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structName</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structDefinitionBlock</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#separator</string>
          </dict>
        </array>
      </dict>
      <key>structDefinitionBlock</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.struct.gdshader</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>name</key>
        <string>meta.definition.block.struct.gdshader</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#precisionKeyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fieldDefinition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#any</string>
          </dict>
        </array>
      </dict>
      <key>structKeyword</key>
      <dict>
        <key>match</key>
        <string>\bstruct\b</string>
        <key>name</key>
        <string>keyword.other.struct.gdshader</string>
      </dict>
      <key>structName</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>name</key>
        <string>entity.name.type.struct.gdshader</string>
      </dict>
      <key>swizzling</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.gdshader</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.gdshader</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\.)\s*([w-z]{2,4}|[abgr]{2,4}|[pqst]{2,4})\b</string>
      </dict>
      <key>typeKeyword</key>
      <dict>
        <key>match</key>
        <string>\b(?:void|bool|[biu]?vec[234]|u?int|float|mat[234]|[iu]?sampler(?:3D|2D(?:Array)?)|samplerCube)\b</string>
        <key>name</key>
        <string>support.type.gdshader</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.gdshader</string>
  </dict>
</plist>