<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>git-commit</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(?=^diff --git)</string>
        <key>contentName</key>
        <string>source.diff</string>
        <key>end</key>
        <string>\z</string>
        <key>name</key>
        <string>meta.embedded.diff.git-commit</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.diff</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(?!#)</string>
        <key>end</key>
        <string>^(?=#)</string>
        <key>name</key>
        <string>meta.scope.message.git-commit</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.deprecated.line-too-long.git-commit</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.line-too-long.git-commit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\G.{0,50}(.{0,22}(.*))$</string>
            <key>name</key>
            <string>meta.scope.subject.git-commit</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(?=#)</string>
        <key>contentName</key>
        <string>comment.line.number-sign.git-commit</string>
        <key>end</key>
        <string>^(?!#)</string>
        <key>name</key>
        <string>meta.scope.metadata.git-commit</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>markup.changed.git-commit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^#\t((modified|renamed):.*)$</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>markup.inserted.git-commit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^#\t(new file:.*)$</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>markup.deleted.git-commit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^#\t(deleted.*)$</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.file-type.git-commit</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.filename.git-commit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^#\t([^:]+): *(.*)$</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>scopeName</key>
    <string>text.git-commit</string>
  </dict>
</plist>