<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>gleam</string>
    </array>
    <key>name</key>
    <string>gleam</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#entity</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#discards</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>binary_number</key>
      <dict>
        <key>match</key>
        <string>\b0[Bb][01_]*\b</string>
        <key>name</key>
        <string>constant.numeric.binary.gleam</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>//.*</string>
            <key>name</key>
            <string>comment.line.gleam</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#binary_number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#octal_number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hexadecimal_number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#decimal_number</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\p{upper}\p{alnum}*</string>
            <key>name</key>
            <string>entity.name.type.gleam</string>
          </dict>
        </array>
      </dict>
      <key>decimal_number</key>
      <dict>
        <key>match</key>
        <string>\b([0-9][0-9_]*)(\.([0-9_]*)?(e-?[0-9]+)?)?\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.gleam</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>discards</key>
      <dict>
        <key>match</key>
        <string>\b_\p{word}+{0,1}\b</string>
        <key>name</key>
        <string>comment.unused.gleam</string>
      </dict>
      <key>entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(\p{lower}\p{word}*)\b\s*\(</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.gleam</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\p{lower}\p{word}*):\s</string>
            <key>name</key>
            <string>variable.parameter.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\p{lower}\p{word}*):</string>
            <key>name</key>
            <string>entity.name.namespace.gleam</string>
          </dict>
        </array>
      </dict>
      <key>hexadecimal_number</key>
      <dict>
        <key>match</key>
        <string>\b0[Xx][_\h]+\b</string>
        <key>name</key>
        <string>constant.numeric.hexadecimal.gleam</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(as|use|case|if|fn|import|let|assert|pub|type|opaque|const|todo|panic|else|echo)\b</string>
            <key>name</key>
            <string>keyword.control.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;-|-&gt;)</string>
            <key>name</key>
            <string>keyword.operator.arrow.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|&gt;</string>
            <key>name</key>
            <string>keyword.operator.pipe.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>keyword.operator.splat.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([!=]=)</string>
            <key>name</key>
            <string>keyword.operator.comparison.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([&lt;&gt;]=?\.)</string>
            <key>name</key>
            <string>keyword.operator.comparison.float.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;=|&gt;=|[&lt;&gt;])</string>
            <key>name</key>
            <string>keyword.operator.comparison.int.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&amp;&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&gt;</string>
            <key>name</key>
            <string>keyword.operator.string.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|</string>
            <key>name</key>
            <string>keyword.operator.other.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-*+/]\.)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.float.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-%*+/])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.int.gleam</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.gleam</string>
          </dict>
        </array>
      </dict>
      <key>octal_number</key>
      <dict>
        <key>match</key>
        <string>\b0[Oo][0-7_]*\b</string>
        <key>name</key>
        <string>constant.numeric.octal.gleam</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>strings</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.gleam</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.gleam</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.gleam</string>
  </dict>
</plist>