<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injections</key>
    <dict>
      <key>L:source.gjs -comment -(string -meta.embedded)</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>name</key>
    <string>glimmer-js</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.js</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>as-keyword</key>
      <dict>
        <key>match</key>
        <string>\s\b(as)\b(?=\s\|)</string>
        <key>name</key>
        <string>keyword.control</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>as-params</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\|)(\|)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.other.symbol.begin.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\|)(?!\|)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.other.symbol.end.ember-handlebars</string>
          </dict>
        </dict>
        <key>name</key>
        <string>keyword.block-params.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
        </array>
      </dict>
      <key>attention</key>
      <dict>
        <key>match</key>
        <string>@?(TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW|NB|BUG|QUESTION|TEMP)\b</string>
        <key>name</key>
        <string>storage.type.class.${1:/downcase}</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>boolean</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.regexp</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.regexp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.regexp</string>
          </dict>
        </dict>
        <key>match</key>
        <string>true|false|undefined|null</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>component-tag</key>
      <dict>
        <key>begin</key>
        <string>(&lt;/?)(@|this.)?([-$.0-:A-Z_a-z]+)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(@|this)</string>
                <key>name</key>
                <string>variable.language</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#glimmer-component-path</string>
              </dict>
              <dict>
                <key>match</key>
                <string>([$:@])</string>
                <key>name</key>
                <string>markup.bold</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(/?)(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.any.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-like-content</string>
          </dict>
        </array>
      </dict>
      <key>digit</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\d*(\.)?\d+</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>entities</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.entity.html.ember-handlebars</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.entity.html.ember-handlebars</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(&amp;)([0-9A-Za-z]+|#[0-9]+|#x\h+)(;)</string>
            <key>name</key>
            <string>constant.character.entity.html.ember-handlebars</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;</string>
            <key>name</key>
            <string>invalid.illegal.bad-ampersand.html.ember-handlebars</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-argument</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.ember-handlebars.argument</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(@)</string>
                <key>name</key>
                <string>markup.italic</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.ember-handlebars</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s(@[-.0-:A-Z_a-z]+)(=)?</string>
      </dict>
      <key>glimmer-as-stuff</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#as-keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#as-params</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-block</key>
      <dict>
        <key>begin</key>
        <string>(\{\{~?)([#/])(([$\--9@-Z_a-z]+))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#glimmer-component-path</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(/)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-as-stuff</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-supexp-content</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-bools</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.regexp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.regexp</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{\{~?)(true|false|null|undefined|\d*(\.)?\d+)(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
      </dict>
      <key>glimmer-comment-block</key>
      <dict>
        <key>begin</key>
        <string>\{\{!--</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.comment.glimmer</string>
          </dict>
        </dict>
        <key>end</key>
        <string>--}}</string>
        <key>name</key>
        <string>comment.block.glimmer</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#script</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attention</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-comment-inline</key>
      <dict>
        <key>begin</key>
        <string>\{\{!</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.comment.glimmer</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}</string>
        <key>name</key>
        <string>comment.inline.glimmer</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#script</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attention</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-component-path</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(::|[$._])</string>
      </dict>
      <key>glimmer-control-expression</key>
      <dict>
        <key>begin</key>
        <string>(\{\{~?)(([-/-9A-Z_a-z]+)\s)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-supexp-content</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-else-block</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#glimmer-subexp</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-single-quoted-handlebars</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-double-quoted-handlebars</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#boolean</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#digit</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#param</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-parameter-name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-parameter-value</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{\{~?)(else(?:\s[a-z]+\s|))([\x08().0-9@-Za-z\s]+)?(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
      </dict>
      <key>glimmer-expression</key>
      <dict>
        <key>begin</key>
        <string>(\{\{~?)(([-().0-9@-Z_a-z\s]+))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\(+</string>
                <key>name</key>
                <string>string.regexp</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\)+</string>
                <key>name</key>
                <string>string.regexp</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-supexp-content</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-supexp-content</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-expression-property</key>
      <dict>
        <key>begin</key>
        <string>(\{\{~?)((@|this.)([-.0-9A-Z_a-z]+))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(@|this)</string>
                <key>name</key>
                <string>variable.language</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-supexp-content</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-parameter-name</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.name.ember-handlebars</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.expression.ember-handlebars</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b([-0-9A-Z_a-z]+)(\s?=)</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>glimmer-parameter-value</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\b([-.0-:A-Z_a-z]+)\b(?!=)</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>glimmer-special-block</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{\{~?)(yield|outlet)(~?}})</string>
        <key>name</key>
        <string>entity.expression.ember-handlebars</string>
      </dict>
      <key>glimmer-subexp</key>
      <dict>
        <key>begin</key>
        <string>(\()([-.0-9@-Za-z]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>name</key>
        <string>entity.subexpression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-supexp-content</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-supexp-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-subexp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-single-quoted-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-double-quoted-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#digit</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-parameter-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-parameter-value</string>
          </dict>
        </array>
      </dict>
      <key>glimmer-unescaped-expression</key>
      <dict>
        <key>begin</key>
        <string>\{\{\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}}</string>
        <key>name</key>
        <string>entity.unescaped.expression.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-single-quoted-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-double-quoted-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-subexp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#param</string>
          </dict>
        </array>
      </dict>
      <key>html-attribute</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.ember-handlebars</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\.\.\.attributes)</string>
                <key>name</key>
                <string>markup.bold</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.ember-handlebars</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s([-.0-:A-Z_a-z]+)(=)?</string>
      </dict>
      <key>html-comment</key>
      <dict>
        <key>begin</key>
        <string>&lt;!--</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.html.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>--\s*&gt;</string>
        <key>name</key>
        <string>comment.block.html.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attention</string>
          </dict>
          <dict>
            <key>match</key>
            <string>--</string>
            <key>name</key>
            <string>invalid.illegal.bad-comments-or-CDATA.html.ember-handlebars</string>
          </dict>
        </array>
      </dict>
      <key>html-tag</key>
      <dict>
        <key>begin</key>
        <string>(&lt;/?)([-0-9a-z]+)(?![.:])\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(/?)(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.any.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-like-content</string>
          </dict>
        </array>
      </dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(template)\s*(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.other.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(template)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.other.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.js.embeddedTemplateWithoutArgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#style</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-else-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-bools</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-special-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-unescaped-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-comment-inline</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-expression-property</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-control-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#component-tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#entities</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)(template)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.other.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(template)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.other.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.js.embeddedTemplateWithArgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&lt;template)</string>
                <key>end</key>
                <string>(?=&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#tag-like-content</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(&gt;)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.js</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>meta.html.embedded.block</string>
                <key>end</key>
                <string>(?=&lt;/template&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#style</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#script</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-else-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-bools</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-special-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-unescaped-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-inline</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression-property</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-control-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#component-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-comment</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#entities</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b((?:\w+\.)*h(?:bs|tml)\s*)(`)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.tagged-template.js</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.template.begin.js</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.block.html</string>
            <key>end</key>
            <string>(`)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.js</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.template.end.js</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#template-substitution-element</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#style</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-else-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-bools</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-special-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-unescaped-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-comment-inline</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-expression-property</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-control-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#glimmer-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#component-tag</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#entities</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((createTemplate|hbs|html))(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ts</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.function-call.ts</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.ts</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.block.html</string>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.ts</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>((["'`]))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>string.template.ts</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.template.begin.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>((["'`]))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>string.template.ts</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.template.end.ts</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#style</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#script</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-else-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-bools</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-special-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-unescaped-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-inline</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression-property</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-control-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#component-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-comment</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#entities</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((precompileTemplate)\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ts</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.function-call.ts</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.ts</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>((["'`]))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>string.template.ts</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.template.begin.ts</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>meta.embedded.block.html</string>
                <key>end</key>
                <string>((["'`]))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>string.template.ts</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.template.end.ts</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#style</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#script</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-else-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-bools</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-special-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-unescaped-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-comment-inline</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression-property</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-control-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-expression</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#component-tag</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-comment</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#entities</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#object-literal</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>param</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(@|this)</string>
                <key>name</key>
                <string>variable.language</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\.)+</string>
                <key>name</key>
                <string>punctuation.definition.tag</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@|this.)([-.0-9A-Z_a-z]+)</string>
        <key>patterns</key>
        <array/>
      </dict>
      <key>script</key>
      <dict>
        <key>begin</key>
        <string>(^[\t ]+)?(?=&lt;(?i:script)\b(?!-))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)([\t ]*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(&lt;)((?i:script))\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.tag.metadata.script.start.html</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(/)((?i:script))(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.tag.metadata.script.end.html</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.html</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G</string>
                <key>end</key>
                <string>(?=/)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>meta.tag.metadata.script.start.html</string>
                      </dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.end.html</string>
                      </dict>
                    </dict>
                    <key>end</key>
                    <string>((&lt;))(?=/(?i:script))</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>meta.tag.metadata.script.end.html</string>
                      </dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin.html</string>
                      </dict>
                      <key>2</key>
                      <dict>
                        <key>name</key>
                        <string>source.js-ignored-vscode</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>begin</key>
                        <string>\G</string>
                        <key>end</key>
                        <string>(?=&lt;/(?i:script))</string>
                        <key>name</key>
                        <string>source.js</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>begin</key>
                            <string>(^[\t ]+)?(?=//)</string>
                            <key>beginCaptures</key>
                            <dict>
                              <key>1</key>
                              <dict>
                                <key>name</key>
                                <string>punctuation.whitespace.comment.leading.js</string>
                              </dict>
                            </dict>
                            <key>end</key>
                            <string>(?!\G)</string>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>begin</key>
                                <string>//</string>
                                <key>beginCaptures</key>
                                <dict>
                                  <key>0</key>
                                  <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.comment.js</string>
                                  </dict>
                                </dict>
                                <key>end</key>
                                <string>(?=&lt;/script)|\n</string>
                                <key>name</key>
                                <string>comment.line.double-slash.js</string>
                              </dict>
                            </array>
                          </dict>
                          <dict>
                            <key>begin</key>
                            <string>/\*</string>
                            <key>captures</key>
                            <dict>
                              <key>0</key>
                              <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.js</string>
                              </dict>
                            </dict>
                            <key>end</key>
                            <string>\*/|(?=&lt;/script)</string>
                            <key>name</key>
                            <string>comment.block.js</string>
                          </dict>
                          <dict>
                            <key>include</key>
                            <string>source.js</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?i:(?=type\s*=\s*(["']?)text/(x-handlebars|(x-(handlebars-)?|ng-)?template|html)["'&gt;\s]))</string>
                    <key>end</key>
                    <string>((&lt;))(?=/(?i:script))</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>meta.tag.metadata.script.end.html</string>
                      </dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin.html</string>
                      </dict>
                      <key>2</key>
                      <dict>
                        <key>name</key>
                        <string>text.html.basic</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>begin</key>
                        <string>(?!\G)</string>
                        <key>end</key>
                        <string>(?=&lt;/(?i:script))</string>
                        <key>name</key>
                        <string>text.html.basic</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>text.html.basic</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(?=(?i:type))</string>
                    <key>end</key>
                    <string>(&lt;)(?=/(?i:script))</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>meta.tag.metadata.script.end.html</string>
                      </dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin.html</string>
                      </dict>
                    </dict>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#string-double-quoted-html</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#string-single-quoted-html</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-argument</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-attribute</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-double-quoted-handlebars</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ember-handlebars</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\"</string>
            <key>name</key>
            <string>constant.character.escape.ember-handlebars</string>
          </dict>
        </array>
      </dict>
      <key>string-double-quoted-html</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ember-handlebars</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.html.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\"</string>
            <key>name</key>
            <string>constant.character.escape.ember-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-bools</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression-property</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-control-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-block</string>
          </dict>
        </array>
      </dict>
      <key>string-single-quoted-handlebars</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ember-handlebars</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\'</string>
            <key>name</key>
            <string>constant.character.escape.ember-handlebars</string>
          </dict>
        </array>
      </dict>
      <key>string-single-quoted-html</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ember-handlebars</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ember-handlebars</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.html.ember-handlebars</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\'</string>
            <key>name</key>
            <string>constant.character.escape.ember-handlebars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-bools</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression-property</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-control-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-block</string>
          </dict>
        </array>
      </dict>
      <key>style</key>
      <dict>
        <key>begin</key>
        <string>(^[\t ]+)?(?=&lt;(?i:style)\b(?!-))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)([\t ]*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?i)(&lt;)(style)(?=\s|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.tag.metadata.style.start.html</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)((&lt;)/)(style)\s*(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.tag.metadata.style.end.html</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>source.css-ignored-vscode</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.html</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.html</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(&gt;)</string>
                <key>name</key>
                <string>meta.tag.metadata.style.start.html</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#glimmer-argument</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#html-attribute</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?!\G)</string>
                <key>end</key>
                <string>(?=&lt;/(?i:style))</string>
                <key>name</key>
                <string>source.css</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tag-like-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#glimmer-bools</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-unescaped-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-comment-inline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression-property</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#digit</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-control-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-double-quoted-html</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-single-quoted-html</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-as-stuff</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#glimmer-argument</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-attribute</string>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>match</key>
        <string>\b([-0-9A-Z_a-z]+)\b</string>
        <key>name</key>
        <string>support.function</string>
        <key>patterns</key>
        <array/>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.gjs</string>
  </dict>
</plist>