<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>gp</string>
      <string>plt</string>
      <string>plot</string>
      <string>gnuplot</string>
    </array>
    <key>name</key>
    <string>gnuplot</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>(\\(?!\n).*)</string>
        <key>name</key>
        <string>invalid.illegal.backslash.gnuplot</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(;)</string>
        <key>name</key>
        <string>punctuation.separator.statement.gnuplot</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#LineComment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#DataBlock</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#MacroExpansion</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#VariableDecl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#ArrayDecl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#FunctionDecl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#ShellCommand</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Command</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>ArrayDecl</key>
      <dict>
        <key>begin</key>
        <string>\b(array)\s+([A-Z_a-z]\w*)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.array.gnuplot</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.gnuplot</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#InvalidVariableDecl</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#BuiltinVariable</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
        <key>name</key>
        <string>meta.variable.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
      <key>BuiltinFunction</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bdefined\b</string>
            <key>name</key>
            <string>invalid.deprecated.function.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:abs|acosh??|airy|arg|asinh??|atan2??|atanh|EllipticK|EllipticE|EllipticPi|besj0|besj1|besy0|besy1|ceil|cosh??|erfc??|exp|expint|floor|gamma|ibeta|inverf|igamma|imag|invnorm|int|lambertw|lgamma|log|log10|norm|rand|real|sgn|sinh??|sqrt|tanh??|voigt|cerf|cdawson|faddeeva|erfi|VP)\b</string>
            <key>name</key>
            <string>support.function.math.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:gprintf|sprintf|strlen|strstrt|substr|strftime|strptime|system|words??)\b</string>
            <key>name</key>
            <string>support.function.string.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:column|columnhead|exists|hsv2rgb|stringcolumn|timecolumn|tm_hour|tm_mday|tm_min|tm_mon|tm_sec|tm_wday|tm_yday|tm_year|time|valid|value)\b</string>
            <key>name</key>
            <string>support.function.other.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>BuiltinOperator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&amp;&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;&lt;|&gt;&gt;|[\&amp;^|])</string>
            <key>name</key>
            <string>keyword.operator.bitwise.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=|&lt;=?|&gt;=?)</string>
            <key>name</key>
            <string>keyword.operator.comparison.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-!+~])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\*\*|[-%*+/])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.gnuplot</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.word.gnuplot</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\.|\b(eq|ne)\b)</string>
            <key>name</key>
            <string>keyword.operator.strings.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>BuiltinVariable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bFIT_(?:LIMIT|MAXITER|START_LAMBDA|LAMBDA_FACTOR|SKIP|INDEX)\b</string>
            <key>name</key>
            <string>invalid.deprecated.variable.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(GPVAL_\w*|MOUSE_\w*)\b</string>
            <key>name</key>
            <string>support.constant.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ARG[0-9C]|GPFUN_\w*|FIT_\w*|STATS_\w*|pi|NaN)\b</string>
            <key>name</key>
            <string>support.variable.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>ColumnIndexLiteral</key>
      <dict>
        <key>match</key>
        <string>(\$[0-9]+)\b</string>
        <key>name</key>
        <string>support.constant.columnindex.gnuplot</string>
      </dict>
      <key>Command</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\bupdate\b</string>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>name</key>
            <string>invalid.deprecated.command.gnuplot</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(?:break|clear|continue|pwd|refresh|replot|reread|shell)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#InvalidWord</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(?:cd|call|eval|exit|help|history|load|lower|pause|print|printerr|quit|raise|save|stats|system|test|toggle)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(import)\s(.+)\s(from)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.gnuplot</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#FunctionDecl</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#SingleQuotedStringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#DoubleQuotedStringLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#InvalidWord</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(reset)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(bind|error(state)?|session)\b</string>
                <key>name</key>
                <string>support.class.reset.gnuplot</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#InvalidWord</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(undefine)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#BuiltinVariable</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#BuiltinFunction</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;=\s)(\$?[A-Z_a-z]\w*\*?)(?=\s)</string>
                <key>name</key>
                <string>source.gnuplot</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#InvalidWord</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(if|while)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#{]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(else)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#{]|\\(?!\n)|(?&lt;!\\)\n$))</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(do)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.flow.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#{]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#ForIterationExpr</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(set)(?=\s+pm3d)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(hidden3d|map|transparent|solid)\b</string>
                <key>name</key>
                <string>invalid.deprecated.options.gnuplot</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#SetUnsetOptions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#ForIterationExpr</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b((un)?set)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#SetUnsetOptions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#ForIterationExpr</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(show)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#ExtraShowOptions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#SetUnsetOptions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(fit|(s)?plot)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command.gnuplot</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#ColumnIndexLiteral</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#PlotModifiers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#ForIterationExpr</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>DataBlock</key>
      <dict>
        <key>begin</key>
        <string>(\$[A-Z_a-z]\w*)\s*(&lt;&lt;)\s*([A-Z_a-z]\w*)\s*(?=(#|$))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#SpecialVariable</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.datablock.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(\3)\b(.*)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.language.datablock.gnuplot</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.datablock.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.datablock.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#LineComment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#NumberLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#DoubleQuotedStringLiteral</string>
          </dict>
        </array>
      </dict>
      <key>DeprecatedScriptArgsLiteral</key>
      <dict>
        <key>match</key>
        <string>(\$[#0-9])</string>
        <key>name</key>
        <string>invalid.illegal.scriptargs.gnuplot</string>
      </dict>
      <key>DoubleQuotedStringLiteral</key>
      <dict>
        <key>begin</key>
        <string>(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((")|(?=(?&lt;!\\)\n$))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#EscapedChar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#RGBColorSpec</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#DeprecatedScriptArgsLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#InterpolatedStringLiteral</string>
          </dict>
        </array>
      </dict>
      <key>EscapedChar</key>
      <dict>
        <key>match</key>
        <string>(\\.)</string>
        <key>name</key>
        <string>constant.character.escape.gnuplot</string>
      </dict>
      <key>Expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#SpecialVariable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#BuiltinVariable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#BuiltinOperator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#TernaryExpr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#FunctionCallExpr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#SummationExpr</string>
          </dict>
        </array>
      </dict>
      <key>ExtraShowOptions</key>
      <dict>
        <key>match</key>
        <string>\b(?:all|bind|colornames|functions|plot|variables|version)\b</string>
        <key>name</key>
        <string>support.class.options.gnuplot</string>
      </dict>
      <key>ForIterationExpr</key>
      <dict>
        <key>begin</key>
        <string>\b(for)\s*(\[)\s*(?:([A-Z_a-z]\w*)\s+(in)\b)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.gnuplot</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#RangeSeparators</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.iterator.gnuplot</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((])|(?=(#|\\(?!\n)|(?&lt;!\\)\n$)))</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#RangeSeparators</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#RangeSeparators</string>
          </dict>
        </array>
      </dict>
      <key>FunctionCallExpr</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.function.gnuplot</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#BuiltinFunction</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.arguments.begin.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((\))|(?=(#|\\(?!\n)|(?&lt;!\\)\n$)))</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.arguments.end.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function-call.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
      <key>FunctionDecl</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*((\()\s*([A-Z_a-z]\w*)\s*(?:(,)\s*([A-Z_a-z]\w*)\s*)*(\)))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.gnuplot</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#BuiltinFunction</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.function.parameters.gnuplot</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.gnuplot</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.function.language.gnuplot</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.parameters.gnuplot</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.function.language.gnuplot</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
        <key>name</key>
        <string>meta.function.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
      <key>InterpolatedStringLiteral</key>
      <dict>
        <key>begin</key>
        <string>(`)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((`)|(?=(?&lt;!\\)\n$))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#EscapedChar</string>
          </dict>
        </array>
      </dict>
      <key>InvalidVariableDecl</key>
      <dict>
        <key>match</key>
        <string>\b(GPVAL_\w*|MOUSE_\w*)\b</string>
        <key>name</key>
        <string>invalid.illegal.variable.gnuplot</string>
      </dict>
      <key>InvalidWord</key>
      <dict>
        <key>match</key>
        <string>([^#;\\\s]+)</string>
        <key>name</key>
        <string>invalid.illegal.gnuplot</string>
      </dict>
      <key>LineComment</key>
      <dict>
        <key>begin</key>
        <string>(#)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?&lt;!\\)\n$)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.line.number-sign.gnuplot</string>
      </dict>
      <key>Literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#NumberLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#DeprecatedScriptArgsLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#SingleQuotedStringLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#DoubleQuotedStringLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#InterpolatedStringLiteral</string>
          </dict>
        </array>
      </dict>
      <key>MacroExpansion</key>
      <dict>
        <key>begin</key>
        <string>(@[A-Z_a-z]\w*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#SpecialVariable</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
      <key>NumberLiteral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((\b([0-9]+)|(?&lt;!\d)))(\.[0-9]+)([Ee][-+]?[0-9]+)?(cm|in)?\b</string>
            <key>name</key>
            <string>constant.numeric.float.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+)((([Ee][-+]?[0-9]+))\b|(\.([Ee][-+]?[0-9]+\b)?))((?:cm|in)\b)?</string>
            <key>name</key>
            <string>constant.numeric.float.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0[Xx]\h+)(cm|in)?\b</string>
            <key>name</key>
            <string>constant.numeric.hex.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0+)(cm|in)?\b</string>
            <key>name</key>
            <string>constant.numeric.dec.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0[0-7]+)(cm|in)?\b</string>
            <key>name</key>
            <string>constant.numeric.oct.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0[0-9]+)(cm|in)?\b</string>
            <key>name</key>
            <string>invalid.illegal.oct.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+)(cm|in)?\b</string>
            <key>name</key>
            <string>constant.numeric.dec.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>PlotModifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(thru)\b</string>
            <key>name</key>
            <string>invalid.deprecated.plot.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:in(dex)?|every|us(ing)?|wi(th)?|via)\b</string>
            <key>name</key>
            <string>storage.type.plot.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(newhist(ogram)?)\b</string>
            <key>name</key>
            <string>storage.type.plot.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>RGBColorSpec</key>
      <dict>
        <key>match</key>
        <string>\G(0x|#)((\h{6})|(\h{8}))\b</string>
        <key>name</key>
        <string>constant.other.placeholder.gnuplot</string>
      </dict>
      <key>RangeSeparators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\[)</string>
            <key>name</key>
            <string>punctuation.section.brackets.begin.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(:)</string>
            <key>name</key>
            <string>punctuation.separator.range.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(])</string>
            <key>name</key>
            <string>punctuation.section.brackets.end.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>SetUnsetOptions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\G\s*\b(?:clabel|data|function|historysize|macros|ticslevel|ticscale|(style\s+increment\s+\w+))\b</string>
            <key>name</key>
            <string>invalid.deprecated.options.gnuplot</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\G\s*\b(?:angles|arrow|autoscale|border|boxwidth|clip|cntr(label|param)|color(box|sequence)?|contour|(dash|line)type|datafile|decimal(sign)?|dgrid3d|dummy|encoding|(error)?bars|fit|fontpath|format|grid|hidden3d|history|(iso)?samples|jitter|key|label|link|loadpath|locale|logscale|mapping|[blrt]margin|margins|micro|minus(sign)?|mono(chrome)?|mouse|multiplot|nonlinear|object|offsets|origin|output|parametric|([pr])axis|pm3d|palette|pointintervalbox|pointsize|polar|print|psdir|size|style|surface|table|terminal|termoption|theta|tics|timestamp|timefmt|title|view|xyplane|zero|(no)?(m)?(x2??|y2??|z|cb|[rt])tics|(x2??|y2??|z|cb)data|(x2??|y2??|z|cb|r)label|(x2??|y2??|z|cb)dtics|(x2??|y2??|z|cb)mtics|(x2??|y2??|z|cb|[rtuv])range|(x2??|y2??|z)?zeroaxis)\b</string>
            <key>name</key>
            <string>support.class.options.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>ShellCommand</key>
      <dict>
        <key>begin</key>
        <string>(!)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.shell.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(#|\\(?!\n)|(?&lt;!\\)\n$))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([^#]|\\(?=\n))</string>
            <key>name</key>
            <string>string.unquoted</string>
          </dict>
        </array>
      </dict>
      <key>SingleQuotedStringLiteral</key>
      <dict>
        <key>begin</key>
        <string>(')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((')(?!')|(?=(?&lt;!\\)\n$))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.gnuplot</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#RGBColorSpec</string>
          </dict>
          <dict>
            <key>match</key>
            <string>('')</string>
            <key>name</key>
            <string>constant.character.escape.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>SpecialVariable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.wildcard.gnuplot</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=[:=\[])\s*(\*)\s*(?=[]:])</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.gnuplot</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(([$@])[A-Z_a-z]\w*)\b</string>
            <key>name</key>
            <string>constant.language.special.gnuplot</string>
          </dict>
        </array>
      </dict>
      <key>SummationExpr</key>
      <dict>
        <key>begin</key>
        <string>\b(sum)\s*(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.sum.gnuplot</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#RangeSeparators</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>((])|(?=(#|\\(?!\n)|(?&lt;!\\)\n$)))</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#RangeSeparators</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#RangeSeparators</string>
          </dict>
        </array>
      </dict>
      <key>TernaryExpr</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\?)(\?)(?!\?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.ternary.gnuplot</string>
          </dict>
        </dict>
        <key>end</key>
        <string>((?&lt;!:)(:)(?!:)|(?=(#|\\(?!\n)|(?&lt;!\\)\n$)))</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.ternary.gnuplot</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
      <key>VariableDecl</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*(?:(\[)\s*(.*)\s*(])\s*)?(?=(=)(?!\s*=))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.gnuplot</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#InvalidVariableDecl</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#BuiltinVariable</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#Expression</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=([#;]|\\(?!\n)|(?&lt;!\\)\n$))</string>
        <key>name</key>
        <string>meta.variable.gnuplot</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Expression</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.gnuplot</string>
  </dict>
</plist>