<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>hcl</string>
    </array>
    <key>name</key>
    <string>hcl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attribute_definition</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expressions</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attribute_access</key>
      <dict>
        <key>begin</key>
        <string>\.(?!\*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.accessor.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\p{alpha}[-\w]*|\d*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(?!null|false|true)\p{alpha}[-\w]*</string>
                <key>name</key>
                <string>variable.other.member.hcl</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\d+</string>
                <key>name</key>
                <string>constant.numeric.integer.hcl</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>attribute_definition</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.readwrite.hcl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end.hcl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.hcl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\()?\b((?!(?:null|false|true)\b)\p{alpha}[-_[:alnum:]]*)(\))?\s*(=(?![=&gt;]))\s*</string>
        <key>name</key>
        <string>variable.declaration.hcl</string>
      </dict>
      <key>attribute_splat</key>
      <dict>
        <key>begin</key>
        <string>\.</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.accessor.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.splat.hcl</string>
          </dict>
        </dict>
      </dict>
      <key>block</key>
      <dict>
        <key>begin</key>
        <string>(\w[-\w]*)(([^\n\r\S]+(\w[-_\w]*|"[^\n\r"]*"))*)[^\n\r\S]*(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?!null|false|true)\p{alpha}[-_[:alnum:]]*\b</string>
                <key>name</key>
                <string>entity.name.type.hcl</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>"[^\n\r"]*"</string>
                <key>name</key>
                <string>variable.other.enummember.hcl</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\p{alpha}[-_[:alnum:]]*</string>
                <key>name</key>
                <string>variable.other.enummember.hcl</string>
              </dict>
            </array>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.block.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute_definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
        </array>
      </dict>
      <key>block_inline_comments</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.hcl</string>
      </dict>
      <key>brackets</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brackets.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brackets.end.hcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\*</string>
            <key>name</key>
            <string>keyword.operator.splat.hcl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline_if_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local_identifiers</string>
          </dict>
        </array>
      </dict>
      <key>char_escapes</key>
      <dict>
        <key>match</key>
        <string>\\(?:["\\nrt]|u(\h{8}|\h{4}))</string>
        <key>name</key>
        <string>constant.character.escape.hcl</string>
      </dict>
      <key>comma</key>
      <dict>
        <key>match</key>
        <string>,</string>
        <key>name</key>
        <string>punctuation.separator.hcl</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#hash_line_comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#double_slash_line_comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_inline_comments</string>
          </dict>
        </array>
      </dict>
      <key>double_slash_line_comments</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>comment.line.double-slash.hcl</string>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_values</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tuple_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#objects</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute_access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute_splat</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
        </array>
      </dict>
      <key>for_expression_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bin\b</string>
            <key>name</key>
            <string>keyword.operator.word.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bif\b</string>
            <key>name</key>
            <string>keyword.control.conditional.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local_identifiers</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>begin</key>
        <string>([-:\w]+)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b\p{alpha}[-_\w]*::(\p{alpha}[-_\w]*::)?\p{alpha}[-_\w]*\b</string>
                <key>name</key>
                <string>support.function.namespaced.hcl</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b\p{alpha}[-_\w]*\b</string>
                <key>name</key>
                <string>support.function.builtin.hcl</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function-call.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
        </array>
      </dict>
      <key>hash_line_comments</key>
      <dict>
        <key>begin</key>
        <string>#</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>comment.line.number-sign.hcl</string>
      </dict>
      <key>hcl_type_keywords</key>
      <dict>
        <key>match</key>
        <string>\b(any|string|number|bool|list|set|map|tuple|object)\b</string>
        <key>name</key>
        <string>storage.type.hcl</string>
      </dict>
      <key>heredoc</key>
      <dict>
        <key>begin</key>
        <string>(&lt;&lt;-?)\s*(\w+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.heredoc.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.heredoc.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^\s*\2\s*$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.heredoc.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.heredoc.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_interpolation</string>
          </dict>
        </array>
      </dict>
      <key>inline_for_expression</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>=&gt;</string>
                <key>name</key>
                <string>storage.type.function.hcl</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#for_expression_body</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(for)\b(.*)\n</string>
      </dict>
      <key>inline_if_expression</key>
      <dict>
        <key>begin</key>
        <string>(if)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\n</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local_identifiers</string>
          </dict>
        </array>
      </dict>
      <key>language_constants</key>
      <dict>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
        <key>name</key>
        <string>constant.language.hcl</string>
      </dict>
      <key>literal_values</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric_literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#language_constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hcl_type_keywords</string>
          </dict>
        </array>
      </dict>
      <key>local_identifiers</key>
      <dict>
        <key>match</key>
        <string>\b(?!null|false|true)\p{alpha}[-_[:alnum:]]*\b</string>
        <key>name</key>
        <string>variable.other.readwrite.hcl</string>
      </dict>
      <key>numeric_literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.exponent.hcl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b\d+([Ee][-+]?)\d+\b</string>
            <key>name</key>
            <string>constant.numeric.float.hcl</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.decimal.hcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.exponent.hcl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b\d+(\.)\d+(?:([Ee][-+]?)\d+)?\b</string>
            <key>name</key>
            <string>constant.numeric.float.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+\b</string>
            <key>name</key>
            <string>constant.numeric.integer.hcl</string>
          </dict>
        </array>
      </dict>
      <key>object_for_expression</key>
      <dict>
        <key>begin</key>
        <string>(\{)\s?(for)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end.hcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>storage.type.function.hcl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for_expression_body</string>
          </dict>
        </array>
      </dict>
      <key>object_key_values</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_values</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tuple_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
        </array>
      </dict>
      <key>objects</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.braces.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#objects</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline_for_expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline_if_expression</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.mapping.key.hcl variable.other.readwrite.hcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.hcl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b((?!null|false|true)\p{alpha}[-_[:alnum:]]*)\s*(=(?!=))\s*</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.mapping.key.hcl string.quoted.double.hcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.hcl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.hcl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.hcl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*((").*("))\s*(=)\s*</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.hcl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))\s*([:=])\s*</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.hcl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.hcl</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.mapping.key.hcl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#attribute_access</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attribute_splat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#object_key_values</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&gt;=</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>==</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!=</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>/</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;&amp;</string>
            <key>name</key>
            <string>keyword.operator.logical.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|\|</string>
            <key>name</key>
            <string>keyword.operator.logical.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!</string>
            <key>name</key>
            <string>keyword.operator.logical.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&gt;</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.\.</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end.hcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>string_interpolation</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;![$%])([$%]\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interpolation.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.other.interpolation.end.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.interpolation.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>~\s</string>
            <key>name</key>
            <string>keyword.operator.template.left.trim.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s~</string>
            <key>name</key>
            <string>keyword.operator.template.right.trim.hcl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|else|endif|for|in|endfor)\b</string>
            <key>name</key>
            <string>keyword.control.hcl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local_identifiers</string>
          </dict>
        </array>
      </dict>
      <key>string_literals</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_interpolation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#char_escapes</string>
          </dict>
        </array>
      </dict>
      <key>tuple_for_expression</key>
      <dict>
        <key>begin</key>
        <string>(\[)\s?(for)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brackets.begin.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.hcl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brackets.end.hcl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#for_expression_body</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.hcl</string>
  </dict>
</plist>