<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>hurl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sections</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#http</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#body</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#request</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>```graphql(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>meta.embedded.block.graphql.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.graphql</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>```xml(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>meta.embedded.block.xml.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.xml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>```json(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>meta.embedded.block.json.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.json</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>```csv(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>meta.embedded.block.csv.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.csv</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>```hex(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.plain</string>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>string.quoted.multiline.hurl</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>```base64(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.plain</string>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>string.quoted.multiline.hurl</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>```([^,]*)(,\w+)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type</string>
              </dict>
            </dict>
            <key>end</key>
            <string>```$</string>
            <key>name</key>
            <string>string.quoted.multiline.hurl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>`(\\.|[^\\`])*`</string>
            <key>name</key>
            <string>string.quoted.backtick.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escapes</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(base64|hex),</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.name</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.plain</string>
            <key>end</key>
            <string>;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.function</string>
              </dict>
            </dict>
            <key>name</key>
            <string>support.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#placeholders</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>#.*$</string>
            <key>name</key>
            <string>comment.line.number-sign.hurl</string>
          </dict>
        </array>
      </dict>
      <key>escapes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\["#\\`bnrtu]</string>
            <key>name</key>
            <string>constant.character.escape.hurl</string>
          </dict>
        </array>
      </dict>
      <key>http</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.version.hurl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.status.hurl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(HTTP(/(?:1\.0|1\.1|2))?)([\t ]+([0-9]{3}))?\b</string>
          </dict>
        </array>
      </dict>
      <key>placeholders</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{\{)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.interpolated.hurl</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>variable.other.hurl</string>
            <key>end</key>
            <string>\s*(}})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.interpolated.hurl</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>request</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS|TRACE|CONNECT)\b</string>
            <key>name</key>
            <string>keyword.control.method.hurl</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.url.hurl</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#placeholders</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>(https?://[^\t\n]+)\s*$</string>
            <key>name</key>
            <string>string.unquoted.url.hurl</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^([-0-9A-Za-z]+)(:)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.header.hurl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.hurl</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>string.unquoted.hurl</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>entity.name.tag.header.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#placeholders</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>sections</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*\[(QueryStringParams|Query|FormParams|Form|MultipartFormData|Multipart|Cookies|Captures|Asserts|BasicAuth|Options)]</string>
            <key>name</key>
            <string>entity.name.section.hurl</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>"(\\.|[^"\\])*"</string>
            <key>name</key>
            <string>string.quoted.double.hurl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escapes</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.hurl</string>
  </dict>
</plist>