<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>json5</string>
    </array>
    <key>name</key>
    <string>json5</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.end.json5</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.array.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.array.json5</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^]\s]</string>
            <key>name</key>
            <string>invalid.illegal.expected-array-separator.json5</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>/{2}.*</string>
            <key>name</key>
            <string>comment.single.json5</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json5</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.json5</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json5</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.json5</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>match</key>
        <string>\b(?:true|false|null|Infinity|NaN)\b</string>
        <key>name</key>
        <string>constant.language.json5</string>
      </dict>
      <key>infinity</key>
      <dict>
        <key>match</key>
        <string>(-)*\b(?:Infinity|NaN)\b</string>
        <key>name</key>
        <string>constant.language.json5</string>
      </dict>
      <key>key</key>
      <dict>
        <key>name</key>
        <string>string.key.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringSingle</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#stringDouble</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-0-9A-Z_a-z]</string>
            <key>name</key>
            <string>string.key.json5</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(0x)[0-9A-f]*</string>
            <key>name</key>
            <string>constant.hex.numeric.json5</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[+-.]?(?=[1-9]|0(?!\d))\d+(\.\d+)?([Ee][-+]?\d+)?</string>
            <key>name</key>
            <string>constant.dec.numeric.json5</string>
          </dict>
        </array>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.end.json5</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.dictionary.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#key</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.key-value.json5</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(,)|(?=})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.pair.json5</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.structure.dictionary.value.json5</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[^,\s]</string>
                <key>name</key>
                <string>invalid.illegal.expected-dictionary-separator.json5</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>[^}\s]</string>
            <key>name</key>
            <string>invalid.illegal.expected-dictionary-separator.json5</string>
          </dict>
        </array>
      </dict>
      <key>stringDouble</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.json5</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(?:["/\\bfnrt]|u\h{4})</string>
            <key>name</key>
            <string>constant.character.escape.json5</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unrecognized-string-escape.json5</string>
          </dict>
        </array>
      </dict>
      <key>stringSingle</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.json5</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(?:["/\\bfnrt]|u\h{4})</string>
            <key>name</key>
            <string>constant.character.escape.json5</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unrecognized-string-escape.json5</string>
          </dict>
        </array>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#infinity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#stringSingle</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#stringDouble</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.json5</string>
  </dict>
</plist>