<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>m</string>
    </array>
    <key>name</key>
    <string>matlab</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#all_before_command_dual</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#command_dual</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#all_after_command_dual</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>all_after_command_dual</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_continuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#conjugate_transpose</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#transpose</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
        </array>
      </dict>
      <key>all_before_command_dual</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#classdef</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blocks</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control_statements</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#global_persistent</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#square_brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#indexing_curly_brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#curly_brackets</string>
          </dict>
        </array>
      </dict>
      <key>blocks</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(for)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.for.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.for.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.for.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(if)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.if.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.if.matlab</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.if.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.elseif.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>^</string>
                <key>match</key>
                <string>(\s*)(?:^|[,;\s])(elseif)\b(.*)$\n?</string>
                <key>name</key>
                <string>meta.elseif.matlab</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.else.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>^</string>
                <key>match</key>
                <string>(\s*)(?:^|[,;\s])(else)\b(.*)?$\n?</string>
                <key>name</key>
                <string>meta.else.matlab</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(parfor)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.for.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.for.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.parfor.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G(?!$)</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>meta.parfor-quantity.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(spmd)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.spmd.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.spmd.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.spmd.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G(?!$)</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>meta.spmd-statement.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(switch)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.switch.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.switch.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.switch.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.case.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>^</string>
                <key>match</key>
                <string>(\s*)(?:^|[,;\s])(case)\b(.*)$\n?</string>
                <key>name</key>
                <string>meta.case.matlab</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.otherwise.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>^</string>
                <key>match</key>
                <string>(\s*)(?:^|[,;\s])(otherwise)\b(.*)?$\n?</string>
                <key>name</key>
                <string>meta.otherwise.matlab</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(try)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.try.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.try.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.try.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.catch.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>^</string>
                <key>match</key>
                <string>(\s*)(?:^|[,;\s])(catch)\b(.*)?$\n?</string>
                <key>name</key>
                <string>meta.catch.matlab</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?:^|[,;\s])(while)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.while.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.while.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.while.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>braced_validator_list</key>
      <dict>
        <key>begin</key>
        <string>\s*(\{)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.matlab</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.matlab</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#braced_validator_list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#validator_strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_continuation</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.matlab</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([^"'.{}]+)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>storage.type.matlab</string>
          </dict>
        </array>
      </dict>
      <key>classdef</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(\s*)(classdef)\b\s*(.*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.class.matlab</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>captures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>match</key>
                            <string>[A-Za-z][0-9A-Z_a-z]*</string>
                            <key>name</key>
                            <string>variable.parameter.class.matlab</string>
                          </dict>
                          <dict>
                            <key>begin</key>
                            <string>=\s*</string>
                            <key>end</key>
                            <string>,|(?=\))</string>
                            <key>patterns</key>
                            <array>
                              <dict>
                                <key>match</key>
                                <string>true|false</string>
                                <key>name</key>
                                <string>constant.language.boolean.matlab</string>
                              </dict>
                              <dict>
                                <key>include</key>
                                <string>#string</string>
                              </dict>
                            </array>
                          </dict>
                        </array>
                      </dict>
                      <key>2</key>
                      <dict>
                        <key>name</key>
                        <string>meta.class-declaration.matlab</string>
                      </dict>
                      <key>3</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.section.class.matlab</string>
                      </dict>
                      <key>4</key>
                      <dict>
                        <key>name</key>
                        <string>keyword.operator.other.matlab</string>
                      </dict>
                      <key>5</key>
                      <dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>match</key>
                            <string>[A-Za-z][0-9A-Z_a-z]*(\.[A-Za-z][0-9A-Z_a-z]*)*</string>
                            <key>name</key>
                            <string>entity.other.inherited-class.matlab</string>
                          </dict>
                          <dict>
                            <key>match</key>
                            <string>&amp;</string>
                            <key>name</key>
                            <string>keyword.operator.other.matlab</string>
                          </dict>
                        </array>
                      </dict>
                      <key>6</key>
                      <dict>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>$self</string>
                          </dict>
                        </array>
                      </dict>
                    </dict>
                    <key>match</key>
                    <string>(\([^)]*\))?\s*(([A-Za-z][0-9A-Z_a-z]*)(?:\s*(&lt;)\s*([^%]*))?)\s*($|(?=(%|...)).*)</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.class.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.class.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>^(\s*)(properties)\b([^%]*)\s*(\([^)]*\))?\s*($|(?=%))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.properties.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>match</key>
                        <string>[A-Za-z][0-9A-Z_a-z]*</string>
                        <key>name</key>
                        <string>variable.parameter.properties.matlab</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>=\s*</string>
                        <key>end</key>
                        <string>,|(?=\))</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>match</key>
                            <string>true|false</string>
                            <key>name</key>
                            <string>constant.language.boolean.matlab</string>
                          </dict>
                          <dict>
                            <key>match</key>
                            <string>p(?:ublic|rotected|rivate)</string>
                            <key>name</key>
                            <string>constant.language.access.matlab</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?:^|[,;\s])(end)\b</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.end.properties.matlab</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.properties.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#validators</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(methods)\b([^%]*)\s*(\([^)]*\))?\s*($|(?=%))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.methods.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>match</key>
                        <string>[A-Za-z][0-9A-Z_a-z]*</string>
                        <key>name</key>
                        <string>variable.parameter.methods.matlab</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>=\s*</string>
                        <key>end</key>
                        <string>,|(?=\))</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>match</key>
                            <string>true|false</string>
                            <key>name</key>
                            <string>constant.language.boolean.matlab</string>
                          </dict>
                          <dict>
                            <key>match</key>
                            <string>p(?:ublic|rotected|rivate)</string>
                            <key>name</key>
                            <string>constant.language.access.matlab</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?:^|[,;\s])(end)\b</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.end.methods.matlab</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.methods.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(events)\b([^%]*)\s*(\([^)]*\))?\s*($|(?=%))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.events.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>match</key>
                        <string>[A-Za-z][0-9A-Z_a-z]*</string>
                        <key>name</key>
                        <string>variable.parameter.events.matlab</string>
                      </dict>
                      <dict>
                        <key>begin</key>
                        <string>=\s*</string>
                        <key>end</key>
                        <string>,|(?=\))</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>match</key>
                            <string>true|false</string>
                            <key>name</key>
                            <string>constant.language.boolean.matlab</string>
                          </dict>
                          <dict>
                            <key>match</key>
                            <string>p(?:ublic|rotected|rivate)</string>
                            <key>name</key>
                            <string>constant.language.access.matlab</string>
                          </dict>
                        </array>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?:^|[,;\s])(end)\b</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.end.events.matlab</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.events.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(enumeration)\b([^%]*)\s*($|(?=%))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.enumeration.matlab</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?:^|[,;\s])(end)\b</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.end.enumeration.matlab</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.enumeration.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>command_dual</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.interpolated.matlab</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.command.matlab</string>
          </dict>
          <key>28</key>
          <dict>
            <key>name</key>
            <string>comment.line.percentage.matlab</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(([A-HJ-MO-Zbcdfghklmoq-z]\w*|an??|a([0-9A-Z_a-mo-z]\w*|n[0-9A-Z_a-rt-z]\w*|ns\w+)|ep??|e([0-9A-Z_a-oq-z]\w*|p[0-9A-Z_a-rt-z]\w*|ps\w+)|in|i([0-9A-Z_a-mo-z]\w*|n[0-9A-Z_a-eg-z]\w*|nf\w+)|In??|I([0-9A-Z_a-mo-z]\w*|n[0-9A-Z_a-eg-z]\w*|nf\w+)|j\w+|Na??|N([0-9A-Z_b-z]\w*|a[0-9A-MO-Z_a-z]\w*|aN\w+)|na??|narg??|nargi|nargou??|n([0-9A-Z_b-z]\w*|a([0-9A-Z_a-mopqs-z]\w*|n\w+|r([0-9A-Z_a-fh-z]\w*|g([0-9A-Z_a-hj-nq-z]\w*|i([0-9A-Z_a-mo-z]\w*|n\w+)|o([0-9A-Z_a-tv-z]\w*|u([A-Za-su-z]\w*|t\w+))))))|p|p[0-9A-Z_a-hj-z]\w*|pi\w+)\s+((([^"%-/:-&gt;@\\^{|~\s]|(?=')|(?="))|(\.\^|\.\*|\./|\.\\|\.'|\.\(|&amp;&amp;|==|\|\||&amp;(?=[^\&amp;])|\|(?=[^|])|~=|&lt;=|&gt;=|~(?!=)|&lt;(?!=)|&gt;(?!=)|[-*+/:@\\^])(\S|\s*(?=%)|\s+$|\s+([]\&amp;)*,/:-&gt;@\\^|}]|(\.(?:[^.\d]|\.[^.]))))|(\.[^'(*/A-Z\\^a-z\s]))([^%]|'[^']*'|"[^"]*")*|(\.(?=\s)|\.[A-Za-z]|(?=\{))([^"%'(=]|==|'[^']*'|"[^"]*"|\(|\([^%)]*\)|\[|\[[^]%]*]|\{|\{[^%}]*})*(\.\.\.[^%]*)?((?=%)|$)))(%.*)?$</string>
      </dict>
      <key>comment_block</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)%\{[^\n\S]*+\n</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.matlab</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^\s*%}[^\n\S]*+(?:\n|$)</string>
        <key>name</key>
        <string>comment.block.percentage.matlab</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^[^\n]*\n</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^[\t ]+)?(?=%%\s)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>%%</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.matlab</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\n</string>
                <key>name</key>
                <string>comment.line.double-percentage.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>\G[^\n\S]*(?![\n\s])</string>
                    <key>contentName</key>
                    <string>meta.cell.matlab</string>
                    <key>end</key>
                    <string>(?=\n)</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[\t ]+)?(?=%)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>%</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.matlab</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\n</string>
                <key>name</key>
                <string>comment.line.percentage.matlab</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>conjugate_transpose</key>
      <dict>
        <key>match</key>
        <string>((?&lt;=\S)|(?&lt;=])|(?&lt;=\))|(?&lt;=}))'</string>
        <key>name</key>
        <string>keyword.operator.transpose.matlab</string>
      </dict>
      <key>constants</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(eps|false|Inf|inf|intmax|intmin|namelengthmax|NaN|nan|on|off|realmax|realmin|true|pi)\b</string>
        <key>name</key>
        <string>constant.language.matlab</string>
      </dict>
      <key>control_statements</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.matlab</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s*(?:^|[,;\s])(break|continue|return)\b</string>
        <key>name</key>
        <string>meta.control.matlab</string>
      </dict>
      <key>curly_brackets</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#end_in_parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_before_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_after_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#end_in_parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_keywords</string>
          </dict>
        </array>
      </dict>
      <key>end_in_parens</key>
      <dict>
        <key>match</key>
        <string>\bend\b</string>
        <key>name</key>
        <string>keyword.operator.symbols.matlab</string>
      </dict>
      <key>function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(\s*)(function)\s+(?:(?:(\[)([^]]*)(])|([A-Za-z][0-9A-Z_a-z]*))\s*=\s*)?([A-Za-z][0-9A-Z_a-z]*(\.[A-Za-z][0-9A-Z_a-z]*)*)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.matlab</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.begin.matlab</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\w+</string>
                    <key>name</key>
                    <string>variable.parameter.output.matlab</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arguments.end.matlab</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.output.function.matlab</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?:^|[,;\s])(end)\b(\s*\n)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.end.function.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G\(</string>
                <key>end</key>
                <string>\)</string>
                <key>name</key>
                <string>meta.arguments.function.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#line_continuation</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\w+</string>
                    <key>name</key>
                    <string>variable.parameter.input.matlab</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(arguments)\b([^%]*)\s*(\([^)]*\))?\s*($|(?=%))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.arguments.matlab</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>match</key>
                        <string>[A-Za-z][0-9A-Z_a-z]*</string>
                        <key>name</key>
                        <string>variable.parameter.arguments.matlab</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?:^|[,;\s])(end)\b</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.end.arguments.matlab</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>meta.arguments.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#validators</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>global_persistent</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.globalpersistent.matlab</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(global|persistent)\b</string>
        <key>name</key>
        <string>meta.globalpersistent.matlab</string>
      </dict>
      <key>indexing_curly_brackets</key>
      <dict>
        <key>Comment</key>
        <string>Match identifier{idx, idx, } and stop at newline without ... This helps with partially written code like x{idx </string>
        <key>begin</key>
        <string>([A-Za-z][.0-9A-Z_a-z]*\s*)\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(}|(?&lt;!\.\.\.).\n)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#end_in_parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_before_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_after_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#end_in_parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_keywords</string>
          </dict>
        </array>
      </dict>
      <key>line_continuation</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.symbols.matlab</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.line.continuation.matlab</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\.\.\.)(.*)$</string>
        <key>name</key>
        <string>meta.linecontinuation.matlab</string>
      </dict>
      <key>numbers</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=[(*-\-/:=\[\\{\s]|^)\d*\.?\d+([Ee][-+]?\d)?([0-9&amp;&amp;[^.]])*([ij])?\b</string>
        <key>name</key>
        <string>constant.numeric.matlab</string>
      </dict>
      <key>operators</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=\s)(==|~=|&gt;=??|&lt;=??|&amp;&amp;??|[:|]|\|\||[-*+]|\.\*|/|\./|\\|\.\\|\^|\.\^)(?=\s)</string>
        <key>name</key>
        <string>keyword.operator.symbols.matlab</string>
      </dict>
      <key>parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>(\)|(?&lt;!\.\.\.).\n)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#end_in_parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_before_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_after_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_keywords</string>
          </dict>
        </array>
      </dict>
      <key>square_brackets</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all_before_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#all_after_command_dual</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_keywords</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.interpolated.matlab</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.matlab</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*((!).*$\n?)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>((?&lt;=([\&amp;(*-/:-&gt;\[\\^{|~\s]))|^)'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'(?=([\&amp;(-/:-&gt;\[-^{-~\s]))</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>''</string>
                <key>name</key>
                <string>constant.character.escape.matlab</string>
              </dict>
              <dict>
                <key>match</key>
                <string>'(?=.)</string>
                <key>name</key>
                <string>invalid.illegal.unescaped-quote.matlab</string>
              </dict>
              <dict>
                <key>match</key>
                <string>((%([-+0]?\d{0,3}(\.\d{1,3})?)([EGc-gs]|(([bt])?([Xoux]))))|%%|\\([\\bfnrt]))</string>
                <key>name</key>
                <string>constant.character.escape.matlab</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((?&lt;=([\&amp;(*-/:-&gt;\[\\^{|~\s]))|^)"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.matlab</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"(?=([\&amp;(-/:-&gt;\[-^{-~\s]))</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.matlab</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.matlab</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>""</string>
                <key>name</key>
                <string>constant.character.escape.matlab</string>
              </dict>
              <dict>
                <key>match</key>
                <string>"(?=.)</string>
                <key>name</key>
                <string>invalid.illegal.unescaped-quote.matlab</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>transpose</key>
      <dict>
        <key>match</key>
        <string>\.'</string>
        <key>name</key>
        <string>keyword.operator.transpose.matlab</string>
      </dict>
      <key>validator_strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>((?&lt;=([\&amp;(*-/:-&gt;\[\\^{|~\s]))|^)'</string>
                <key>end</key>
                <string>'(?=([\&amp;(-/:-&gt;\[-^{-~\s]))</string>
                <key>name</key>
                <string>storage.type.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>''</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>'(?=.)</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>([^']+)</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>((?&lt;=([\&amp;(*-/:-&gt;\[\\^{|~\s]))|^)"</string>
                <key>end</key>
                <string>"(?=([\&amp;(-/:-&gt;\[-^{-~\s]))</string>
                <key>name</key>
                <string>storage.type.matlab</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>""</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>"(?=.)</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>[^"]+</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>validators</key>
      <dict>
        <key>begin</key>
        <string>\s*;?\s*([A-Za-z][.0-9?A-Z_a-z]*)</string>
        <key>end</key>
        <string>([\n%;=].*)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>match</key>
                <string>(%.*)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>match</key>
                <string>(=[^;]*)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#validators</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
                <key>match</key>
                <string>([\n;]\s*[A-Za-z].*)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line_continuation</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s*(\([^)]*\))</string>
            <key>name</key>
            <string>storage.type.matlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([A-Za-z][.0-9A-Z_a-z]*)</string>
            <key>name</key>
            <string>storage.type.matlab</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#braced_validator_list</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(nargin|nargout|varargin|varargout)\b</string>
        <key>name</key>
        <string>variable.other.function.matlab</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.matlab</string>
  </dict>
</plist>