<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>nim</string>
    </array>
    <key>name</key>
    <string>nim</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>[\t ]*##\[</string>
        <key>contentName</key>
        <string>comment.block.doc-comment.content.nim</string>
        <key>end</key>
        <string>]##</string>
        <key>name</key>
        <string>comment.block.doc-comment.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#multilinedoccomment</string>
            <key>name</key>
            <string>comment.block.doc-comment.nested.nim</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>[\t ]*#\[</string>
        <key>contentName</key>
        <string>comment.block.content.nim</string>
        <key>end</key>
        <string>]#</string>
        <key>name</key>
        <string>comment.block.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#multilinecomment</string>
            <key>name</key>
            <string>comment.block.nested.nim</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^[\t ]+)?(?=##)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.comment.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>##</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.number-sign.doc-comment.nim</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^[\t ]+)?(?=#[^\[])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.comment.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.number-sign.nim</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.proc.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(proc|method|template|macro|iterator|converter|func)\s+`?([^(*:`{\s]*)`?(\s*\*)?\s*(?=[\n(:=\[{])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.nim</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.export</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.nim</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>discard """</string>
        <key>end</key>
        <string>"""(?!")</string>
        <key>name</key>
        <string>comment.line.discarded.nim</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#float_literal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#integer_literal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=`)[^ `]+(?=`)</string>
        <key>name</key>
        <string>entity.name.function.nim</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.export</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b\s*(\*)(?:\s*(?=[,:])|\s+(?==))</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.export</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b([A-Z]\w+)(\*)</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string_literal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false|Inf|NegInf|NaN|nil)\b</string>
        <key>name</key>
        <string>constant.language.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(block|break|case|continue|do|elif|else|end|except|finally|for|if|raise|return|try|when|while|yield)\b</string>
        <key>name</key>
        <string>keyword.control.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((and|in|is|isnot|not|notin|or|xor))\b</string>
        <key>name</key>
        <string>keyword.boolean.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([-!$%\&amp;*+./:&lt;-@\\^~])+</string>
        <key>name</key>
        <string>keyword.operator.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((addr|asm??|atomic|bind|cast|const|converter|concept|defer|discard|distinct|div|enum|export|from|import|include|let|mod|mixin|object|of|ptr|ref|shl|shr|static|type|using|var|tuple|iterator|macro|func|method|proc|template))\b</string>
        <key>name</key>
        <string>keyword.other.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((generic|interface|lambda|out|shared))\b</string>
        <key>name</key>
        <string>invalid.illegal.invalid-keyword.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(new|await|assert|echo|defined|declared|newException|countup|countdown|high|low)\b</string>
        <key>name</key>
        <string>keyword.other.common.function.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(((u?int)(8|16|32|64)?)|float(32|64)?|bool|string|auto|cstring|char|byte|tobject|typedesc|stmt|expr|any|untyped|typed)\b</string>
        <key>name</key>
        <string>storage.type.concrete.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(range|array|seq|set|pointer)\b</string>
        <key>name</key>
        <string>storage.type.generic.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(openarray|varargs|void)\b</string>
        <key>name</key>
        <string>storage.type.generic.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z][0-9A-Z_]+\b</string>
        <key>name</key>
        <string>support.constant.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z]\w+\b</string>
        <key>name</key>
        <string>support.type.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b\w+\b(?=(\[([,0-9A-Z_a-z\s])+])?\()</string>
        <key>name</key>
        <string>support.function.any-method.nim</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?!(openarray|varargs|void|range|array|seq|set|pointer|new|await|assert|echo|defined|declared|newException|countup|countdown|high|low|((u?int)(8|16|32|64)?)|float(32|64)?|bool|string|auto|cstring|char|byte|tobject|typedesc|stmt|expr|any|untyped|typed|addr|asm??|atomic|bind|cast|const|converter|concept|defer|discard|distinct|div|enum|export|from|import|include|let|mod|mixin|object|of|ptr|ref|shl|shr|static|type|using|var|tuple|iterator|macro|func|method|proc|template|and|in|is|isnot|not|notin|or|xor|proc|method|template|macro|iterator|converter|func|true|false|Inf|NegInf|NaN|nil|block|break|case|continue|do|elif|else|end|except|finally|for|if|raise|return|try|when|while|yield)\b)\w+\s+(?!(and|in|is|isnot|not|notin|or|xor|[^"'-+0-9A-Z_-z]+)\b)(?=["'-+0-9A-Z_-z])</string>
        <key>name</key>
        <string>support.function.any-method.nim</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=\{\.emit: ?""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{\.(emit:) ?(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.c</string>
            <key>end</key>
            <string>(")""(?!")(\.?})?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.c</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.c</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>`</string>
                <key>end</key>
                <string>`</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.c</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\{\.</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.pragma.start.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\.?}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.pragma.end.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(\p{alpha}\w*)(?:\s|\s*:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\.?}|,)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.nim</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\p{alpha}\w*)\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.nim</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(\p{alpha}\w*)(?=\.?}|,)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\p{alpha}\w*)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.nim</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.triple.raw.nim</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\p{alpha}\w*)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.nim</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.raw.nim</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(hint\[\w+]):</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.pragma.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\.?}|,)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.nim</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.nim</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=asm """)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(asm) (""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.asm</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.asm</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.asm</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>`</string>
                <key>end</key>
                <string>`</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.asm</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.nim</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(tmpl(i)?)(?=( (html|xml|js|css|glsl|md))?""")</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=html""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(html)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.html</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.html</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=xml""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(xml)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.xml</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.xml</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.xml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.xml</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=js""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(js)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.js</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.js</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.js</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=css""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(css)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.css</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.css</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.css</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.css</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=glsl""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(glsl)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.glsl</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.glsl</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.glsl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.glsl</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\s*)?(?=md""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.leading.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!\G)(\s*$\n?)?</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.embedded.trailing.nim</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(md)(""")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.nim</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.nim</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.html.markdown</string>
            <key>end</key>
            <string>(")""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.nim</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html.markdown</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.block.html.markdown</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\(</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)\{</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.nim</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>([\n{])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>plain</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.nim</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!\$)(\$\w+)</string>
                <key>name</key>
                <string>keyword.operator.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.markdown</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>char_escapes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[CRcr]</string>
            <key>name</key>
            <string>constant.character.escape.carriagereturn.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[LNln]</string>
            <key>name</key>
            <string>constant.character.escape.linefeed.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Ff]</string>
            <key>name</key>
            <string>constant.character.escape.formfeed.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Tt]</string>
            <key>name</key>
            <string>constant.character.escape.tabulator.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Vv]</string>
            <key>name</key>
            <string>constant.character.escape.verticaltabulator.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\"</string>
            <key>name</key>
            <string>constant.character.escape.double-quote.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\'</string>
            <key>name</key>
            <string>constant.character.escape.single-quote.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[0-9]+</string>
            <key>name</key>
            <string>constant.character.escape.chardecimalvalue.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Aa]</string>
            <key>name</key>
            <string>constant.character.escape.alert.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Bb]</string>
            <key>name</key>
            <string>constant.character.escape.backspace.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Ee]</string>
            <key>name</key>
            <string>constant.character.escape.escape.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Xx]\h\h</string>
            <key>name</key>
            <string>constant.character.escape.hex.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\\\</string>
            <key>name</key>
            <string>constant.character.escape.backslash.nim</string>
          </dict>
        </array>
      </dict>
      <key>extended_string_quoted_double_raw</key>
      <dict>
        <key>begin</key>
        <string>\b(\w+)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.any-method.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.raw.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#raw_string_escapes</string>
          </dict>
        </array>
      </dict>
      <key>extended_string_quoted_triple_raw</key>
      <dict>
        <key>begin</key>
        <string>\b(\w+)(""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.any-method.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.raw.nim</string>
      </dict>
      <key>float_literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b\d[_\d]*((\.\d[_\d]*([Ee][-+]?\d[_\d]*)?)|([Ee][-+]?\d[_\d]*))('([Ff](32|64|128)|[DFdf]))?</string>
            <key>name</key>
            <string>constant.numeric.float.decimal.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0[Xx]\h[_\h]*'([Ff](32|64|128)|[DFdf])</string>
            <key>name</key>
            <string>constant.numeric.float.hexadecimal.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0o[0-7][0-7_]*'([Ff](32|64|128)|[DFdf])</string>
            <key>name</key>
            <string>constant.numeric.float.octal.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0([Bb])[01][01_]*'([Ff](32|64|128)|[DFdf])</string>
            <key>name</key>
            <string>constant.numeric.float.binary.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d[_\d]*)'([Ff](32|64|128)|[DFdf])</string>
            <key>name</key>
            <string>constant.numeric.float.decimal.nim</string>
          </dict>
        </array>
      </dict>
      <key>fmt_interpolation</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.template.expression.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>:</string>
            <key>end</key>
            <string>(?=})</string>
            <key>name</key>
            <string>meta.template.format-specifier.nim</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.nim</string>
          </dict>
        </array>
      </dict>
      <key>fmt_string</key>
      <dict>
        <key>begin</key>
        <string>\b(fmt)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.any-method.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.raw.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;!")"(?!")</string>
            <key>name</key>
            <string>invalid.illegal.nim</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#raw_string_escapes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_interpolation</string>
          </dict>
        </array>
      </dict>
      <key>fmt_string_call</key>
      <dict>
        <key>begin</key>
        <string>(fmt)\((?=")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.any-method.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.nim</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"(?=\))</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.nim</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.nim</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>"</string>
                <key>name</key>
                <string>invalid.illegal.nim</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_escapes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#fmt_interpolation</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>fmt_string_operator</key>
      <dict>
        <key>begin</key>
        <string>(&amp;)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>"</string>
            <key>name</key>
            <string>invalid.illegal.nim</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_escapes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_interpolation</string>
          </dict>
        </array>
      </dict>
      <key>fmt_string_triple</key>
      <dict>
        <key>begin</key>
        <string>\b(fmt)(""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.any-method.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.raw.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fmt_interpolation</string>
          </dict>
        </array>
      </dict>
      <key>fmt_string_triple_operator</key>
      <dict>
        <key>begin</key>
        <string>(&amp;)(""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.nim</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.raw.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fmt_interpolation</string>
          </dict>
        </array>
      </dict>
      <key>integer_literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(0[Xx]\h[_\h]*)('(([IUiu](8|16|32|64))|[Uu]))?</string>
            <key>name</key>
            <string>constant.numeric.integer.hexadecimal.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0o[0-7][0-7_]*)('(([IUiu](8|16|32|64))|[Uu]))?</string>
            <key>name</key>
            <string>constant.numeric.integer.octal.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0([Bb])[01][01_]*)('(([IUiu](8|16|32|64))|[Uu]))?</string>
            <key>name</key>
            <string>constant.numeric.integer.binary.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d[_\d]*)('(([IUiu](8|16|32|64))|[Uu]))?</string>
            <key>name</key>
            <string>constant.numeric.integer.decimal.nim</string>
          </dict>
        </array>
      </dict>
      <key>multilinecomment</key>
      <dict>
        <key>begin</key>
        <string>#\[</string>
        <key>end</key>
        <string>]#</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#multilinecomment</string>
          </dict>
        </array>
      </dict>
      <key>multilinedoccomment</key>
      <dict>
        <key>begin</key>
        <string>##\[</string>
        <key>end</key>
        <string>]##</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#multilinedoccomment</string>
          </dict>
        </array>
      </dict>
      <key>raw_string_escapes</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.double-quote.nim</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[^"]("")</string>
      </dict>
      <key>string_escapes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[Pp]</string>
            <key>name</key>
            <string>constant.character.escape.newline.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Uu]\h\h\h\h</string>
            <key>name</key>
            <string>constant.character.escape.hex.nim</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[Uu]\{\h+}</string>
            <key>name</key>
            <string>constant.character.escape.hex.nim</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#char_escapes</string>
          </dict>
        </array>
      </dict>
      <key>string_literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fmt_string_triple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_string_triple_operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#extended_string_quoted_triple_raw</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_quoted_triple_raw</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_string_operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fmt_string_call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_quoted_double_raw</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#extended_string_quoted_double_raw</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_quoted_single</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_quoted_triple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_quoted_double</string>
          </dict>
        </array>
      </dict>
      <key>string_quoted_double</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escapes</string>
          </dict>
        </array>
      </dict>
      <key>string_quoted_double_raw</key>
      <dict>
        <key>begin</key>
        <string>\br"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.raw.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#raw_string_escapes</string>
          </dict>
        </array>
      </dict>
      <key>string_quoted_single</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.nim</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#char_escapes</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^']{2,}?)</string>
            <key>name</key>
            <string>invalid.illegal.character.nim</string>
          </dict>
        </array>
      </dict>
      <key>string_quoted_triple</key>
      <dict>
        <key>begin</key>
        <string>"""</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""(?!")</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.nim</string>
      </dict>
      <key>string_quoted_triple_raw</key>
      <dict>
        <key>begin</key>
        <string>r"""</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.nim</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.nim</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.raw.nim</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.nim</string>
  </dict>
</plist>