<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>pkl</string>
      <string>pcf</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{</string>
    <key>foldingStopMarker</key>
    <string>}</string>
    <key>name</key>
    <string>pkl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.language.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.module.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(module)\s+([$_\p{L}][$0-9_\p{L}]*(?:\.[$_\p{L}][$0-9_\p{L}]*)*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.class.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.pkl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(typealias)\s+([$_\p{L}][$0-9_\p{L}]*)\s*(=)\s*([$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??\s*(\|\s*[$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??)*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.class.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(class)\s+[$_\p{L}][$0-9_\p{L}]*</string>
        <key>name</key>
        <string>entity.name.type.pkl</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(for)\s*\(([$_\p{L}][$0-9_\p{L}]*)(?:\s*,\s*([$_\p{L}][$0-9_\p{L}]*))*\s+(in)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(new)\s+([$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??\s*(\|\s*[$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??)*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(function)\s+([$_\p{L}][$0-9_\p{L}]*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(as)\s+([$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??\s*(\|\s*[$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??)*)</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
        <key>name</key>
        <string>constant.character.language.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>//.*</string>
        <key>name</key>
        <string>comment.line.pkl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.pkl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>((?:\b|\s*)[$_\p{L}][$0-9_\p{L}]*|`[^`]+`)\s*(:)\s*([$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??\s*(\|\s*[$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??)*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.pkl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=|[),]|^[\t ]*$</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\b[$_\p{L}][$0-9_\p{L}]*|`[^`]+`)\s*(=)(?!=)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(:)\s*([$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??\s*(\|\s*[$_\p{L}][$0-9_\p{L}]*\s*(?:&lt;[^&gt;]*&gt;)?\s*(?:\([^)]*\))?\s*\??)*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.pkl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*([$_\p{L}][$0-9_\p{L}]*)\s*\{</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(hidden|local|abstract|external|open|in|out|amends|extends|fixed|const)\b</string>
        <key>name</key>
        <string>storage.modifier.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(amends|as|extends|function|is|let|read\???|import|throw|trace)\b</string>
        <key>name</key>
        <string>keyword.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(if|else|when|for|import|new)\b</string>
        <key>name</key>
        <string>keyword.control.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0x(?:[A-Fa-f\d][A-F_a-f\d]*[A-Fa-f\d]|[A-F_a-f\d])\b</string>
        <key>name</key>
        <string>constant.numeric.hex.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0b(?:[01][01_]*[01]|[01])\b</string>
        <key>name</key>
        <string>constant.numeric.binary.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0o(?:[0-7][0-7_]*[0-7]|[0-7])\b</string>
        <key>name</key>
        <string>constant.numeric.octal.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b\d(?:[0-9_]*\d|)\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?:(?:\d(?:[0-9_]*\d|))?\.\d(?:[0-9_]*\d|)(?:[Ee][-+]?\d(?:[0-9_]*\d|))?|\d(?:[0-9_]*\d|)[Ee][-+]?\d(?:[0-9_]*\d|))\b</string>
        <key>name</key>
        <string>constant.numeric.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[-*+/]|~/|%|\*\*|&gt;=??|&lt;=??|==|!=?|&amp;&amp;|\|\||\|&gt;|\?\?|!!|=|-&gt;|\|</string>
        <key>name</key>
        <string>keyword.operator.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(this|module|outer|super)\b</string>
        <key>name</key>
        <string>variable.language.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(unknown|never)\b</string>
        <key>name</key>
        <string>support.type.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[]()\[{}]</string>
        <key>name</key>
        <string>meta.brace.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(class|typealias)\b</string>
        <key>name</key>
        <string>keyword.class.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\.\?|[.:;]</string>
        <key>name</key>
        <string>punctuation.pkl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>@[$_\p{L}][$0-9_\p{L}]*</string>
        <key>name</key>
        <string>entity.name.type.pkl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(""")</string>
        <key>name</key>
        <string>string.quoted.triple.0.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\.)</string>
            <key>name</key>
            <string>constant.character.escape.0.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.0.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\.)</string>
            <key>name</key>
            <string>constant.character.escape.0.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(#""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""#)</string>
        <key>name</key>
        <string>string.quoted.triple.1.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\#(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\#.)</string>
            <key>name</key>
            <string>constant.character.escape.1.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(#")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("#)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.1.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\#(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\#.)</string>
            <key>name</key>
            <string>constant.character.escape.1.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(##""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""##)</string>
        <key>name</key>
        <string>string.quoted.triple.2.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\##(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\##.)</string>
            <key>name</key>
            <string>constant.character.escape.2.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(##")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("##)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.2.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\##(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\##.)</string>
            <key>name</key>
            <string>constant.character.escape.2.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(###""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""###)</string>
        <key>name</key>
        <string>string.quoted.triple.3.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\###(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\###.)</string>
            <key>name</key>
            <string>constant.character.escape.3.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(###")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("###)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.3.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\###(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\###.)</string>
            <key>name</key>
            <string>constant.character.escape.3.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(####""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""####)</string>
        <key>name</key>
        <string>string.quoted.triple.4.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\####(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\####.)</string>
            <key>name</key>
            <string>constant.character.escape.4.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(####")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("####)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.4.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\####(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\####.)</string>
            <key>name</key>
            <string>constant.character.escape.4.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(#####""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""#####)</string>
        <key>name</key>
        <string>string.quoted.triple.5.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\#####(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\#####.)</string>
            <key>name</key>
            <string>constant.character.escape.5.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(#####")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("#####)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.5.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\#####(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\#####.)</string>
            <key>name</key>
            <string>constant.character.escape.5.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(######""")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("""######)</string>
        <key>name</key>
        <string>string.quoted.triple.6.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\######(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\######.)</string>
            <key>name</key>
            <string>constant.character.escape.6.pkl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(######")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimiter.pkl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>("######)|(.?)$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.delimimter.pkl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.pkl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.6.pkl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.pkl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\\######(?:["\\nrt]|u\{[A-Fa-f\d]+}|\(.+?\))|(\\######.)</string>
            <key>name</key>
            <string>constant.character.escape.6.pkl</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.pkl</string>
  </dict>
</plist>