<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>polar</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#rule</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#rule-type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inline-query</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#resource-block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#test-block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#fixture</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>boolean</key>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.boolean</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>match</key>
        <string>#.*</string>
        <key>name</key>
        <string>comment.line.number-sign</string>
      </dict>
      <key>fixture</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bfixture\b</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\btest\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\bfixture\b</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>inline-query</key>
      <dict>
        <key>begin</key>
        <string>\?=</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>name</key>
        <string>meta.inline-query</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(cut|or|debug|print|in|forall|if|and|of|not|matches|type|on|global)\b</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[-+]?\d+(?:(\.)\d+(?:e[-+]?\d+)?|e[-+]?\d+)\b</string>
            <key>name</key>
            <string>constant.numeric.float</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([-+])\d+\b</string>
            <key>name</key>
            <string>constant.numeric.integer</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+\b</string>
            <key>name</key>
            <string>constant.numeric.natural</string>
          </dict>
        </array>
      </dict>
      <key>object-literal</key>
      <dict>
        <key>begin</key>
        <string>([A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.resource</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>name</key>
        <string>constant.other.object-literal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([-!*+/&lt;=&gt;])</string>
      </dict>
      <key>resource-block</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;resourceType&gt;[A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*){0}((resource|actor)\s+(\g&lt;resourceType&gt;)(?:\s+(extends)\s+(\g&lt;resourceType&gt;(?:\s*,\s*\g&lt;resourceType&gt;)*)\s*,?\s*)?|(global))\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>6</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*)</string>
                <key>name</key>
                <string>entity.name.type</string>
              </dict>
            </array>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>name</key>
        <string>meta.resource-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.separator.sequence.declarations</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.relation-declaration</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#specializer</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.sequence.dict</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
        </array>
      </dict>
      <key>rule</key>
      <dict>
        <key>name</key>
        <string>meta.rule</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#rule-functor</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\bif\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.if</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#term</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
          </dict>
        </array>
      </dict>
      <key>rule-functor</key>
      <dict>
        <key>begin</key>
        <string>([A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*)\s*\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.rule</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#specializer</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.sequence.list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
        </array>
      </dict>
      <key>rule-type</key>
      <dict>
        <key>begin</key>
        <string>\btype\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.other.type-decl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>name</key>
        <string>meta.rule-type</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#rule-functor</string>
          </dict>
        </array>
      </dict>
      <key>specializer</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.resource</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*\s*:\s*([A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*)</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape</string>
          </dict>
        </array>
      </dict>
      <key>term</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-literal</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>]</string>
            <key>name</key>
            <string>meta.bracket.list</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#term</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.sequence.list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.bracket.dict</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#term</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.sequence.dict</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.parens</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#term</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>test-block</key>
      <dict>
        <key>begin</key>
        <string>(test)\s+("[^"]*")\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>name</key>
        <string>meta.test-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(setup)\s*\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.test-setup</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#rule</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#fixture</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#rule</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(assert(?:|_not))\b</string>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.iff-rule</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#rule-functor</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\biff\b</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>;</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#term</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>;</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.polar</string>
  </dict>
</plist>