<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>pp</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(^\s*/\*|([(\[{])\s*$)</string>
    <key>foldingStopMarker</key>
    <string>(\*/|^\s*([])}]))</string>
    <key>name</key>
    <string>puppet</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#line_comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.puppet</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(node)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.puppet</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\{)</string>
        <key>name</key>
        <string>meta.definition.class.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bdefault\b</string>
            <key>name</key>
            <string>keyword.puppet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#regex-literal</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(class)\s+((?:[a-z][0-9_a-z]*)?(?:::[a-z][0-9_a-z]*)+|[a-z][0-9_a-z]*)\s*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.puppet</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\{)</string>
        <key>name</key>
        <string>meta.definition.class.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(inherits)\b\s+</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.puppet</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=[({])</string>
            <key>name</key>
            <string>meta.definition.class.inherits.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b((?:[-".0-9A-Z_a-z]+::)*[-".0-9A-Z_a-z]+)\b</string>
                <key>name</key>
                <string>support.type.puppet</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#resource-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(plan)\s+((?:[a-z][0-9_a-z]*)?(?:::[a-z][0-9_a-z]*)+|[a-z][0-9_a-z]*)\s*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.puppet</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.plan.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\{)</string>
        <key>name</key>
        <string>meta.definition.plan.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#resource-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(define|function)\s+([a-z][0-9_a-z]*|(?:[a-z][0-9_a-z]*)?(?:::[a-z][0-9_a-z]*)+)\s*(\()</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.puppet</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\{)</string>
        <key>name</key>
        <string>meta.function.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#resource-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.puppet</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(case|else|elsif|if|unless)(?!::)\b</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#resource-definition</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#heredoc</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#puppet-datatypes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#array</string>
      </dict>
      <dict>
        <key>match</key>
        <string>((\$?)"?[A-Z_a-z\x7F-ÿ][0-9A-Z_a-z\x7F-ÿ]*"?):(?=\s+|$)</string>
        <key>name</key>
        <string>entity.name.section.puppet</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variable</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(import|include|contain|require)\s+(?!.*=&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.include.puppet</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>variable.parameter.include.puppet</string>
        <key>end</key>
        <string>(?=\s|$)</string>
        <key>name</key>
        <string>meta.include.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b\w+\s*(?==&gt;)\s*</string>
        <key>name</key>
        <string>constant.other.key.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=\{)\s*\w+\s*(?=})</string>
        <key>name</key>
        <string>constant.other.bareword.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(alert|crit|debug|defined|emerg|err|escape|fail|failed|file|generate|gsub|info|notice|package|realize|search|tag|tagged|template|warning)\b(?!.*\{)</string>
        <key>name</key>
        <string>support.function.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>=&gt;</string>
        <key>name</key>
        <string>punctuation.separator.key-value.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>-&gt;</string>
        <key>name</key>
        <string>keyword.control.orderarrow.puppet</string>
      </dict>
      <dict>
        <key>match</key>
        <string>~&gt;</string>
        <key>name</key>
        <string>keyword.control.notifyarrow.puppet</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#regex-literal</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>begin</key>
        <string>(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.begin.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.end.puppet</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.array.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*,\s*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(absent|directory|false|file|present|running|stopped|true)\b(?!.*\{)</string>
            <key>name</key>
            <string>constant.language.puppet</string>
          </dict>
        </array>
      </dict>
      <key>double-quoted-string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.puppet</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.interpolated.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_puppet</string>
          </dict>
        </array>
      </dict>
      <key>escaped_char</key>
      <dict>
        <key>match</key>
        <string>\\.</string>
        <key>name</key>
        <string>constant.character.escape.puppet</string>
      </dict>
      <key>function_call</key>
      <dict>
        <key>begin</key>
        <string>([A-Z_a-z][0-9A-Z_a-z]*)(\()</string>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>meta.function-call.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.parameters.puppet</string>
          </dict>
        </array>
      </dict>
      <key>hash</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.hash.begin.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.hash.end.puppet</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.hash.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b\w+\s*(?==&gt;)\s*</string>
            <key>name</key>
            <string>constant.other.key.puppet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-default-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
        </array>
      </dict>
      <key>heredoc</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>@\(\p{blank}*"([^\t )/:]+)"\p{blank}*(:\p{blank}*[a-z][+0-9A-Z_a-z]*\p{blank}*)?(/\p{blank}*[$Lnrst]*)?\p{blank}*\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.puppet</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\p{blank}*(\|\p{blank}*-|[-|])?\p{blank}*\1</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.interpolated.heredoc.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolated_puppet</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>@\(\p{blank}*([^\t )/:]+)\p{blank}*(:\p{blank}*[a-z][+0-9A-Z_a-z]*\p{blank}*)?(/\p{blank}*[$Lnrst]*)?\p{blank}*\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.puppet</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\p{blank}*(\|\p{blank}*-|[-|])?\p{blank}*\1</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.unquoted.heredoc.puppet</string>
          </dict>
        </array>
      </dict>
      <key>interpolated_puppet</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\$\{)(\d+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>source.puppet variable.other.readwrite.global.pre-defined.puppet</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.puppet</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\$\{)(_[0-9A-Z_a-z]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>source.puppet variable.other.readwrite.global.puppet</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.puppet</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\$\{)(([a-z][0-9_a-z]*)?(?:::[a-z][0-9_a-z]*)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>source.puppet variable.other.readwrite.global.puppet</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.puppet</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.puppet</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.puppet</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.puppet</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.puppet</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(undef)\b</string>
      </dict>
      <key>line_comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.line.number-sign.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^((#).*$\n?)</string>
            <key>name</key>
            <string>meta.comment.full-line.puppet</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#).*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.puppet</string>
          </dict>
        </array>
      </dict>
      <key>nested_braces</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_braces</string>
          </dict>
        </array>
      </dict>
      <key>nested_braces_interpolated</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_braces_interpolated</string>
          </dict>
        </array>
      </dict>
      <key>nested_brackets</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_brackets</string>
          </dict>
        </array>
      </dict>
      <key>nested_brackets_interpolated</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_brackets_interpolated</string>
          </dict>
        </array>
      </dict>
      <key>nested_parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_parens</string>
          </dict>
        </array>
      </dict>
      <key>nested_parens_interpolated</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nested_parens_interpolated</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![\w\d])([-+]?)(?i:0x)(?i:[0-9a-f])+(?![\w\d])</string>
            <key>name</key>
            <string>constant.numeric.hexadecimal.puppet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![.\w])([-+]?)(?&lt;!\d)\d+(?i:e([-+])?\d+)?(?![.\w\d])</string>
            <key>name</key>
            <string>constant.numeric.integer.puppet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\w)([-+]?)\d+\.\d+(?i:e([-+])?\d+)?(?![\w\d])</string>
            <key>name</key>
            <string>constant.numeric.integer.puppet</string>
          </dict>
        </array>
      </dict>
      <key>parameter-default-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#puppet-datatypes</string>
          </dict>
        </array>
      </dict>
      <key>puppet-datatypes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![$A-Za-z])([A-Z][0-9A-Z_a-z]*)(?![0-9A-Z_a-z])</string>
            <key>name</key>
            <string>storage.type.puppet</string>
          </dict>
        </array>
      </dict>
      <key>regex-literal</key>
      <dict>
        <key>match</key>
        <string>(/)(.+?)[^\\]/</string>
        <key>name</key>
        <string>string.regexp.literal.puppet</string>
      </dict>
      <key>resource-definition</key>
      <dict>
        <key>begin</key>
        <string>(?:^|\b)(::[a-z][0-9_a-z]*|[a-z][0-9_a-z]*|(?:[a-z][0-9_a-z]*)?(?:::[a-z][0-9_a-z]*)+)\s*(\{)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.definition.resource.puppet storage.type.puppet</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>entity.name.section.puppet</string>
        <key>end</key>
        <string>:</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
        </array>
      </dict>
      <key>resource-parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((\$+)[A-Z_a-z][0-9A-Z_a-z]*)\s*(?=[),])</string>
            <key>name</key>
            <string>meta.function.argument.puppet</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>((\$+)[A-Z_a-z][0-9A-Z_a-z]*)\s*(=)\s*\s*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.puppet</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.puppet</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.puppet</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=[),])</string>
            <key>name</key>
            <string>meta.function.argument.puppet</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameter-default-types</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>single-quoted-string</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.puppet</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.puppet</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.puppet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#double-quoted-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-quoted-string</string>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\$)(\d+)</string>
            <key>name</key>
            <string>variable.other.readwrite.global.pre-defined.puppet</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\$)_[0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>variable.other.readwrite.global.puppet</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.puppet</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\$)(([a-z][0-9A-Z_a-z]*)?(?:::[a-z][0-9A-Z_a-z]*)*)</string>
            <key>name</key>
            <string>variable.other.readwrite.global.puppet</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.puppet</string>
  </dict>
</plist>