<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>ron</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.array.begin.ron</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.array.end.ron</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-name</string>
          </dict>
          <dict>
            <key>meta_scope</key>
            <string>meta.structure.array.ron</string>
          </dict>
        </array>
      </dict>
      <key>block_comment</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.ron</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
        </array>
      </dict>
      <key>character</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>contentName</key>
        <string>constant.character.ron</string>
        <key>end</key>
        <string>'</string>
        <key>name</key>
        <string>string.quoted.single</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escapes</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.ron</string>
      </dict>
      <key>dictionary</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.dictionary.begin.ron</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.dictionary.end.ron</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum-variant</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.dictionary.ron</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>punctuation.separator.dictionary.key-value.ron</string>
          </dict>
        </array>
      </dict>
      <key>enum-variant</key>
      <dict>
        <key>match</key>
        <string>[_a-z][0-9A-Z_a-z]*</string>
        <key>name</key>
        <string>entity.name.tag.ron</string>
      </dict>
      <key>escapes</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.backslash.ron</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.bit.ron</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.ron</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.punctuation.ron</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.punctuation.ron</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\\)(?:(x[0-7][0-7A-Fa-f])|(u(\{)[A-Fa-f\d]{4,6}(}))|.)</string>
        <key>name</key>
        <string>constant.character.escape.ron</string>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dictionary</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#raw_string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#character</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum-variant</string>
          </dict>
        </array>
      </dict>
      <key>line_comment</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.ron</string>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>-?\b0x[_\h]+\b</string>
            <key>name</key>
            <string>constant.numeric.hex.ron</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-?\b0b[01_]+\b</string>
            <key>name</key>
            <string>constant.numeric.binary.ron</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-?\b0o[0-7_]+\b</string>
            <key>name</key>
            <string>constant.numeric.octal.ron</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-?\b[0-9][0-9_]*(?:\.[0-9][0-9_]*)?(?:[Ee][-+]?[0-9_]+)?\b</string>
            <key>name</key>
            <string>constant.numeric.ron</string>
          </dict>
        </array>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin.ron</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end.ron</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dictionary</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum-variant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
        </array>
      </dict>
      <key>raw_string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>r#{5}"</string>
            <key>end</key>
            <string>"#{5}</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>r#{4}"</string>
            <key>end</key>
            <string>"#{4}</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>r#{3}"</string>
            <key>end</key>
            <string>"#{3}</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>r#{2}"</string>
            <key>end</key>
            <string>"#{2}</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>r#"</string>
            <key>end</key>
            <string>"#</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>r"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.other.raw.ron</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>(b?)(")</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escapes</string>
          </dict>
        </array>
      </dict>
      <key>struct-field</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.member.ron</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.ron</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([_a-z][0-9A-Z_a-z]*)\s*(:)</string>
      </dict>
      <key>struct-name</key>
      <dict>
        <key>match</key>
        <string>[A-Z][0-9A-Z_a-z]*</string>
        <key>name</key>
        <string>entity.name.type.ron</string>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dictionary</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#raw_string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#character</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.ron</string>
  </dict>
</plist>