<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>scala</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!/.*\b\w*scala\b</string>
    <key>foldingStartMarker</key>
    <string>/\*\*|\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>\*\*/|^\s*}</string>
    <key>name</key>
    <string>scala</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>backQuotedVariable</key>
      <dict>
        <key>match</key>
        <string>`[^`]+`</string>
      </dict>
      <key>block-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.empty.scala</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s*(/\*\*)(?!/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.documentation.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.scaladoc.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@param)\s+(\S+)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.scaladoc.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@t(?:param|hrows))\s+(\S+)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>@(return|see|note|example|constructor|usecase|author|version|since|todo|deprecated|migration|define|inheritdoc|groupname|groupprio|groupdesc|group|contentDiagram|documentable|syntax)\b</string>
                <key>name</key>
                <string>keyword.other.documentation.scaladoc.scala</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.documentation.link.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>string.other.link.title.markdown</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.documentation.link.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\[\[)([^]]+)(]])</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>char-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.character.begin.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.character.end.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(')'(')</string>
            <key>name</key>
            <string>string.quoted.other constant.character.literal.scala</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.character.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'|$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.character.end.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other constant.character.literal.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(?:["'\\bfnrt]|[0-7]{1,3}|u\h{4})</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>invalid.illegal.unrecognized-character-escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[^']{2,}</string>
                <key>name</key>
                <string>invalid.illegal.character-literal-too-long</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;!')[^']</string>
                <key>name</key>
                <string>invalid.illegal.character-literal-too-long</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#using-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#script-header</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declarations</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inheritance</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#extension</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#imports</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#exports</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#initialization</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xml-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#namedBounds</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#using</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#singleton-type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#scala-quoted-or-symbol</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#char-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#empty-parentheses</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter-list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qualifiedClassName</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#backQuotedVariable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#curly-braces</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#meta-brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#meta-bounds</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#meta-colons</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[\t ]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.scala</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\n</string>
                <key>name</key>
                <string>comment.line.double-slash.scala</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(false|null|true)\b</string>
            <key>name</key>
            <string>constant.language.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0[Xx][_\h]*)\b</string>
            <key>name</key>
            <string>constant.numeric.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(([0-9][0-9_]*(\.[0-9][0-9_]*)?)([Ee]([-+])?[0-9][0-9_]*)?|[0-9][0-9_]*)[DFLdfl]?\b</string>
            <key>name</key>
            <string>constant.numeric.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.[0-9][0-9_]*)([Ee]([-+])?[0-9][0-9_]*)?[DFLdfl]?\b</string>
            <key>name</key>
            <string>constant.numeric.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0[Bb][01]([01_]*[01])?[Ll]?\b</string>
            <key>name</key>
            <string>constant.numeric.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(this|super)\b</string>
            <key>name</key>
            <string>variable.language.scala</string>
          </dict>
        </array>
      </dict>
      <key>curly-braces</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.scala</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.scala</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#code</string>
          </dict>
        </array>
      </dict>
      <key>declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(def)\b\s*(?!/[*/])((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(trait)\b\s*(?!/[*/])((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.class.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(?:(case)\s+)?(class|object|enum)\b\s*(?!/[*/])((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;!\.)\b(type)\b\s*(?!/[*/])((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.stable.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.volatile.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(?:(val)|(var))\b\s*(?!/[*/])(?=(?:(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?\()</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.stable.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.stable.declaration.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(val)\b\s*(?!/[*/])((?:(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)(?:\s*,\s*(?:(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`))*)?(?!")</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.volatile.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.volatile.declaration.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(var)\b\s*(?!/[*/])((?:(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)(?:\s*,\s*(?:(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`))*)?(?!")</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.package.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.class.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(package)\s+(object)\b\s*(?!/[*/])((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)?</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(package)\s+</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.package.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=[\n;])</string>
            <key>name</key>
            <string>meta.package.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+))</string>
                <key>name</key>
                <string>entity.name.package.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\.</string>
                <key>name</key>
                <string>punctuation.definition.package</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.given.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(given)\b\s*([$_a-z\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|`[^`]+`)?</string>
          </dict>
        </array>
      </dict>
      <key>empty-parentheses</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.bracket.scala</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\(\))</string>
        <key>name</key>
        <string>meta.parentheses.scala</string>
      </dict>
      <key>exports</key>
      <dict>
        <key>begin</key>
        <string>\b(export)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.export.scala</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=[\n;])</string>
        <key>name</key>
        <string>meta.export.scala</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(given)\b</string>
            <key>name</key>
            <string>keyword.other.export.given.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?</string>
            <key>name</key>
            <string>entity.name.class.export.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+))</string>
            <key>name</key>
            <string>entity.name.export.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>punctuation.definition.export</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.export.selector.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.export.given.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.export.renamed-from.scala</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.export.renamed-from.scala</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.arrow.scala</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.export.renamed-to.scala</string>
                  </dict>
                  <key>6</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.export.renamed-to.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(given\s)?\s*(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))\s*(=&gt;)\s*(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))\s*</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(given)\b</string>
                <key>name</key>
                <string>keyword.other.export.given.scala</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.export.given.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.export.scala</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.export.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(given\s+)?(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>extension</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*(extension)\s+(?=[(\[])</string>
          </dict>
        </array>
      </dict>
      <key>imports</key>
      <dict>
        <key>begin</key>
        <string>\b(import)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.scala</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=[\n;])</string>
        <key>name</key>
        <string>meta.import.scala</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(given)\b</string>
            <key>name</key>
            <string>keyword.other.import.given.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s(as)\s</string>
            <key>name</key>
            <string>keyword.other.import.as.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?</string>
            <key>name</key>
            <string>entity.name.class.import.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+))</string>
            <key>name</key>
            <string>entity.name.import.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>punctuation.definition.import</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.import.selector.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.import.given.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.import.renamed-from.scala</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.import.renamed-from.scala</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.arrow.scala</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.import.renamed-to.scala</string>
                  </dict>
                  <key>6</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.import.renamed-to.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(given\s)?\s*(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))\s*(=&gt;)\s*(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))\s*</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(given)\b</string>
                <key>name</key>
                <string>keyword.other.import.given.scala</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.import.given.scala</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.import.scala</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.import.scala</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(given\s+)?(?:([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)|(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)))</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inheritance</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(extends|with|derives)\b\s*([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|`[^`]+`|(?=\([^)]+=&gt;)|(?=[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|(?="))?</string>
          </dict>
        </array>
      </dict>
      <key>initialization</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.scala</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(new)\b</string>
      </dict>
      <key>inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(inline)(?=\s+((?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)|`[^`]+`)\s*:)</string>
            <key>name</key>
            <string>storage.modifier.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(inline)\b(?=(?:.(?!\b(?:val|def|given)\b))*\b(if|match)\b)</string>
            <key>name</key>
            <string>keyword.control.flow.scala</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(return|throw)\b</string>
            <key>name</key>
            <string>keyword.control.flow.jump.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((?:class|isInstance|asInstance)Of)\b</string>
            <key>name</key>
            <string>support.function.type-of.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(else|if|then|do|while|for|yield|match|case)\b</string>
            <key>name</key>
            <string>keyword.control.flow.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(end)\s+(if|while|for|match)(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
            <key>name</key>
            <string>keyword.control.flow.end.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(end)\s+(val)(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
            <key>name</key>
            <string>keyword.declaration.stable.end.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(end)\s+(var)(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
            <key>name</key>
            <string>keyword.declaration.volatile.end.scala</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.end.scala</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*(end)\s+(?:(new|extension)|([A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?))(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(catch|finally|try)\b</string>
            <key>name</key>
            <string>keyword.control.exception.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(end)\s+(try)(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
            <key>name</key>
            <string>keyword.control.exception.end.scala</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.declaration</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*(end)\s+(`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+))?(?=\s*(/(?:/.*|\*(?!.*\*/\s*\S.*).*))?$)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-!#%\&amp;*+/:&lt;-@\\^|~\p{Sm}\p{So}]){3,}</string>
            <key>name</key>
            <string>keyword.operator.scala</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(\|\||&amp;&amp;)</string>
                    <key>name</key>
                    <string>keyword.operator.logical.scala</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>([!&lt;=&gt;]=)</string>
                    <key>name</key>
                    <string>keyword.operator.comparison.scala</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>..</string>
                    <key>name</key>
                    <string>keyword.operator.scala</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>([-!#%\&amp;*+/:&lt;-@\\^|~\p{Sm}\p{So}]{2,}|_\*)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(!)</string>
                    <key>name</key>
                    <string>keyword.operator.logical.scala</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>([-%*+/~])</string>
                    <key>name</key>
                    <string>keyword.operator.arithmetic.scala</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>([&lt;=&gt;])</string>
                    <key>name</key>
                    <string>keyword.operator.comparison.scala</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>.</string>
                    <key>name</key>
                    <string>keyword.operator.scala</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;!_)([-!#%\&amp;*+/:&lt;-@\\^|~\p{Sm}\p{So}])</string>
          </dict>
        </array>
      </dict>
      <key>meta-bounds</key>
      <dict>
        <key>match</key>
        <string>&lt;%|=:=|&lt;:&lt;|&lt;%&lt;|&gt;:|&lt;:</string>
        <key>name</key>
        <string>meta.bounds.scala</string>
      </dict>
      <key>meta-brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\{</string>
            <key>name</key>
            <string>punctuation.section.block.begin.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>}</string>
            <key>name</key>
            <string>punctuation.section.block.end.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[]()\[{}]</string>
            <key>name</key>
            <string>meta.bracket.scala</string>
          </dict>
        </array>
      </dict>
      <key>meta-colons</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;!:):(?!:)</string>
            <key>name</key>
            <string>meta.colon.scala</string>
          </dict>
        </array>
      </dict>
      <key>namedBounds</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.import.as.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.stable.declaration.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s+(as)\s+([$_a-z\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)\b</string>
          </dict>
        </array>
      </dict>
      <key>parameter-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.colon.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=[^$.0-9A-Z_a-z])(`[^`]+`|[$_a-z\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)\s*(:)\s+</string>
          </dict>
        </array>
      </dict>
      <key>qualifiedClassName</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.class</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(([A-Z]\w*)(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)</string>
      </dict>
      <key>scala-quoted-or-symbol</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.flow.staging.scala constant.other.symbol.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.other.symbol.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(')((?&gt;[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+))(?!')</string>
          </dict>
          <dict>
            <key>match</key>
            <string>'(?=\s*\{(?!'))</string>
            <key>name</key>
            <string>keyword.control.flow.staging.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>'(?=\s*\[(?!'))</string>
            <key>name</key>
            <string>keyword.control.flow.staging.scala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$(?=\s*\{)</string>
            <key>name</key>
            <string>keyword.control.flow.staging.scala</string>
          </dict>
        </array>
      </dict>
      <key>script-header</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.shebang.scala</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^#!(.*)$</string>
        <key>name</key>
        <string>comment.block.shebang.scala</string>
      </dict>
      <key>singleton-type</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.type.scala</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\.(type)(?![$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[0-9])</string>
      </dict>
      <key>storage-modifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(pr(?:ivate\[\S+]|otected\[\S+]|ivate|otected))\b</string>
            <key>name</key>
            <string>storage.modifier.access</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(synchronized|@volatile|abstract|final|lazy|sealed|implicit|override|@transient|@native)\b</string>
            <key>name</key>
            <string>storage.modifier.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)\b(transparent|opaque|infix|open|inline)\b(?=[a-z\s]*\b(def|val|var|given|type|class|trait|object|enum)\b)</string>
            <key>name</key>
            <string>storage.modifier.other</string>
          </dict>
        </array>
      </dict>
      <key>string-interpolation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\$\$</string>
            <key>name</key>
            <string>constant.character.escape.interpolation.scala</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.template-expression.begin.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\$)([$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*)</string>
            <key>name</key>
            <string>meta.template.expression.scala</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.template-expression.begin.scala</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.line.scala</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.template-expression.end.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template.expression.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.triple.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(?:\\|u\h{4})</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(raw)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.interpolation.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")(?!")|\$\n|(\$[^"$A-Z_a-{\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala punctuation.definition.string.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\$["$]</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.</string>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b([$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.interpolation.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")(?!")|\$\n|(\$[^"$A-Z_a-{\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala punctuation.definition.string.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\(?:\\|u\h{4})</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.</string>
                <key>name</key>
                <string>string.quoted.triple.interpolated.scala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.scala</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(?:["'\\bfnrt]|[0-7]{1,3}|u\h{4})</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(raw)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.interpolation.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")|\$\n|(\$[^"$A-Z_a-{\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala punctuation.definition.string.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\$["$]</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.</string>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b([$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.interpolation.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala punctuation.definition.string.begin.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")|\$\n|(\$[^"$A-Z_a-{\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala punctuation.definition.string.end.scala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\$["$]</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\(?:["'\\bfnrt]|[0-7]{1,3}|u\h{4})</string>
                <key>name</key>
                <string>constant.character.escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>invalid.illegal.unrecognized-string-escape.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.</string>
                <key>name</key>
                <string>string.quoted.double.interpolated.scala</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>using</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.scala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=\()\s*(using)\s</string>
          </dict>
        </array>
      </dict>
      <key>using-directive</key>
      <dict>
        <key>begin</key>
        <string>^\s*(//&gt;)\s*(using)[^\n\S]+(\S+)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.scala</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.scala</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[A-Z\p{Lt}\p{Lu}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|`[^`]+`|(?:[$A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}][$0-9A-Z_a-z\p{Lt}\p{Lu}\p{Lo}\p{Nl}\p{Ll}]*(?:(?&lt;=_)[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)?|[-!#%\&amp;*+/:&lt;-@^|~\p{Sm}\p{So}]+)</string>
                <key>name</key>
                <string>entity.name.import.scala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\.</string>
                <key>name</key>
                <string>punctuation.definition.import</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.shebang.scala</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^,\s]+</string>
            <key>name</key>
            <string>string.quoted.double.scala</string>
          </dict>
        </array>
      </dict>
      <key>xml-doublequotedString</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#xml-entity</string>
          </dict>
        </array>
      </dict>
      <key>xml-embedded-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.scala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.source.embedded.scala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.namespace.xml</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.xml</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.xml</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.localname.xml</string>
              </dict>
            </dict>
            <key>match</key>
            <string> (?:([-0-9A-Z_a-z]+)((:)))?([-A-Z_a-z]+)=</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xml-doublequotedString</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xml-singlequotedString</string>
          </dict>
        </array>
      </dict>
      <key>xml-entity</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(&amp;)([:A-Z_a-z][-.0-:A-Z_a-z]*|#[0-9]+|#x\h+)(;)</string>
        <key>name</key>
        <string>constant.character.entity.xml</string>
      </dict>
      <key>xml-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(&lt;)((?:([0-9A-Z_a-z][0-9A-Z_a-z]*)((:)))?([0-9A-Z_a-z][-0-:A-Z_a-z]*))(?=(\s[^&gt;]*)?&gt;&lt;/\2&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.xml</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.namespace.xml</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.xml</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.xml</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.localname.xml</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;(&lt;))/(?:([-0-9A-Z_a-z]+)((:)))?([-0-:A-Z_a-z]*[0-9A-Z_a-z])(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.xml</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.scope.between-tag-pair.xml</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.namespace.xml</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.xml</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.xml</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.localname.xml</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.xml</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.no-content.xml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#xml-embedded-content</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;/?)(?:([0-9A-Z_a-z][-0-9A-Z_a-z]*)((:)))?([0-9A-Z_a-z][-0-:A-Z_a-z]*)(?=[^&gt;]*?&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.xml</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.namespace.xml</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.xml</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.xml</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.localname.xml</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(/?&gt;)</string>
            <key>name</key>
            <string>meta.tag.xml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#xml-embedded-content</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#xml-entity</string>
          </dict>
        </array>
      </dict>
      <key>xml-singlequotedString</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#xml-entity</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.scala</string>
  </dict>
</plist>