<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>shaderlab</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Range|Float|Int|Color|Vector|2D|3D|Cube|Any)\b</string>
        <key>name</key>
        <string>support.type.basic.shaderlab</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Shader|Properties|SubShader|Pass|Category)\b</string>
        <key>name</key>
        <string>storage.type.structure.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Name|Tags|Fallback|CustomEditor|Cull|ZWrite|ZTest|Offset|Blend|BlendOp|ColorMask|AlphaToMask|LOD|Lighting|Stencil|Ref|ReadMask|WriteMask|Comp|CompBack|CompFront|Fail|ZFail|UsePass|GrabPass|Dependency|Material|Diffuse|Ambient|Shininess|Specular|Emission|Fog|Mode|Density|SeparateSpecular|SetTexture|Combine|ConstantColor|Matrix|AlphaTest|ColorMaterial|BindChannels|Bind)\b</string>
        <key>name</key>
        <string>support.type.propertyname.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Back|Front|On|Off|[ABGR]{1,3}|AmbientAndDiffuse|Emission)\b</string>
        <key>name</key>
        <string>support.constant.property-value.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Less|Greater|LEqual|GEqual|Equal|NotEqual|Always|Never)\b</string>
        <key>name</key>
        <string>support.constant.property-value.comparisonfunction.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Keep|Zero|Replace|IncrSat|DecrSat|Invert|IncrWrap|DecrWrap)\b</string>
        <key>name</key>
        <string>support.constant.property-value.stenciloperation.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Previous|Primary|Texture|Constant|Lerp|Double|Quad|Alpha)\b</string>
        <key>name</key>
        <string>support.constant.property-value.texturecombiners.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Global|Linear|Exp2?)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fog.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Vertex|Normal|Tangent|TexCoord0|TexCoord1)\b</string>
        <key>name</key>
        <string>support.constant.property-value.bindchannels.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:Add|Sub|RevSub|Min|Max|LogicalClear|LogicalSet|LogicalCopyInverted|LogicalCopy|LogicalNoop|LogicalInvert|LogicalAnd|LogicalNand|LogicalOr|LogicalNor|LogicalXor|LogicalEquiv|LogicalAndReverse|LogicalAndInverted|LogicalOrReverse|LogicalOrInverted)\b</string>
        <key>name</key>
        <string>support.constant.property-value.blendoperations.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:One|Zero|SrcColor|SrcAlpha|DstColor|DstAlpha|OneMinusSrcColor|OneMinusSrcAlpha|OneMinusDstColor|OneMinusDstAlpha)\b</string>
        <key>name</key>
        <string>support.constant.property-value.blendfactors.shaderlab</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\[([A-Z_a-z][0-9A-Z_a-z]*)](?!\s*[A-Z_a-z][0-9A-Z_a-z]*\s*\(")</string>
        <key>name</key>
        <string>support.variable.reference.shaderlab</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(\[)</string>
        <key>end</key>
        <string>(])</string>
        <key>name</key>
        <string>meta.attribute.shaderlab</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\G([A-Za-z]+)\b</string>
            <key>name</key>
            <string>support.type.attributename.shaderlab</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([A-Z_a-z][0-9A-Z_a-z]*)\s*\(</string>
        <key>name</key>
        <string>support.variable.declaration.shaderlab</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(CG(?:PROGRAM|INCLUDE))\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\b(ENDCG)\b</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.cgblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#hlsl-embedded</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(HLSL(?:PROGRAM|INCLUDE))\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\b(ENDHLSL)\b</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.hlslblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#hlsl-embedded</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.shaderlab</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>hlsl-embedded</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.hlsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(fixed([1-4](x[1-4])?)?)\b</string>
            <key>name</key>
            <string>storage.type.basic.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNITY_MATRIX_MVP?|UNITY_MATRIX_M|UNITY_MATRIX_V|UNITY_MATRIX_P|UNITY_MATRIX_VP|UNITY_MATRIX_T_MV|UNITY_MATRIX_I_V|UNITY_MATRIX_IT_MV|_Object2World|_World2Object|unity_ObjectToWorld|unity_WorldToObject)\b</string>
            <key>name</key>
            <string>support.variable.transformations.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(_WorldSpaceCameraPos|_ProjectionParams|_ScreenParams|_ZBufferParams|unity_OrthoParams|unity_CameraProjection|unity_CameraInvProjection|unity_CameraWorldClipPlanes)\b</string>
            <key>name</key>
            <string>support.variable.camera.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((?:_|_Sin|_Cos|unity_Delta)Time)\b</string>
            <key>name</key>
            <string>support.variable.time.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(_LightColor0|_WorldSpaceLightPos0|_LightMatrix0|unity_4LightPosX0|unity_4LightPosY0|unity_4LightPosZ0|unity_4LightAtten0|unity_LightColor|_LightColor|unity_LightPosition|unity_LightAtten|unity_SpotDirection)\b</string>
            <key>name</key>
            <string>support.variable.lighting.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(unity_AmbientSky|unity_AmbientEquator|unity_AmbientGround|UNITY_LIGHTMODEL_AMBIENT|unity_FogColor|unity_FogParams)\b</string>
            <key>name</key>
            <string>support.variable.fog.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(unity_LODFade)\b</string>
            <key>name</key>
            <string>support.variable.various.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SHADER_API_(?:D3D9|D3D11|GLCORE|OPENGL|GLES3??|METAL|D3D11_9X|PSSL|XBOXONE|PSP2|WIIU|MOBILE|GLSL))\b</string>
            <key>name</key>
            <string>support.variable.preprocessor.targetplatform.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SHADER_TARGET)\b</string>
            <key>name</key>
            <string>support.variable.preprocessor.targetmodel.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNITY_VERSION)\b</string>
            <key>name</key>
            <string>support.variable.preprocessor.unityversion.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNITY_(?:BRANCH|FLATTEN|NO_SCREENSPACE_SHADOWS|NO_LINEAR_COLORSPACE|NO_RGBM|NO_DXT5nm|FRAMEBUFFER_FETCH_AVAILABLE|USE_RGBA_FOR_POINT_SHADOWS|ATTEN_CHANNEL|HALF_TEXEL_OFFSET|UV_STARTS_AT_TOP|MIGHT_NOT_HAVE_DEPTH_Texture|NEAR_CLIP_VALUE|VPOS_TYPE|CAN_COMPILE_TESSELLATION|COMPILER_HLSL|COMPILER_HLSL2GLSL|COMPILER_CG|REVERSED_Z))\b</string>
            <key>name</key>
            <string>support.variable.preprocessor.platformdifference.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNITY_PASS_(?:FORWARDBASE|FORWARDADD|DEFERRED|SHADOWCASTER|PREPASSBASE|PREPASSFINAL))\b</string>
            <key>name</key>
            <string>support.variable.preprocessor.texture2D.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(appdata_(?:base|tan|full|img))\b</string>
            <key>name</key>
            <string>support.class.structures.shaderlab</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SurfaceOutputStandardSpecular|SurfaceOutputStandard|SurfaceOutput|Input)\b</string>
            <key>name</key>
            <string>support.class.surface.shaderlab</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([0-9]+\.?[0-9]*)\b</string>
            <key>name</key>
            <string>constant.numeric.shaderlab</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.shaderlab</string>
  </dict>
</plist>