<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>soy</string>
    </array>
    <key>injections</key>
    <dict>
      <key>meta.tag</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>name</key>
    <string>soy</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#alias</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#delpackage</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#template</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>alias</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.soy</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.soy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(alias)\s+([.\w]+)(?:\s+(as)\s+(\w+))?}</string>
      </dict>
      <key>attribute</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.other.attribute.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.double.quoted.soy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\w+)=("(?:\\?.)*?")</string>
      </dict>
      <key>body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#let</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#css</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xid</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#condition-control</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#msg</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#special-character</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#print</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic</string>
          </dict>
        </array>
      </dict>
      <key>boolean</key>
      <dict>
        <key>match</key>
        <string>true|false</string>
        <key>name</key>
        <string>language.constant.boolean.soy</string>
      </dict>
      <key>call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{((?:del)?call)\s+([.\w]+)(?=[^/]*?})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\{/(\1)}</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.soy</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variant</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attribute</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#param</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{((?:del)?call)(\s+[.\w]+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#variant</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attribute</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.soy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.parameter.soy</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.soy</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@param\??)\s+(\S+)</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(//.*)$</string>
            <key>name</key>
            <string>comment.line.double-slash.soy</string>
          </dict>
        </array>
      </dict>
      <key>condition</key>
      <dict>
        <key>begin</key>
        <string>\{/?(if|elseif|switch|case)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>condition-control</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.soy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(else|ifempty|default)}</string>
      </dict>
      <key>css</key>
      <dict>
        <key>begin</key>
        <string>\{(css)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>delpackage</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.soy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(delpackage)\s+([.\w]+)}</string>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#null</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-ref</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
        </array>
      </dict>
      <key>for</key>
      <dict>
        <key>begin</key>
        <string>\{/?(for(?:each|))(?=[}\s])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>in</string>
            <key>name</key>
            <string>keyword.control.soy</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>begin</key>
        <string>(\w+)\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>let</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{(let)\s+(\$\w+\s*:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{(let)\s+(\$\w+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\{/(\1)}</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#attribute</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#body</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal</key>
      <dict>
        <key>begin</key>
        <string>\{(literal)}</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\{/(\1)}</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.literal</string>
      </dict>
      <key>msg</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>match</key>
        <string>\{/?((?:|fallback)msg)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
        </array>
      </dict>
      <key>namespace</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.soy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(namespace)\s+([.\w]+)}</string>
      </dict>
      <key>null</key>
      <dict>
        <key>match</key>
        <string>null</string>
        <key>name</key>
        <string>language.constant.null.soy</string>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>-?\.?\d+|\d[.\d]*</string>
        <key>name</key>
        <string>language.constant.numeric</string>
      </dict>
      <key>operator</key>
      <dict>
        <key>match</key>
        <string>-|not|[%*+/]|&lt;=|&gt;=|[&lt;&gt;]|==|!=|and|or|\?:|[:?]</string>
        <key>name</key>
        <string>keyword.operator.soy</string>
      </dict>
      <key>param</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{(param)\s+(\w+\s*:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{(param)\s+(\w+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\{/(\1)}</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.soy</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#attribute</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#body</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>print</key>
      <dict>
        <key>begin</key>
        <string>\{(print)?\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.soy</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\|\s*(changeNewlineToBr|truncate|bidiSpanWrap|bidiUnicodeWrap)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>special-character</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>language.support.constant</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(sp|nil|\\r|\\n|\\t|lb|rb)}</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>name</key>
        <string>string.quoted.single.soy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(?:["'\\bfnrt]|u\h{4})</string>
            <key>name</key>
            <string>constant.character.escape.soy</string>
          </dict>
        </array>
      </dict>
      <key>template</key>
      <dict>
        <key>begin</key>
        <string>\{((?:|del)template)\s([.\w]+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\{(/\1)}</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.soy</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{(@param)(\??)\s+(\S+\s*:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.parameter.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.keyword.operator.soy</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.parameter.soy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#variant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>any|null|\?|string|bool|int|float|number|html|uri|js|css|attributes</string>
            <key>name</key>
            <string>support.type.soy</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(list|map)(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.soy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.punctuation.soy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.modifier.soy</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>variable-ref</key>
      <dict>
        <key>match</key>
        <string>\$[\a-z][.\w]*</string>
        <key>name</key>
        <string>variable.other.soy</string>
      </dict>
      <key>variant</key>
      <dict>
        <key>begin</key>
        <string>(variant)=(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.other.attribute.soy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.double.quoted.soy</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.double.quoted.soy</string>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.double.quoted.soy</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>xid</key>
      <dict>
        <key>begin</key>
        <string>\{(xid)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.soy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.soy</string>
  </dict>
</plist>