<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>talonscript</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#body-header</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#header</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#body-noheader</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#settings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>action</key>
      <dict>
        <key>begin</key>
        <string>([.0-9A-Z_a-z]+)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\.</string>
                <key>name</key>
                <string>punctuation.separator.talon</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.talon</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.talon</string>
          </dict>
        </dict>
        <key>name</key>
        <string>variable.parameter.talon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#action</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring-long</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#argsep</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#varname</string>
          </dict>
        </array>
      </dict>
      <key>action-gamepad</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.talon</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#key-mods</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.key.talon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(deck|gamepad|action|face|parrot)(\()(.*)(\))</string>
        <key>name</key>
        <string>entity.name.function.talon</string>
      </dict>
      <key>action-key</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.talon</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#key-prefixes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#key-mods</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keystring</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.key.talon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>key(\()(.*)(\))</string>
        <key>name</key>
        <string>entity.name.function.talon</string>
      </dict>
      <key>argsep</key>
      <dict>
        <key>match</key>
        <string>,</string>
        <key>name</key>
        <string>punctuation.separator.talon</string>
      </dict>
      <key>assignment</key>
      <dict>
        <key>begin</key>
        <string>(\S*)(\s?=\s?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.talon</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.talon</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\n</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-invalid</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>body-header</key>
      <dict>
        <key>begin</key>
        <string>^-$</string>
        <key>end</key>
        <string>(?=not)possible</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#body-noheader</string>
          </dict>
        </array>
      </dict>
      <key>body-noheader</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-invalid</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#other-rule-definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#speech-rule-definition</string>
          </dict>
        </array>
      </dict>
      <key>capture</key>
      <dict>
        <key>match</key>
        <string>(&lt;[.0-9A-Z_a-z]+&gt;)</string>
        <key>name</key>
        <string>variable.parameter.talon</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>match</key>
        <string>^\s*(#.*)$</string>
        <key>name</key>
        <string>comment.line.number-sign.talon</string>
      </dict>
      <key>comment-invalid</key>
      <dict>
        <key>match</key>
        <string>(\s*#.*)$</string>
        <key>name</key>
        <string>invalid.illegal</string>
      </dict>
      <key>context</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(and |or )</string>
                <key>name</key>
                <string>keyword.operator.talon</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment-invalid</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#regexp</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(.*): (.*)</string>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#qstring-long</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#action-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#action</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#varname</string>
          </dict>
        </array>
      </dict>
      <key>fstring</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#action</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operator</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#number</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#varname</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#qstring</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\{(.+?)}</string>
        <key>name</key>
        <string>constant.character.format.placeholder.talon</string>
      </dict>
      <key>header</key>
      <dict>
        <key>begin</key>
        <string>(?=(?:^app|title|os|tag|list|language):)</string>
        <key>end</key>
        <string>(?=^-$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#context</string>
          </dict>
        </array>
      </dict>
      <key>key-mods</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.talon</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.talon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(:)(up|down|change|repeat|start|stop|\d+)</string>
        <key>name</key>
        <string>keyword.operator.talon</string>
      </dict>
      <key>key-prefixes</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.talon</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.talon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(ctrl|shift|cmd|alt|win|super)(-)</string>
      </dict>
      <key>keystring</key>
      <dict>
        <key>begin</key>
        <string>(["'])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.talon</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\1)|$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.talon</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.talon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-body</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#key-mods</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#key-prefixes</string>
          </dict>
        </array>
      </dict>
      <key>list</key>
      <dict>
        <key>match</key>
        <string>(\{[.0-9A-Z_a-z]+?})</string>
        <key>name</key>
        <string>string.interpolated.talon</string>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=\b)\d+(\.\d+)?</string>
        <key>name</key>
        <string>constant.numeric.talon</string>
      </dict>
      <key>operator</key>
      <dict>
        <key>match</key>
        <string>\s([-*+/]|or)\s</string>
        <key>name</key>
        <string>keyword.operator.talon</string>
      </dict>
      <key>other-rule-definition</key>
      <dict>
        <key>begin</key>
        <string>^([a-z]+\(.*[^-]\)|[a-z]+\(.*--\)|[a-z]+\(-\)|[a-z]+\(\)):</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#action-key</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#action-gamepad</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#rule-specials</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^[^#\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statement</string>
          </dict>
        </array>
      </dict>
      <key>qstring</key>
      <dict>
        <key>begin</key>
        <string>(["'])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.talon</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\1)|$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.talon</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.talon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-body</string>
          </dict>
        </array>
      </dict>
      <key>qstring-long</key>
      <dict>
        <key>begin</key>
        <string>("""|''')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.talon</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\1)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.talon</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.talon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-body</string>
          </dict>
        </array>
      </dict>
      <key>regexp</key>
      <dict>
        <key>begin</key>
        <string>(/)</string>
        <key>end</key>
        <string>(/)</string>
        <key>name</key>
        <string>string.regexp.talon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>support.other.match.any.regexp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$</string>
            <key>name</key>
            <string>support.other.match.end.regexp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^</string>
            <key>name</key>
            <string>support.other.match.begin.regexp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[$*+.?^]</string>
            <key>name</key>
            <string>constant.character.escape.talon</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\[(\\]|[^]])*]</string>
            <key>name</key>
            <string>constant.other.set.regexp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[*+?]</string>
            <key>name</key>
            <string>keyword.operator.quantifier.regexp</string>
          </dict>
        </array>
      </dict>
      <key>rule-specials</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.talon</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.talon</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.talon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(settings|tag)(\()(\))</string>
      </dict>
      <key>speech-rule-definition</key>
      <dict>
        <key>begin</key>
        <string>^(.*?):</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>^\^</string>
                <key>name</key>
                <string>string.regexp.talon</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$$</string>
                <key>name</key>
                <string>string.regexp.talon</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\(</string>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.talon</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\)</string>
                <key>name</key>
                <string>punctuation.definition.parameters.end.talon</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\|</string>
                <key>name</key>
                <string>punctuation.separator.talon</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#capture</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#list</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^[^#\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statement</string>
          </dict>
        </array>
      </dict>
      <key>statement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-invalid</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring-long</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#action-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#action</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#assignment</string>
          </dict>
        </array>
      </dict>
      <key>string-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\{\{|}}</string>
            <key>name</key>
            <string>string.quoted.double.talon</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\["'\\nrt]</string>
            <key>name</key>
            <string>constant.character.escape.python</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#fstring</string>
          </dict>
        </array>
      </dict>
      <key>varname</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.talon</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>_</string>
                <key>name</key>
                <string>keyword.operator.talon</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>([.0-9A-Z_a-z])(_(list|\d+)(?=[^.0-9A-Z_a-z]))?</string>
        <key>name</key>
        <string>variable.parameter.talon</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.talon</string>
  </dict>
</plist>