<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>vala</string>
      <string>vapi</string>
      <string>gs</string>
    </array>
    <key>name</key>
    <string>vala</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.vala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.empty.vala</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.javadoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments-inline</string>
          </dict>
        </array>
      </dict>
      <key>comments-inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.vala</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.vala</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.vala</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.vala</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s*((//).*$\n?)</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((0([Xx])\h*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))(([Ee])([-+])?[0-9]+)?)([DFLUdflu]|UL|ul)?\b</string>
            <key>name</key>
            <string>constant.numeric.vala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z][0-9A-Z_]+)\b</string>
            <key>name</key>
            <string>variable.other.constant.vala</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\w+)(?=\s*(&lt;[.\s\w]+&gt;\s*)?\()</string>
            <key>name</key>
            <string>entity.name.function.vala</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|[^.@\w])(as|do|if|in|is|not|or|and|for|get|new|out|ref|set|try|var|base|case|else|enum|lock|null|this|true|void|weak|async|break|catch|class|const|false|owned|throw|using|while|with|yield|delete|extern|inline|params|public|return|sealed|signal|sizeof|static|struct|switch|throws|typeof|unlock|default|dynamic|ensures|finally|foreach|private|unowned|virtual|abstract|continue|delegate|internal|override|requires|volatile|construct|interface|namespace|protected|errordomain)\b</string>
            <key>name</key>
            <string>keyword.vala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|[^.@\w])(bool|double|float|unichar2??|char|uchar|int|uint|long|ulong|short|ushort|size_t|ssize_t|string|string16|string32|void|signal|int8|int16|int32|int64|uint8|uint16|uint32|uint64|va_list|time_t)\b</string>
            <key>name</key>
            <string>keyword.vala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(#(?:if|elif|else|endif))</string>
            <key>name</key>
            <string>keyword.vala</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"""</string>
            <key>end</key>
            <string>"""</string>
            <key>name</key>
            <string>string.quoted.triple.vala</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>@"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.interpolated.vala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.vala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$\w+</string>
                <key>name</key>
                <string>constant.character.escape.vala</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$\(([^()]|\(([^()]|\([^)]*\))*\))*\)</string>
                <key>name</key>
                <string>constant.character.escape.vala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.vala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.vala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>name</key>
            <string>string.quoted.single.vala</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.vala</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>/((\\/)|([^/]))*/(?=\s*[\n),.;])</string>
            <key>name</key>
            <string>string.regexp.vala</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|[^.@\w])(bool|double|float|unichar2??|char|uchar|int|uint|long|ulong|short|ushort|size_t|ssize_t|string|string16|string32|void|signal|int8|int16|int32|int64|uint8|uint16|uint32|uint64|va_list|time_t)\b</string>
            <key>name</key>
            <string>storage.type.primitive.vala</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z]+\w*)\b</string>
            <key>name</key>
            <string>entity.name.type.vala</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_a-z]+\w*)\b</string>
            <key>name</key>
            <string>variable.other.vala</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.vala</string>
  </dict>
</plist>