<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>wasm</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#instructions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#modules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#invalid</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.wat</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(;;).*$</string>
            <key>name</key>
            <string>comment.line.wat</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.wat</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.wat</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.wat</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i8x16)(?:\s+0x\h{1,2}){16}\b</string>
                <key>name</key>
                <string>constant.numeric.vector.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i16x8)(?:\s+0x\h{1,4}){8}\b</string>
                <key>name</key>
                <string>constant.numeric.vector.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32x4)(?:\s+0x\h{1,8}){4}\b</string>
                <key>name</key>
                <string>constant.numeric.vector.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64x2)(?:\s+0x\h{1,16}){2}\b</string>
                <key>name</key>
                <string>constant.numeric.vector.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[-+]?\b[0-9][0-9]*(?:\.[0-9][0-9]*)?(?:[Ee][-+]?[0-9]+)?\b</string>
                <key>name</key>
                <string>constant.numeric.float.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[-+]?\b0x(\h*\.\h+|\h+\.?)[Pp][-+]?[0-9]+\b</string>
                <key>name</key>
                <string>constant.numeric.float.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[-+]?\binf\b</string>
                <key>name</key>
                <string>constant.numeric.float.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[-+]?\bnan:0x\h\h*\b</string>
                <key>name</key>
                <string>constant.numeric.float.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[-+]?\b(?:0x\h\h*|\d\d*)\b</string>
                <key>name</key>
                <string>constant.numeric.integer.wat</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>instructions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i(?:32|64))\.trunc_sat_f(?:32|64)_[su]\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32)\.extend(?:8|16)_s\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64)\.extend(?:8|16|32)_s\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(memory)\.(?:copy|fill|init|drop)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(v128)\.(?:const|and|or|xor|not|andnot|bitselect|load|store)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i8x16)\.(?:shuffle|swizzle|splat|replace_lane|add|sub|mul|neg|shl|shr_[su]|eq|ne|lt_[su]|le_[su]|gt_[su]|ge_[su]|min_[su]|max_[su]|any_true|all_true|extract_lane_[su]|add_saturate_[su]|sub_saturate_[su]|avgr_u|narrow_i16x8_[su])\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i16x8)\.(?:splat|replace_lane|add|sub|mul|neg|shl|shr_[su]|eq|ne|lt_[su]|le_[su]|gt_[su]|ge_[su]|min_[su]|max_[su]|any_true|all_true|extract_lane_[su]|add_saturate_[su]|sub_saturate_[su]|avgr_u|load8x8_[su]|narrow_i32x4_[su]|widen_(low|high)_i8x16_[su])\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32x4)\.(?:splat|replace_lane|add|sub|mul|neg|shl|shr_[su]|eq|ne|lt_[su]|le_[su]|gt_[su]|ge_[su]|min_[su]|max_[su]|any_true|all_true|extract_lane|load16x4_[su]|trunc_sat_f32x4_[su]|widen_(low|high)_i16x8_[su])\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64x2)\.(?:splat|replace_lane|add|sub|mul|neg|shl|shr_[su]|extract_lane|load32x2_[su])\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f32x4)\.(?:splat|replace_lane|add|sub|mul|neg|extract_lane|eq|ne|lt|le|gt|ge|abs|min|max|div|sqrt|convert_i32x4_[su])\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f64x2)\.(?:splat|replace_lane|add|sub|mul|neg|extract_lane|eq|ne|lt|le|gt|ge|abs|min|max|div|sqrt)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(v8x16)\.(?:load_splat|shuffle|swizzle)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(v16x8)\.load_splat\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(v32x4)\.load_splat\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(v64x2)\.load_splat\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32)\.(atomic)\.(?:load(?:8_u|16_u)?|store(?:8|16)?|wait|(rmw)\.(?:add|sub|and|or|xor|xchg|cmpxchg)|(rmw(?:8|16))\.(?:add|sub|and|or|xor|xchg|cmpxchg)_u)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64)\.(atomic)\.(?:load(?:(?:8|16|32)_u)?|store(?:8|16|32)?|wait|(rmw)\.(?:add|sub|and|or|xor|xchg|cmpxchg)|(rmw(?:8|16|32))\.(?:add|sub|and|or|xor|xchg|cmpxchg)_u)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(atomic)\.(?:notify|fence)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\bshared\b</string>
                <key>name</key>
                <string>storage.modifier.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(ref)\.(?:null|is_null|func|extern)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(table)\.(?:get|size|grow|fill|init|copy)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(?:extern|func|null)ref\b</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\breturn_call(?:_indirect)?\b</string>
                <key>name</key>
                <string>keyword.control.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:try|catch|throw|rethrow|br_on_exn)\b</string>
                <key>name</key>
                <string>keyword.control.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;=\()event\b</string>
                <key>name</key>
                <string>storage.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32|i64|f32|f64|externref|funcref|nullref|exnref)\.p(?:ush|op)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32)\.(?:load|load(?:8|16)(?:_[su])?|store(?:8|16)?)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64)\.(?:load|load(?:8|16|32)(?:_[su])?|store(?:8|16|32)?)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f(?:32|64))\.(?:load|store)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.memory.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(memory)\.(?:size|grow)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(offset|align)=\b</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.local.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(local)\.(?:get|set|tee)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.global.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(global)\.[gs]et\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i(?:32|64))\.(const|eqz?|ne|lt_[su]|gt_[su]|le_[su]|ge_[su]|clz|ctz|popcnt|add|sub|mul|div_[su]|rem_[su]|and|or|xor|shl|shr_[su]|rotl|rotr)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f(?:32|64))\.(const|eq|ne|lt|gt|le|ge|abs|neg|ceil|floor|trunc|nearest|sqrt|add|sub|mul|div|min|max|copysign)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i32)\.(wrap_i64|trunc_(f(?:32|64))_[su]|reinterpret_f32)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i64)\.(extend_i32_[su]|trunc_f(32|64)_[su]|reinterpret_f64)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f32)\.(convert_i(32|64)_[su]|demote_f64|reinterpret_i32)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.type.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(f64)\.(convert_i(32|64)_[su]|promote_f32|reinterpret_i64)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(?:unreachable|nop|block|loop|if|then|else|end|br|br_if|br_table|return|call|call_indirect)\b</string>
                <key>name</key>
                <string>keyword.control.wat</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(?:drop|select)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(ref)\.(?:eq|test|cast)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(struct)\.(?:new_canon|new_canon_default|get|get_s|get_u|set)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(array)\.(?:new_canon|new_canon_default|get|get_s|get_u|set|len|new_canon_fixed|new_canon_data|new_canon_elem)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(i31)\.(?:new|get_s|get_u)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\bbr_on_(?:non_null|cast|cast_fail)\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.class.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\b(extern)\.(?:in|ex)ternalize\b</string>
                <key>name</key>
                <string>keyword.operator.word.wat</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>invalid</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[^()\s]+</string>
            <key>name</key>
            <string>invalid.wat</string>
          </dict>
        </array>
      </dict>
      <key>modules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\(data)\s+(passive)\b</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(?&lt;=\()(?:module|import|export|memory|data|table|elem|start|func|type|param|result|global|local)\b</string>
                <key>name</key>
                <string>storage.type.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\()\s*(mut)\b</string>
                <key>name</key>
                <string>storage.modifier.wat</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\(func|\(start|call|return_call|ref\.func)\s+(\$[!#-'*+\--:&lt;-Z\\^-z|~]*)</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\)\s+(\$[!#-'*+\--:&lt;-Z\\^-z|~]*)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.wat</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(?&lt;=\s)\$[!#-'*+\--:&lt;-Z\\^-z|~]*</string>
                    <key>name</key>
                    <string>entity.name.function.wat</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.function.wat</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(?&lt;=\(type)\s+(\$[!#-'*+\--:&lt;-Z\\^-z|~]*)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$[!#-'*+\--:&lt;-Z\\^-z|~]*\b</string>
                <key>name</key>
                <string>variable.other.wat</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.wat</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(["'\\nt]|\h{2})</string>
            <key>name</key>
            <string>constant.character.escape.wat</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\bv128\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:extern|func|null)ref\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\bexnref\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:i32|i64|f32|f64)\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:i8|i16|ref|funcref|externref|anyref|eqref|i31ref|nullfuncref|nullexternref|structref|arrayref|nullref)\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:type|func|extern|any|eq|nofunc|noextern|struct|array|none)\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(?:struct|array|sub|final|rec|field|mut)\b(?!\.)</string>
                <key>name</key>
                <string>entity.name.type.wat</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.wat</string>
  </dict>
</plist>