<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>wenyan</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#symbols</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment-blocks</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment-lines</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment-blocks</key>
      <dict>
        <key>begin</key>
        <string>([批注疏]曰)。?(「「|『)</string>
        <key>end</key>
        <string>(」」|』)</string>
        <key>name</key>
        <string>comment.block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
        </array>
      </dict>
      <key>comment-lines</key>
      <dict>
        <key>begin</key>
        <string>[批注疏]曰</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[·〇一七三九二五京億兆八六分十千又四垓埃塵微忽極正毫沙渺溝漠澗百秭穰絲纖萬負載釐零]</string>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[其陰陽]</string>
            <key>name</key>
            <string>constant.language</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>「「|『</string>
            <key>end</key>
            <string>」」|』</string>
            <key>name</key>
            <string>string.quoted</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[元列數爻物術言]</string>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <dict>
            <key>match</key>
            <string>乃行是術曰|若其不然者|乃歸空無|欲行是術|乃止是遍|若其然者|其物如是|乃得矣|之術也|必先得|是術曰|恆為是|之物也|乃得|是謂|云云|中之|為是|乃止|若非|或若|之長|其餘</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>match</key>
            <string>或云|蓋謂</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>match</key>
            <string>中有陽乎|中無陰乎|所餘幾何|不等於|不大於|不小於|等於|大於|小於|[乘以加於減變除]</string>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <dict>
            <key>match</key>
            <string>不知何禍歟|不復存矣|姑妄行此|如事不諧|名之曰|吾嘗觀|之禍歟|乃作罷|吾有|今有|物之|書之|以施|昔之|是矣|之書|方悟|之義|嗚呼|之禍|[中今取噫夫施曰有豈]</string>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[之也充凡者若遍銜]</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </array>
      </dict>
      <key>symbols</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[、。]</string>
            <key>name</key>
            <string>punctuation.separator</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>begin</key>
        <string>「</string>
        <key>end</key>
        <string>」</string>
        <key>name</key>
        <string>variable.other</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.wenyan</string>
  </dict>
</plist>