<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectTo</key>
    <array>
      <string>source.ts.ng</string>
    </array>
    <key>injectionSelector</key>
    <string>L:source.ts#meta.decorator.ts -comment</string>
    <key>name</key>
    <string>angular-inline-style</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#inlineStyles</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>inlineStyles</key>
      <dict>
        <key>begin</key>
        <string>(styles)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.object-literal.key.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.object-literal.key.ts punctuation.separator.key-value.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[,}])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tsParenExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tsBracketExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#style</string>
          </dict>
        </array>
      </dict>
      <key>style</key>
      <dict>
        <key>begin</key>
        <string>\s*(["'`|])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.css.scss</string>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css.scss</string>
          </dict>
        </array>
      </dict>
      <key>tsBracketExpression</key>
      <dict>
        <key>begin</key>
        <string>\G\s*(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.array.literal.ts meta.brace.square.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.array.literal.ts meta.brace.square.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#style</string>
          </dict>
        </array>
      </dict>
      <key>tsParenExpression</key>
      <dict>
        <key>begin</key>
        <string>\G\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tsBracketExpression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#style</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>inline-styles.ng</string>
  </dict>
</plist>