<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>berry</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#controls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment-block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#member</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#identifier</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#number</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operator</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment-block</key>
      <dict>
        <key>begin</key>
        <string>#-</string>
        <key>end</key>
        <string>-#</string>
        <key>name</key>
        <string>comment.berry</string>
        <key>patterns</key>
        <array>
          <dict/>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>begin</key>
        <string>#</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.berry</string>
        <key>patterns</key>
        <array>
          <dict/>
        </array>
      </dict>
      <key>controls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(if|elif|else|for|while|do|end|break|continue|return|try|except|raise)\b</string>
            <key>name</key>
            <string>keyword.control.berry</string>
          </dict>
        </array>
      </dict>
      <key>function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([A-Z_a-z][0-9A-Z_a-z]*(?=\s*\())</string>
            <key>name</key>
            <string>entity.name.function.berry</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z_a-z]\w+\b</string>
            <key>name</key>
            <string>identifier.berry</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(var|static|def|class|true|false|nil|self|super|import|as|_class)\b</string>
            <key>name</key>
            <string>keyword.berry</string>
          </dict>
        </array>
      </dict>
      <key>member</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.berry</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\.([A-Z_a-z][0-9A-Z_a-z]*)</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>0x\h+|\d+|(\d+\.?|\.\d)\d*([Ee][-+]?\d+)?</string>
            <key>name</key>
            <string>constant.numeric.berry</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[-\]!%\&amp;(-+./:&lt;=&gt;\[^|~]</string>
            <key>name</key>
            <string>keyword.operator.berry</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>f(?=["'])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"</string>
                <key>name</key>
                <string>string.quoted.other.berry</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(\\x\h{2})|(\\[0-7]{3})|(\\\\)|(\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
                    <key>name</key>
                    <string>constant.character.escape.berry</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\{\{[^}]*}}</string>
                    <key>name</key>
                    <string>string.quoted.other.berry</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>\{</string>
                    <key>end</key>
                    <string>}</string>
                    <key>name</key>
                    <string>keyword.other.unit.berry</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#keywords</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#numbers</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#identifier</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#operator</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#member</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#function</string>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>'</string>
                <key>end</key>
                <string>'</string>
                <key>name</key>
                <string>string.quoted.other.berry</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(\\x\h{2})|(\\[0-7]{3})|(\\\\)|(\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
                    <key>name</key>
                    <string>constant.character.escape.berry</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\{\{[^}]*}}</string>
                    <key>name</key>
                    <string>string.quoted.other.berry</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>\{</string>
                    <key>end</key>
                    <string>}</string>
                    <key>name</key>
                    <string>keyword.other.unit.berry</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#keywords</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#numbers</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#identifier</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#operator</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#member</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#function</string>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
            <key>while</key>
            <string>\G|^[\t ]*(?=["'])</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(["'])</string>
            <key>end</key>
            <string>\1</string>
            <key>name</key>
            <string>string.quoted.double.berry</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\\x\h{2})|(\\[0-7]{3})|(\\\\)|(\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
                <key>name</key>
                <string>constant.character.escape.berry</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.berry</string>
  </dict>
</plist>