<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>bibtex</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.bibtex</string>
          </dict>
        </dict>
        <key>match</key>
        <string>@(?i:comment)(?=[({\s])</string>
        <key>name</key>
        <string>comment.block.at-sign.bibtex</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preamble</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#entry</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>[^\n@]</string>
        <key>end</key>
        <string>(?=@)</string>
        <key>name</key>
        <string>comment.block.bibtex</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>entry</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>((@)[-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)\s*(\{)\s*([^,}\s]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.entry-type.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.entry.begin.bibtex</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.entry-key.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.entry.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.entry.braces.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>([-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)\s*(=)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.function.key.bibtex</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.bibtex</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[,}])</string>
                <key>name</key>
                <string>meta.key-assignment.bibtex</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#field_value</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((@)[-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)\s*(\()\s*([^,\s]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.entry-type.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.entry.begin.bibtex</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.entry-key.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.entry.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.entry.parenthesis.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>([-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)\s*(=)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.function.key.bibtex</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.bibtex</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[),])</string>
                <key>name</key>
                <string>meta.key-assignment.bibtex</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#field_value</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>field_value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_content</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#integer</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_var</string>
          </dict>
          <dict>
            <key>match</key>
            <string>#</string>
            <key>name</key>
            <string>keyword.operator.bibtex</string>
          </dict>
        </array>
      </dict>
      <key>integer</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.bibtex</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s*(\d+)\s*</string>
      </dict>
      <key>nested_braces</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.begin.bibtex</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.end.bibtex</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nested_braces</string>
          </dict>
        </array>
      </dict>
      <key>preamble</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>((@)(?i:preamble))\s*(\{)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.preamble.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.preamble.begin.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.preamble.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.preamble.braces.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#field_value</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((@)(?i:preamble))\s*(\()\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.preamble.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.preamble.begin.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.preamble.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.preamble.parenthesis.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#field_value</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>((@)(?i:string))\s*(\{)\s*([-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.string-constant.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.string-constant.begin.bibtex</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.string-constant.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.string-constant.braces.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#field_value</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((@)(?i:string))\s*(\()\s*([-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.string-constant.bibtex</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.bibtex</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.string-constant.begin.bibtex</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.string-constant.end.bibtex</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.string-constant.parenthesis.bibtex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#field_value</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string_content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.bibtex</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested_braces</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.bibtex</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.bibtex</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nested_braces</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string_var</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.variable.bibtex</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[-!$\&amp;*+./:;&lt;&gt;-z|~][!$\&amp;*+\--&lt;&gt;-z|~]*</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.bibtex</string>
  </dict>
</plist>