<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>clojure</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#shebang-comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#quoted-sexp</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sexp</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyfn</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#vector</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#set</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#map</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#regexp</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#var</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#dynamic-variables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#metadata</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace-symbol</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#symbol</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\);</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.semicolon.clojure</string>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(nil)(?=([])}\s]))</string>
            <key>name</key>
            <string>constant.language.nil.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(true|false)</string>
            <key>name</key>
            <string>constant.language.boolean.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(##(?:Inf|-Inf|NaN))</string>
            <key>name</key>
            <string>constant.numeric.symbol.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?\d+/\d+)</string>
            <key>name</key>
            <string>constant.numeric.ratio.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?(?:3[0-6]|[12]\d|[2-9])[Rr][0-9A-Za-z]+N?)</string>
            <key>name</key>
            <string>constant.numeric.arbitrary-radix.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?0[Xx]\h+N?)</string>
            <key>name</key>
            <string>constant.numeric.hexadecimal.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?0[0-7]+N?)</string>
            <key>name</key>
            <string>constant.numeric.octal.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?[0-9]+(\.|(?=[EMe]))[0-9]*([Ee][-+]?[0-9]+)?M?)</string>
            <key>name</key>
            <string>constant.numeric.double.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-+]?\d+N?)</string>
            <key>name</key>
            <string>constant.numeric.long.clojure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
        </array>
      </dict>
      <key>dynamic-variables</key>
      <dict>
        <key>match</key>
        <string>\*[-!+.:&lt;-?_\w\d]+\*</string>
        <key>name</key>
        <string>meta.symbol.dynamic.clojure</string>
      </dict>
      <key>keyfn</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=([(\[{\s]))(if(-[-?\p{Ll}]*)?|when(-[-\p{Ll}]*)?|for(-[-\p{Ll}]*)?|cond|do|let(-[-?\p{Ll}]*)?|binding|loop|recur|fn|throw[-\p{Ll}]*|try|catch|finally|(\p{Ll}*case))(?=([])}\s]))</string>
            <key>name</key>
            <string>storage.control.clojure</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=([(\[{\s]))(declare-?|(in-)?ns|import|use|require|load|compile|(def[-\p{Ll}]*))(?=([])}\s]))</string>
            <key>name</key>
            <string>keyword.control.clojure</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=([(\[{\s])):[-!#*+./:&lt;-?_\w]+(?=([]),}\s]))</string>
        <key>name</key>
        <string>constant.keyword.clojure</string>
      </dict>
      <key>map</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.map.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(}(?=[])}\s]*(?:;|$)))|(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.map.end.trailing.clojure</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.map.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.map.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>metadata</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\^\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.metadata.map.begin.clojure</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(}(?=[])}\s]*(?:;|$)))|(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.metadata.map.end.trailing.clojure</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.metadata.map.end.clojure</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.metadata.map.clojure</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\^)</string>
            <key>end</key>
            <string>(\s)</string>
            <key>name</key>
            <string>meta.metadata.simple.clojure</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>namespace-symbol</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.symbol.namespace.clojure</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([-!*+.&lt;-?_\p{L}][-!*+.:&lt;-?_\w\d]*)/</string>
          </dict>
        </array>
      </dict>
      <key>quoted-sexp</key>
      <dict>
        <key>begin</key>
        <string>(['`]\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))$|(\)(?=[])}\s]*(?:;|$)))|(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.trailing.clojure</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.trailing.clojure</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.quoted-expression.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>regexp</key>
      <dict>
        <key>begin</key>
        <string>#"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.regexp.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.regexp.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regexp_escaped_char</string>
          </dict>
        </array>
      </dict>
      <key>regexp_escaped_char</key>
      <dict>
        <key>match</key>
        <string>\\.</string>
        <key>name</key>
        <string>constant.character.escape.clojure</string>
      </dict>
      <key>set</key>
      <dict>
        <key>begin</key>
        <string>(#\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.set.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(}(?=[])}\s]*(?:;|$)))|(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.set.end.trailing.clojure</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.set.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.set.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>sexp</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))$|(\)(?=[])}\s]*(?:;|$)))|(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.trailing.clojure</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.trailing.clojure</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.expression.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.expression.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\()(ns|declare|def[-!*+.:&lt;-?_\w\d]*|[-!*+.:&lt;-?_\w][-!*+.:&lt;-?_\w\d]*/def[-!*+.:&lt;-?_\w\d]*)\s+</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.clojure</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\))</string>
            <key>name</key>
            <string>meta.definition.global.clojure</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#metadata</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#dynamic-variables</string>
              </dict>
              <dict>
                <key>match</key>
                <string>([-!*+.&lt;-?_\p{L}][-!*+.:&lt;-?_\w\d]*)</string>
                <key>name</key>
                <string>entity.global.clojure</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyfn</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#set</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sexp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.clojure</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=\()(.+?)(?=[)\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>shebang-comment</key>
      <dict>
        <key>begin</key>
        <string>^(#!)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.shebang.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.shebang.clojure</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.clojure</string>
          </dict>
        </array>
      </dict>
      <key>symbol</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([-!*+.&lt;-?_\p{L}][-!*+.:&lt;-?_\w\d]*)</string>
            <key>name</key>
            <string>meta.symbol.clojure</string>
          </dict>
        </array>
      </dict>
      <key>var</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=([(\[{\s])#)'[-!*+./:&lt;-?_\w]+(?=([])}\s]))</string>
        <key>name</key>
        <string>meta.var.clojure</string>
      </dict>
      <key>vector</key>
      <dict>
        <key>begin</key>
        <string>(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.vector.begin.clojure</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(](?=[])}\s]*(?:;|$)))|(])</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.vector.end.trailing.clojure</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.vector.end.clojure</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.vector.clojure</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.clojure</string>
  </dict>
</plist>