<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>v</string>
    </array>
    <key>name</key>
    <string>coq</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>\b(From|Require|Import|Export|Local|Global|Include)\b</string>
        <key>name</key>
        <string>keyword.control.import.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((Open|Close|Delimit|Undelimit|Bind)\s+Scope)\b</string>
        <key>name</key>
        <string>keyword.control.import.coq</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.theorem.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Theorem|Lemma|Remark|Fact|Corollary|Property|Proposition)\s+(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bGoal\b</string>
        <key>name</key>
        <string>keyword.source.coq</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.assumption.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Parameters?|Axioms?|Conjectures?|Variables?|Hypothesis|Hypotheses)(\s+Inline)?\b\s*\(?\s*(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.assumption.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Context)\b\s*`?\s*([({])?\s*(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\b(?:Program|Local)\s+)?\b(Definition|Fixpoint|CoFixpoint|Function|Example|Let(?:(?:\s+|\s+Co)Fixpoint)?|Instance|Equations|Equations?)\s+(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((Show\s+)?Obligation\s+Tactic|Obligations\s+of|Obligation|Next\s+Obligation(\s+of)?|Solve\s+Obligations(\s+of)?|Solve\s+All\s+Obligations|Admit\s+Obligations(\s+of)?|Instance)\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.coq</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(CoInductive|Inductive|Variant|Record|Structure|Class)\s+(&gt;\s*)?(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.ltac</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Ltac)\s+(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.source.coq</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.ltac</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(Ltac2)\s+(mutable\s+)?(rec\s+)?(([_ \p{L}])(['0-9_ \p{L}])*)</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Hint(\s+Mode)?|Create\s+HintDb|Constructors|Resolve|Rewrite|Ltac2??|Implicit(\s+Types)?|Set|Unset|Remove\s+Printing|Arguments|((Tactic|Reserved)\s+)?Notation|Infix|Section|Module(\s+Type)?|End|Check|Print(\s+All)?|Eval|Compute|Search|Universe|Coercions|Generalizable(\s+(All|Variable))?|Existing(\s+(Class|Instance))?|Canonical|About|Locate|Collection|Typeclasses\s+(Opaque|Transparent))\b</string>
        <key>name</key>
        <string>keyword.source.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Proof|Qed|Defined|Save|Abort(\s+All)?|Undo(\s+To)?|Restart|Focus|Unfocus|Unfocused|Show\s+Proof|Show\s+Existentials|Show|Unshelve)\b</string>
        <key>name</key>
        <string>keyword.source.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Quit|Drop|Time|Redirect|Timeout|Fail)\b</string>
        <key>name</key>
        <string>keyword.debug.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(admit|Admitted)\b</string>
        <key>name</key>
        <string>invalid.illegal.admit.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[-*+:&lt;=&gt;{|}¬→↔∧∨≠≤≥]</string>
        <key>name</key>
        <string>keyword.operator.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(forall|exists|Type|Set|Prop|nat|bool|option|list|unit|sum|prod|comparison|Empty_set)\b|[∀∃]</string>
        <key>name</key>
        <string>support.type.coq</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(try|repeat|rew|progress|fresh|solve|now|first|tryif|at|once|do|only)\b</string>
        <key>name</key>
        <string>keyword.control.ltac</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(into|with|eqn|by|move|as|using)\b</string>
        <key>name</key>
        <string>keyword.control.ltac</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(match|lazymatch|multimatch|match!|lazy_match!|multi_match!|fun|with|return|end|let|in|if|then|else|fix|for|where|and)\b|λ</string>
        <key>name</key>
        <string>keyword.control.gallina</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(intros??|revert|induction|destruct|auto|eauto|tauto|eassumption|apply|eapply|assumption|constructor|econstructor|reflexivity|inversion|injection|assert|split|esplit|omega|fold|unfold|specialize|rewrite|erewrite|change|symmetry|refine|simpl|intuition|firstorder|generalize|idtac|exists??|eexists|elim|eelim|rename|subst|congruence|trivial|left|right|set|pose|discriminate|clear|clearbody|contradict|contradiction|exact|dependent|remember|case|easy|unshelve|pattern|transitivity|etransitivity|f_equal|exfalso|replace|abstract|cycle|swap|revgoals|shelve|unshelve)\b</string>
        <key>name</key>
        <string>support.function.builtin.ltac</string>
      </dict>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\(\*(?!#)</string>
        <key>end</key>
        <string>\*\)</string>
        <key>name</key>
        <string>comment.block.coq</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_double_quoted_string</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((0([Xx])\h+)|([0-9]+(\.[0-9]+)?))\b</string>
        <key>name</key>
        <string>constant.numeric.gallina</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(True|False|tt|false|true|Some|None|nil|cons|pair|inl|inr|[OS]|Eq|Lt|Gt|id|ex|all|unique)\b</string>
        <key>name</key>
        <string>constant.language.constructor.gallina</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b_\b</string>
        <key>name</key>
        <string>constant.language.wildcard.coq</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.coq</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.coq</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.coq</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>block_comment</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\(\*(?!#)</string>
        <key>end</key>
        <string>\*\)</string>
        <key>name</key>
        <string>comment.block.coq</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_double_quoted_string</string>
          </dict>
        </array>
      </dict>
      <key>block_double_quoted_string</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.coq</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.coq</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.coq</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.coq</string>
  </dict>
</plist>