<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>cr</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!/.*\bcrystal</string>
    <key>foldingStartMarker</key>
    <string>(?:^(\s*+(annotation|module|class|struct|union|enum|def(?!.*\bend\s*$)|unless|if|case|begin|for|while|until|^=begin|("(\\.|[^"])*+"|'(\\.|[^'])*+'|[^"#'])*(\s(do|begin|case)|(?&lt;!\$)[-%\&amp;*+/&lt;=&gt;^|~]\s*+(if|unless)))\b(?![^;]*+;.*?\bend\b)|("(\\.|[^"])*+"|'(\\.|[^'])*+'|[^"#'])*(\{(?![^}]*+})|\[(?![^]]*+]))).*|#.*?\(fold\)\s*+)$</string>
    <key>foldingStopMarker</key>
    <string>((^|;)\s*+end\s*+(#.*)?$|(^|;)\s*+end\..*$|^\s*+[]}],?\s*+(#.*)?$|#.*?\(end\)\s*+$|^=end)</string>
    <key>name</key>
    <string>crystal</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.class.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.class.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.crystal</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.crystal</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>support.class.other.type-param.crystal</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.crystal</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.crystal</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.crystal</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>support.class.other.type-param.crystal</string>
          </dict>
          <key>11</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(abstract)?\s*(class|struct|union|annotation|enum)\s+(([.:A-Z_\x{80}-\x{10FFFF}][.:\x{80}-\x{10FFFF}\w]*(\(([,.0-:A-Z_a-z\x{80}-\x{10FFFF}\s]+)\))?(\s*(&lt;)\s*[.:A-Z\x{80}-\x{10FFFF}][.:\x{80}-\x{10FFFF}\w]*(\(([.0-:A-Z_a-z]+\s,)\))?)?)|((&lt;&lt;)\s*[.0-:A-Z_\x{80}-\x{10FFFF}]+))</string>
        <key>name</key>
        <string>meta.class.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.module.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.module.first.crystal</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.module.second.crystal</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.module.third.crystal</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(module)\s+(([A-Z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*(::))?([A-Z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*(::))?([A-Z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*(::))*[A-Z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*)</string>
        <key>name</key>
        <string>meta.module.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.lib.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.lib.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.lib.first.crystal</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.lib.second.crystal</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.lib.third.crystal</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.inheritance.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(lib)\s+(([A-Z]\w*(::))?([A-Z]\w*(::))?([A-Z]\w*(::))*[A-Z]\w*)</string>
        <key>name</key>
        <string>meta.lib.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.lib.type.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.lib.type.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.lib.crystal</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.lib.type.value.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(type)\s+([A-Z]\w+)\s*(=)\s*(.+)</string>
        <key>name</key>
        <string>meta.lib.type.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(fun|begin|case|class|else|elsif|end|ensure|enum|for|if|macro|module|rescue|struct|then|union|unless|until|when|while)\b(?![!:?])</string>
        <key>name</key>
        <string>keyword.control.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(abstract|alias|asm|break|extend|in|include|next|of|private|protected|struct|return|select|super|with|yield)\b(?![!:?])</string>
        <key>name</key>
        <string>keyword.control.primary.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(describe|context|it|expect_raises)\b(?![!:?])</string>
        <key>name</key>
        <string>keyword.control.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\bdo\b\s*</string>
        <key>name</key>
        <string>keyword.control.start-block.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=\{)(\s+)</string>
        <key>name</key>
        <string>meta.syntax.crystal.start-block</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(pointerof|typeof|sizeof|instance_sizeof|offsetof|previous_def|forall|out|uninitialized)\b(?![!:?])|\.(is_a\?|nil\?|responds_to\?|as\?|as\x08)</string>
        <key>name</key>
        <string>keyword.control.pseudo-method.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bnil\b(?![!:?])</string>
        <key>name</key>
        <string>constant.language.nil.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b(?![!:?])</string>
        <key>name</key>
        <string>constant.language.boolean.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(__(DIR|FILE|LINE|END_LINE)__)\b(?![!:?])</string>
        <key>name</key>
        <string>variable.language.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(self)\b(?![!:?])</string>
        <key>name</key>
        <string>variable.language.self.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(((class_)?((getter|property)\b[!?]?|setter\b))|(def_(clone|equals|equals_and_hash|hash)|delegate|forward_missing_to)\b)(?![!:?])</string>
        <key>name</key>
        <string>support.function.kernel.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(require)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.special-method.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$|(?=#)</string>
        <key>name</key>
        <string>meta.require.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)[A-Z_a-z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*[!=?]?</string>
        <key>name</key>
        <string>variable.other.readwrite.instance.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(@@)[A-Z_a-z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*[!=?]?</string>
        <key>name</key>
        <string>variable.other.readwrite.class.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$)[A-Z_a-z]\w*</string>
        <key>name</key>
        <string>variable.other.readwrite.global.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?!%[Qiqrwx]?[(&lt;\[{|])%([A-Z_a-z]\w*\.)*[A-Z_a-z]\w*</string>
        <key>name</key>
        <string>variable.other.readwrite.fresh.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$)([!\&amp;'+@`]|\d+|["$*,./:-?\\_~]|-[0FIadilpv])</string>
        <key>name</key>
        <string>variable.other.readwrite.global.pre-defined.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(ENV)\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>name</key>
        <string>meta.environment-variable.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*</string>
        <key>name</key>
        <string>support.class.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(abort|at_exit|caller|exit|gets|loop|main|pp??|printf??|puts|raise|rand|read_line|sleep|spawn|sprintf|system|debugger|record|spawn)\b(?![!:?])</string>
        <key>name</key>
        <string>support.function.kernel.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z_]+\b</string>
        <key>name</key>
        <string>variable.other.constant.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?=def\b)(?&lt;=^|\s)(def)\s+((?&gt;[A-Z_a-z]\w*(?&gt;\.|::))?(?&gt;[A-Z_a-z]\w*(?&gt;[!?]|=(?!&gt;))?|\^|===?|!=|&gt;[=&gt;]?|&lt;=&gt;|&lt;[&lt;=]?|[%\&amp;/`|]|\*\*?|=?~|[-+]@?|\[][=?]?|\[]=?))\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.def.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function.method.with-arguments.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?![),\s])</string>
            <key>end</key>
            <string>(?=,|\)\s*)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.variable.crystal</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>constant.other.symbol.hashkey.parameter.function.crystal</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.constant.hashkey.crystal</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.function.crystal</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\G([\&amp;*]?)(?:([A-Z_a-z]\w*(:))|([A-Z_a-z]\w*))</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.def.crystal</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?=def\b)(?&lt;=^|\s)(def)\b(\s+((?&gt;[A-Z_a-z]\w*(?&gt;\.|::))?(?&gt;[A-Z_a-z]\w*(?&gt;[!?]|=(?!&gt;))?|\^|===?|!=|&gt;[=&gt;]?|&lt;=&gt;|&lt;[&lt;=]?|[%\&amp;/`|]|\*\*?|=?~|[-+]@?|\[][=?]?|\[]=?)))?</string>
        <key>name</key>
        <string>meta.function.method.without-arguments.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[0-9][0-9_]*\.[0-9][0-9_]*([Ee][-+]?[0-9_]+)?(f(?:32|64))?\b</string>
        <key>name</key>
        <string>constant.numeric.float.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[0-9][0-9_]*(\.[0-9][0-9_]*)?[Ee][-+]?[0-9_]+(f(?:32|64))?\b</string>
        <key>name</key>
        <string>constant.numeric.float.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[0-9][0-9_]*(\.[0-9][0-9_]*)?([Ee][-+]?[0-9_]+)?(f(?:32|64))\b</string>
        <key>name</key>
        <string>constant.numeric.float.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?!0[0-9])[0-9][0-9_]*([iu](8|16|32|64|128))?\b</string>
        <key>name</key>
        <string>constant.numeric.integer.decimal.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0x[_\h]+([iu](8|16|32|64|128))?\b</string>
        <key>name</key>
        <string>constant.numeric.integer.hexadecimal.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0o[0-7_]+([iu](8|16|32|64|128))?\b</string>
        <key>name</key>
        <string>constant.numeric.integer.octal.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b0b[01_]+([iu](8|16|32|64|128))?\b</string>
        <key>name</key>
        <string>constant.numeric.integer.binary.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>:'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.symbol.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.symbol.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.other.symbol.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\['\\]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>:"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.symbol.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.symbol.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.other.symbol.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\()/=</string>
        <key>name</key>
        <string>keyword.operator.assignment.augmented.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\['\\]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>`</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>`</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%x\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%x\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%x&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%x\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%x\|</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\|</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.interpolated.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?:^|(?&lt;=[\&amp;(,:;=&gt;?\[|~]|[;\s]if\s|[;\s]elsif\s|[;\s]while\s|[;\s]unless\s|[;\s]when\s|[;\s]assert_match\s|[;\s]or\s|[;\s]and\s|[;\s]not\s|[.\s]index\s|[.\s]scan\s|[.\s]sub\s|[.\s]sub!\s|[.\s]gsub\s|[.\s]gsub!\s|[.\s]match\s)|(?&lt;=^(?:when|if|elsif|while|unless)\s))\s*((/))(?![*+?{}])</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.regexp.classic.crystal</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.regexp.classic.crystal</string>
        <key>end</key>
        <string>((/[imsx]*))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%r\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}[imsx]*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.mod-r.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly_r</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%r\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>][imsx]*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.mod-r.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets_r</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%r\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)[imsx]*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.mod-r.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens_r</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%r&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;[imsx]*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.mod-r.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt_r</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%r\|</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\|[imsx]*</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.regexp.mod-r.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%Q?\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.upper.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%Q?\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.upper.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%Q?&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.upper.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%Q?\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.crystal.mod</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly_i</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%Q\|</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\|</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.upper.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%[iqw]\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.lower.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[)\\]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%[iqw]&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.lower.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[&gt;\\]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%[iqw]\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.lower.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[]\\]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%[iqw]\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.lower.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[\\}]</string>
            <key>name</key>
            <string>constant.character.escape.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%[iqw]\|</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\|</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.other.literal.lower.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;!:)(:)(?&gt;[A-Z_a-z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*(?&gt;[!?]|=(?![=&gt;]))?|===?|&gt;[=&gt;]?|&lt;[&lt;=]?|&lt;=&gt;|[%\&amp;/`|]|\*\*?|=?~|[-+]@?|\[][=?]?|@@?[A-Z_a-z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*)</string>
        <key>name</key>
        <string>constant.other.symbol.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&gt;[A-Z_a-z\x{80}-\x{10FFFF}][\x{80}-\x{10FFFF}\w]*[!?]?)(:)(?!:)</string>
        <key>name</key>
        <string>constant.other.symbol.crystal.19syntax</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?:^[\t ]+)?(#).*$\n?</string>
        <key>name</key>
        <string>comment.line.number-sign.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!}})\b_(\w+[!?]?)\b(?!\()</string>
        <key>name</key>
        <string>comment.unused.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)HTML)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.html.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.html.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)SQL)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.sql.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.sql.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.sql</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)CSS)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.css.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.css.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)CPP)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.c++.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.cplusplus.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.c++</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)C)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.c.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.c.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.c</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)J(?:S|AVASCRIPT))\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.js.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.js.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)JQUERY)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.js.jquery.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.js.jquery.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js.jquery</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)SH(?:|ELL))\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.shell.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.shell.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.shell</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-('?)((?:[_\w]+_|)CRYSTAL)\b\1)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>text.crystal.embedded.crystal</string>
        <key>end</key>
        <string>\s*\2\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.embedded.crystal.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-'(\w+)')</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*\1\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.heredoc.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&gt;&lt;&lt;-(\w+)\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*\1\b</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.crystal</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.heredoc.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#heredoc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&lt;=\{\s??|[^0-9A-Z_a-z]do|^do|[^0-9A-Z_a-z]do\s|^do\s)(\|)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.variable.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\|)(\|)(?!\|)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.crystal</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>variable.other.block.crystal</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.variable.crystal</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>=&gt;</string>
        <key>name</key>
        <string>punctuation.separator.key-value</string>
      </dict>
      <dict>
        <key>match</key>
        <string>-&gt;</string>
        <key>name</key>
        <string>support.function.kernel.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>&lt;&lt;=|%=|&amp;{1,2}=|\*=|\*\*=|\+=|-=|\^=|\|{1,2}=|&lt;&lt;</string>
        <key>name</key>
        <string>keyword.operator.assignment.augmented.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>&lt;=&gt;|&lt;(?![&lt;=])|&gt;(?![&lt;=&gt;])|&lt;=|&gt;=|===?|=~|!=|!~|(?&lt;=[\t ])\?</string>
        <key>name</key>
        <string>keyword.operator.comparison.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^|[\t ])!|&amp;&amp;|\|\||\^</string>
        <key>name</key>
        <string>keyword.operator.logical.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(\{%|%}|\{\{|}})</string>
        <key>name</key>
        <string>keyword.operator.macro.crystal</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.method.crystal</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(&amp;\.)\s*(?![A-Z])</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([%\&amp;]|\*\*|[-*+/])</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>=</string>
        <key>name</key>
        <string>keyword.operator.assignment.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[|~]|&gt;&gt;</string>
        <key>name</key>
        <string>keyword.operator.other.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>:</string>
        <key>name</key>
        <string>punctuation.separator.other.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>;</string>
        <key>name</key>
        <string>punctuation.separator.statement.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>,</string>
        <key>name</key>
        <string>punctuation.separator.object.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\.|::</string>
        <key>name</key>
        <string>punctuation.separator.method.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[{}]</string>
        <key>name</key>
        <string>punctuation.section.scope.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[]\[]</string>
        <key>name</key>
        <string>punctuation.section.array.crystal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[()]</string>
        <key>name</key>
        <string>punctuation.section.function.crystal</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?=[!0-9?A-Z_a-z]+\()</string>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>name</key>
        <string>meta.function-call.crystal</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([!0-9?A-Z_a-z]+)(?=\()</string>
            <key>name</key>
            <string>entity.name.function.crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>((?&lt;=\W)\b|^)\w+\b(?=\s*([]$)-/=^}]|&lt;\s|&lt;&lt;[.|\s]))</string>
        <key>name</key>
        <string>variable.other.crystal</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>escaped_char</key>
      <dict>
        <key>match</key>
        <string>\\(?:[0-7]{1,3}|x\h{2}|u\h{4}|u\{[ \h]+}|.)</string>
        <key>name</key>
        <string>constant.character.escape.crystal</string>
      </dict>
      <key>heredoc</key>
      <dict>
        <key>begin</key>
        <string>^&lt;&lt;-?\w+</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>interpolated_crystal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.crystal</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.crystal</string>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.crystal</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.crystal</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.crystal</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nest_curly_and_self</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
            <key>repository</key>
            <dict>
              <key>nest_curly_and_self</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>\{</string>
                    <key>captures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>punctuation.section.scope.crystal</string>
                      </dict>
                    </dict>
                    <key>end</key>
                    <string>}</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#nest_curly_and_self</string>
                      </dict>
                    </array>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.crystal</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#@)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.instance.crystal</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.crystal</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#@@)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.class.crystal</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.crystal</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#\$)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.global.crystal</string>
          </dict>
        </array>
      </dict>
      <key>nest_brackets</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nest_brackets</string>
          </dict>
        </array>
      </dict>
      <key>nest_brackets_i</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets_i</string>
          </dict>
        </array>
      </dict>
      <key>nest_brackets_r</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_brackets_r</string>
          </dict>
        </array>
      </dict>
      <key>nest_curly</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nest_curly</string>
          </dict>
        </array>
      </dict>
      <key>nest_curly_and_self</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.crystal</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nest_curly_and_self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>nest_curly_i</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly_i</string>
          </dict>
        </array>
      </dict>
      <key>nest_curly_r</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_curly_r</string>
          </dict>
        </array>
      </dict>
      <key>nest_ltgt</key>
      <dict>
        <key>begin</key>
        <string>&lt;</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nest_ltgt</string>
          </dict>
        </array>
      </dict>
      <key>nest_ltgt_i</key>
      <dict>
        <key>begin</key>
        <string>&lt;</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt_i</string>
          </dict>
        </array>
      </dict>
      <key>nest_ltgt_r</key>
      <dict>
        <key>begin</key>
        <string>&lt;</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_ltgt_r</string>
          </dict>
        </array>
      </dict>
      <key>nest_parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nest_parens</string>
          </dict>
        </array>
      </dict>
      <key>nest_parens_i</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens_i</string>
          </dict>
        </array>
      </dict>
      <key>nest_parens_r</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.crystal</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex_sub</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nest_parens_r</string>
          </dict>
        </array>
      </dict>
      <key>regex_sub</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_crystal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped_char</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arbitrary-repetition.crystal</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.arbitrary-repetition.crystal</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\{)\d+(,\d+)?(})</string>
            <key>name</key>
            <string>string.regexp.arbitrary-repetition.crystal</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[(?:\^?])?</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.character-class.crystal</string>
              </dict>
            </dict>
            <key>end</key>
            <string>]</string>
            <key>name</key>
            <string>string.regexp.character-class.crystal</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.crystal</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>string.regexp.group.crystal</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#regex_sub</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.crystal</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(#)\s[-\t !,.0-9?A-Za-z[^\x00-\x7F]]*$</string>
            <key>name</key>
            <string>comment.line.number-sign.crystal</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.crystal</string>
  </dict>
</plist>