<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>desktop</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#layout</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#values</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inCommands</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inCategories</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>inCategories</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^Categories.*)AudioVideo|(?&lt;=^Categories.*)Audio|(?&lt;=^Categories.*)Video|(?&lt;=^Categories.*)Development|(?&lt;=^Categories.*)Education|(?&lt;=^Categories.*)Game|(?&lt;=^Categories.*)Graphics|(?&lt;=^Categories.*)Network|(?&lt;=^Categories.*)Office|(?&lt;=^Categories.*)Science|(?&lt;=^Categories.*)Settings|(?&lt;=^Categories.*)System|(?&lt;=^Categories.*)Utility</string>
            <key>name</key>
            <string>markup.bold</string>
          </dict>
        </array>
      </dict>
      <key>inCommands</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^Exec.*\s)-+\S+</string>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^Exec.*)\s%[FUcfiku]\s</string>
            <key>name</key>
            <string>variable.language</string>
          </dict>
          <dict>
            <key>match</key>
            <string>".*"</string>
            <key>name</key>
            <string>string</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(?:Type|Version|Name|GenericName|NoDisplay|Comment|Icon|Hidden|OnlyShowIn|NotShowIn|DBusActivatable|TryExec|Exec|Path|Terminal|Actions|MimeType|Categories|Implements|Keywords|StartupNotify|StartupWMClass|URL|PrefersNonDefaultGPU|Encoding)\b</string>
            <key>name</key>
            <string>keyword</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^X-[- 0-9A-z]*</string>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!^)\[.+]</string>
            <key>name</key>
            <string>constant.language</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^(?:GtkTheme|MetacityTheme|IconTheme|CursorTheme|ButtonLayout|ApplicationFont)\b</string>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </array>
      </dict>
      <key>layout</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\[Desktop</string>
            <key>end</key>
            <string>]</string>
            <key>name</key>
            <string>markup.heading</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[X-\w*</string>
            <key>end</key>
            <string>]</string>
            <key>name</key>
            <string>markup.heading</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*#.*</string>
            <key>name</key>
            <string>comment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>strong</string>
          </dict>
        </array>
      </dict>
      <key>values</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^\S+)=</string>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:tru|fals)e\b</string>
            <key>name</key>
            <string>variable.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^Version.*)\d+(\.?\d*)</string>
            <key>name</key>
            <string>variable.other</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.desktop</string>
  </dict>
</plist>