<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injections</key>
    <dict>
      <key>text.html.edge - (meta.embedded | meta.tag | comment.block.edge), L:(text.html.edge meta.tag - (comment.block.edge | meta.embedded.block.edge)), L:(source.ts.embedded.html - (comment.block.edge | meta.embedded.block.edge))</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escapedMustache</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#safeMustache</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mustache</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nonSeekableTag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>name</key>
    <string>edge</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>text.html.derivative</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>begin</key>
        <string>\{\{--</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.edge</string>
          </dict>
        </dict>
        <key>end</key>
        <string>--}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.edge</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block</string>
      </dict>
      <key>escapedMustache</key>
      <dict>
        <key>begin</key>
        <string>@\{\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.edge</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.edge</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block</string>
      </dict>
      <key>mustache</key>
      <dict>
        <key>begin</key>
        <string>\{\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.mustache.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.mustache.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.block.javascript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#expression</string>
          </dict>
        </array>
      </dict>
      <key>nonSeekableTag</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.function.edge</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(\s*)((@{1,2})(!)?([.A-Z_a-z]+))(~)?$</string>
        <key>name</key>
        <string>meta.embedded.block.javascript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#expression</string>
          </dict>
        </array>
      </dict>
      <key>safeMustache</key>
      <dict>
        <key>begin</key>
        <string>\{\{\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.mustache.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.mustache.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.block.javascript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#expression</string>
          </dict>
        </array>
      </dict>
      <key>tag</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)((@{1,2})(!)?([.A-Z_a-z]+)(\s{0,2}))(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.function.edge</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.open</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.block.javascript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.edge</string>
  </dict>
</plist>