<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>fsharp</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#compiler_directives</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#chars</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#double_tick</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#definition</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#abstract_definition</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#modules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#anonymous_functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#du_declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#record_declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#records</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strp_inlined</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#cexprs</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#text</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>abstract_definition</key>
      <dict>
        <key>begin</key>
        <string>\b(static\s+)?(abstract)\s+(member)?(\s+\[&lt;.*&gt;])?\s*([,.0-9_`[:alpha:]\s]+)(&lt;)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.function.attribute.fsharp</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(with)\b|=|$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
        </dict>
        <key>name</key>
        <string>abstract.definition.fsharp</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#common_declaration</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\??)([ '.0-9^_`[:alpha:]]+)\s*(:)((?!with\b)\b([ '.0-9^_`\w]+))?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>Here we need the \w modifier in order to check that the words isn't blacklisted</string>
            <key>match</key>
            <string>(?!with|get|set\b)\s*(['.0-9^_`\w]+)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>anonymous_functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(fun)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(-&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.arrow.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>function.anonymous</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(\()</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?=(-&gt;))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.arrow.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#member_declaration</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>anonymous_record_declaration</key>
      <dict>
        <key>begin</key>
        <string>(\{\|)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\|})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[ '0-9^_`[:alpha:]]+(:)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([ '0-9^_`[:alpha:]]+)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#anonymous_record_declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[&lt;</string>
            <key>end</key>
            <string>&gt;?]</string>
            <key>name</key>
            <string>support.function.attribute.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>cexprs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(async|seq|promise|task|maybe|asyncMaybe|controller|scope|application|pipeline)(?=\s*\{)</string>
            <key>name</key>
            <string>cexpr.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>chars</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>('\\?.')</string>
            <key>name</key>
            <string>char.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(\(\*\*(?!\)))((?!\*\)).)*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.block.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.markdown.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.html.markdown</string>
              </dict>
            </array>
            <key>while</key>
            <string>^(?!\s*(\*)+\)\s*$)</string>
            <key>whileCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.block.fsharp</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\(\*(?!\)))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.block.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*+\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.block.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>comments</key>
                <string>Capture // when inside of (* *) like that the rule which capture comments starting by // is not trigger. See https://github.com/ionide/ionide-fsgrammar/issues/155</string>
                <key>match</key>
                <string>//</string>
                <key>name</key>
                <string>fast-capture.comment.line.double-slash.fsharp</string>
              </dict>
              <dict>
                <key>comments</key>
                <string>Capture (*) when inside of (* *) so that it doesn't prematurely end the comment block.</string>
                <key>match</key>
                <string>\(\*\)</string>
                <key>name</key>
                <string>fast-capture.comment.line.mul-operator.fsharp</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.block.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((?&lt;!\()(\*)+\))</string>
            <key>name</key>
            <string>comment.block.markdown.fsharp.end</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;![!%\&amp;+-/&lt;-@^|])///(?!/)</string>
            <key>name</key>
            <string>comment.line.markdown.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.html.markdown</string>
              </dict>
            </array>
            <key>while</key>
            <string>(?&lt;![!%\&amp;+-/&lt;-@^|])///(?!/)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![!%\&amp;+-/&lt;-@^|])//(.*)$</string>
            <key>name</key>
            <string>comment.line.double-slash.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>common_binding_definition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attributes</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\()\s*((?:static |)member)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>SRTP syntax support</string>
            <key>end</key>
            <string>(\))\s*((?=,)|(?==))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\^['.0-9_[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\)\s*(([ '.0-9?^_`[:alpha:]]*)))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\^['.0-9_[:alpha:]]+)\s*(when)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(and|when|or)\b</string>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(['.0-9^_[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>match</key>
                <string>([()])</string>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(:)\s*([ '.0-9?^_`[:alpha:]]+)(\|\s*(null))?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.arrow.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(-&gt;)\s*(\()?\s*([ '.0-9?^_`[:alpha:]]+)*</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\)\s*(([ '.0-9?^_`[:alpha:]]+))*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\*)(\s*([ '.0-9?^_`[:alpha:]]+))*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?==)|(?=\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;+(?!\s*\)))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>beginComment</key>
            <string>The group (?![[:space:]]*\) is for protection against overload operator. static member (&lt;)</string>
            <key>end</key>
            <string>((?&lt;!:)&gt;|\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>endComment</key>
            <string>The group (?&lt;!:) prevent us from stopping on :&gt; when using SRTP synthax</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#generic_declaration</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#anonymous_record_declaration</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#record_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>common_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(-&gt;)\s*([ '.0-9^_`[:alpha:]]+)(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.arrow.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>([ '.0-9^_`[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.arrow.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s*(-&gt;)\s*(?!with|get|set\b)\b(['.0-9^_`\w]+)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#anonymous_record_declaration</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\??)([ '.0-9^_`[:alpha:]]+)\s*(:)(\s*([ '.0-9?^_`[:alpha:]]+)(&lt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>([ '.0-9^_`[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>compiler_directives</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict/>
            <key>match</key>
            <string>\s?(#(?:if|elif|elseif|else|endif|light|nowarn|warnon))</string>
            <key>name</key>
            <string>keyword.control.directive.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\(\)</string>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b-?[0-9][0-9_]*((\.(?!\.)([0-9][0-9_]*([Ee][-+]??[0-9][0-9_]*)?)?)|([Ee][-+]??[0-9][0-9_]*))</string>
            <key>name</key>
            <string>constant.numeric.float.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(-?((0([Xx])\h[_\h]*)|(0([Oo])[0-7][0-7_]*)|(0([Bb])[01][01_]*)|([0-9][0-9_]*)))</string>
            <key>name</key>
            <string>constant.numeric.integer.nativeint.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(null|void)\b</string>
            <key>name</key>
            <string>constant.other.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>definition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(let mutable|static let mutable|static let|let inline|let|and inline|and|member val|member inline|static member inline|static member val|static member|default|member|override|let!)(\s+rec|mutable)?(\s+\[&lt;.*&gt;])?\s*(private|internal|public)?\s+(\[[^-=]*]|[_[:alpha:]]([.0-9_[:alpha:]]+)*|``[_[:alpha:]]([.0-9_`[:alpha:]\s]+|(?&lt;=,)\s)*)?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.fsharp</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*((with(?: inline|))\b|(=|\n+=|(?&lt;==)))</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>binding.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common_binding_definition</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(use!??|and!??)\s+(\[[^-=]*]|[_[:alpha:]]([.0-9_[:alpha:]]+)*|``[_[:alpha:]]([.0-9_`[:alpha:]\s]+|(?&lt;=,)\s)*)?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(=)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>binding.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common_binding_definition</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=with|and)\s*\b(([gs]et)\s*(?=\())(\[[^-=]*]|[_[:alpha:]]([.0-9_[:alpha:]]+)*|``[_[:alpha:]]([.0-9_`[:alpha:]\s]+|(?&lt;=,)\s)*)?</string>
            <key>beginCaptures</key>
            <dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(=|\n+=|(?&lt;==))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>binding.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common_binding_definition</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(static val mutable|val mutable|val inline|val)(\s+rec|mutable)?(\s+\[&lt;.*&gt;])?\s*(private|internal|public)?\s+(\[[^-=]*]|[_[:alpha:]]([,.0-9_[:alpha:]]+)*|``[_[:alpha:]]([,.0-9_`[:alpha:]\s]+|(?&lt;=,)\s)*)?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.fsharp</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n$</string>
            <key>name</key>
            <string>binding.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common_binding_definition</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(new)\b\s+(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>binding.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#common_binding_definition</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>double_tick</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.binding.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(``)([^`]*)(``)</string>
            <key>name</key>
            <string>variable.other.binding.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>du_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(of)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$|(\|)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>du_declaration.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.fsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(['.0-9&lt;&gt;^_`[:alpha:]]+|``[ '.0-9&lt;&gt;^_[:alpha:]]+``)\s*(:)\s*(['.0-9&lt;&gt;^_`[:alpha:]]+|``[ '.0-9&lt;&gt;^_[:alpha:]]+``)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(``([ '.0-9^_[:alpha:]]+)``|['.0-9^_`[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#anonymous_record_declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>generic_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\()\s*((?:static |)member)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>SRTP syntax support</string>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(\()</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(\))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#member_declaration</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>((['^])['.0-9_[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(private|to|public|internal|function|yield!?|class|exception|match|delegate|of|new|in|as|if|then|else|elif|for|begin|end|inherit|do|let!|return!?|interface|with|abstract|enum|member|try|finally|and|when|or|use!??|struct|while|mutable|assert|base|done|downcast|downto|extern|fixed|global|lazy|upcast|not)(?!')\b</string>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((['^])['.0-9_[:alpha:]]+)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>((['^])['.0-9_[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#generic_declaration</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(([ '.0-9?^_`[:alpha:]]+))+</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>Here we need the \w modifier in order to check that the words are allowed</string>
            <key>match</key>
            <string>(?!when|and|or\b)\b(['.0-9^_`\w]+)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>Prevent captures of `|&gt;` as a keyword when defining custom operator like `&lt;|&gt;`</string>
            <key>match</key>
            <string>(\|)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(private|public|internal)\b</string>
            <key>name</key>
            <string>storage.modifier</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(private|to|public|internal|function|class|exception|delegate|of|new|as|begin|end|inherit|let!|interface|abstract|enum|member|and|when|or|use!??|struct|mutable|assert|base|done|downcast|downto|extern|fixed|global|lazy|upcast|not)(?!')\b</string>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(match|yield!??|with|if|then|else|elif|for|in|return!?|try|finally|while|do)(?!')\b</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(-&gt;|&lt;-)</string>
            <key>name</key>
            <string>keyword.symbol.arrow.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[.?]*(&amp;&amp;&amp;|\|\|\||\^\^\^|~~~|~\+|~-|&lt;&lt;&lt;|&gt;&gt;&gt;|\|&gt;|:&gt;|:\?&gt;|[]:;\[]|&lt;&gt;|[=@]|\|\||&amp;&amp;|[%\&amp;_{|}]|\.\.|[!*-\-/&gt;^]|&gt;=|&gt;&gt;|&lt;=??|[()]|&lt;&lt;)[.?]*</string>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>member_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#common_declaration</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\()\s*((?:static |)member)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
            </dict>
            <key>comments</key>
            <string>SRTP syntax support</string>
            <key>end</key>
            <string>(\))\s*((?=,)|(?==))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(\()</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(\))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#member_declaration</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\^['.0-9_[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\^['.0-9_[:alpha:]]+)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(and|when|or)\b</string>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([()])</string>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\??)(['.0-9^_`[:alpha:]]+|``[ ',.0-:^_`[:alpha:]]+``)\s*(:?)(\s*([ '.0-9&lt;&gt;?_`[:alpha:]]+))?(\|\s*(null))?</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>modules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(?:(namespace global)|(namespace|module)\s*(public|internal|private|rec)?\s+([`|[:alpha:]][ '.0-9_[:alpha:]]*))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\s?=|\s|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>entity.name.section.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.namespace-reference.fsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.section.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\.)([A-Z]['0-9_[:alpha:]]*)</string>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(open(?: type|))\s+([`|[:alpha:]]['0-9_[:alpha:]]*)(?=(\.[A-Z][0-9_[:alpha:]]*)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\s|$)</string>
            <key>name</key>
            <string>namespace.open.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.namespace-reference.fsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.section.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\.)(\p{alpha}['0-9_[:alpha:]]*)</string>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s*(module)\s+([A-Z]['0-9_[:alpha:]]*)\s*(=)\s*([A-Z]['0-9_[:alpha:]]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.namespace.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\s|$)</string>
            <key>name</key>
            <string>namespace.alias.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.namespace-reference.fsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.section.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\.)([A-Z]['0-9_[:alpha:]]*)</string>
                <key>name</key>
                <string>entity.name.section.fsharp</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>record_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(((mutable)\s\p{alpha}+)|['.0-9&lt;&gt;^_`[:alpha:]]*)\s*((?&lt;!:):(?!:))\s*</string>
                <key>beginCaptures</key>
                <dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.fsharp</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>$|([;}])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#comments</string>
                  </dict>
                  <dict>
                    <key>captures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.type.fsharp</string>
                      </dict>
                    </dict>
                    <key>match</key>
                    <string>([ '0-9^_`[:alpha:]]+)</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#keywords</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#compiler_directives</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#chars</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#double_tick</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#definition</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#anonymous_functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#cexprs</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#text</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>record_signature</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[ '0-9^_`[:alpha:]]+(=)([ '0-9^_`[:alpha:]]+)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>[ '0-9^_`[:alpha:]]+(=)([ '0-9^_`[:alpha:]]+)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#record_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>records</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(type)\s+(private|internal|public)?\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*((with)|((as)\s+(['0-9[:alpha:]]+))|(=)|[\n=]|(\(\)))</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>record.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(['.0-9^_[:alpha:]]+|``[ ',.0-:^_`[:alpha:]]+``)</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(&lt;)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>((?&lt;!:)&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>captures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.type.fsharp</string>
                      </dict>
                    </dict>
                    <key>match</key>
                    <string>((['^])``[ ,.0-:^_`[:alpha:]]+``|(['^])[.0-:^_`[:alpha:]]+)</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\b(interface|with|abstract|and|when|or|not|struct|equality|comparison|unmanaged|delegate|enum)\b</string>
                    <key>name</key>
                    <string>keyword.fsharp</string>
                  </dict>
                  <dict>
                    <key>begin</key>
                    <string>(\()</string>
                    <key>beginCaptures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>keyword.symbol.fsharp</string>
                      </dict>
                    </dict>
                    <key>end</key>
                    <string>(\))</string>
                    <key>endCaptures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>keyword.symbol.fsharp</string>
                      </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>captures</key>
                        <dict>
                          <key>1</key>
                          <dict>
                            <key>name</key>
                            <string>keyword.fsharp</string>
                          </dict>
                        </dict>
                        <key>match</key>
                        <string>(static member|member|new)</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#common_binding_definition</string>
                      </dict>
                    </array>
                  </dict>
                  <dict>
                    <key>captures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.type.fsharp</string>
                      </dict>
                    </dict>
                    <key>comments</key>
                    <string>Here we need the \w modifier in order to check that the words isn't blacklisted</string>
                    <key>match</key>
                    <string>(['.0-9^_`\w]+)</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#keywords</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\s*(private|internal|public)</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(\()</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(?=(=)|[\n=]|(\(\))|(as))</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.symbol.fsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#member_declaration</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string_formatter</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.format.specifier.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(%0?-?(\d+)?(([at])|(\.\d+)?([EFGMefg])|([Xbcdiosux])|([Obs])|(\+?A)))</string>
            <key>name</key>
            <string>entity.name.type.format.specifier.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?=[^\\])(@")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")(?!")</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.literal.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>"(")</string>
                <key>name</key>
                <string>constant.character.string.escape.fsharp</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[^\\])(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.triple.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_formatter</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[^\\])(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.fsharp</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.fsharp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\$[\t ]*</string>
                <key>name</key>
                <string>punctuation.separator.string.ignore-eol.fsharp</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\(["'\\abfnrtv]|([01][0-9][0-9]|2[0-4][0-9]|25[0-5])|(x\h{2})|(u\h{4})|(U00(0\h|10)\h{4}))</string>
                <key>name</key>
                <string>constant.character.string.escape.fsharp</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\(([0-9]{1,3})|(x\S{0,2})|(u\S{0,4})|(U\S{0,8})|\S)</string>
                <key>name</key>
                <string>invalid.illegal.character.string.fsharp</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_formatter</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strp_inlined</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#strp_inlined_body</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strp_inlined_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#anonymous_functions</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\^['.0-9_[:alpha:]]+)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(and|when|or)\b</string>
            <key>name</key>
            <string>keyword.fsharp</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#strp_inlined_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.fsharp</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((?:static |)member)\s*(['.0-9&lt;&gt;^_`[:alpha:]]+|``[ '.0-9&lt;&gt;^_[:alpha:]]+``)\s*(:)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#compiler_directives</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#chars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#double_tick</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#text</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attributes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cexprs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#text</string>
          </dict>
        </array>
      </dict>
      <key>text</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\</string>
            <key>name</key>
            <string>text.fsharp</string>
          </dict>
        </array>
      </dict>
      <key>tuple_signature</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(([ '.0-9?^_`[:alpha:]]+))+</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsharp</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(([ '.0-9?^_`[:alpha:]]+))+</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tuple_signature</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\(\)</string>
            <key>name</key>
            <string>keyword.symbol.fsharp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.symbol.fsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsharp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\??)(``[ ',.0-:^_`[:alpha:]]+``|(?!private|struct\b)\b[ '.0-9&lt;&gt;^_`\w[:alpha:]]+)</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.fsharp</string>
  </dict>
</plist>