<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>haml</string>
      <string>html.haml</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^\s*([-#%.:=\w].*)\s$</string>
    <key>foldingStopMarker</key>
    <string>^\s*$</string>
    <key>name</key>
    <string>haml</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>^(\s*)==</string>
        <key>contentName</key>
        <string>string.quoted.double.ruby</string>
        <key>end</key>
        <string>$\n*</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):ruby</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.ruby.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.prolog.haml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(!!!)($|\s.*)</string>
        <key>name</key>
        <string>meta.prolog.haml</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):javascript</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>js.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)%script</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>js.inline.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):ruby$</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.ruby.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.comment.haml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(\s*)(/\[[^]].*?$\n?)</string>
        <key>name</key>
        <string>comment.line.slash.haml</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(-#|/|-\s*/\*+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.comment.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|\n)</string>
        <key>name</key>
        <string>comment.block.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.haml</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(?:((%)([-:\w]+))|(?=[#.]))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.haml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.haml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$|(?![#(.\[{]|&amp;amp;|[-=~]|!=|&amp;=|/)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>==</string>
            <key>contentName</key>
            <string>string.quoted.double.ruby</string>
            <key>end</key>
            <string>$\n?</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#interpolated_ruby</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.class</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\.[-:\w]+)</string>
            <key>name</key>
            <string>meta.selector.css</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.id</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#[-\w]+)</string>
            <key>name</key>
            <string>meta.selector.css</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!#)\{(?=.*(,|(do)|[{|}]|(#.*)|\R)\s*)</string>
            <key>end</key>
            <string>\s*}(?!\s*,)(?!\s*\|)(?!#\{.*})</string>
            <key>name</key>
            <string>meta.section.attributes.haml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ruby</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#continuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#rubyline</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.section.attributes.plain.haml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([-\w]+)</string>
                <key>name</key>
                <string>constant.other.symbol.ruby</string>
              </dict>
              <dict>
                <key>match</key>
                <string>=</string>
                <key>name</key>
                <string>punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"</string>
                <key>name</key>
                <string>string.quoted.double.ruby</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[012][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.ruby</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#interpolated_ruby</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolated_ruby</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[(?=.+([],\[|]|(#.*))\s*)</string>
            <key>end</key>
            <string>\s*](?!.*(?!#\[)])</string>
            <key>name</key>
            <string>meta.section.object.haml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ruby</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#continuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#rubyline</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#interpolated_ruby_line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rubyline</string>
          </dict>
          <dict>
            <key>match</key>
            <string>/</string>
            <key>name</key>
            <string>punctuation.terminator.tag.haml</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):(ruby|opal)$</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.ruby.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):ruby$</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.ruby.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):(s(?:tyle|ass))$</string>
        <key>end</key>
        <string>^(?=\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.sass.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.sass</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):coffee(script)?</string>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.coffee.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.coffee</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):plain$</string>
        <key>end</key>
        <string>^(?=\1\s+|$\n*)</string>
        <key>name</key>
        <string>text.plain.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.plain</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:ruby)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.filter.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?m:(?&lt;=\n)(?!\1\s+|$\n*))</string>
        <key>name</key>
        <string>source.ruby.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:sass)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.filter.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.embedded.filter.sass</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.sass</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):(s(?:tyles|ass))$</string>
        <key>end</key>
        <string>^(?=\1\s+|$\n*)</string>
        <key>name</key>
        <string>source.sass.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.sass</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*):plain$</string>
        <key>end</key>
        <string>^(?=\1\s+|$\n*)</string>
        <key>name</key>
        <string>text.plain.embedded.filter.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.plain</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.escape.haml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(\.)</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(?=[-=~]|!=|&amp;=)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_ruby_line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rubyline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:php)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>meta.embedded.php</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.html.php#language</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:markdown)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>meta.embedded.markdown</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.html.markdown</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:(css|styles?))$</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>meta.embedded.css</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:sass)$</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>meta.embedded.sass</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.sass</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\s*)(:scss)$</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.haml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s+|$\n*)</string>
        <key>name</key>
        <string>meta.embedded.scss</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.scss</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>continuation</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.continuation.haml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\|)\s*\n</string>
      </dict>
      <key>interpolated_ruby</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.ruby</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.ruby.embedded.source.empty</string>
              </dict>
            </dict>
            <key>match</key>
            <string>#\{(})</string>
            <key>name</key>
            <string>source.ruby.embedded.source</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>#\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.ruby</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>name</key>
            <string>source.ruby.embedded.source</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nest_curly_and_self</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ruby</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
        </array>
      </dict>
      <key>interpolated_ruby_line</key>
      <dict>
        <key>begin</key>
        <string>!?==</string>
        <key>contentName</key>
        <string>string.source.ruby.embedded.haml</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>meta.line.ruby.interpolated.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolated_ruby</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ruby#escaped_char</string>
          </dict>
        </array>
      </dict>
      <key>nest_curly_and_self</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.ruby</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nest_curly_and_self</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ruby</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>rubyline</key>
      <dict>
        <key>begin</key>
        <string>(&amp;amp|!)?([-=~])</string>
        <key>contentName</key>
        <string>source.ruby.embedded.haml</string>
        <key>end</key>
        <string>((do|\{)( \|[*.]+\|)?)$|$|^(?!.*\|\s*)$\n?</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>source.ruby.embedded.html</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.ruby.start-block</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.line.ruby.haml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.php</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s+((elseif|foreach|switch|declare|default|use))(?=[(\s])</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.include.php</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s+((?:requir|includ)e_once)(?=[(\s])</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+(catch|try|throw|exception|finally|die)(?=[(\s]|\n*)</string>
            <key>name</key>
            <string>keyword.control.exception.php</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.php</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s+(function\s*)((?=\())</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.php</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s+(use\s*)((?=\())</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([,&lt;|]|do|\{)\s*(#.*)?$\n*</string>
            <key>name</key>
            <string>source.ruby</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#rubyline</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>#.*$</string>
            <key>name</key>
            <string>comment.line.number-sign.ruby</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#continuation</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.ruby</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#@)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.instance.ruby</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.ruby</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#@@)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.class.ruby</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.ruby</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#\$)[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>variable.other.readwrite.global.ruby</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.haml</string>
  </dict>
</plist>