<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>hlsl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.line.block.hlsl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[0-9]+\.[0-9]*([Ff])?\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(\.([0-9]+)([Ff])?)\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([0-9]+([Ff])?)\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(0([Xx])\h+)\b</string>
        <key>name</key>
        <string>constant.numeric.hex.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(false|true)\b</string>
        <key>name</key>
        <string>constant.language.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*#\s*(define|elif|else|endif|ifdef|ifndef|if|undef|include|line|error|pragma)</string>
        <key>name</key>
        <string>keyword.preprocessor.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(break|case|continue|default|discard|do|else|for|if|return|switch|while)\b</string>
        <key>name</key>
        <string>keyword.control.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(compile)\b</string>
        <key>name</key>
        <string>keyword.control.fx.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(typedef)\b</string>
        <key>name</key>
        <string>keyword.typealias.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(bool([1-4](x[1-4])?)?|double([1-4](x[1-4])?)?|dword|float([1-4](x[1-4])?)?|half([1-4](x[1-4])?)?|int([1-4](x[1-4])?)?|matrix|min10float([1-4](x[1-4])?)?|min12int([1-4](x[1-4])?)?|min16float([1-4](x[1-4])?)?|min16int([1-4](x[1-4])?)?|min16uint([1-4](x[1-4])?)?|unsigned|uint([1-4](x[1-4])?)?|vector|void)\b</string>
        <key>name</key>
        <string>storage.type.basic.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([A-Z_a-z][0-9A-Z_a-z]*)(?=\s*\()</string>
        <key>name</key>
        <string>support.function.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=:\s?)(?i:BINORMAL[0-9]*|BLENDINDICES[0-9]*|BLENDWEIGHT[0-9]*|COLOR[0-9]*|NORMAL[0-9]*|POSITIONT?|PSIZE[0-9]*|TANGENT[0-9]*|TEXCOORD[0-9]*|FOG|TESSFACTOR[0-9]*|VFACE|VPOS|DEPTH[0-9]*)\b</string>
        <key>name</key>
        <string>support.variable.semantic.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=:\s?)(?i:SV_(?:ClipDistance[0-9]*|CullDistance[0-9]*|Coverage|Depth|DepthGreaterEqual[0-9]*|DepthLessEqual[0-9]*|InstanceID|IsFrontFace|Position|RenderTargetArrayIndex|SampleIndex|StencilRef|Target[0-7]?|VertexID|ViewportArrayIndex))\b</string>
        <key>name</key>
        <string>support.variable.semantic.sm4.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=:\s?)(?i:SV_(?:DispatchThreadID|DomainLocation|GroupID|GroupIndex|GroupThreadID|GSInstanceID|InsideTessFactor|OutputControlPointID|TessFactor))\b</string>
        <key>name</key>
        <string>support.variable.semantic.sm5.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=:\s?)(?i:SV_(?:InnerCoverage|StencilRef))\b</string>
        <key>name</key>
        <string>support.variable.semantic.sm5_1.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(column_major|const|export|extern|globallycoherent|groupshared|inline|inout|in|out|precise|row_major|shared|static|uniform|volatile)\b</string>
        <key>name</key>
        <string>storage.modifier.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([su]norm)\b</string>
        <key>name</key>
        <string>storage.modifier.float.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(packoffset|register)\b</string>
        <key>name</key>
        <string>storage.modifier.postfix.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(centroid|linear|nointerpolation|noperspective|sample)\b</string>
        <key>name</key>
        <string>storage.modifier.interpolation.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(lineadj|line|point|triangle|triangleadj)\b</string>
        <key>name</key>
        <string>storage.modifier.geometryshader.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(string)\b</string>
        <key>name</key>
        <string>support.type.other.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(AppendStructuredBuffer|Buffer|ByteAddressBuffer|ConstantBuffer|ConsumeStructuredBuffer|InputPatch|OutputPatch)\b</string>
        <key>name</key>
        <string>support.type.object.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(RasterizerOrdered(?:Buffer|ByteAddressBuffer|StructuredBuffer|Texture1D|Texture1DArray|Texture2D|Texture2DArray|Texture3D))\b</string>
        <key>name</key>
        <string>support.type.object.rasterizerordered.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(RW(?:Buffer|ByteAddressBuffer|StructuredBuffer|Texture1D|Texture1DArray|Texture2D|Texture2DArray|Texture3D))\b</string>
        <key>name</key>
        <string>support.type.object.rw.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((?:Line|Point|Triangle)Stream)\b</string>
        <key>name</key>
        <string>support.type.object.geometryshader.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(sampler(?:|1D|2D|3D|CUBE|_state))\b</string>
        <key>name</key>
        <string>support.type.sampler.legacy.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Sampler(?:|Comparison)State)\b</string>
        <key>name</key>
        <string>support.type.sampler.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(texture(?:2D|CUBE))\b</string>
        <key>name</key>
        <string>support.type.texture.legacy.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Texture(?:1D|1DArray|2D|2DArray|2DMS|2DMSArray|3D|Cube|CubeArray))\b</string>
        <key>name</key>
        <string>support.type.texture.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(cbuffer|class|interface|namespace|struct|tbuffer)\b</string>
        <key>name</key>
        <string>storage.type.structured.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(FALSE|TRUE|NULL)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((?:Blend|DepthStencil|Rasterizer)State)\b</string>
        <key>name</key>
        <string>support.type.fx.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(technique|Technique|technique10|technique11|pass)\b</string>
        <key>name</key>
        <string>storage.type.fx.technique.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(AlphaToCoverageEnable|BlendEnable|SrcBlend|DestBlend|BlendOp|SrcBlendAlpha|DestBlendAlpha|BlendOpAlpha|RenderTargetWriteMask)\b</string>
        <key>name</key>
        <string>meta.object-literal.key.fx.blendstate.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(DepthEnable|DepthWriteMask|DepthFunc|StencilEnable|StencilReadMask|StencilWriteMask|FrontFaceStencilFail|FrontFaceStencilZFail|FrontFaceStencilPass|FrontFaceStencilFunc|BackFaceStencilFail|BackFaceStencilZFail|BackFaceStencilPass|BackFaceStencilFunc)\b</string>
        <key>name</key>
        <string>meta.object-literal.key.fx.depthstencilstate.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(FillMode|CullMode|FrontCounterClockwise|DepthBias|DepthBiasClamp|SlopeScaleDepthBias|ZClipEnable|ScissorEnable|MultiSampleEnable|AntiAliasedLineEnable)\b</string>
        <key>name</key>
        <string>meta.object-literal.key.fx.rasterizerstate.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(Filter|AddressU|AddressV|AddressW|MipLODBias|MaxAnisotropy|ComparisonFunc|BorderColor|MinLOD|MaxLOD)\b</string>
        <key>name</key>
        <string>meta.object-literal.key.fx.samplerstate.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:ZERO|ONE|SRC_COLOR|INV_SRC_COLOR|SRC_ALPHA|INV_SRC_ALPHA|DEST_ALPHA|INV_DEST_ALPHA|DEST_COLOR|INV_DEST_COLOR|SRC_ALPHA_SAT|BLEND_FACTOR|INV_BLEND_FACTOR|SRC1_COLOR|INV_SRC1_COLOR|SRC1_ALPHA|INV_SRC1_ALPHA)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.blend.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:ADD|SUBTRACT|REV_SUBTRACT|MIN|MAX)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.blendop.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:ALL)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.depthwritemask.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:NEVER|LESS|EQUAL|LESS_EQUAL|GREATER|NOT_EQUAL|GREATER_EQUAL|ALWAYS)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.comparisonfunc.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:KEEP|REPLACE|INCR_SAT|DECR_SAT|INVERT|INCR|DECR)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.stencilop.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:WIREFRAME|SOLID)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.fillmode.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:NONE|FRONT|BACK)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.cullmode.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:MIN_MAG_MIP_POINT|MIN_MAG_POINT_MIP_LINEAR|MIN_POINT_MAG_LINEAR_MIP_POINT|MIN_POINT_MAG_MIP_LINEAR|MIN_LINEAR_MAG_MIP_POINT|MIN_LINEAR_MAG_POINT_MIP_LINEAR|MIN_MAG_LINEAR_MIP_POINT|MIN_MAG_MIP_LINEAR|ANISOTROPIC|COMPARISON_MIN_MAG_MIP_POINT|COMPARISON_MIN_MAG_POINT_MIP_LINEAR|COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT|COMPARISON_MIN_POINT_MAG_MIP_LINEAR|COMPARISON_MIN_LINEAR_MAG_MIP_POINT|COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR|COMPARISON_MIN_MAG_LINEAR_MIP_POINT|COMPARISON_MIN_MAG_MIP_LINEAR|COMPARISON_ANISOTROPIC|TEXT_1BIT)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.filter.hlsl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(?i:WRAP|MIRROR|CLAMP|BORDER|MIRROR_ONCE)\b</string>
        <key>name</key>
        <string>support.constant.property-value.fx.textureaddressmode.hlsl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.hlsl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.hlsl</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.hlsl</string>
  </dict>
</plist>