<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>hy</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#all</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>all</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keysym</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#builtin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#symbol</string>
          </dict>
        </array>
      </dict>
      <key>builtin</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![-!$%\&amp;*./:&lt;-@^_\w])(abs|all|any|ascii|bin|breakpoint|callable|chr|compile|delattr|dir|divmod|eval|exec|format|getattr|globals|hasattr|hash|hex|id|input|isinstance|issubclass|iter|aiter|len|locals|max|min|next|anext|oct|ord|pow|print|repr|round|setattr|sorted|sum|vars|False|None|True|NotImplemented|bool|memoryview|bytearray|bytes|classmethod|complex|dict|enumerate|filter|float|frozenset|property|int|list|map|object|range|reversed|set|slice|staticmethod|str|super|tuple|type|zip|open|quit|exit|copyright|credits|help)(?![-!$%\&amp;*./:&lt;-@^_\w])</string>
            <key>name</key>
            <string>storage.builtin.hy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\(\s*)\.\.\.(?![-!$%\&amp;*./:&lt;-@^_\w])</string>
            <key>name</key>
            <string>storage.builtin.dots.hy</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(;).*$</string>
            <key>name</key>
            <string>comment.line.hy</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=[(\[{\s])([0-9]+(\.[0-9]+)?|(#x)\h+|(#o)[0-7]+|(#b)[01]+)(?=[]"'(),;\[{}\s])</string>
            <key>name</key>
            <string>constant.numeric.hy</string>
          </dict>
        </array>
      </dict>
      <key>keysym</key>
      <dict>
        <key>match</key>
        <string>(?&lt;![-!$%\&amp;*./:&lt;-@^_\w]):[-!$%\&amp;*./:&lt;-@^_\w]*</string>
        <key>name</key>
        <string>variable.other.constant</string>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![-!$%\&amp;*./:&lt;-@^_\w])(and|await|match|let|annotate|assert|break|chainc|cond|continue|deftype|do|except\*?|finally|else|defreader|([dgls])?for|set[vx]|defclass|defmacro|del|export|eval-and-compile|eval-when-compile|get|global|if|import|(de)?fn|nonlocal|not-in|or|(quasi)?quote|require|return|cut|raise|try|unpack-iterable|unpack-mapping|unquote|unquote-splice|when|while|with|yield|local-macros|in|is|py(s)?|pragma|nonlocal|(is-)?not)(?![-!$%\&amp;*./:&lt;-@^_\w])</string>
            <key>name</key>
            <string>keyword.control.hy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\(\s*)\.(?![-!$%\&amp;*./:&lt;-@^_\w])</string>
            <key>name</key>
            <string>keyword.control.dot.hy</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![-!$%\&amp;*./:&lt;-@^_\w])(\+=?|//?=?|\*\*?=?|--?=?|[!&lt;&gt;]?=|@=?|%=?|&lt;&lt;?=?|&gt;&gt;?=?|&amp;=?|\|=?|\^|~@|~=?|#\*\*?)(?![-!$%\&amp;*./:&lt;-@^_\w])</string>
            <key>name</key>
            <string>keyword.control.hy</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>begin</key>
        <string>(f?"|}(?=\N*?["{]))</string>
        <key>end</key>
        <string>("|(?&lt;=["}]\N*?)\{)</string>
        <key>name</key>
        <string>string.quoted.double.hy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.hy</string>
          </dict>
        </array>
      </dict>
      <key>symbol</key>
      <dict>
        <key>match</key>
        <string>(?&lt;![-!#-\&amp;*./:&lt;-@^_\w])[-!#$%*./&lt;-Z^_a-zΑ-Ωα-ω][-!#-\&amp;*./:&lt;-@^_\w]*</string>
        <key>name</key>
        <string>variable.other.hy</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.hy</string>
  </dict>
</plist>