<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>jsonnet</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>builtin-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bstd\.(acos|asin|atan|ceil|char|codepoint|cos|exp|exponent)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(filter|floor|force|length|log|makeArray|mantissa)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(objectFields|objectHas|pow|sin|sqrt|tan|type|thisFile)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(acos|asin|atan|ceil|char|codepoint|cos|exp|exponent)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(abs|assertEqual|escapeString(Bash|Dollars|Json|Python))\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(filterMap|flattenArrays|foldl|foldr|format|join)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(lines|manifest(Ini|Python(Vars)?)|map|max|min|mod)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(s(?:et(Diff|Inter|Member|Union)??|ort))\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstd\.(range|split|stringChars|substr|toString|uniq)\b</string>
            <key>name</key>
            <string>support.function.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>//.*$</string>
            <key>name</key>
            <string>comment.line.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>#.*$</string>
            <key>name</key>
            <string>comment.block.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>double-quoted-strings</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.jsonnet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(["/\\bfnrt]|(u\h{4}))</string>
            <key>name</key>
            <string>constant.character.escape.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[^"/\\bfnrtu]</string>
            <key>name</key>
            <string>invalid.illegal.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-quoted-strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#double-quoted-strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#triple-quoted-strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#builtin-functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b([A-Z_a-z][0-9A-Z_a-z]*)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.jsonnet</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.function</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[-!%\&amp;*+/:&lt;=&gt;^|~]</string>
            <key>name</key>
            <string>keyword.operator.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$</string>
            <key>name</key>
            <string>keyword.other.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(self|super|import|importstr|local|tailstrict)\b</string>
            <key>name</key>
            <string>keyword.other.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|then|else|for|in|error|assert)\b</string>
            <key>name</key>
            <string>keyword.control.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(function)\b</string>
            <key>name</key>
            <string>storage.type.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][0-9A-Z_a-z]*\s*(\+??:::)</string>
            <key>name</key>
            <string>variable.parameter.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][0-9A-Z_a-z]*\s*(\+??::)</string>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][0-9A-Z_a-z]*\s*(\+??:)</string>
            <key>name</key>
            <string>variable.parameter.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>name</key>
            <string>constant.language.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d+([Ee][-+]?\d+)?)\b</string>
            <key>name</key>
            <string>constant.numeric.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+\.\d*([Ee][-+]?\d+)?\b</string>
            <key>name</key>
            <string>constant.numeric.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\.\d+([Ee][-+]?\d+)?\b</string>
            <key>name</key>
            <string>constant.numeric.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>single-quoted-strings</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>name</key>
        <string>string.quoted.double.jsonnet</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(['/\\bfnrt]|(u\h{4}))</string>
            <key>name</key>
            <string>constant.character.escape.jsonnet</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[^'/\\bfnrtu]</string>
            <key>name</key>
            <string>invalid.illegal.jsonnet</string>
          </dict>
        </array>
      </dict>
      <key>triple-quoted-strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\|\|\|</string>
            <key>end</key>
            <string>\|\|\|</string>
            <key>name</key>
            <string>string.quoted.triple.jsonnet</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.jsonnet</string>
  </dict>
</plist>