<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>jsonl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.begin.json.lines</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.end.json.lines</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.array.json.lines</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.array.json.lines</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^]\s]</string>
            <key>name</key>
            <string>invalid.illegal.expected-array-separator.json.lines</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json.lines</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.json.lines</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json.lines</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.json.lines</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json.lines</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>match</key>
        <string>\b(?:true|false|null)\b</string>
        <key>name</key>
        <string>constant.language.json.lines</string>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[Ee][-+]?\d+)?)?</string>
        <key>name</key>
        <string>constant.numeric.json.lines</string>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.begin.json.lines</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.end.json.lines</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.dictionary.json.lines</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#objectkey</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.key-value.json.lines</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(,)|(?=})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.pair.json.lines</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.structure.dictionary.value.json.lines</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[^,\s]</string>
                <key>name</key>
                <string>invalid.illegal.expected-dictionary-separator.json.lines</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>[^}\s]</string>
            <key>name</key>
            <string>invalid.illegal.expected-dictionary-separator.json.lines</string>
          </dict>
        </array>
      </dict>
      <key>objectkey</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.support.type.property-name.begin.json.lines</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.support.type.property-name.end.json.lines</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.json.lines support.type.property-name.json.lines</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringcontent</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.json.lines</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.json.lines</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.json.lines</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringcontent</string>
          </dict>
        </array>
      </dict>
      <key>stringcontent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(?:["/\\bfnrt]|u\h{4})</string>
            <key>name</key>
            <string>constant.character.escape.json.lines</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unrecognized-string-escape.json.lines</string>
          </dict>
        </array>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.json.lines</string>
  </dict>
</plist>