<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>julia</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#operator</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#array</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#parentheses</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bracket</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function_decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function_call</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#for_block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#number</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type_decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#symbol</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(])(\.?'*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transpose.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.array.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\bbegin\b</string>
                <key>name</key>
                <string>constant.numeric.julia</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\bend\b</string>
                <key>name</key>
                <string>constant.numeric.julia</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#self_no_for_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>bracket</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})(\.?'*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transpose.julia</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#self_no_for_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>#</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.number-sign.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_tags</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment_block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>#=</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>=#</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.number-sign-equals.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_tags</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment_tags</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bTODO\b</string>
            <key>name</key>
            <string>keyword.other.comment-annotation.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bFIXME\b</string>
            <key>name</key>
            <string>keyword.other.comment-annotation.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bCHANGED\b</string>
            <key>name</key>
            <string>keyword.other.comment-annotation.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bXXX\b</string>
            <key>name</key>
            <string>keyword.other.comment-annotation.julia</string>
          </dict>
        </array>
      </dict>
      <key>for_block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(for)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;![,\s])(\s*\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\bouter\b</string>
                <key>name</key>
                <string>keyword.other.julia</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function_call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*})*})*})?\.?(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.julia</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)(('|(\.'))*\.?')?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transposed-func.julia</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#self_no_for_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function_decl</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*})*})*})?(?=\([^#]*\)(::\S+)?(\s*\bwhere\b\s+.+?)?\s*?=(?![=&gt;]))</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.dots.julia</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.julia</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.type.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(function|macro)(?:\s+(?:[_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*(\.))?([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*})*})*})?|\s*)(?=\()</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![.:_])(?:function|mutable\s+struct|struct|macro|quote|abstract\s+type|primitive\s+type|typegroup|module|baremodule|where)\b</string>
            <key>name</key>
            <string>keyword.other.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])(?:if|else|elseif|for|while|begin|let|do|try|catch|finally|return|break|continue)\b</string>
            <key>name</key>
            <string>keyword.control.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])end\b</string>
            <key>name</key>
            <string>keyword.control.end.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])(?:global|local|const)\b</string>
            <key>name</key>
            <string>keyword.storage.modifier.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])export\b</string>
            <key>name</key>
            <string>keyword.control.export.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^public\b</string>
            <key>name</key>
            <string>keyword.control.public.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])import\b</string>
            <key>name</key>
            <string>keyword.control.import.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;![:_])using\b</string>
            <key>name</key>
            <string>keyword.control.using.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\S\s+)\b(as)\b(?=\s+\S)</string>
            <key>name</key>
            <string>keyword.control.as.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@(\.|[_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*|[[\p{S}\p{P}]&amp;&amp;[^@\s]]+)</string>
            <key>name</key>
            <string>support.function.macro.julia</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.conjugate-number.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((?&lt;![!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]])\b(?:0[Xx]\h(?:_?\h)*|0o[0-7](?:_?[0-7])*|0b[01](?:_?[01])*|(?:[0-9](?:_?[0-9])*\.?(?!\.)[0-9_]*|\.[0-9](?:_?[0-9])*)(?:[Eef][-+]?[0-9](?:_?[0-9])*)?(?:(?:im|Inf(?:16|32|64)?|NaN(?:16|32|64)?|π|pi|ℯ)\b)?|[0-9]+|Inf(?:16|32|64)?\b|NaN(?:16|32|64)?\b|π\b|pi\b|ℯ\b))('*)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:ARGS|C_NULL|DEPOT_PATH|ENDIAN_BOM|ENV|LOAD_PATH|PROGRAM_FILE|stdin|stdout|stderr|VERSION|devnull)\b</string>
            <key>name</key>
            <string>constant.global.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:true|false|nothing|missing)\b</string>
            <key>name</key>
            <string>constant.language.julia</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\.?(?:&lt;--&gt;|-&gt;|--&gt;|&lt;--|[←→↔↚-↞↠↢↣↤↦↩-↬↮↶↷↺-↽⇀⇁⇄⇆⇇⇉⇋-⇐⇒⇔⇚-⇝⇠⇢⇴⇶-⇿⟵⟶⟷⟹-⟿⤀-⤇⤌-⤑⤔-⤘⤝-⤠⥄-⥈⥊⥋⥎⥐⥒⥓⥖⥗⥚⥛⥞⥟⥢⥤⥦-⥭⥰⥷⥺⧴⬰-⭄⭇-⭌￩￫]|=&gt;)</string>
            <key>name</key>
            <string>keyword.operator.arrow.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:=|\+=|-=|\*=|//=|/=|\.//=|\./=|\.\*=|\\=|\.\\=|\^=|\.\^=|%=|\.%=|÷=|\.÷=|\|=|&amp;=|\.&amp;=|⊻=|\.⊻=|\$=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|=(?!=)</string>
            <key>name</key>
            <string>keyword.operator.update.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&lt;|&gt;&gt;&gt;?|\.&gt;&gt;&gt;?|\.&lt;&lt;</string>
            <key>name</key>
            <string>keyword.operator.shift.julia</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.relation.types.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.julia</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transpose.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s*([:&lt;&gt;]:)\s*((?:Union)?\([^)]*\)|[$_∇[:alpha:]][!.′⁺-ₜ[:word:]]*(?:\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*})*})*}|".+?(?&lt;!\\)")?)(?:\.\.\.)?(\.?'*)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.?((?&lt;!&lt;)&lt;=|(?&lt;!&gt;)&gt;=|[&lt;&gt;≤≥]|===?|≡|!=|≠|!==|[∈-∍∝∥∦∷∺∻∽∾≁-≎≐-≓≖-≟≢≣≦-⊋⊏-⊒⊜⊢⊣⊩⊬⊮⊰-⊷⋍⋐⋑⋕-⋭⋲-⋿⟂⟈⟉⟒⦷⧀⧁⧡⧣⧤⧥⩦⩧⩪-⩳⩵-⫙⫪⫫⫷-⫺]|&lt;:|&gt;:))</string>
            <key>name</key>
            <string>keyword.operator.relation.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\s)\?(?=\s)</string>
            <key>name</key>
            <string>keyword.operator.ternary.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\s):(?=\s)</string>
            <key>name</key>
            <string>keyword.operator.ternary.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|\||&amp;&amp;|(?&lt;![!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]])!</string>
            <key>name</key>
            <string>keyword.operator.boolean.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=[]!)}′⁺-ₜ∇[:word:]]):</string>
            <key>name</key>
            <string>keyword.operator.range.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|&gt;</string>
            <key>name</key>
            <string>keyword.operator.applies.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\||\.\||&amp;|\.&amp;|[~¬]|\.~|⊻|\.⊻</string>
            <key>name</key>
            <string>keyword.operator.bitwise.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.?(?:\+\+|--|[-*+|¦±−∓∔∨∪∸≏⊎⊔⊕⊖⊞⊟⊻⊽⋎⋓⟇⧺⧻⨈⨢-⨮⨹⨺⩁⩂⩅⩊⩌⩏⩐⩒⩔⩖⩗⩛⩝⩡⩢⩣]|//?|[%\&amp;\\^±·×÷·⅋↑↓⇵∓∗-∜∤∧∩≀⊍⊓⊗-⊛⊠⊡⊼⋄-⋇⋉-⋌⋏⋒⌿▷⟑⟕⟖⟗⟰⟱⤈-⤋⤒⤓⥉⥌⥍⥏⥑⥔⥕⥘⥙⥜⥝⥠⥡⥣⥥⥮⥯⦸⦼⦾⦿⧶⧷⨇⨝⨟⨰-⨸⨻⨼⨽⩀⩃⩄⩋⩍⩎⩑⩓⩕⩘⩚⩜⩞⩟⩠⫛￪￬])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>∘</string>
            <key>name</key>
            <string>keyword.operator.compose.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>::|(?&lt;=\s)isa(?=\s)</string>
            <key>name</key>
            <string>keyword.operator.isa.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\s)in(?=\s)</string>
            <key>name</key>
            <string>keyword.operator.relation.in.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.(?=[@_\p{L}])|\.\.+|[…⁝⋮-⋱]</string>
            <key>name</key>
            <string>keyword.operator.dots.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$(?=.+)</string>
            <key>name</key>
            <string>keyword.operator.interpolation.julia</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transposed-variable.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)(('|(\.'))*\.?')</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>bracket.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transposed-matrix.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(])((?:\.??')*\.?')</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>bracket.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transposed-parens.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\))((?:\.??')*\.?')</string>
          </dict>
        </array>
      </dict>
      <key>parentheses</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))(\.?'*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.transpose.julia</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#self_no_for_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.julia</string>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.separator.semicolon.julia</string>
          </dict>
        </array>
      </dict>
      <key>self_no_for_block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parentheses</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bracket</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type_decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#symbol</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(@doc)\s((?:doc)?""")|(doc""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""") ?(-&gt;)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.arrow.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.docstring.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(i?cxx)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.inline.cpp</string>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>embed.cxx.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cpp#root_context</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(py)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.inline.python</string>
            <key>end</key>
            <string>([\s\w]*)(""")</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>embed.python.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(js)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.inline.javascript</string>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>embed.js.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(R)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.inline.r</string>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>embed.R.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.r</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(raw)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(raw)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(sql)(""")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.embedded.inline.sql</string>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>embed.sql.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.sql</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>var"""</string>
            <key>end</key>
            <string>"""</string>
            <key>name</key>
            <string>constant.other.symbol.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>var"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>constant.other.symbol.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s?(doc)?(""")\s?$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.docstring.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'(?!')</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.multiline.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.multiline.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.triple.double.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"(?!"")</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>r"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")([imsx]{0,4})?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.option-toggle.regexp.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>r"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.begin.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")([imsx]{0,4})?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.option-toggle.regexp.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!")([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(""")([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!")([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;![^\\]\\)(")([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!`)([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?```</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(```)([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.interpolated.backtick.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!`)([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?`</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.julia</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;![^\\]\\)(`)([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.macro.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.interpolated.backtick.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_dollar_sign_interpolate</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string_dollar_sign_interpolate</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\$[_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}[^←-⇿\P{So}][^$\P{Sc}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}][^$\P{Sc}]]*</string>
            <key>name</key>
            <string>variable.interpolation.julia</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.bracket.julia</string>
              </dict>
            </dict>
            <key>name</key>
            <string>variable.interpolation.julia</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#self_no_for_block</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string_escaped_char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(\\|[0-3]\d{0,2}|[4-7]\d?|x\h{0,2}|u\h{0,4}|U\h{0,8}|.)</string>
            <key>name</key>
            <string>constant.character.escape.julia</string>
          </dict>
        </array>
      </dict>
      <key>symbol</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![]!)}′⁺-ₜ∇[:word:]]):[_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*(?![!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]])(?!["`])</string>
            <key>name</key>
            <string>constant.other.symbol.julia</string>
          </dict>
        </array>
      </dict>
      <key>type_decl</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.julia</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.inherited-class.julia</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.inheritance.julia</string>
              </dict>
            </dict>
            <key>match</key>
            <string>!:_(?:struct|mutable\s+struct|abstract\s+type|primitive\s+type)\s+([_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*)(\s*(&lt;:)\s*[_ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:alpha:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^←-⇿\P{So}]][!_′-‷⁗ⁱ-⁾₁-₎℘℮⅀-⅄∂∅∆∇∎-∑∞-∢∫-∳∿⊤⊥⊾-⋃◸-◿♯⟀⟁⟘⟙⦛-⦴⨀-⨆⨉-⨖⨛⨜゛゜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃𝟎-𝟡[:word:]\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}[^\x01-¡\P{Mn}][^\x01-¡\P{Mc}][^\x01-¡\D][^\x01-¡\P{Pc}][^\x01-¡\P{Sk}][^\x01-¡\P{Me}][^\x01-¡\P{No}][^←-⇿\P{So}]]*(?:\{.*})?)?</string>
            <key>name</key>
            <string>meta.type.julia</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.julia</string>
  </dict>
</plist>