<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kt</string>
      <string>kts</string>
    </array>
    <key>name</key>
    <string>kotlin</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>annotation-simple</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!\w)@[.\w]+\b(?!:)</string>
        <key>name</key>
        <string>entity.name.type.annotation.kotlin</string>
      </dict>
      <key>annotation-site</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\w)(@\w+):\s*(?!\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.annotation-site.kotlin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#unescaped-annotation</string>
          </dict>
        </array>
      </dict>
      <key>annotation-site-list</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\w)(@\w+):\s*\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.annotation-site.kotlin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#unescaped-annotation</string>
          </dict>
        </array>
      </dict>
      <key>binary-literal</key>
      <dict>
        <key>match</key>
        <string>0([Bb])[01][01_]*</string>
        <key>name</key>
        <string>constant.numeric.binary.kotlin</string>
      </dict>
      <key>boolean-literal</key>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.boolean.kotlin</string>
      </dict>
      <key>character</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>name</key>
        <string>string.quoted.single.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>class-declaration</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.class.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.kotlin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(class|(?:fun\s+)?interface)\s+(\b\w+\b|`[^`]+`)\s*(?&lt;GROUP&gt;&lt;([^&lt;&gt;]|\g&lt;GROUP&gt;)+&gt;)?</string>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation-simple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation-site-list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation-site</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-alias</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-constraint</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method-reference</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-empty</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-multiline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#character</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lambda-arrow</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#self-reference</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#decimal-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hex-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#binary-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#null-literal</string>
          </dict>
        </array>
      </dict>
      <key>comment-block</key>
      <dict>
        <key>begin</key>
        <string>/\*(?!\*)</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.kotlin</string>
      </dict>
      <key>comment-javadoc</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.javadoc.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>@(return|constructor|receiver|sample|see|author|since|suppress)\b</string>
                <key>name</key>
                <string>keyword.other.documentation.javadoc.kotlin</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.javadoc.kotlin</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@p(?:aram|roperty))\s+(\S+)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.javadoc.kotlin</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@param)\[(\S+)]</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.javadoc.kotlin</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.class.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(@(?:exception|throws))\s+(\S+)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.documentation.javadoc.kotlin</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.class.kotlin</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\{(@link)\s+(\S+)?#([$\w]+\s*\([^()]*\)).*}</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment-line</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.kotlin</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-javadoc</string>
          </dict>
        </array>
      </dict>
      <key>control-keywords</key>
      <dict>
        <key>match</key>
        <string>\b(if|else|while|do|when|try|throw|break|continue|return|for)\b</string>
        <key>name</key>
        <string>keyword.control.kotlin</string>
      </dict>
      <key>decimal-literal</key>
      <dict>
        <key>match</key>
        <string>\b\d[_\d]*(\.[_\d]+)?(([Ee])\d+)?([Uu])?([FLf])?\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.kotlin</string>
      </dict>
      <key>function</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.fun.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.extension.kotlin</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.declaration.kotlin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(fun)\b\s*(?&lt;GROUP&gt;&lt;([^&lt;&gt;]|\g&lt;GROUP&gt;)+&gt;)?\s*(?:(?:(\w+)\.)?(\b\w+\b|`[^`]+`))?</string>
      </dict>
      <key>function-call</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.call.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\??\.?(\b\w+\b|`[^`]+`)\s*(?&lt;GROUP&gt;&lt;([^&lt;&gt;]|\g&lt;GROUP&gt;)+&gt;)?\s*(?=[({])</string>
      </dict>
      <key>hard-keywords</key>
      <dict>
        <key>match</key>
        <string>\b(as|typeof|is|in)\b</string>
        <key>name</key>
        <string>keyword.hard.kotlin</string>
      </dict>
      <key>hex-literal</key>
      <dict>
        <key>match</key>
        <string>0([Xx])\h[_\h]*([Uu])?</string>
        <key>name</key>
        <string>constant.numeric.hex.kotlin</string>
      </dict>
      <key>import</key>
      <dict>
        <key>begin</key>
        <string>\b(import)\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.soft.kotlin</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>entity.name.package.kotlin</string>
        <key>end</key>
        <string>;|$</string>
        <key>name</key>
        <string>meta.import.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hard-keywords</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*</string>
            <key>name</key>
            <string>variable.language.wildcard.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>key</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.kotlin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(\w=)\s*(=)</string>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#prefix-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#postfix-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#soft-keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hard-keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-keywords</string>
          </dict>
        </array>
      </dict>
      <key>lambda-arrow</key>
      <dict>
        <key>match</key>
        <string>-&gt;</string>
        <key>name</key>
        <string>storage.type.function.arrow.kotlin</string>
      </dict>
      <key>method-reference</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.reference.kotlin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\??::(\b\w+\b|`[^`]+`)</string>
      </dict>
      <key>null-literal</key>
      <dict>
        <key>match</key>
        <string>\bnull\b</string>
        <key>name</key>
        <string>constant.language.null.kotlin</string>
      </dict>
      <key>object</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.object.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.object.kotlin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(object)(?:\s+(\b\w+\b|`[^`]+`))?</string>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(===?|!==?|&lt;=|&gt;=|[&lt;&gt;])</string>
            <key>name</key>
            <string>keyword.operator.comparison.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-%*+/]=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.arithmetic.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-%*+/])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(!|&amp;&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(--|\+\+)</string>
            <key>name</key>
            <string>keyword.operator.increment-decrement.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.\.)</string>
            <key>name</key>
            <string>keyword.operator.range.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>package</key>
      <dict>
        <key>begin</key>
        <string>\b(package)\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.package.kotlin</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>entity.name.package.kotlin</string>
        <key>end</key>
        <string>;|$</string>
        <key>name</key>
        <string>meta.package.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>postfix-modifiers</key>
      <dict>
        <key>match</key>
        <string>\b(where|by|get|set)\b</string>
        <key>name</key>
        <string>storage.modifier.other.kotlin</string>
      </dict>
      <key>prefix-modifiers</key>
      <dict>
        <key>match</key>
        <string>\b(abstract|final|enum|open|annotation|sealed|data|override|final|lateinit|private|protected|public|internal|inner|companion|noinline|crossinline|vararg|reified|tailrec|operator|infix|inline|external|const|suspend|value)\b</string>
        <key>name</key>
        <string>storage.modifier.other.kotlin</string>
      </dict>
      <key>self-reference</key>
      <dict>
        <key>match</key>
        <string>\b(this|super)(@\w+)?\b</string>
        <key>name</key>
        <string>variable.language.this.kotlin</string>
      </dict>
      <key>soft-keywords</key>
      <dict>
        <key>match</key>
        <string>\b(init|catch|finally|field)\b</string>
        <key>name</key>
        <string>keyword.soft.kotlin</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!")"(?!")</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.kotlin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-escape-simple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-escape-bracketed</string>
          </dict>
        </array>
      </dict>
      <key>string-empty</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!")""(?!")</string>
        <key>name</key>
        <string>string.quoted.double.kotlin</string>
      </dict>
      <key>string-escape-bracketed</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)(\$\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.template.expression.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#code</string>
          </dict>
        </array>
      </dict>
      <key>string-escape-simple</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!\\)\$\w+\b</string>
        <key>name</key>
        <string>variable.string-escape.kotlin</string>
      </dict>
      <key>string-multiline</key>
      <dict>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
        <key>name</key>
        <string>string.quoted.double.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.kotlin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-escape-simple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-escape-bracketed</string>
          </dict>
        </array>
      </dict>
      <key>type-alias</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.typealias.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.kotlin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(typealias)\s+(\b\w+\b|`[^`]+`)\s*(?&lt;GROUP&gt;&lt;([^&lt;&gt;]|\g&lt;GROUP&gt;)+&gt;)?</string>
      </dict>
      <key>type-annotation</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(?&lt;![:?]):\s*([?\w\s]|-&gt;|(?&lt;GROUP&gt;[(&lt;]([^"'()&lt;&gt;]|\g&lt;GROUP&gt;)+[)&gt;]))+</string>
      </dict>
      <key>type-parameter</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b\w+\b</string>
            <key>name</key>
            <string>entity.name.type.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(in|out)\b</string>
            <key>name</key>
            <string>storage.modifier.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>unescaped-annotation</key>
      <dict>
        <key>match</key>
        <string>\b[.\w]+\b</string>
        <key>name</key>
        <string>entity.name.type.annotation.kotlin</string>
      </dict>
      <key>variable-declaration</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.hard.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(va[lr])\b\s*(?&lt;GROUP&gt;&lt;([^&lt;&gt;]|\g&lt;GROUP&gt;)+&gt;)?</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.kotlin</string>
  </dict>
</plist>