<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>log</string>
    </array>
    <key>name</key>
    <string>log</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>\b([Tt]race|TRACE)\b:?</string>
        <key>name</key>
        <string>comment log.verbose</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)\[(v(?:erbose|erb|rb|b?))]</string>
        <key>name</key>
        <string>comment log.verbose</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^[p\s\d]*)\bV\b</string>
        <key>name</key>
        <string>comment log.verbose</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(D(?:EBUG|ebug))\b|(?i)\b(debug):</string>
        <key>name</key>
        <string>markup.changed log.debug</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)\[(d(?:ebug|bug|bg|e?))]</string>
        <key>name</key>
        <string>markup.changed log.debug</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^[p\s\d]*)\bD\b</string>
        <key>name</key>
        <string>markup.changed log.debug</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(HINT|INFO|INFORMATION|Info|NOTICE|II)\b|(?i)\b(info(?:|rmation)):</string>
        <key>name</key>
        <string>markup.inserted log.info</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)\[(i(?:nformation|nfo?|n?))]</string>
        <key>name</key>
        <string>markup.inserted log.info</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^[p\s\d]*)\bI\b</string>
        <key>name</key>
        <string>markup.inserted log.info</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(W(?:ARNING|ARN|arn|W))\b|(?i)\b(warning):</string>
        <key>name</key>
        <string>markup.deleted log.warning</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)\[(w(?:arning|arn|rn|n?))]</string>
        <key>name</key>
        <string>markup.deleted log.warning</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^[p\s\d]*)\bW\b</string>
        <key>name</key>
        <string>markup.deleted log.warning</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(ALERT|CRITICAL|EMERGENCY|ERROR|FAILURE|FAIL|Fatal|FATAL|Error|EE)\b|(?i)\b(error):</string>
        <key>name</key>
        <string>string.regexp, strong log.error</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)\[(error|eror|err?|e|fatal|fatl|ftl|fa?)]</string>
        <key>name</key>
        <string>string.regexp, strong log.error</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=^[p\s\d]*)\bE\b</string>
        <key>name</key>
        <string>string.regexp, strong log.error</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b\d{4}-\d{2}-\d{2}(?=T|\b)</string>
        <key>name</key>
        <string>comment log.date</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=(^|\s))\d{2}[^\w\s]\d{2}[^\w\s]\d{4}\b</string>
        <key>name</key>
        <string>comment log.date</string>
      </dict>
      <dict>
        <key>match</key>
        <string>T?\d{1,2}:\d{2}(:\d{2}([,.]\d+)?)?(Z| ?[-+]\d{1,2}:\d{2})?\b</string>
        <key>name</key>
        <string>comment log.date</string>
      </dict>
      <dict>
        <key>match</key>
        <string>T\d{2}\d{2}(\d{2}([,.]\d+)?)?(Z| ?[-+]\d{1,2}\d{2})?\b</string>
        <key>name</key>
        <string>comment log.date</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(\h{40}|\h{10}|\h{7})\b</string>
        <key>name</key>
        <string>constant.language</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b\h{8}-?(\h{4}-?){3}\h{12}\b</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(\h{2,}[-:])+\h{2,}+\b</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([0-9]+|true|false|null)\b</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(0x\h+)\b</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>"[^"]*"</string>
        <key>name</key>
        <string>string log.string</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\w)'[^']*'</string>
        <key>name</key>
        <string>string log.string</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([.A-Za-z]*Exception)\b</string>
        <key>name</key>
        <string>string.regexp, emphasis log.exceptiontype</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^[\t ]*at[\t ]</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>string.key, emphasis log.exception</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[a-z]+://\S+\b/?</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;![/\\\w])([-\w]+\.)+([-\w])+(?![/\\\w])</string>
        <key>name</key>
        <string>constant.language log.constant</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>text.log</string>
  </dict>
</plist>