<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>marko</string>
    </array>
    <key>name</key>
    <string>marko</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>^\s*(style)(\b\S*\.css)?\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.css</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.css</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(style)\b(\S*\.less)\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.less</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.less</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css.less</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(style)\b(\S*\.scss)\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.scss</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.scss</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css.scss</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(style)\b(\S*\.[jt]s)\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(?:((?:static|server|client)(?![-$0-9@-Z_a-z]))|(?=(?:class|import|export)[^-$0-9@-Z_a-z]))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.static.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>(?=\n|$)</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#content-concise-mode</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attr-value</key>
      <dict>
        <key>begin</key>
        <string>\s*(:?=)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>(?=[],;]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!%\&amp;*:?^|~]|[-!%\&amp;*+/&lt;-?^|~]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[]%).0-9&lt;A-Za-z}]\s/|[^$.\w]await|[^$.\w]async|[^$.\w]class|[^$.\w]function|[^$.\w]keyof|[^$.\w]new|[^$.\w]readonly|[^$.\w]infer|[^$.\w]typeof|[^$.\w]void)\s+(?![\n!%\&amp;(*+:?^{|~]|[-/&lt;=&gt;]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^,/:;=&gt;]))</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-expression</string>
          </dict>
        </array>
      </dict>
      <key>attrs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>(?:(key|on[-$0-9A-Z_a-z]+|[$0-9A-Z_a-z]+Change|no-update(?:-body)?(?:-if)?)|([$0-9A-Z_a-z][-$0-9A-Z_a-z]*)|(#[$0-9A-Z_a-z][-$0-9A-Z_a-z]*))(:[$0-9A-Z_a-z][-$0-9A-Z_a-z]*)?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.attribute-name.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.marko</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute-name.marko</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute-name.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=.|$)</string>
            <key>name</key>
            <string>meta.marko-attribute</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#html-args-or-method</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attr-value</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\.\.\.)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.spread.marko</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?=[],;]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!%\&amp;*:?^|~]|[-!%\&amp;*+/&lt;-?^|~]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[]%).0-9&lt;A-Za-z}]\s/|[^$.\w]await|[^$.\w]async|[^$.\w]class|[^$.\w]function|[^$.\w]keyof|[^$.\w]new|[^$.\w]readonly|[^$.\w]infer|[^$.\w]typeof|[^$.\w]void)\s+(?![\n!%\&amp;(*+:?^{|~]|[-/&lt;=&gt;]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^,/:;=&gt;]))</string>
            <key>name</key>
            <string>meta.marko-spread-attribute</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#javascript-expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(,(?!,))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.comma.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\S)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
      </dict>
      <key>cdata</key>
      <dict>
        <key>begin</key>
        <string>\s*&lt;!\[CDATA\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.other.inline-data.marko</string>
        <key>end</key>
        <string>]]&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.metadata.cdata.marko</string>
      </dict>
      <key>concise-attr-group</key>
      <dict>
        <key>begin</key>
        <string>\s*(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#concise-attr-group</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s+</string>
            <key>end</key>
            <string>(?=\S)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attrs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
      </dict>
      <key>concise-comment-block</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-comment-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-comment</string>
          </dict>
        </array>
      </dict>
      <key>concise-comment-line</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-comment-line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-comment</string>
          </dict>
        </array>
      </dict>
      <key>concise-html-block</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-html-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-html-mode</string>
          </dict>
        </array>
      </dict>
      <key>concise-html-line</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#cdata</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#doctype</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#javascript-comments-after-whitespace</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag-html</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>text.marko</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#placeholder</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.+?</string>
                <key>name</key>
                <string>text.marko</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s*(--+)(?=\s+\S)(.*)$()</string>
        <key>name</key>
        <string>meta.section.marko-html-line</string>
      </dict>
      <key>concise-open-tag-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-before-attrs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-semi-eol</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!^)[\t ,]</string>
            <key>end</key>
            <string>(?=--)|(?=\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#concise-semi-eol</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#concise-attr-group</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>[\t ]+</string>
                <key>end</key>
                <string>(?=[\n\S])</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attrs</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#invalid</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>concise-script-block</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-script-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-script</string>
          </dict>
        </array>
      </dict>
      <key>concise-script-line</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-script-line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-script</string>
          </dict>
        </array>
      </dict>
      <key>concise-semi-eol</key>
      <dict>
        <key>begin</key>
        <string>\s*(;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-block</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.css</string>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-block-less</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.less</string>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-less</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-block-scss</key>
      <dict>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.scss</string>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-scss</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-line</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.css</string>
        <key>end</key>
        <string>$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-line-less</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.less</string>
        <key>end</key>
        <string>$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-less</string>
          </dict>
        </array>
      </dict>
      <key>concise-style-line-scss</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.scss</string>
        <key>end</key>
        <string>$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-scss</string>
          </dict>
        </array>
      </dict>
      <key>content-concise-mode</key>
      <dict>
        <key>name</key>
        <string>meta.marko-concise-content</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#scriptlet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cdata</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctype</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-html-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-html-line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-html</string>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=html-comment[^-$0-9@-Z_a-z])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-comment-line</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=style\b\S*\.less\b)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block-less</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line-less</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=style\b\S*\.scss\b)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block-scss</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line-scss</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=style\b\S*\.[jt]s\b)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-line</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?style[^-$0-9@-Z_a-z])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?script[^-$0-9@-Z_a-z])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-line</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>^([\t ]*)(?=[#$.0-9@-Z_a-z])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#content-concise-mode</string>
                  </dict>
                </array>
                <key>while</key>
                <string>(?=^(?:\s*[])`}]|\*/|\s*$|\1\s+(\S|$)))</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>content-embedded-comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.</string>
            <key>name</key>
            <string>comment.block.marko</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-script</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.css</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style-less</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.css.less</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css.less</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style-scss</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.css.scss</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css.scss</string>
          </dict>
        </array>
      </dict>
      <key>content-html-mode</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#scriptlet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cdata</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctype</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#javascript-comments-after-whitespace</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-html</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>text.marko</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>text.marko</string>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>begin</key>
        <string>(&lt;\?)\s*([-$0-9A-Z_a-z]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\??&gt;)</string>
        <key>name</key>
        <string>meta.tag.metadata.processing.xml.marko</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.marko</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.marko</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.marko</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((?:[^=&gt;?\s]|\?(?!&gt;))+)(=)(?:("(?:[^"\\]|\\.)*")|('(?:[^'\\]|\\.)*')|((?:[^&gt;?\s]|\?(?!&gt;))+))</string>
          </dict>
        </array>
      </dict>
      <key>doctype</key>
      <dict>
        <key>begin</key>
        <string>\s*&lt;!(?=(?i:DOCTYPE\s))</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.metadata.doctype.marko</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\G(?i:DOCTYPE)</string>
            <key>name</key>
            <string>entity.name.tag.marko</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.marko</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^&gt;\s]+</string>
            <key>name</key>
            <string>entity.other.attribute-name.marko</string>
          </dict>
        </array>
      </dict>
      <key>html-args-or-method</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-type-params</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(?=\()</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#paren-expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\))\s*(?=\{)</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?&lt;=})</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>html-comment</key>
      <dict>
        <key>begin</key>
        <string>\s*(&lt;!(--)?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.marko</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\2&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.marko</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.marko</string>
      </dict>
      <key>invalid</key>
      <dict>
        <key>match</key>
        <string>\S</string>
        <key>name</key>
        <string>invalid.illegal.character-not-allowed-here.marko</string>
      </dict>
      <key>invalid-close-tag</key>
      <dict>
        <key>begin</key>
        <string>\s*&lt;/[^&gt;]*</string>
        <key>end</key>
        <string>&gt;</string>
        <key>name</key>
        <string>invalid.illegal.character-not-allowed-here.marko</string>
      </dict>
      <key>javascript-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(?=/\*)</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?&lt;=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>\s*//.*$</string>
          </dict>
        </array>
      </dict>
      <key>javascript-comments-after-whitespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?:^|\s+)(?=/\*)</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?&lt;=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>(?:^|\s+)//.*$</string>
          </dict>
        </array>
      </dict>
      <key>javascript-expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>(?:\s*\b(?:as|await|extends|in|instanceof|satisfies|keyof|new|typeof|void))+\s+(?![,/:;=&gt;])[#$0-9@-Z_a-z]*</string>
          </dict>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.regexp.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#regexp</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>(?&lt;![]%).0-9&lt;A-Za-z}])\s*/(?:[^/\[\\]|\\.|\[(?:[^]\\]|\\.)*])*/[A-Za-z]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>javascript-placeholder</key>
      <dict>
        <key>begin</key>
        <string>\$\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.ts</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>open-tag-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-before-attrs</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!/?&gt;)</string>
            <key>end</key>
            <string>(?=/?&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#attrs</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>placeholder</key>
      <dict>
        <key>begin</key>
        <string>\$!?\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.ts</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>scriptlet</key>
      <dict>
        <key>begin</key>
        <string>^\s*(\$)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.scriptlet.marko</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>tag-before-attrs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-shorthand-class-or-id</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/(?![*/])</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.tag-variable.marko</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>(?=[(,/;&lt;&gt;|]|:?=|\s+[^:]|$)</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[$A-Z_a-z][$0-9A-Z_a-z]*</string>
                <key>name</key>
                <string>variable.other.constant.object.ts</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\{</string>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.binding-pattern.object.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#object-binding-element</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>\[</string>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.binding-pattern.array.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>]</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#array-binding-element</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>\s*(:)(?!=)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.type.annotation.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[](,;]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!%\&amp;*:?^|~]|[-!%\&amp;*+/&lt;-?^|~]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[]%).0-9&lt;A-Za-z}]\s/|[^$.\w]await|[^$.\w]async|[^$.\w]class|[^$.\w]function|[^$.\w]keyof|[^$.\w]new|[^$.\w]readonly|[^$.\w]infer|[^$.\w]typeof|[^$.\w]void)\s+(?![\n!%\&amp;*+:?^{|~]|[-/&lt;=&gt;]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^,/:;=&gt;]))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#type</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#javascript-expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*\|</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.begin.marko</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.ts</string>
            <key>end</key>
            <string>\|</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#decorator</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#destructuring-parameter</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#parameter-name</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(:)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.type.annotation.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[,|])|(?==[^&gt;])</string>
                <key>name</key>
                <string>meta.type.annotation.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#type</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#variable-initializer</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.parameter.ts</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-args-or-method</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attr-value</string>
          </dict>
        </array>
      </dict>
      <key>tag-html</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr|const|debug|id|let|lifecycle|log|return)[^-$0-9@-Z_a-z])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/?&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=html-comment[^-$0-9@-Z_a-z])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/(?:&gt;|html-comment&gt;))</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*&lt;/(?:&gt;|html-comment&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-comment</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=style\S*\.less\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/style&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.less</string>
                <key>end</key>
                <string>\s*(&lt;/)(style)?(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style-less</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=style\S*\.scss\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/style&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.scss</string>
                <key>end</key>
                <string>\s*(&lt;/)(style)?(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style-scss</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=style\S*\.[jt]s\b)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/style&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.ts</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-script</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?style)[^-$0-9@-Z_a-z])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/\2&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.css</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?script)[^-$0-9@-Z_a-z])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/\2&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.ts</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?script)?(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-script</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(&lt;)(?=[#$.]|([-$0-9@-Z_a-z]+))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;)|(?&lt;=&lt;/\2&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&gt;</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\s*(&lt;/)([-#$.0-:@-Z_a-z]+)?([^&gt;]*)(&gt;)</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#tag-shorthand-class-or-id</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#invalid</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-html-mode</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tag-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\G(style)\b(\.[-$0-9A-Z_a-z]+(?:\.[-$0-9A-Z_a-z]+)*)|([0-9@-Z_a-z](?:[-0-9@-Z_a-z]|:(?!=))*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.builtin.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.marko.css</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(script|style|html-script|html-style|html-comment)(?![-$0-9@-Z_a-z])</string>
                    <key>name</key>
                    <string>support.type.builtin.marko</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>(for|if|while|else-if|else|try|await|return)(?![-$0-9@-Z_a-z])</string>
                    <key>name</key>
                    <string>keyword.control.flow.marko</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>(const|context|debug|define|id|let|log|lifecycle)(?![-$0-9@-Z_a-z])</string>
                    <key>name</key>
                    <string>support.function.marko</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>@.+</string>
                    <key>name</key>
                    <string>entity.other.attribute-name.marko</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>.+</string>
                    <key>name</key>
                    <string>entity.name.tag.marko</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=.)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-type-args</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[$0-9A-Z_a-z]|-[^-])</string>
            <key>end</key>
            <string>(?=[^-$0-9A-Z_a-z]|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#javascript-placeholder</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?:[-0-9A-Z_a-z]|\$(?!\{))+</string>
                <key>name</key>
                <string>entity.name.tag.marko</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>tag-shorthand-class-or-id</key>
      <dict>
        <key>begin</key>
        <string>(?=[#.])</string>
        <key>end</key>
        <string>$|(?=--|[^-#$.0-9A-Z_a-z])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-placeholder</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:[-#.0-9A-Z_a-z]|\$(?!\{))+</string>
            <key>name</key>
            <string>entity.other.attribute-name.marko</string>
          </dict>
        </array>
      </dict>
      <key>tag-type-args</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>(?=&lt;)</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>(?&lt;=&gt;)</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>(?&lt;=&gt;)(?=[\t ]*&lt;)</string>
            <key>end</key>
            <string>(?=.)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-type-params</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts#type-arguments</string>
          </dict>
        </array>
      </dict>
      <key>tag-type-params</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>(?!^)[\t ]*(?=&lt;)</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>end</key>
        <string>(?&lt;=&gt;)</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#type-parameters</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.marko</string>
  </dict>
</plist>