<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>mbt</string>
    </array>
    <key>name</key>
    <string>moonbit</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#support</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attribute</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#modules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attribute</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#strings</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>[ .0-9A-Z_a-z]+</string>
                    <key>name</key>
                    <string>entity.name.tag</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>=</string>
                    <key>name</key>
                    <string>keyword.operator.attribute.moonbit</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>(#[a-z][ .0-9A-Z_a-z]*)(.*)</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>//[^/].*</string>
            <key>name</key>
            <string>comment.line</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>///</string>
            <key>name</key>
            <string>comment.block.documentation.moonbit</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^|\G)(\s*)(`{3,}|~{3,})\s*(?i:(mbt\s+test|mbt\s+test(async)|mbt|moonbit\s+test|moonbit\s+test(async)|moonbit|)(\s+[^`~]*)?$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.markdown</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>fenced_code.block.language</string>
                  </dict>
                  <key>6</key>
                  <dict>
                    <key>name</key>
                    <string>fenced_code.block.language.attributes</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(^|\G)(\2|\s{0,3})(\3)\s*$</string>
                <key>endCaptures</key>
                <dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.markdown</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>markup.fenced_code.block.markdown</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>(^|\G)(\s*)(.*)</string>
                    <key>contentName</key>
                    <string>meta.embedded.block.moonbit</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                    <key>while</key>
                    <string>(^|\G)(?!\s*([`~]{3,})\s*$)</string>
                  </dict>
                </array>
              </dict>
            </array>
            <key>while</key>
            <string>///</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b\d([_\d])*(?!\.)((U)?(L)?|N?)\b</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\.)\d((?=\.)|\b)</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+(?=\.\.)</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d[_\d]*\.[_\d]*([Ee][-+]?\d[_\d]*\b)?</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0[Oo][0-7][0-7]*((U)?(L)?|N?)\b</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b0[Xx][A-Fa-f\d][A-F_a-f\d]*(([LU]|UL|N)\b|\.[A-F_a-f\d]*([Pp][-+]?[A-F_a-f\d]+\b)?)?</string>
            <key>name</key>
            <string>constant.numeric.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>escape</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\["'0\\bnrt]</string>
            <key>name</key>
            <string>constant.character.escape.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\x\h{2}</string>
            <key>name</key>
            <string>constant.character.escape.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\o[0-3][0-7]{2}</string>
            <key>name</key>
            <string>constant.character.escape.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\u\h{4}</string>
            <key>name</key>
            <string>constant.character.escape.unicode.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\u\{\h*}</string>
            <key>name</key>
            <string>constant.character.escape.unicode.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.moonbit</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.moonbit</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.moonbit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(fn)\b\s*(?:([A-Z][0-9A-Z_a-z]*)::)?([0-9_a-z][0-9A-Z_a-z]*)?\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!\bfn\s+)(?:\.|::)?([0-9_a-z][0-9A-Z_a-z]*([!?]|!!)?)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.moonbit</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.moonbit</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.moonbit</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.call.moonbit</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#support</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#modules</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>interpolation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\\\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.moonbit</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>source.moonbit</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.moonbit</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.embedded.line.moonbit</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(async)\b</string>
            <key>name</key>
            <string>keyword.control.moonbit.async</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(guard|if|while|break|continue|return|try|catch|except|raise|noraise|match|lexmatch|using|else|as|in|is|loop|for|async|defer)\b</string>
            <key>name</key>
            <string>keyword.control.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(type!|lexmatch\?|(type|typealias|let|const|enum|struct|import|trait|traitalias|derive|test|impl|with|fnalias|recur|suberror|letrec|and|where|declare)\b)</string>
            <key>name</key>
            <string>keyword.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(mut|pub|priv|readonly|extern)\b</string>
            <key>name</key>
            <string>storage.modifier.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>storage.type.function.arrow.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>storage.type.function.arrow.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|&gt;</string>
            <key>name</key>
            <string>keyword.operator.other.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(===?|!=|&gt;=|&lt;=|(?&lt;!-)(?&lt;!\|)&gt;(?!&gt;)|&lt;(?!&lt;))</string>
            <key>name</key>
            <string>keyword.operator.comparison.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bnot\b|&amp;&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\|(?!\|)(?!&gt;)|&amp;(?!&amp;)|\^|&lt;&lt;|&gt;&gt;)</string>
            <key>name</key>
            <string>keyword.operator.bitwise.moonbit</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+|-(?!&gt;)|[%*/])</string>
            <key>name</key>
            <string>keyword.operator.math.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>modules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>@[A-Za-z][/-9A-Z_a-z]*</string>
            <key>name</key>
            <string>entity.name.namespace.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.other.moonbit</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#\|).*</string>
            <key>name</key>
            <string>string.line</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.other.moonbit</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#escape</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#interpolation</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>(\$\|)(.*)</string>
            <key>name</key>
            <string>string.line</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>name</key>
            <string>string.quoted.single.moonbit</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escape</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.moonbit</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escape</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolation</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>support</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(Eq|Compare|Hash|Show|Default|ToJson|FromJson)\b</string>
            <key>name</key>
            <string>support.class.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?&lt;!@)[A-Z][0-9A-Z_a-z]*((\?)+|\b)</string>
            <key>name</key>
            <string>entity.name.type.moonbit</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?&lt;!\.|::)[_a-z][0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.other.moonbit</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.moonbit</string>
  </dict>
</plist>