<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>foldingStartMarker</key>
    <string>(\{\s*$|^\s*// \{\{\{)</string>
    <key>foldingStopMarker</key>
    <string>^\s*(}|// }}}$)</string>
    <key>name</key>
    <string>nextflow-groovy</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.groovy</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(#!).+$\n</string>
        <key>name</key>
        <string>comment.line.hashbang.groovy</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#groovy</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>braces</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#groovy-code</string>
          </dict>
        </array>
      </dict>
      <key>closures</key>
      <dict>
        <key>begin</key>
        <string>\{(?=.*?-&gt;)</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\{)(?=[^}]*?-&gt;)</string>
            <key>end</key>
            <string>-&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.groovy</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?!-&gt;)</string>
                <key>end</key>
                <string>(?=-&gt;)</string>
                <key>name</key>
                <string>meta.closure.parameters.groovy</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>begin</key>
                    <string>(?!,|-&gt;)</string>
                    <key>end</key>
                    <string>(?=,|-&gt;)</string>
                    <key>name</key>
                    <string>meta.closure.parameter.groovy</string>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>begin</key>
                        <string>=</string>
                        <key>beginCaptures</key>
                        <dict>
                          <key>0</key>
                          <dict>
                            <key>name</key>
                            <string>keyword.operator.assignment.groovy</string>
                          </dict>
                        </dict>
                        <key>end</key>
                        <string>(?=,|-&gt;)</string>
                        <key>name</key>
                        <string>meta.parameter.default.groovy</string>
                        <key>patterns</key>
                        <array>
                          <dict>
                            <key>include</key>
                            <string>#groovy-code</string>
                          </dict>
                        </array>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#parameters</string>
                      </dict>
                    </array>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[^}])</string>
            <key>end</key>
            <string>(?=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#groovy-code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.groovy</string>
              </dict>
            </dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.empty.groovy</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.javadoc</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.groovy</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.groovy</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.groovy</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([A-Z][0-9A-Z_]+)\b</string>
            <key>name</key>
            <string>constant.other.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>name</key>
            <string>constant.language.groovy</string>
          </dict>
        </array>
      </dict>
      <key>constructor-call</key>
      <dict>
        <key>begin</key>
        <string>\bnew\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.new.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))|$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?=\w.*\(?)</string>
            <key>end</key>
            <string>(?&lt;=\))|$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#object-types</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\(</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.groovy</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#groovy</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>groovy</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#groovy-code</string>
          </dict>
        </array>
      </dict>
      <key>groovy-code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#groovy-code-minus-map-keys</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map-keys</string>
          </dict>
        </array>
      </dict>
      <key>groovy-code-minus-map-keys</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-language</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#values</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#closures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#braces</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keyword-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-language</string>
          </dict>
        </array>
      </dict>
      <key>keyword-language</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(try|catch|throw)\b</string>
            <key>name</key>
            <string>keyword.control.exception.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((?&lt;!\.)(?:return|if|else))\b</string>
            <key>name</key>
            <string>keyword.control.groovy</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(assert)\s</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.assert.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$|[;}]</string>
            <key>name</key>
            <string>meta.declaration.assertion.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>keyword.operator.assert.expression-seperator.groovy</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#groovy-code-minus-map-keys</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keyword-operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(as)\b</string>
            <key>name</key>
            <string>keyword.operator.as.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(in)\b</string>
            <key>name</key>
            <string>keyword.operator.in.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?:</string>
            <key>name</key>
            <string>keyword.operator.elvis.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>keyword.operator.range.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&lt;</string>
            <key>name</key>
            <string>keyword.operator.leftshift.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\S)\.(?=\S)</string>
            <key>name</key>
            <string>keyword.operator.navigation.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\S)\?\.(?=\S)</string>
            <key>name</key>
            <string>keyword.operator.safe-navigation.groovy</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\?</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.ternary.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$|[])}])</string>
            <key>name</key>
            <string>meta.evaluation.ternary.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>keyword.operator.ternary.expression-seperator.groovy</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#groovy-code-minus-map-keys</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>==~</string>
            <key>name</key>
            <string>keyword.operator.match.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=~</string>
            <key>name</key>
            <string>keyword.operator.find.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(instanceof)\b</string>
            <key>name</key>
            <string>keyword.operator.instanceof.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=|&lt;=|&gt;=|&lt;=&gt;|&lt;&gt;|[&lt;&gt;]|&lt;&lt;)</string>
            <key>name</key>
            <string>keyword.operator.comparison.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(--|\+\+)</string>
            <key>name</key>
            <string>keyword.operator.increment-decrement.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([-%*+/])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.groovy</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(!|&amp;&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.groovy</string>
          </dict>
        </array>
      </dict>
      <key>map-keys</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.other.key.groovy</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.seperator.key-value.groovy</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\w+)\s*(:)</string>
          </dict>
        </array>
      </dict>
      <key>method-call</key>
      <dict>
        <key>begin</key>
        <string>([$\w]+)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.method.groovy</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method-parameters.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method-parameters.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.method-call.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.definition.seperator.parameter.groovy</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#groovy-code</string>
          </dict>
        </array>
      </dict>
      <key>nest-curly</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#nest-curly</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((0([Xx])\h*)|([-+])?\b(([0-9]+\.?[0-9]*)|(\.[0-9]+))(([Ee])([-+])?[0-9]+)?)([DFLUdfglu]|UL|ul)?\b</string>
            <key>name</key>
            <string>constant.numeric.groovy</string>
          </dict>
        </array>
      </dict>
      <key>object-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b((?:[a-z]\w*\.)*(?:[A-Z]+\w*[a-z]+\w*|UR[IL]))&lt;</string>
            <key>end</key>
            <string>[&gt;[^],&lt;?\[\w\s]]</string>
            <key>name</key>
            <string>storage.type.generic.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#object-types</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>&lt;</string>
                <key>end</key>
                <string>[&gt;[^],&lt;\[\w\s]]</string>
                <key>name</key>
                <string>storage.type.generic.groovy</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:[A-Za-z]\w*\.)*(?:[A-Z]+\w*[a-z]+\w*|UR[IL])\b</string>
            <key>name</key>
            <string>storage.type.groovy</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\w+</string>
            <key>name</key>
            <string>variable.parameter.method.groovy</string>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#groovy-code</string>
          </dict>
        </array>
      </dict>
      <key>primitive-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:boolean|byte|char|short|int|float|long|double)\b</string>
            <key>name</key>
            <string>storage.type.primitive.groovy</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-double</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-double-contents</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-double-contents</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.groovy</string>
          </dict>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\$\w</string>
            <key>end</key>
            <string>(?=\W)</string>
            <key>name</key>
            <string>variable.other.interpolated.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\w</string>
                <key>name</key>
                <string>variable.other.interpolated.groovy</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\.</string>
                <key>name</key>
                <string>keyword.other.dereference.groovy</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>source.groovy.embedded.source</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nest-curly</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-quoted-double-multiline</key>
      <dict>
        <key>begin</key>
        <string>"""</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.multiline.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-double-contents</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-single</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-single-contents</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-single-contents</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.groovy</string>
          </dict>
        </array>
      </dict>
      <key>string-quoted-single-multiline</key>
      <dict>
        <key>begin</key>
        <string>'''</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'''</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.multiline.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-single-contents</string>
          </dict>
        </array>
      </dict>
      <key>string-slashy</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/(?=[^/]+/([^&gt;]|$))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.begin.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.end.groovy</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.groovy</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>~"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.begin.groovy</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.regexp.end.groovy</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.compiled.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.groovy</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-quoted-double-multiline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-quoted-single-multiline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-quoted-double</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-quoted-single</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-slashy</string>
          </dict>
        </array>
      </dict>
      <key>structures</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.structure.begin.groovy</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.structure.end.groovy</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.groovy</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#groovy-code</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.definition.separator.groovy</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(def)\b</string>
            <key>name</key>
            <string>storage.type.def.groovy</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#primitive-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-types</string>
          </dict>
        </array>
      </dict>
      <key>values</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constructor-call</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>(?=(?:def|(?:boolean|byte|char|short|int|float|long|double)|(?:[a-z]\w*\.)*[A-Z]+\w*)\s+[],&lt;&gt;\[_\w\d\s]+(?:=|$))</string>
            <key>end</key>
            <string>;|$</string>
            <key>name</key>
            <string>meta.definition.variable.groovy</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\s</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>constant.variable.groovy</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>([0-9A-Z_]+)\s+(?==)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>meta.definition.variable.name.groovy</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\w[^,\s]*)\s+(?==)</string>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.groovy</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>: (\w+)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#types</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>=</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment.groovy</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>$</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#groovy-code</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>meta.definition.variable.name.groovy</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\w[^=\s]*)(?=\s*($|;))</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#groovy-code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.nextflow-groovy</string>
  </dict>
</plist>