<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>odin</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#file-tags</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package-name-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>assignments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#procedure-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#distinct-type-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
        </array>
      </dict>
      <key>attribute</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.attribute.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.odin</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(@)\s*([A-Z_a-z]\w*)\b</string>
            <key>name</key>
            <string>meta.attribute.odin</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(@)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.attribute.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.attribute.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b([A-Z_a-z]\w*)\b</string>
                <key>name</key>
                <string>entity.other.attribute-name.odin</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.odin</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>=</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment.odin</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[),])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#expressions</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>basic-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(i(?:8|16|32|64|128|nt))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(u(?:8|16|32|64|128|int|intptr))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((?:u16|u32|u64|u128|i16|i32|i64|i128)le)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((?:i16|i32|i64|i128|u16|u32|u64|u128)be)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(f(?:16|32|64))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(f(?:16|32|64)le)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(f(?:16|32|64)be)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(complex(?:32|64|128))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(quaternion(?:64|128|256))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(b(?:ool|8|16|32|64))\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(string|cstring|rune)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(rawptr)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(any|typeid)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(byte)\b</string>
            <key>name</key>
            <string>support.type.primitive.odin</string>
          </dict>
        </array>
      </dict>
      <key>block-comment</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\*/</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
        </array>
      </dict>
      <key>block-definition</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.block.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>block-label</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.label.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.label.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\w+)(:)\s*(?=for|switch|if|\{)</string>
        <key>name</key>
        <string>meta.block.label.odin</string>
      </dict>
      <key>case-clause</key>
      <dict>
        <key>begin</key>
        <string>\b(case)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.case.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>:</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.section.case-statement.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.case-clause.expr.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.double-slash.odin</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>#!</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.shebang.odin</string>
          </dict>
        </array>
      </dict>
      <key>constant-assignment</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([A-Z_a-z]\w*)\s*(:\s*:)</string>
        <key>name</key>
        <string>meta.definition.variable.odin</string>
      </dict>
      <key>distinct-type-assignment</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*(:\s*:)\s*(?=(distinct)\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^)|(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.variable.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ternary</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map-bitset</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#slice</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#basic-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#procedure-calls</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#property-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#union-member-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#union-non-nil-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-name</string>
          </dict>
        </array>
      </dict>
      <key>file-tags</key>
      <dict>
        <key>begin</key>
        <string>#\+[A-Z_a-z][-0-9A-Z_a-z]*</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.double-slash.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!</string>
            <key>name</key>
            <string>keyword.operator.logical.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][-0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>entity.other.attribute-name.odin</string>
          </dict>
        </array>
      </dict>
      <key>import-declaration</key>
      <dict>
        <key>begin</key>
        <string>\b((?:|foreign\s+)import)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^|;)</string>
        <key>name</key>
        <string>meta.import.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b[A-Z_a-z]\w*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.name.namespace.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^|;)</string>
            <key>name</key>
            <string>entity.name.alias.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(import|foreign|package)\b</string>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|else|or_else|when|where|for|in|not_in|defer|switch|return|or_return)\b</string>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.label.odin</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b((?:|or_)(?:break|continue))\b\s*(\w+)?</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(fallthrough|case|dynamic)\b</string>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(do|force_inline|no_inline)\b</string>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(asm)\b</string>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(auto_cast|distinct|using)\b</string>
            <key>name</key>
            <string>storage.modifier.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(context)\b</string>
            <key>name</key>
            <string>keyword.context.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ODIN_(?:ARCH|OS))\b</string>
            <key>name</key>
            <string>variable.other.constant.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(nil|true|false)\b</string>
            <key>name</key>
            <string>constant.language.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>---</string>
            <key>name</key>
            <string>constant.language.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d([_\d])*(\.\d([_\d])*)?)(([Ee])([-+])?\d+)?[ijk]?\b</string>
            <key>name</key>
            <string>constant.numeric.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((0b([01_])+)|(0o([_\d])+)|(0d([_\d])+)|(0[Xhx]([_\h])+))i?\b</string>
            <key>name</key>
            <string>constant.numeric.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(struct|enum|union|map|bit_set|bit_field|matrix)\b</string>
            <key>name</key>
            <string>storage.type.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-%*+/]=|%%=</string>
            <key>name</key>
            <string>keyword.operator.assignment.compound.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:[|~]|&amp;~?|&lt;&lt;|&gt;&gt;)=</string>
            <key>name</key>
            <string>keyword.operator.assignment.compound.bitwise.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[!=]=</string>
            <key>name</key>
            <string>keyword.operator.comparison.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[&lt;&gt;]=?</string>
            <key>name</key>
            <string>keyword.operator.relational.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.[&lt;=]</string>
            <key>name</key>
            <string>keyword.operator.range.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>keyword.operator.spread.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:[:=]|=</string>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;</string>
            <key>name</key>
            <string>keyword.operator.address.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^</string>
            <key>name</key>
            <string>keyword.operator.address.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>storage.type.function.arrow.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@|([-!%*+/:|]|&lt;&lt;?|&gt;&gt;?|~)=?|=|: : ?|\$</string>
            <key>name</key>
            <string>keyword.operator.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>#[A-Z_a-z]\w*</string>
            <key>name</key>
            <string>entity.name.tag.odin</string>
          </dict>
        </array>
      </dict>
      <key>map-bitset</key>
      <dict>
        <key>begin</key>
        <string>\b(bit_set|map)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>storage.type.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.bracket.square.odin</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\[</string>
            <key>name</key>
            <string>punctuation.definition.bracket.square.odin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>object-definition</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.object.type.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>package-name-declaration</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(package)\s+([A-Z_a-z]\w*)</string>
      </dict>
      <key>parameters</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.parameters.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#assignments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>procedure-assignment</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*(:\s*:|=)\s*(#\w+)?\s*(?=proc\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.definition.function.odin entity.name.function.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^)|(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.variable.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>procedure-calls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(cast|transmute)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.function.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-declaration</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b((?:size|align)_of)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.builtin.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-declaration</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(len|cap|offset_of_selector|offset_of_member|offset_of|offset_of_by_string|type_of|type_info_of|typeid_of|swizzle|complex|quaternion|real|imag|jmag|kmag|conj|expand_values|min|max|abs|clamp|soa_zip|soa_unzip|make|new|new_clone|resize|reserve|append|delete|free|free_all|assert|panic)\b\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.builtin.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([A-Z_a-z]\w*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.odin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>property-access</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.object.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([A-Z_a-z]\w*)\s*(\.)\s*(?=[A-Z_a-z]\w*)</string>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>match</key>
        <string>[](),.;\[\\{}]</string>
        <key>name</key>
        <string>punctuation.odin</string>
      </dict>
      <key>return-type-declaration</key>
      <dict>
        <key>begin</key>
        <string>-&gt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.arrow.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^|[),;{]|where)</string>
        <key>name</key>
        <string>meta.return.type.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#basic-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#property-access</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.parameters.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#assignments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#basic-types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#property-access</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type-name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-name</string>
          </dict>
        </array>
      </dict>
      <key>slice</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.slice.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\?</string>
            <key>name</key>
            <string>keyword.operator.array.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.operator.slice.odin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attribute</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#procedure-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#distinct-type-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#case-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-label</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>string-escaped-char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(x1b|e|033)\[[0-9;]*m</string>
            <key>name</key>
            <string>constant.character.escape.ansi-color-sequence.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\(["'\\abefnrtuv]|x\h{2}|u\h{4}|U\h{8}|[0-7]{3})</string>
            <key>name</key>
            <string>constant.character.escape.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%([%E-HMTUXb-imo-tvwxz])</string>
            <key>name</key>
            <string>constant.character.escape.placeholders.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%(\d*\.?\d*f)</string>
            <key>name</key>
            <string>constant.character.escape.placeholders-floats.odin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unknown-escape.odin</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-escaped-char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.odin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-escaped-char</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>`</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.odin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.raw.odin</string>
          </dict>
        </array>
      </dict>
      <key>ternary</key>
      <dict>
        <key>begin</key>
        <string>\?</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.ternary.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>:</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.ternary.odin</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.ternary.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>type-annotation</key>
      <dict>
        <key>begin</key>
        <string>(?:([A-Z_a-z]\w*)\s*(,)\s*)?(?:([A-Z_a-z]\w*)\s*(,)\s*)?([A-Z_a-z]\w*)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.odin</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.type.annotation.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^|[),:;=]|for|switch|if|\{)</string>
        <key>name</key>
        <string>meta.type.annotation.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>type-assignment</key>
      <dict>
        <key>begin</key>
        <string>\b([A-Z_a-z]\w*)\s*(:\s*:)\s*(?=(struct|union|enum|bit_set|bit_field)\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^)|(?&lt;=})</string>
        <key>name</key>
        <string>meta.definition.variable.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>type-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.type.declaration.odin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#map-bitset</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(proc|struct|union|enum|bit_field)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=^|[),;])|(?&lt;=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#return-type-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#object-definition</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#basic-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#slice</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.typeparameters.begin.odin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.typeparameters.end.odin</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-declaration</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#property-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-name</string>
          </dict>
        </array>
      </dict>
      <key>type-name</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>name</key>
        <string>entity.name.type.odin</string>
      </dict>
      <key>type-parameter</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameter.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$)\s*\b([A-Z_a-z]\w*)\b</string>
      </dict>
      <key>union-member-access</key>
      <dict>
        <key>begin</key>
        <string>([A-Z_a-z]\w*)\s*(\.)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.object.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.odin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.odin</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declaration</string>
          </dict>
        </array>
      </dict>
      <key>union-non-nil-access</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.object.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.optional.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([A-Z_a-z]\w*)\s*(\.)\s*(\?)</string>
      </dict>
      <key>variable-assignment</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.odin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.odin</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.name.odin</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.odin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(?:([A-Z_a-z]\w*)\s*(,)\s*)?(?:([A-Z_a-z]\w*)\s*(,)\s*)?([A-Z_a-z]\w*)\s*(:\s*=)</string>
        <key>name</key>
        <string>meta.definition.variable.odin</string>
      </dict>
      <key>variable-name</key>
      <dict>
        <key>match</key>
        <string>\b[A-Z_a-z]\w*\b</string>
        <key>name</key>
        <string>variable.name.odin</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.odin</string>
  </dict>
</plist>