<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>razor</string>
      <string>cshtml</string>
    </array>
    <key>injections</key>
    <dict>
      <key>source.cs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline-template</string>
          </dict>
        </array>
      </dict>
      <key>string.quoted.double.html</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#explicit-razor-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression</string>
          </dict>
        </array>
      </dict>
      <key>string.quoted.single.html</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#explicit-razor-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>name</key>
    <string>razor</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#razor-control-structures</string>
      </dict>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>addTagHelper-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.addTagHelper</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tagHelper-directive-argument</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(addTagHelper)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>attribute-directive</key>
      <dict>
        <key>begin</key>
        <string>(@)(attribute)\b\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.attribute</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=])|$</string>
        <key>name</key>
        <string>meta.directive</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#attribute-section</string>
          </dict>
        </array>
      </dict>
      <key>await-prefix</key>
      <dict>
        <key>match</key>
        <string>(await)\s+</string>
        <key>name</key>
        <string>keyword.other.await.cs</string>
      </dict>
      <key>balanced-brackets-csharp</key>
      <dict>
        <key>begin</key>
        <string>(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(])</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.close.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>razor.test.balanced.brackets</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
      </dict>
      <key>balanced-parenthesis-csharp</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>razor.test.balanced.parenthesis</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
      </dict>
      <key>catch-clause</key>
      <dict>
        <key>begin</key>
        <string>(?:^|(?&lt;=}))\s*(catch)\b\s*?(?=[\n({])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.try.catch.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.catch.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#catch-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs#when-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>catch-condition</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.cs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.cs#type</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>entity.name.variable.local.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;type-name&gt;(?:(?:(?&lt;identifier&gt;@?[_[:alpha:]][_[:alnum:]]*)\s*::\s*)?(?&lt;name-and-type-args&gt;\g&lt;identifier&gt;\s*(?&lt;type-args&gt;\s*&lt;(?:[^&lt;&gt;]|\g&lt;type-args&gt;)+&gt;\s*)?)(?:\s*\.\s*\g&lt;name-and-type-args&gt;)*|(?&lt;tuple&gt;\s*\((?:[^()]|\g&lt;tuple&gt;)+\)))(?:\s*\?\s*)?(?:\s*\[(?:\s*,\s*)*]\s*)*)\s*(?:(\g&lt;identifier&gt;)\b)?</string>
          </dict>
        </array>
      </dict>
      <key>code-directive</key>
      <dict>
        <key>begin</key>
        <string>(@)(code)((?=\{)|\s+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.code</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|\s</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#directive-codeblock</string>
          </dict>
        </array>
      </dict>
      <key>csharp-code-block</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.close.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.razor.csharp.codeblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>csharp-condition</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.cs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#local-variable-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs#punctuation-comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs#punctuation-semicolon</string>
          </dict>
        </array>
      </dict>
      <key>directive-codeblock</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.open</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cs</string>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.razor.directive.codeblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#class-or-struct-members</string>
          </dict>
        </array>
      </dict>
      <key>directive-markupblock</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.open</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.razor.directive.markblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>directives</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#code-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#page-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#addTagHelper-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#removeTagHelper-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tagHelperPrefix-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#model-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inherits-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implements-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#namespace-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inject-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#section-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#layout-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#using-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rendermode-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#preservewhitespace-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typeparam-directive</string>
          </dict>
        </array>
      </dict>
      <key>do-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(do)\b\s</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.do.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.do.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>do-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(do)\b\s</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.do.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.do.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>else-part</key>
      <dict>
        <key>begin</key>
        <string>(?:^|(?&lt;=}))\s*(else)\b\s*?(?: (if))?\s*?(?=[\n({])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.else.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.if.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.else.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>escaped-transition</key>
      <dict>
        <key>match</key>
        <string>@@</string>
        <key>name</key>
        <string>constant.character.escape.razor.transition</string>
      </dict>
      <key>explicit-razor-expression</key>
      <dict>
        <key>begin</key>
        <string>(@)\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.cshtml</string>
          </dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.cshtml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.expression.explicit.cshtml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#expression</string>
          </dict>
        </array>
      </dict>
      <key>finally-clause</key>
      <dict>
        <key>begin</key>
        <string>(?:^|(?&lt;=}))\s*(finally)\b\s*?(?=[\n{])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.try.finally.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.finally.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>for-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(for)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.for.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.for.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>for-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(for)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.for.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.for.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>foreach-condition</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.cs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.var.cs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.cs#type</string>
                  </dict>
                </array>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>entity.name.variable.local.cs</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>keyword.control.loop.in.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:\b(var)\b|(?&lt;type-name&gt;(?:(?:(?&lt;identifier&gt;@?[_[:alpha:]][_[:alnum:]]*)\s*::\s*)?(?&lt;name-and-type-args&gt;\g&lt;identifier&gt;\s*(?&lt;type-args&gt;\s*&lt;(?:[^&lt;&gt;]|\g&lt;type-args&gt;)+&gt;\s*)?)(?:\s*\.\s*\g&lt;name-and-type-args&gt;)*|(?&lt;tuple&gt;\s*\((?:[^()]|\g&lt;tuple&gt;)+\)))(?:\s*\?\s*)?(?:\s*\[(?:\s*,\s*)*]\s*)*))\s+(\g&lt;identifier&gt;)\s+\b(in)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.var.cs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.cs#tuple-declaration-deconstruction-element-list</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.loop.in.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:\b(var)\b\s*)?(?&lt;tuple&gt;\((?:[^()]|\g&lt;tuple&gt;)+\))\s+\b(in)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs#expression</string>
          </dict>
        </array>
      </dict>
      <key>foreach-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(await\s+)?(foreach)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#await-prefix</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.foreach.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.foreach.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#foreach-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>foreach-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@)(await\s+)?)(foreach)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#await-prefix</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.foreach.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.foreach.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#foreach-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>functions-directive</key>
      <dict>
        <key>begin</key>
        <string>(@)(functions)((?=\{)|\s+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.functions</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|\s</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#directive-codeblock</string>
          </dict>
        </array>
      </dict>
      <key>if-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(if)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.if.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.if.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>if-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(if)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.if.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.if.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>implements-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.implements</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(implements)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>implicit-expression</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;![[:alpha:][:alnum:]])(@)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cs</string>
        <key>end</key>
        <string>(?=[]"')&lt;&gt;{}\s])</string>
        <key>name</key>
        <string>meta.expression.implicit.cshtml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#await-prefix</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-body</string>
          </dict>
        </array>
      </dict>
      <key>implicit-expression-accessor</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=\.)[_[:alpha:]][_[:alnum:]]*</string>
        <key>name</key>
        <string>variable.other.object.property.cs</string>
      </dict>
      <key>implicit-expression-accessor-start</key>
      <dict>
        <key>begin</key>
        <string>([_[:alpha:]][_[:alnum:]]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.object.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[]"')&lt;&gt;{}\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#implicit-expression-continuation</string>
          </dict>
        </array>
      </dict>
      <key>implicit-expression-body</key>
      <dict>
        <key>end</key>
        <string>(?=[]"')&lt;&gt;{}\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#implicit-expression-invocation-start</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-accessor-start</string>
          </dict>
        </array>
      </dict>
      <key>implicit-expression-continuation</key>
      <dict>
        <key>end</key>
        <string>(?=[]"')&lt;&gt;{}\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#balanced-parenthesis-csharp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#balanced-brackets-csharp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-accessor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-extension</string>
          </dict>
        </array>
      </dict>
      <key>implicit-expression-dot-operator</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\.)(?=[_[:alpha:]][_[:alnum:]]*)</string>
      </dict>
      <key>implicit-expression-invocation</key>
      <dict>
        <key>match</key>
        <string>(?&lt;=\.)[_[:alpha:]][_[:alnum:]]*(?=\()</string>
        <key>name</key>
        <string>entity.name.function.cs</string>
      </dict>
      <key>implicit-expression-invocation-start</key>
      <dict>
        <key>begin</key>
        <string>([_[:alpha:]][_[:alnum:]]*)(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[]"')&lt;&gt;{}\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#implicit-expression-continuation</string>
          </dict>
        </array>
      </dict>
      <key>implicit-expression-null-conditional-operator</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.null-conditional.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\?)(?=[.\[])</string>
      </dict>
      <key>implicit-expression-null-forgiveness-operator</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(!)(?=\.[_[:alpha:]][_[:alnum:]]*|[(?\[])</string>
      </dict>
      <key>implicit-expression-operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#implicit-expression-dot-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-null-conditional-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression-null-forgiveness-operator</string>
          </dict>
        </array>
      </dict>
      <key>inherits-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.inherits</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(inherits)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>inject-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.inject</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.property.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(inject)\s*([\S\s]+?)?\s*([_[:alpha:]][_[:alnum:]]*)?\s*(?=$)</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>inline-template</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline-template-void-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline-template-non-void-tag</string>
          </dict>
        </array>
      </dict>
      <key>inline-template-non-void-tag</key>
      <dict>
        <key>begin</key>
        <string>(@)(&lt;)(!)?([^/&gt;\s]+)(?=\s|/?&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.razor.tagHelperOptOut</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&lt;/)(\4)\s*(&gt;)|(/&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=&gt;)(?!$)</string>
            <key>end</key>
            <string>(?=&lt;/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline-template</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#wellformed-html</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#razor-control-structures</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-control-structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic#attribute</string>
          </dict>
        </array>
      </dict>
      <key>inline-template-void-tag</key>
      <dict>
        <key>begin</key>
        <string>(?i)(@)(&lt;)(!)?(area|base|br|col|command|embed|hr|img|input|keygen|link|meta|param|source|track|wbr)(?=\s|/?&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.razor.tagHelperOptOut</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>/?&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.structure.$4.void.html</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#razor-control-structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic#attribute</string>
          </dict>
        </array>
      </dict>
      <key>layout-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.layout</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(layout)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>lock-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(lock)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.lock.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.lock.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>lock-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(lock)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.lock.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.lock.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>model-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.model</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(model)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>namespace-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.namespace</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#namespace-directive-argument</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(namespace)\s+(\S+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>namespace-directive-argument</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.namespace.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([_[:alpha:]][_[:alnum:]]*)(\.)?</string>
      </dict>
      <key>non-void-tag</key>
      <dict>
        <key>begin</key>
        <string>(?=&lt;(!)?([^/&gt;\s]+)(\s|/?&gt;))</string>
        <key>end</key>
        <string>(&lt;/)(\2)\s*(&gt;)|(/&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(&lt;)(!)?([^/&gt;\s]+)(?=\s|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.character.escape.razor.tagHelperOptOut</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=/?&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#razor-control-structures</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic#attribute</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>&gt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=&lt;/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#wellformed-html</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>optionally-transitioned-csharp-control-structures</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#using-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#else-part</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#foreach-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#while-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#switch-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lock-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#do-statement-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#try-statement-with-optional-transition</string>
          </dict>
        </array>
      </dict>
      <key>optionally-transitioned-razor-control-structures</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#razor-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#explicit-razor-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#directives</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionally-transitioned-csharp-control-structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression</string>
          </dict>
        </array>
      </dict>
      <key>page-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.page</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#string-literal</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(page)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>preservewhitespace-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.preservewhitespace</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#boolean-literal</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(preservewhitespace)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>razor-codeblock</key>
      <dict>
        <key>begin</key>
        <string>(@)(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.open</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>source.cs</string>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.codeblock.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.razor.codeblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>razor-codeblock-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#text-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline-template</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#wellformed-html</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-single-line-markup</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionally-transitioned-razor-control-structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
      </dict>
      <key>razor-comment</key>
      <dict>
        <key>begin</key>
        <string>(@)(\*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.comment.star</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>comment.block.razor</string>
        <key>end</key>
        <string>(\*)(@)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.comment.star</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.comment.razor</string>
      </dict>
      <key>razor-control-structures</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#razor-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#explicit-razor-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escaped-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#directives</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#transitioned-csharp-control-structures</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#implicit-expression</string>
          </dict>
        </array>
      </dict>
      <key>razor-single-line-markup</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.singleLineMarkup</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#razor-control-structures</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@:)([^$]*)$</string>
      </dict>
      <key>removeTagHelper-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.removeTagHelper</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tagHelper-directive-argument</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(removeTagHelper)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>rendermode-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.rendermode</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(rendermode)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>section-directive</key>
      <dict>
        <key>begin</key>
        <string>(@)(section)\b\s+([_[:alpha:]][_[:alnum:]]*)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.section</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.razor.directive.sectionName</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>name</key>
        <string>meta.directive.block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#directive-markupblock</string>
          </dict>
        </array>
      </dict>
      <key>switch-code-block</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.open.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.close.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.razor.csharp.codeblock.switch</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#switch-label</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>switch-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(switch)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.switch.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.switch.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#switch-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>switch-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(switch)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.switch.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.switch.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#switch-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>tagHelper-directive-argument</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#unquoted-string-argument</string>
          </dict>
        </array>
      </dict>
      <key>tagHelperPrefix-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.tagHelperPrefix</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tagHelper-directive-argument</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(tagHelperPrefix)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>text-tag</key>
      <dict>
        <key>begin</key>
        <string>(&lt;text\s*&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.cshtml.transition.textTag.open</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&lt;/text&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.cshtml.transition.textTag.close</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#wellformed-html</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>transition</key>
      <dict>
        <key>match</key>
        <string>@</string>
        <key>name</key>
        <string>keyword.control.cshtml.transition</string>
      </dict>
      <key>transitioned-csharp-control-structures</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#using-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#else-part</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#foreach-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#for-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#while-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#switch-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lock-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#do-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#try-statement</string>
          </dict>
        </array>
      </dict>
      <key>try-block</key>
      <dict>
        <key>begin</key>
        <string>(@)(try)\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.try.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.try.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>try-block-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(try)\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.try.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.try.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>try-statement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#try-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#finally-clause</string>
          </dict>
        </array>
      </dict>
      <key>try-statement-with-optional-transition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#try-block-with-optional-transition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#catch-clause</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#finally-clause</string>
          </dict>
        </array>
      </dict>
      <key>typeparam-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.directive.typeparam</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(typeparam)\s+([^$]+)?</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>unquoted-string-argument</key>
      <dict>
        <key>match</key>
        <string>[^$]+</string>
        <key>name</key>
        <string>string.quoted.double.cs</string>
      </dict>
      <key>using-alias-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.alias.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.cs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>([_[:alpha:]][_[:alnum:]]*)\b\s*(=)\s*(.+)\s*</string>
      </dict>
      <key>using-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using.cs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#using-static-directive</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#using-alias-directive</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#using-standard-directive</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.control.razor.optionalSemicolon</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(@)(using)\b\s+(?![(\s])(.+?)?(;)?$</string>
        <key>name</key>
        <string>meta.directive</string>
      </dict>
      <key>using-standard-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.namespace.cs</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([_[:alpha:]][_[:alnum:]]*)\s*</string>
      </dict>
      <key>using-statement</key>
      <dict>
        <key>begin</key>
        <string>(@)(using)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.using.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>using-statement-with-optional-transition</key>
      <dict>
        <key>begin</key>
        <string>(?:^\s*|(@))(using)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(?&lt;=;)|(?=^\s*})</string>
        <key>name</key>
        <string>meta.statement.using.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
      <key>using-static-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.static.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs#type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(static)\b\s+(.+)</string>
      </dict>
      <key>void-tag</key>
      <dict>
        <key>begin</key>
        <string>(?i)(&lt;)(!)?(area|base|br|col|command|embed|hr|img|input|keygen|link|meta|param|source|track|wbr)(?=\s|/?&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.razor.tagHelperOptOut</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>/?&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.structure.$3.void.html</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>text.html.basic#attribute</string>
          </dict>
        </array>
      </dict>
      <key>wellformed-html</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#void-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#non-void-tag</string>
          </dict>
        </array>
      </dict>
      <key>while-statement</key>
      <dict>
        <key>begin</key>
        <string>(?:(@)|^\s*|(?&lt;=})\s*)(while)\b\s*(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#transition</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.while.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})|(;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.statement.while.razor</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#csharp-condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#csharp-code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#razor-codeblock-body</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.aspnetcorerazor</string>
  </dict>
</plist>