<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>rel</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#single-line-comment-consuming-line-ending</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#deprecated-temporary</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#symbols</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#otherkeywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rel</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rel</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.documentation.rel</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#docblock</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(/\*)(?:\s*((@)internal)(?=\s|(\*/)))?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rel</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.internaldeclaration.rel</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.decorator.internaldeclaration.rel</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rel</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.rel</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>doc"""</string>
            <key>end</key>
            <string>"""</string>
            <key>name</key>
            <string>comment.block.documentation.rel</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[\t ]+)?((//)(?:\s*((@)internal)(?=\s|$))?)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.rel</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.rel</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rel</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.type.internaldeclaration.rel</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.decorator.internaldeclaration.rel</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.line.double-slash.rel</string>
            <key>end</key>
            <string>(?=$)</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((true|false))\b</string>
            <key>name</key>
            <string>constant.language.rel</string>
          </dict>
        </array>
      </dict>
      <key>deprecated-temporary</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>@inspect</string>
            <key>name</key>
            <string>keyword.other.rel</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((def|entity|bound|include|ic|forall|exists|[∀∃]|return|module|^end))\b|(((&lt;)?\|(&gt;)?)|[∀∃])</string>
            <key>name</key>
            <string>keyword.control.rel</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((if|then|else|and|or|not|eq|neq|lt|lt_eq|gt|gt_eq))\b|([-%*+/=^÷]|!=|[&lt;≠]|&lt;=|[&gt;≤]|&gt;=|[\&amp;≥])|\s+(end)</string>
            <key>name</key>
            <string>keyword.other.rel</string>
          </dict>
        </array>
      </dict>
      <key>otherkeywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*(@inline)\s*|\s*(@auto_number)\s*|\s*(function)\s|\b((implies|select|from|∈|where|for|in))\b|(((&lt;)?\|(&gt;)?)|∈)</string>
            <key>name</key>
            <string>keyword.other.rel</string>
          </dict>
        </array>
      </dict>
      <key>single-line-comment-consuming-line-ending</key>
      <dict>
        <key>begin</key>
        <string>(^[\t ]+)?((//)(?:\s*((@)internal)(?=\s|$))?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.comment.leading.rel</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.rel</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.rel</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>storage.type.internaldeclaration.rel</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.decorator.internaldeclaration.rel</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>comment.line.double-slash.rel</string>
        <key>end</key>
        <string>(?=^)</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.rel</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.rel</string>
          </dict>
        </array>
      </dict>
      <key>symbols</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(:[$\[_[:alpha:]](]|[$_[:alnum:]]*))</string>
            <key>name</key>
            <string>variable.parameter.rel</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((Symbol|Char|Bool|Rational|FixedDecimal|Float16|Float32|Float64|Int8|Int16|Int32|Int64|Int128|UInt8|UInt16|UInt32|UInt64|UInt128|Date|DateTime|Day|Week|Month|Year|Nanosecond|Microsecond|Millisecond|Second|Minute|Hour|FilePos|HashValue|AutoNumberValue))\b</string>
            <key>name</key>
            <string>entity.name.type.rel</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.rel</string>
  </dict>
</plist>