<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>rst</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#body</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>anchor</key>
      <dict>
        <key>match</key>
        <string>^\.{2}\s+(_[^:]+:)\s*</string>
        <key>name</key>
        <string>entity.name.tag.anchor</string>
      </dict>
      <key>block</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+\S+::)(.*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1\s|\s*$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
      </dict>
      <key>block-comment</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)\.{2}(\s+|$)</string>
        <key>end</key>
        <string>^(?:(?=\S)|\s*$)</string>
        <key>name</key>
        <string>comment.block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s{3,}(?=\S)</string>
            <key>name</key>
            <string>comment.block</string>
            <key>while</key>
            <string>^(?:\s{3}.*|\s*$)</string>
          </dict>
        </array>
      </dict>
      <key>block-param</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(:param\s+(.+?):)(?:\s|$)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\b(0x[A-Fa-f\d]+|\d+)\b</string>
                    <key>name</key>
                    <string>constant.numeric</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#inline-markup</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>(:.+?:)(?:$|\s+(.*))</string>
          </dict>
        </array>
      </dict>
      <key>blocks</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#domains</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctest</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-cpp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-py</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-console</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-javascript</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-yaml</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-cmake</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-kconfig</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-ruby</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block-dts</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctest-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#raw-html</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
        </array>
      </dict>
      <key>body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#title</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline-markup</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#anchor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#replace-include</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#footnote</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#substitution</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blocks</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#table</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#simple-table</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#options-list</string>
          </dict>
        </array>
      </dict>
      <key>bold</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;=["'(&lt;\[{\s]|^)\*{2}[^*\s]</string>
        <key>end</key>
        <string>\*{2}|^\s*$</string>
        <key>name</key>
        <string>markup.bold</string>
      </dict>
      <key>citation</key>
      <dict>
        <key>applyEndPatternLast</key>
        <integer>0</integer>
        <key>begin</key>
        <string>(?&lt;=["'(&lt;\[{\s]|^)`[^`\s]</string>
        <key>end</key>
        <string>`_{0,2}|^\s*$</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>code-block</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-cmake</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(cmake)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.cmake</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cmake</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-console</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(console|shell|bash)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.console</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.shell</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-cpp</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(c|c\+\+|cpp|C|C\+\+|CPP|Cpp)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.cpp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.cpp</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-dts</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(dts|DTS|devicetree)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.dts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.dts</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-javascript</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(javascript)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.js</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-kconfig</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*([Kk]config)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.kconfig</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.kconfig</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-py</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(python)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.py</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.python</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-ruby</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(ruby)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.ruby</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ruby</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>code-block-yaml</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+(code(?:|-block))::)\s*(ya?ml)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.codeblock.yaml</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.yaml</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>doctest</key>
      <dict>
        <key>begin</key>
        <string>^(&gt;&gt;&gt;)\s*(.*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>^\s*$</string>
      </dict>
      <key>doctest-block</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+doctest::)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.python</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>domain-auto</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+auto(?:class|module|exception|function|decorator|data|method|attribute|property)::)\s*(.*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.py</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>domain-cpp</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+c(?:pp|):(?:class|struct|function|member|var|type|enum|enum-struct|enum-class|enumerator|union|concept)::)\s*(?:(@\w+)|(.*))</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
          <key>4</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cpp</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>domain-js</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+js:\w+::)\s*(.*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\1[\t ]|$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
      </dict>
      <key>domain-py</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+py:(?:module|function|data|exception|class|attribute|property|method|staticmethod|classmethod|decorator|decoratormethod)::)\s*(.*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#body</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>domains</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#domain-cpp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#domain-py</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#domain-auto</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#domain-js</string>
          </dict>
        </array>
      </dict>
      <key>escaped</key>
      <dict>
        <key>match</key>
        <string>\\.</string>
        <key>name</key>
        <string>constant.character.escape</string>
      </dict>
      <key>footnote</key>
      <dict>
        <key>match</key>
        <string>^\s*\.{2}\s+\[(?:[-.\w]+|[#*]|#\w+)]\s+</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>footnote-ref</key>
      <dict>
        <key>match</key>
        <string>\[(?:[-.\w]+|[#*])]_</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>ignore</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>'[*`]+'</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;[*`]+&gt;</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\{[*`]+}</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\([*`]+\)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\[[*`]+]</string>
          </dict>
          <dict>
            <key>match</key>
            <string>"[*`]+"</string>
          </dict>
        </array>
      </dict>
      <key>inline-markup</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escaped</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ignore</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ref</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#monospaced</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#citation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bold</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#italic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#macro</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#reference</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#footnote-ref</string>
          </dict>
        </array>
      </dict>
      <key>italic</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;=["'(&lt;\[{\s]|^)\*[^*\s]</string>
        <key>end</key>
        <string>\*|^\s*$</string>
        <key>name</key>
        <string>markup.italic</string>
      </dict>
      <key>line-block</key>
      <dict>
        <key>match</key>
        <string>^\|\s+</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <key>list</key>
      <dict>
        <key>match</key>
        <string>^\s*(\d+\.|\* -|[#A-Za-z]\.|[CIMVXcimvx]+\.|\(\d+\)|\d+\)|[-*+])\s+</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <key>literal</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(:\S+:)(`.*?`\\?)</string>
      </dict>
      <key>literal-block</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(.*)(::)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline-markup</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>macro</key>
      <dict>
        <key>match</key>
        <string>\|[^|]+\|</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>monospaced</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;=["'(&lt;\[{\s]|^)``[^`\s]</string>
        <key>end</key>
        <string>``|^\s*$</string>
        <key>name</key>
        <string>string.interpolated</string>
      </dict>
      <key>options-list</key>
      <dict>
        <key>match</key>
        <string>(?:(?:^|,\s+)(?:[-+]\w|--?[A-Za-z][-\w]+|/\w+)(?:[ =](?:\w+|&lt;[^&lt;&gt;]+?&gt;))?)+(?=  |\t|$)</string>
        <key>name</key>
        <string>variable.parameter</string>
      </dict>
      <key>raw-html</key>
      <dict>
        <key>begin</key>
        <string>^(\s*)(\.{2}\s+raw\s*::)\s+(html)\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.derivative</string>
          </dict>
        </array>
        <key>while</key>
        <string>^(?:\1(?=\s)|\s*$)</string>
      </dict>
      <key>ref</key>
      <dict>
        <key>begin</key>
        <string>(:ref:)`</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>end</key>
        <string>`|^\s*$</string>
        <key>name</key>
        <string>entity.name.tag</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&lt;.*?&gt;</string>
            <key>name</key>
            <string>markup.underline.link</string>
          </dict>
        </array>
      </dict>
      <key>reference</key>
      <dict>
        <key>match</key>
        <string>[-\w]*[-A-Za-z\d]__?\b</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>replace-include</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(\.{2})\s+(\|[^|]+\|)\s+(replace::)</string>
      </dict>
      <key>simple-table</key>
      <dict>
        <key>match</key>
        <string>^[=\s]+$</string>
        <key>name</key>
        <string>keyword.control.table</string>
      </dict>
      <key>substitution</key>
      <dict>
        <key>match</key>
        <string>^\.{2}\s*\|([^|]+)\|</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <key>table</key>
      <dict>
        <key>begin</key>
        <string>^\s*\+[-+=]+\+\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.table</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?![+|])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[-+=|]</string>
            <key>name</key>
            <string>keyword.control.table</string>
          </dict>
        </array>
      </dict>
      <key>title</key>
      <dict>
        <key>match</key>
        <string>^(\*{3,}|#{3,}|={3,}|~{3,}|\+{3,}|-{3,}|`{3,}|\^{3,}|:{3,}|"{3,}|_{3,}|'{3,})$</string>
        <key>name</key>
        <string>markup.heading</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.rst</string>
  </dict>
</plist>