<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>rust</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(&lt;)(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.angle.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.square.rust</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.angle.rust</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#gtypes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lvariables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lifetimes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.macro.dollar.rust</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.crate.rust</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.metavariable.rust</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.key-value.rust</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>variable.other.metavariable.specifier.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$)((crate)|([A-Z]\w*))(\s*(:)\s*(block|expr(?:_2021)?|ident|item|lifetime|literal|meta|pat(?:_param)?|path|stmt|tt|ty|vis)\b)?</string>
        <key>name</key>
        <string>meta.macro.metavariable.type.rust</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.macro.dollar.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.metavariable.name.rust</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.key-value.rust</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.metavariable.specifier.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$)([a-z]\w*)(\s*(:)\s*(block|expr(?:_2021)?|ident|item|lifetime|literal|meta|pat(?:_param)?|path|stmt|tt|ty|vis)\b)?</string>
        <key>name</key>
        <string>meta.macro.metavariable.rust</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.macro.rules.rust</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.macro.rust</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.macro.rust</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.curly.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(macro_rules!)\s+(([0-9_a-z]+)|([A-Z][0-9_a-z]*))\s+(\{)</string>
        <key>name</key>
        <string>meta.macro.rules.rust</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.module.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(mod)\s+((?:r#(?!crate|[Ss]elf|super))?[a-z][0-9A-Z_a-z]*)</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(extern)\s+(crate)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.crate.rust</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.semi.rust</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.import.rust</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(use)\s</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.rust</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.semi.rust</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.use.rust</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#namespaces</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lvariables</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#block-comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#lvariables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#gtypes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#lifetimes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#macros</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespaces</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attributes</key>
      <dict>
        <key>begin</key>
        <string>(#)(!?)(\[)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.attribute.rust</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.attribute.rust</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.brackets.attribute.rust</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.attribute.rust</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lifetimes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#gtypes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
        </array>
      </dict>
      <key>block-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.rust</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*(?!\*)</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(///).*$</string>
            <key>name</key>
            <string>comment.line.documentation.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$</string>
            <key>name</key>
            <string>comment.line.double-slash.rust</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z]{2}[0-9A-Z_]*\b</string>
            <key>name</key>
            <string>constant.other.caps.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.other.caps.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(const)\s+([A-Z][0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dot.decimal.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.exponent.rust</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.exponent.sign.rust</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.decimal.exponent.mantissa.rust</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b\d[_\d]*(\.?)[_\d]*(?:([Ee])([-+]?)([_\d]+))?(f32|f64|i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b0x[A-F_a-f\d]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
            <key>name</key>
            <string>constant.numeric.hex.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b0o[0-7_]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
            <key>name</key>
            <string>constant.numeric.oct.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b0b[01_]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
            <key>name</key>
            <string>constant.numeric.bin.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.bool.rust</string>
          </dict>
        </array>
      </dict>
      <key>escapes</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.backslash.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.bit.rust</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.rust</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.punctuation.rust</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape.unicode.punctuation.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\\)(?:(x[0-7][A-Fa-f\d])|(u(\{)[A-Fa-f\d]{4,6}(}))|.)</string>
        <key>name</key>
        <string>constant.character.escape.rust</string>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(pub)(\()</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(fn)\s+((?:r#(?!crate|[Ss]elf|super))?[0-9A-Z_a-z]+)((\()|(&lt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.fn.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rust</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\{)|(;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.semi.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.definition.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lvariables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#gtypes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lifetimes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#macros</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#namespaces</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((?:r#(?!crate|[Ss]elf|super))?[0-9A-Z_a-z]+)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.call.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lvariables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#gtypes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lifetimes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#macros</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#namespaces</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>((?:r#(?!crate|[Ss]elf|super))?[0-9A-Z_a-z]+)(?=::&lt;.*&gt;\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.call.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lvariables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#gtypes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lifetimes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#macros</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#namespaces</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>gtypes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(Some|None)\b</string>
            <key>name</key>
            <string>entity.name.type.option.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(Ok|Err)\b</string>
            <key>name</key>
            <string>entity.name.type.result.rust</string>
          </dict>
        </array>
      </dict>
      <key>interpolations</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.interpolation.rust</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.interpolation.rust</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\{)[^"{}]*(})</string>
        <key>name</key>
        <string>meta.interpolation.rust</string>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(await|break|continue|do|else|for|if|loop|match|return|try|while|yield)\b</string>
            <key>name</key>
            <string>keyword.control.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(extern|let|macro|mod)\b</string>
            <key>name</key>
            <string>keyword.other.rust storage.type.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(const)\b</string>
            <key>name</key>
            <string>storage.modifier.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(type)\b</string>
            <key>name</key>
            <string>keyword.declaration.type.rust storage.type.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(enum)\b</string>
            <key>name</key>
            <string>keyword.declaration.enum.rust storage.type.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(trait)\b</string>
            <key>name</key>
            <string>keyword.declaration.trait.rust storage.type.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(struct)\b</string>
            <key>name</key>
            <string>keyword.declaration.struct.rust storage.type.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(abstract|static)\b</string>
            <key>name</key>
            <string>storage.modifier.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(as|async|become|box|dyn|move|final|gen|impl|in|override|priv|pub|ref|typeof|union|unsafe|unsized|use|virtual|where)\b</string>
            <key>name</key>
            <string>keyword.other.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bfn\b</string>
            <key>name</key>
            <string>keyword.other.fn.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bcrate\b</string>
            <key>name</key>
            <string>keyword.other.crate.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bmut\b</string>
            <key>name</key>
            <string>storage.modifier.mut.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\^|]|\|\||&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
            <key>name</key>
            <string>keyword.operator.logical.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;(?![\&amp;=])</string>
            <key>name</key>
            <string>keyword.operator.borrow.and.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:[-%\&amp;*+/^|]|&lt;&lt;|&gt;&gt;)=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![&lt;&gt;])=(?![=&gt;])</string>
            <key>name</key>
            <string>keyword.operator.assignment.equal.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
            <key>name</key>
            <string>keyword.operator.comparison.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(([%+]|(\*(?!\w)))(?!=))|(-(?!&gt;))|(/(?!/))</string>
            <key>name</key>
            <string>keyword.operator.math.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.square.rust</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.rust</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.comparison.rust</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.rust</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.square.rust</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:\b|(?:(\))|(])|(})))[\t ]+([&lt;&gt;])[\t ]+(?:\b|(?:(\()|(\[)|(\{)))</string>
          </dict>
          <dict>
            <key>match</key>
            <string>::</string>
            <key>name</key>
            <string>keyword.operator.namespace.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.dereference.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(\*)(?=\w+)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@</string>
            <key>name</key>
            <string>keyword.operator.subpattern.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.(?!\.)</string>
            <key>name</key>
            <string>keyword.operator.access.dot.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.{2}([.=])?</string>
            <key>name</key>
            <string>keyword.operator.range.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:(?!:)</string>
            <key>name</key>
            <string>keyword.operator.key-value.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;|&lt;-</string>
            <key>name</key>
            <string>keyword.operator.arrow.skinny.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.fat.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$</string>
            <key>name</key>
            <string>keyword.operator.macro.dollar.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?</string>
            <key>name</key>
            <string>keyword.operator.question.rust</string>
          </dict>
        </array>
      </dict>
      <key>lifetimes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.lifetime.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.lifetime.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(')([A-Z_a-z][0-9A-Z_a-z]*)(?!')\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.borrow.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.lifetime.rust</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.lifetime.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(&amp;)(')([A-Z_a-z][0-9A-Z_a-z]*)(?!')\b</string>
          </dict>
        </array>
      </dict>
      <key>lvariables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[Ss]elf\b</string>
            <key>name</key>
            <string>variable.language.self.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bsuper\b</string>
            <key>name</key>
            <string>variable.language.super.rust</string>
          </dict>
        </array>
      </dict>
      <key>macros</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.macro.rust</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.macro.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(([_a-z][0-9A-Z_a-z]*!)|([A-Z_][0-9A-Z_a-z]*!))</string>
            <key>name</key>
            <string>meta.macro.rust</string>
          </dict>
        </array>
      </dict>
      <key>namespaces</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.namespace.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.namespace.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![0-9A-Z_a-z])([0-9A-Z_a-z]+)((?&lt;!s(?:uper|elf))::)</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.comma.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[{}]</string>
            <key>name</key>
            <string>punctuation.brackets.curly.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[()]</string>
            <key>name</key>
            <string>punctuation.brackets.round.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.semi.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[]\[]</string>
            <key>name</key>
            <string>punctuation.brackets.square.rust</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!=)[&lt;&gt;]</string>
            <key>name</key>
            <string>punctuation.brackets.angle.rust</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(b?)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.byte.raw.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escapes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#interpolations</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(b?r)(#*)(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.byte.raw.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.raw.rust</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")(\2)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.raw.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.rust</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(b)?(')</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.byte.raw.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.char.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.char.rust</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.char.rust</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#escapes</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.numeric.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![A-Za-z])(f32|f64|i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(_?[A-Z][0-9A-Z_a-z]*)(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.rust</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.angle.rust</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lvariables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#lifetimes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(bool|char|str)\b</string>
            <key>name</key>
            <string>entity.name.type.primitive.rust</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.trait.rust storage.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.trait.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(trait)\s+(_?[A-Z][0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.struct.rust storage.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.struct.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(struct)\s+(_?[A-Z][0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.enum.rust storage.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.enum.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(enum)\s+(_?[A-Z][0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.type.rust storage.type.rust</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.declaration.rust</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(type)\s+(_?[A-Z][0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b_?[A-Z][0-9A-Z_a-z]*\b(?!!)</string>
            <key>name</key>
            <string>entity.name.type.rust</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?&lt;!(?&lt;!\.)\.)(?:r#(?!(crate|[Ss]elf|super)))?[0-9_a-z]+\b</string>
            <key>name</key>
            <string>variable.other.rust</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.rust</string>
  </dict>
</plist>