<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>sdbl</string>
      <string>query</string>
    </array>
    <key>firstLineMatch</key>
    <string>(?i)Выбрать|Select(\s+Разрешенные|\s+Allowed)?(\s+Различные|\s+Distinct)?(\s+Первые|\s+Top)?.*</string>
    <key>name</key>
    <string>sdbl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>^(\s*//.*)$</string>
        <key>name</key>
        <string>comment.line.double-slash.sdbl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.sdbl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"(?!")</string>
        <key>name</key>
        <string>string.quoted.double.sdbl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>""</string>
            <key>name</key>
            <string>constant.character.escape.sdbl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^(\s*//.*)$</string>
            <key>name</key>
            <string>comment.line.double-slash.sdbl</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Неопределено|Undefined|Истина|True|Ложь|False|NULL)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>constant.language.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=[^.а-яё\w]|^)(\d+\.?\d*)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>constant.numeric.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Выбор|Case|Когда|When|Тогда|Then|Иначе|Else|Конец|End)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>keyword.control.conditional.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;!КАК\s|AS\s)(?&lt;=[^.а-яё\w]|^)(НЕ|NOT|И|AND|ИЛИ|OR|В\s+ИЕРАРХИИ|IN\s+HIERARCHY|В|In|Между|Between|Есть(\s+НЕ)?\s+NULL|Is(\s+NOT)?\s+NULL|Ссылка|Refs|Подобно|Like)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>keyword.operator.logical.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>&lt;=|&gt;=|[&lt;=&gt;]</string>
        <key>name</key>
        <string>keyword.operator.comparison.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([-%*+/])</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([,;])</string>
        <key>name</key>
        <string>keyword.operator.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Выбрать|Select|Разрешенные|Allowed|Различные|Distinct|Первые|Top|Как|As|ПустаяТаблица|EmptyTable|Поместить|Into|Уничтожить|Drop|Из|From|((Левое|Left|Правое|Right|Полное|Full)\s+(Внешнее\s+|Outer\s+)?Соединение|Join)|((Внутреннее|Inner)\s+Соединение|Join)|Где|Where|(Сгруппировать\s+По(\s+Группирующим\s+Наборам)?)|(Group\s+By(\s+Grouping\s+Set)?)|Имеющие|Having|Объединить(\s+Все)?|Union(\s+All)?|(Упорядочить\s+По)|(Order\s+By)|Автоупорядочивание|Autoorder|Итоги|Totals|По(\s+Общие)?|By(\s+Overall)?|(Только\s+)?Иерархия|(Only\s+)?Hierarchy|Периодами|Periods|Индексировать|Index|Выразить|Cast|Возр|Asc|Убыв|Desc|Для\s+Изменения|(For\s+Update(\s+Of)?)|Спецсимвол|Escape|СгруппированоПо|GroupedBy)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>keyword.control.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Значение|Value|ДатаВремя|DateTime|Тип|Type)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Подстрока|Substring|НРег|Lower|ВРег|Upper|Лев|Left|Прав|Right|ДлинаСтроки|StringLength|СтрНайти|StrFind|СтрЗаменить|StrReplace|СокрЛП|TrimAll|СокрЛ|TrimL|СокрП|TrimR)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Год|Year|Квартал|Quarter|Месяц|Month|ДеньГода|DayOfYear|День|Day|Неделя|Week|ДеньНедели|Weekday|Час|Hour|Минута|Minute|Секунда|Second|НачалоПериода|BeginOfPeriod|КонецПериода|EndOfPeriod|ДобавитьКДате|DateAdd|РазностьДат|DateDiff|Полугодие|HalfYear|Декада|TenDays)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(ACOS|COS|ASIN|SIN|ATAN|TAN|EXP|POW|LOG|LOG10|Цел|Int|Окр|Round|SQRT)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(Сумма|Sum|Среднее|Avg|Минимум|Min|Максимум|Max|Количество|Count)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w]|^)(ЕстьNULL|IsNULL|Представление|Presentation|ПредставлениеСсылки|RefPresentation|ТипЗначения|ValueType|АвтономерЗаписи|RecordAutoNumber|РазмерХранимыхДанных|StoredDataSize|УникальныйИдентификатор|UUID)(?=\()</string>
        <key>name</key>
        <string>support.function.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?i)(?&lt;=[^.а-яё\w])(Число|Number|Строка|String|Дата|Date|Булево|Boolean)(?=[^.а-яё\w]|$)</string>
        <key>name</key>
        <string>support.type.sdbl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(&amp;[а-яё\w]+)</string>
        <key>name</key>
        <string>variable.parameter.sdbl</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.sdbl</string>
  </dict>
</plist>