<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>st</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\[</string>
    <key>foldingStopMarker</key>
    <string>^(?:\s*|\s)]</string>
    <key>name</key>
    <string>smalltalk</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>\^</string>
        <key>name</key>
        <string>keyword.control.flow.return.smalltalk</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method.begin.smalltalk</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.smalltalk</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.method.smalltalk</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.protocol.smalltalk</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.protocol.smalltalk</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.method.stamp.smalltalk</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.stamp.smalltalk</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.stamp.smalltalk</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method.end.smalltalk</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^(!)\s*([A-Z_a-z][0-9A-Z_a-z]*)\s+(methodsFor:)\s*('([^']*)')(?:\s+(stamp:)\s*('([^']*)'))?\s*(!?)$</string>
        <key>name</key>
        <string>meta.method.definition.header.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^! !$</string>
        <key>name</key>
        <string>punctuation.definition.method.end.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\$.</string>
        <key>name</key>
        <string>constant.character.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(class)\b</string>
        <key>name</key>
        <string>storage.type.$1.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(extend|super|self)\b</string>
        <key>name</key>
        <string>storage.modifier.$1.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(yourself|new|Smalltalk)\b</string>
        <key>name</key>
        <string>keyword.control.$1.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>/^:\w*\s*\|/</string>
        <key>name</key>
        <string>constant.other.block.smalltalk</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.begin.smalltalk</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b[A-Z_a-z][0-9A-Z_a-z]*\b</string>
                <key>name</key>
                <string>variable.other.local.smalltalk</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.variable.end.smalltalk</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\|)(\s*[A-Z_a-z][0-9A-Z_a-z]*(?:\s+[A-Z_a-z][0-9A-Z_a-z]*)*\s*)(\|)</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.begin.smalltalk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.smalltalk</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.block.smalltalk</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>:[A-Z_a-z][0-9A-Z_a-z]*</string>
                    <key>name</key>
                    <string>variable.parameter.block.smalltalk</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.arguments.block.smalltalk</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((?:\s*:[A-Z_a-z][0-9A-Z_a-z]*)+)\s*(\|)</string>
            <key>name</key>
            <string>meta.block.arguments.smalltalk</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#numeric</string>
      </dict>
      <dict>
        <key>match</key>
        <string>;</string>
        <key>name</key>
        <string>punctuation.separator.cascade.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\.</string>
        <key>name</key>
        <string>punctuation.terminator.statement.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>:=</string>
        <key>name</key>
        <string>keyword.operator.assignment.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>&lt;(?![&lt;=])|&gt;(?![&lt;=&gt;])|&lt;=|&gt;=|==??|~=|~~|&gt;&gt;</string>
        <key>name</key>
        <string>keyword.operator.comparison.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([-*+/\\])</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=[\t ])!+|\bnot\b|&amp;|\band\b|\||\bor\b</string>
        <key>name</key>
        <string>keyword.operator.logical.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>-&gt;|[,@]</string>
        <key>name</key>
        <string>keyword.operator.misc.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;!\.)\b(ensure|resume|retry|signal)\b(?![!?])</string>
        <key>name</key>
        <string>keyword.control.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b((?:ifCurtailed|ifTrue|ifFalse|whileFalse|whileTrue):)\b</string>
        <key>name</key>
        <string>keyword.control.conditionals.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(to:do:|do:|timesRepeat:|even|collect:|select:|reject:)\b</string>
        <key>name</key>
        <string>keyword.control.loop.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(initialize|show:|cr|printString|space|new:|at:|at:put:|size|value:??|nextPut:)\b</string>
        <key>name</key>
        <string>support.function.smalltalk</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*([A-Z_a-z][0-9A-Z_a-z]*)\s+(subclass:)\s*('#?([A-Z_a-z][0-9A-Z_a-z]*)')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.inherited-class.smalltalk</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.declaration.class.smalltalk</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.smalltalk</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.smalltalk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=^\s*!)</string>
        <key>name</key>
        <string>meta.class.definition.smalltalk</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(instanceVariableNames:|classVariableNames:|poolDictionaries:|category:)\b</string>
            <key>name</key>
            <string>keyword.declaration.class.variables.smalltalk</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_single_quoted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.smalltalk</string>
          </dict>
        </array>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.smalltalk</string>
          </dict>
        </array>
        <key>name</key>
        <string>comment.block.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.boolean.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(nil)\b</string>
        <key>name</key>
        <string>constant.language.nil.smalltalk</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.smalltalk</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(#)[A-Z_a-z][0-:A-Z_a-z]*</string>
        <key>name</key>
        <string>constant.other.symbol.smalltalk</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>#\[</string>
        <key>beginCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.begin.smalltalk</string>
          </dict>
        </array>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.end.smalltalk</string>
          </dict>
        </array>
        <key>name</key>
        <string>meta.array.byte.smalltalk</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[0-9]+(r[0-9A-Za-z]+)?</string>
            <key>name</key>
            <string>constant.numeric.integer.smalltalk</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^]\s]+</string>
            <key>name</key>
            <string>invalid.illegal.character-not-allowed-here.smalltalk</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>#\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.array.begin.smalltalk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.array.end.smalltalk</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.other.array.literal.smalltalk</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_single_quoted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#symbol</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.smalltalk</string>
          </dict>
        </array>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.smalltalk</string>
          </dict>
        </array>
        <key>name</key>
        <string>string.quoted.single.smalltalk</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b[A-Z]\w*\b</string>
        <key>name</key>
        <string>entity.name.type.class.smalltalk</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment_block</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.begin.smalltalk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.end.smalltalk</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.smalltalk</string>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;!\w)[0-9]+\.[0-9]+s[0-9]*</string>
            <key>name</key>
            <string>constant.numeric.float.scaled.smalltalk</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\w)[0-9]+\.[0-9]+([deq]-?[0-9]+)?</string>
            <key>name</key>
            <string>constant.numeric.float.smalltalk</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\w)-?[0-9]+r[0-9A-Za-z]+</string>
            <key>name</key>
            <string>constant.numeric.integer.radix.smalltalk</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\w)-?[0-9]+([deq]-?[0-9]+)?</string>
            <key>name</key>
            <string>constant.numeric.integer.smalltalk</string>
          </dict>
        </array>
      </dict>
      <key>string_single_quoted</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.smalltalk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.smalltalk</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.smalltalk</string>
      </dict>
      <key>symbol</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.symbol.smalltalk</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(#)[A-Z_a-z][0-:A-Z_a-z]*</string>
        <key>name</key>
        <string>constant.other.symbol.smalltalk</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.smalltalk</string>
  </dict>
</plist>