<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>.surql</string>
      <string>.surrealql</string>
    </array>
    <key>foldingStartMarker</key>
    <string>[(\[{|]\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*[])|}]</string>
    <key>name</key>
    <string>surrealql</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#js-function</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#array-content</string>
          </dict>
        </array>
      </dict>
      <key>array-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.array</string>
          </dict>
        </array>
      </dict>
      <key>block</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>}</string>
        <key>name</key>
        <string>surrealql.block</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block-content</string>
          </dict>
        </array>
      </dict>
      <key>block-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>boolean</key>
      <dict>
        <key>match</key>
        <string>\b(true|TRUE|false|FALSE|True|False)\b</string>
        <key>name</key>
        <string>constant.language.bool</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment.line.dash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment.line.slash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment.line.hash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment.block</string>
          </dict>
        </array>
      </dict>
      <key>comment.block</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.surrealql</string>
      </dict>
      <key>comment.line.dash</key>
      <dict>
        <key>begin</key>
        <string>--</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.double-dash</string>
      </dict>
      <key>comment.line.hash</key>
      <dict>
        <key>begin</key>
        <string>#</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.number-sign</string>
      </dict>
      <key>comment.line.slash</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.double-slash</string>
      </dict>
      <key>duration</key>
      <dict>
        <key>match</key>
        <string>(\d+(ns|µs|ms|[dhmswy]))+</string>
        <key>name</key>
        <string>constant.other</string>
      </dict>
      <key>function</key>
      <dict>
        <key>begin</key>
        <string>(?=(\b\w+(?:::\b\w+)+|count|rand)\s*\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.function.arguments</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>ident</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>`</string>
            <key>end</key>
            <string>(?&lt;!\\)`</string>
            <key>name</key>
            <string>support.type.property-name</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>⟨</string>
            <key>end</key>
            <string>(?&lt;!\\)⟩</string>
            <key>name</key>
            <string>support.type.property-name</string>
          </dict>
        </array>
      </dict>
      <key>js-function</key>
      <dict>
        <key>begin</key>
        <string>(?=\b(function)\b)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.js</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.function.arguments</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.embedded.block.javascript</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(ACCESS|access)\b</string>
            <key>name</key>
            <string>keyword.control.access.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ALGORITHM|algorithm)\b</string>
            <key>name</key>
            <string>keyword.control.algorithm.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ALL|all)\b</string>
            <key>name</key>
            <string>keyword.control.all.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ALTER|alter)\b</string>
            <key>name</key>
            <string>keyword.control.alter.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ALWAYS|always)\b</string>
            <key>name</key>
            <string>keyword.control.always.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ANALYZER|analyzer)\b</string>
            <key>name</key>
            <string>keyword.control.analyzer.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AND|and)\b</string>
            <key>name</key>
            <string>keyword.control.and.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ANY|any)\b</string>
            <key>name</key>
            <string>keyword.control.any.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(API|api)\b</string>
            <key>name</key>
            <string>keyword.control.api.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AS|as)\b</string>
            <key>name</key>
            <string>keyword.control.as.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ASC|asc)\b</string>
            <key>name</key>
            <string>keyword.control.asc.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ASSERT|assert)\b</string>
            <key>name</key>
            <string>keyword.control.assert.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AT|at)\b</string>
            <key>name</key>
            <string>keyword.control.at.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AUTHENTICATE|authenticate)\b</string>
            <key>name</key>
            <string>keyword.control.authenticate.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AUTO|auto)\b</string>
            <key>name</key>
            <string>keyword.control.auto.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BACKEND|backend)\b</string>
            <key>name</key>
            <string>keyword.control.backend.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BEGIN|begin)\b</string>
            <key>name</key>
            <string>keyword.control.begin.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BM25|bm25)\b</string>
            <key>name</key>
            <string>keyword.control.bm25.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BREAK|break)\b</string>
            <key>name</key>
            <string>keyword.control.break.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BUCKET|bucket)\b</string>
            <key>name</key>
            <string>keyword.control.bucket.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(BY|by)\b</string>
            <key>name</key>
            <string>keyword.control.by.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CANCEL|cancel)\b</string>
            <key>name</key>
            <string>keyword.control.cancel.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CAPACITY|capacity)\b</string>
            <key>name</key>
            <string>keyword.control.capacity.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CASCADE|cascade)\b</string>
            <key>name</key>
            <string>keyword.control.cascade.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CHANGEFEED|changefeed)\b</string>
            <key>name</key>
            <string>keyword.control.changefeed.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CHANGES|changes)\b</string>
            <key>name</key>
            <string>keyword.control.changes.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(COLLATE|collate)\b</string>
            <key>name</key>
            <string>keyword.control.collate.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(COLUMNS|columns)\b</string>
            <key>name</key>
            <string>keyword.control.columns.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(COMMENT|comment)\b</string>
            <key>name</key>
            <string>keyword.control.comment.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(COMMIT|commit)\b</string>
            <key>name</key>
            <string>keyword.control.commit.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(COMPUTED|computed)\b</string>
            <key>name</key>
            <string>keyword.control.computed.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONCURRENTLY|concurrently)\b</string>
            <key>name</key>
            <string>keyword.control.concurrently.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONFIG|config)\b</string>
            <key>name</key>
            <string>keyword.control.config.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTENT|content)\b</string>
            <key>name</key>
            <string>keyword.control.content.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTINUE|continue)\b</string>
            <key>name</key>
            <string>keyword.control.continue.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CREATE|create)\b</string>
            <key>name</key>
            <string>keyword.control.create.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DATABASE|database)\b</string>
            <key>name</key>
            <string>keyword.control.database.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DB|db)\b</string>
            <key>name</key>
            <string>keyword.control.db.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DEFAULT|default)\b</string>
            <key>name</key>
            <string>keyword.control.default.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DEFER|defer)\b</string>
            <key>name</key>
            <string>keyword.control.defer.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DEFINE|define)\b</string>
            <key>name</key>
            <string>keyword.control.define.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DELETE|delete)\b</string>
            <key>name</key>
            <string>keyword.control.delete.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DESC|desc)\b</string>
            <key>name</key>
            <string>keyword.control.desc.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DIMENSION|dimension)\b</string>
            <key>name</key>
            <string>keyword.control.dimension.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DIST|dist)\b</string>
            <key>name</key>
            <string>keyword.control.dist.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DOC_IDS_CACHE|doc_ids_cache)\b</string>
            <key>name</key>
            <string>keyword.control.doc_ids_cache.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DOC_IDS_ORDER|doc_ids_order)\b</string>
            <key>name</key>
            <string>keyword.control.doc_ids_order.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DOC_LENGTHS_CACHE|doc_lengths_cache)\b</string>
            <key>name</key>
            <string>keyword.control.doc_lengths_cache.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DOC_LENGTHS_ORDER|doc_lengths_order)\b</string>
            <key>name</key>
            <string>keyword.control.doc_lengths_order.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DROP|drop)\b</string>
            <key>name</key>
            <string>keyword.control.drop.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DUPLICATE|duplicate)\b</string>
            <key>name</key>
            <string>keyword.control.duplicate.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(DURATION|duration)\b</string>
            <key>name</key>
            <string>keyword.control.duration.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EFC|efc)\b</string>
            <key>name</key>
            <string>keyword.control.efc.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ELSE|else)\b</string>
            <key>name</key>
            <string>keyword.control.else.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(END|end)\b</string>
            <key>name</key>
            <string>keyword.control.end.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ENFORCED|enforced)\b</string>
            <key>name</key>
            <string>keyword.control.enforced.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EVENT|event)\b</string>
            <key>name</key>
            <string>keyword.control.event.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EXCLUDE|exclude)\b</string>
            <key>name</key>
            <string>keyword.control.exclude.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EXISTS|exists)\b</string>
            <key>name</key>
            <string>keyword.control.exists.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EXPLAIN|explain)\b</string>
            <key>name</key>
            <string>keyword.control.explain.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EXPUNGE|expunge)\b</string>
            <key>name</key>
            <string>keyword.control.expunge.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(EXTEND_CANDIDATES|extend_candidates)\b</string>
            <key>name</key>
            <string>keyword.control.extend_candidates.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FETCH|fetch)\b</string>
            <key>name</key>
            <string>keyword.control.fetch.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FIELD|field)\b</string>
            <key>name</key>
            <string>keyword.control.field.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FIELDS|fields)\b</string>
            <key>name</key>
            <string>keyword.control.fields.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FILTERS|filters)\b</string>
            <key>name</key>
            <string>keyword.control.filters.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FLEXIBLE|flexible)\b</string>
            <key>name</key>
            <string>keyword.control.flexible.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FOR|for)\b</string>
            <key>name</key>
            <string>keyword.control.for.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FROM|from)\b</string>
            <key>name</key>
            <string>keyword.control.from.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FUNCTION|function)\b</string>
            <key>name</key>
            <string>keyword.control.function.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(FUNCTIONS|functions)\b</string>
            <key>name</key>
            <string>keyword.control.functions.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(GET|get)\b</string>
            <key>name</key>
            <string>keyword.control.get.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(GRAPHQL|graphql)\b</string>
            <key>name</key>
            <string>keyword.control.graphql.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(GROUP|group)\b</string>
            <key>name</key>
            <string>keyword.control.group.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(HIGHLIGHTS|highlights)\b</string>
            <key>name</key>
            <string>keyword.control.highlights.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(HNSW|hnsw)\b</string>
            <key>name</key>
            <string>keyword.control.hnsw.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IF|if)\b</string>
            <key>name</key>
            <string>keyword.control.if.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IGNORE|ignore)\b</string>
            <key>name</key>
            <string>keyword.control.ignore.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IN|in)\b</string>
            <key>name</key>
            <string>keyword.control.in.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INCLUDE|include)\b</string>
            <key>name</key>
            <string>keyword.control.include.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INDEX|index)\b</string>
            <key>name</key>
            <string>keyword.control.index.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INFO|info)\b</string>
            <key>name</key>
            <string>keyword.control.info.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INSERT|insert)\b</string>
            <key>name</key>
            <string>keyword.control.insert.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INTO|into)\b</string>
            <key>name</key>
            <string>keyword.control.into.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ISSUER|issuer)\b</string>
            <key>name</key>
            <string>keyword.control.issuer.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(JWT|jwt)\b</string>
            <key>name</key>
            <string>keyword.control.jwt.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(KEEP_PRUNED_CONNECTIONS|keep_pruned_connections)\b</string>
            <key>name</key>
            <string>keyword.control.keep_pruned_connections.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(KEY|key)\b</string>
            <key>name</key>
            <string>keyword.control.key.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(KILL|kill)\b</string>
            <key>name</key>
            <string>keyword.control.kill.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(LET|let)\b</string>
            <key>name</key>
            <string>keyword.control.let.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(LIMIT|limit)\b</string>
            <key>name</key>
            <string>keyword.control.limit.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(LIVE|live)\b</string>
            <key>name</key>
            <string>keyword.control.live.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(LM|lm)\b</string>
            <key>name</key>
            <string>keyword.control.lm.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([Mm])\b</string>
            <key>name</key>
            <string>keyword.control.m.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([Mm]0)\b</string>
            <key>name</key>
            <string>keyword.control.m0.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(MERGE|merge)\b</string>
            <key>name</key>
            <string>keyword.control.merge.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(MIDDLEWARE|middleware)\b</string>
            <key>name</key>
            <string>keyword.control.middleware.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(MTREE|mtree)\b</string>
            <key>name</key>
            <string>keyword.control.mtree.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(MTREE_CACHE|mtree_cache)\b</string>
            <key>name</key>
            <string>keyword.control.mtree_cache.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NAMESPACE|namespace)\b</string>
            <key>name</key>
            <string>keyword.control.namespace.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NOINDEX|noindex)\b</string>
            <key>name</key>
            <string>keyword.control.noindex.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NORMAL|normal)\b</string>
            <key>name</key>
            <string>keyword.control.normal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NOT|not)\b</string>
            <key>name</key>
            <string>keyword.control.not.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NS|ns)\b</string>
            <key>name</key>
            <string>keyword.control.ns.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NUMERIC|numeric)\b</string>
            <key>name</key>
            <string>keyword.control.numeric.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OMIT|omit)\b</string>
            <key>name</key>
            <string>keyword.control.omit.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ON|on)\b</string>
            <key>name</key>
            <string>keyword.control.on.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ONLY|only)\b</string>
            <key>name</key>
            <string>keyword.control.only.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OPTION|option)\b</string>
            <key>name</key>
            <string>keyword.control.option.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ORDER|order)\b</string>
            <key>name</key>
            <string>keyword.control.order.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OUT|out)\b</string>
            <key>name</key>
            <string>keyword.control.out.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OVERWRITE|overwrite)\b</string>
            <key>name</key>
            <string>keyword.control.overwrite.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PARALLEL|parallel)\b</string>
            <key>name</key>
            <string>keyword.control.parallel.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PARAM|param)\b</string>
            <key>name</key>
            <string>keyword.control.param.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PASSHASH|passhash)\b</string>
            <key>name</key>
            <string>keyword.control.passhash.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PASSWORD|password)\b</string>
            <key>name</key>
            <string>keyword.control.password.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PATCH|patch)\b</string>
            <key>name</key>
            <string>keyword.control.patch.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PERMISSIONS|permissions)\b</string>
            <key>name</key>
            <string>keyword.control.permissions.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(POST|post)\b</string>
            <key>name</key>
            <string>keyword.control.post.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(POSTINGS_CACHE|postings_cache)\b</string>
            <key>name</key>
            <string>keyword.control.postings_cache.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(POSTINGS_ORDER|postings_order)\b</string>
            <key>name</key>
            <string>keyword.control.postings_order.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PUT|put)\b</string>
            <key>name</key>
            <string>keyword.control.put.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(READONLY|readonly)\b</string>
            <key>name</key>
            <string>keyword.control.readonly.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(REBUILD|rebuild)\b</string>
            <key>name</key>
            <string>keyword.control.rebuild.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(RECORD|record)\b</string>
            <key>name</key>
            <string>keyword.control.record.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(REFERENCE|reference)\b</string>
            <key>name</key>
            <string>keyword.control.reference.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(REJECT|reject)\b</string>
            <key>name</key>
            <string>keyword.control.reject.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(RELATE|relate)\b</string>
            <key>name</key>
            <string>keyword.control.relate.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(RELATION|relation)\b</string>
            <key>name</key>
            <string>keyword.control.relation.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(REMOVE|remove)\b</string>
            <key>name</key>
            <string>keyword.control.remove.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(REPLACE|replace)\b</string>
            <key>name</key>
            <string>keyword.control.replace.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(RETURN|return)\b</string>
            <key>name</key>
            <string>keyword.control.return.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ROLES|roles)\b</string>
            <key>name</key>
            <string>keyword.control.roles.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ROOT|root)\b</string>
            <key>name</key>
            <string>keyword.control.root.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SC|sc)\b</string>
            <key>name</key>
            <string>keyword.control.sc.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SCHEMAFULL|schemafull)\b</string>
            <key>name</key>
            <string>keyword.control.schemafull.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SCHEMALESS|schemaless)\b</string>
            <key>name</key>
            <string>keyword.control.schemaless.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SCOPE|scope)\b</string>
            <key>name</key>
            <string>keyword.control.scope.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SEARCH|search)\b</string>
            <key>name</key>
            <string>keyword.control.search.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SELECT|select)\b</string>
            <key>name</key>
            <string>keyword.control.select.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SESSION|session)\b</string>
            <key>name</key>
            <string>keyword.control.session.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SET|set)\b</string>
            <key>name</key>
            <string>keyword.control.set.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SHOW|show)\b</string>
            <key>name</key>
            <string>keyword.control.show.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SIGNIN|signin)\b</string>
            <key>name</key>
            <string>keyword.control.signin.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SIGNUP|signup)\b</string>
            <key>name</key>
            <string>keyword.control.signup.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SINCE|since)\b</string>
            <key>name</key>
            <string>keyword.control.since.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SLEEP|sleep)\b</string>
            <key>name</key>
            <string>keyword.control.sleep.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SPLIT|split)\b</string>
            <key>name</key>
            <string>keyword.control.split.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(START|start)\b</string>
            <key>name</key>
            <string>keyword.control.start.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(STRUCTURE|structure)\b</string>
            <key>name</key>
            <string>keyword.control.structure.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TABLE|table)\b</string>
            <key>name</key>
            <string>keyword.control.table.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TABLES|tables)\b</string>
            <key>name</key>
            <string>keyword.control.tables.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TB|tb)\b</string>
            <key>name</key>
            <string>keyword.control.tb.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TEMPFILES|tempfiles)\b</string>
            <key>name</key>
            <string>keyword.control.tempfiles.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TERMS_CACHE|terms_cache)\b</string>
            <key>name</key>
            <string>keyword.control.terms_cache.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TERMS_ORDER|terms_order)\b</string>
            <key>name</key>
            <string>keyword.control.terms_order.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(THEN|then)\b</string>
            <key>name</key>
            <string>keyword.control.then.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(THROW|throw)\b</string>
            <key>name</key>
            <string>keyword.control.throw.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TIMEOUT|timeout)\b</string>
            <key>name</key>
            <string>keyword.control.timeout.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TO|to)\b</string>
            <key>name</key>
            <string>keyword.control.to.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TOKEN|token)\b</string>
            <key>name</key>
            <string>keyword.control.token.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TOKENIZERS|tokenizers)\b</string>
            <key>name</key>
            <string>keyword.control.tokenizers.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TRACE|trace)\b</string>
            <key>name</key>
            <string>keyword.control.trace.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TRANSACTION|transaction)\b</string>
            <key>name</key>
            <string>keyword.control.transaction.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(TYPE|type)\b</string>
            <key>name</key>
            <string>keyword.control.type.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNIQUE|unique)\b</string>
            <key>name</key>
            <string>keyword.control.unique.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UNSET|unset)\b</string>
            <key>name</key>
            <string>keyword.control.unset.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UPDATE|update)\b</string>
            <key>name</key>
            <string>keyword.control.update.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(UPSERT|upsert)\b</string>
            <key>name</key>
            <string>keyword.control.upsert.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(URL|url)\b</string>
            <key>name</key>
            <string>keyword.control.url.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(USE|use)\b</string>
            <key>name</key>
            <string>keyword.control.use.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(USER|user)\b</string>
            <key>name</key>
            <string>keyword.control.user.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(VALUE|value)\b</string>
            <key>name</key>
            <string>keyword.control.value.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(VALUES|values)\b</string>
            <key>name</key>
            <string>keyword.control.values.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(VERSION|version)\b</string>
            <key>name</key>
            <string>keyword.control.version.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(WHEN|when)\b</string>
            <key>name</key>
            <string>keyword.control.when.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(WHERE|where)\b</string>
            <key>name</key>
            <string>keyword.control.where.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(WITH|with)\b</string>
            <key>name</key>
            <string>keyword.control.with.surrealql</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b\d+\.\d+(?:f|dec)?\b</string>
            <key>name</key>
            <string>constant.numeric.decimal</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+(?:f|dec)?\b</string>
            <key>name</key>
            <string>constant.numeric.int</string>
          </dict>
        </array>
      </dict>
      <key>object-key</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:^|[,{])[\t ]*("[^"():?]+")(?=:(?!:))</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:^|[,{])[\t ]*('[^'():?]+')(?=:(?!:))</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.object-literal.key</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(^|[,{])[\t ]*([0-9A-Z_a-z]+)(?=:(?!:))</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&lt;-&gt;|-&gt;|&lt;-|&lt;~</string>
            <key>name</key>
            <string>keyword.operator.arrow.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(AND|and)\b|&amp;&amp;</string>
            <key>name</key>
            <string>keyword.operator.and.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OR|or)\b|\|\|</string>
            <key>name</key>
            <string>keyword.operator.or.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IS NOT|is not)\b|!=</string>
            <key>name</key>
            <string>keyword.operator.is-not.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IS|is)\b|=</string>
            <key>name</key>
            <string>keyword.operator.is.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINSALL|containsall)\b|⊇</string>
            <key>name</key>
            <string>keyword.operator.containsall.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINSANY|containsany)\b|⊃</string>
            <key>name</key>
            <string>keyword.operator.containsany.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINSNONE|containsnone)\b|⊅</string>
            <key>name</key>
            <string>keyword.operator.containsnone.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINSSOME|containssome)\b</string>
            <key>name</key>
            <string>keyword.operator.containssome.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINSNOT|containsnot)\b|∌</string>
            <key>name</key>
            <string>keyword.operator.containsnot.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CONTAINS|contains)\b|∋</string>
            <key>name</key>
            <string>keyword.operator.contains.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ALLINSIDE|allinside)\b|⊆</string>
            <key>name</key>
            <string>keyword.operator.allinside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ANYINSIDE|anyinside)\b|⊂</string>
            <key>name</key>
            <string>keyword.operator.anyinside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NONEINSIDE|noneinside)\b|⊄</string>
            <key>name</key>
            <string>keyword.operator.noneinside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(SOMEINSIDE|someinside)\b</string>
            <key>name</key>
            <string>keyword.operator.someinside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(NOTINSIDE|notinside|NOT IN|not in)\b|∉</string>
            <key>name</key>
            <string>keyword.operator.notinside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INSIDE|inside)\b|∈</string>
            <key>name</key>
            <string>keyword.operator.inside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(OUTSIDE|outside)\b</string>
            <key>name</key>
            <string>keyword.operator.outside.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(INTERSECTS|intersects)\b</string>
            <key>name</key>
            <string>keyword.operator.intersects.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>==</string>
            <key>name</key>
            <string>keyword.operator.equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*=</string>
            <key>name</key>
            <string>keyword.operator.all-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?=</string>
            <key>name</key>
            <string>keyword.operator.any-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!~</string>
            <key>name</key>
            <string>keyword.operator.fuzzy-inequal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*~</string>
            <key>name</key>
            <string>keyword.operator.fuzzy-all-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?~</string>
            <key>name</key>
            <string>keyword.operator.fuzzy-any-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>~</string>
            <key>name</key>
            <string>keyword.operator.fuzzy-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=</string>
            <key>name</key>
            <string>keyword.operator.less-or-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;(?!-|[a-z]+[^:])</string>
            <key>name</key>
            <string>keyword.operator.less.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&gt;=</string>
            <key>name</key>
            <string>keyword.operator.more-or-equal.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!-)&gt;</string>
            <key>name</key>
            <string>keyword.operator.more.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+</string>
            <key>name</key>
            <string>keyword.operator.add.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-</string>
            <key>name</key>
            <string>keyword.operator.subtract.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[*×∙]</string>
            <key>name</key>
            <string>keyword.operator.multiply.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[/÷]</string>
            <key>name</key>
            <string>keyword.operator.devide.surrealql</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.int</string>
              </dict>
            </dict>
            <key>match</key>
            <string>@([0-9]+)?@</string>
            <key>name</key>
            <string>keyword.operator.matches.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?:</string>
            <key>name</key>
            <string>keyword.operator.either.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?\?</string>
            <key>name</key>
            <string>keyword.operator.truthy.surrealql</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;\|([,A-Za-z|\d])+\|&gt;</string>
            <key>name</key>
            <string>keyword.operator.knn.surrealql</string>
          </dict>
        </array>
      </dict>
      <key>positional</key>
      <dict>
        <key>match</key>
        <string>\b(AFTER|after|BEFORE|before)\b</string>
        <key>name</key>
        <string>constant.language.positional</string>
      </dict>
      <key>query</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>record</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(\w+)\b:⟨([^⟩]+)⟩</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(\w+)\b:`([^`]+)`</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\w+)\b:(?=\b([:\w]+)\b\s*\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\(</string>
                <key>end</key>
                <string>\)</string>
                <key>name</key>
                <string>meta.function.arguments</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#value</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(\w+)\b:\b(\w+)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\w+)\b:\[</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>end</key>
            <string>]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#array-content</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(\w+)\b:(?=\{)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.class</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block-content</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[a-z]?"</string>
            <key>end</key>
            <string>(?&lt;!\\)"</string>
            <key>name</key>
            <string>string.quoted.double</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>[a-z]?'</string>
            <key>end</key>
            <string>(?&lt;!\\)'</string>
            <key>name</key>
            <string>string.quoted.single</string>
          </dict>
        </array>
      </dict>
      <key>subquery</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#query</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[&lt;&gt;]</string>
                <key>name</key>
                <string>entity.name.type.surrealql</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#number</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#void-type</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>[a-z]*&lt;[A-Za-z][ ,0-9&lt;&gt;A-Z_a-z|]+[0-9&gt;A-Za-z]+&gt;</string>
        <key>name</key>
        <string>test</string>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#js-function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#var-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ident</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#void-type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#positional</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#duration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#record</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#subquery</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>var-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\$\w+</string>
            <key>name</key>
            <string>variable.name</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$`\w+`</string>
            <key>name</key>
            <string>variable.name</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$⟨\w+⟩</string>
            <key>name</key>
            <string>variable.name</string>
          </dict>
        </array>
      </dict>
      <key>void-type</key>
      <dict>
        <key>match</key>
        <string>\b(null|NULL|none|NONE)\b</string>
        <key>name</key>
        <string>constant.language.void</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.surrealql</string>
  </dict>
</plist>