<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>v</string>
      <string>vh</string>
      <string>sv</string>
      <string>svh</string>
    </array>
    <key>name</key>
    <string>system-verilog</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#typedef-enum-struct-union</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#typedef</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-task</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#class-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#enum-struct-union</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sequence</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#all-types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module-parameters</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module-no-parameters</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#port-net-parameter</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#system-tf</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#assertion</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bind-directive</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#cast-operator</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#storage-scope</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#imports</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#identifiers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#selects</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>all-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#built-ins</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#modifiers</string>
          </dict>
        </array>
      </dict>
      <key>assertion</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.goto-label.php</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.sva.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]*(:)[\t\n\r ]*(assert|assume|cover|restrict)\b</string>
      </dict>
      <key>attributes</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!@[\t\n\r ]?)\(\*</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.attribute.rounds.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\*\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.attribute.rounds.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.attribute.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([A-Z_a-z][$0-9A-Z_a-z]*)(?:[\t\n\r ]*(=)[\t\n\r ]*)?</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
        </array>
      </dict>
      <key>base-grammar</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.interface.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\t\n\r ]*\b([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]+[A-Z_a-z][\t\n ,0-9=A-Z_a-z]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-scope</string>
          </dict>
        </array>
      </dict>
      <key>bind-directive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(bind)[\t\n\r ]+([A-Z_a-z][$.0-9A-Z_a-z]*)\b</string>
        <key>name</key>
        <string>meta.definition.systemverilog</string>
      </dict>
      <key>built-ins</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(bit|logic|reg)\b</string>
            <key>name</key>
            <string>storage.type.vector.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(byte|shortint|int|longint|integer|time|genvar)\b</string>
            <key>name</key>
            <string>storage.type.atom.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(shortreal|real|realtime)\b</string>
            <key>name</key>
            <string>storage.type.notint.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(supply[01]|tri|triand|trior|trireg|tri[01]|uwire|wire|wand|wor)\b</string>
            <key>name</key>
            <string>storage.type.net.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(genvar|var|void|signed|unsigned|string|const|process)\b</string>
            <key>name</key>
            <string>storage.type.built-in.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(uvm_(?:root|transaction|component|monitor|driver|test|env|object|agent|sequence_base|sequence_item|sequence_state|sequencer|sequencer_base|sequence|component_registry|analysis_imp|analysis_port|analysis_export|config_db|active_passive_enum|phase|verbosity|tlm_analysis_fifo|tlm_fifo|report_server|objection|recorder|domain|reg_field|reg_block|reg|bitstream_t|radix_enum|printer|packer|comparer|scope_stack))\b</string>
            <key>name</key>
            <string>storage.type.uvm.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>cast-operator</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#built-ins</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[A-Z_a-z][$0-9A-Z_a-z]*</string>
                <key>name</key>
                <string>storage.type.user-defined.systemverilog</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.cast.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*([0-9]+|[A-Z_a-z][$0-9A-Z_a-z]*)(')(?=\()</string>
        <key>name</key>
        <string>meta.cast.systemverilog</string>
      </dict>
      <key>class-declaration</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(virtual[\t\n\r ]+)?(class)(?:[\t\n\r ]+((?:st|autom)atic))?[\t\n\r ]+([A-Z_a-z][$0-:A-Z_a-z]*)(?:[\t\n\r ]+(extends|implements)[\t\n\r ]+([A-Z_a-z][$0-:A-Z_a-z]*))?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.systemverilog</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.class.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.class.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.systemverilog</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\t\n\r ]+\b(extends|implements)[\t\n\r ]+([A-Z_a-z][$0-:A-Z_a-z]*)(?:[\t\n\r ]*,[\t\n\r ]*([A-Z_a-z][$0-:A-Z_a-z]*))*</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.userdefined.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.param.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\t\n\r ]+\b([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]*(#)\(</string>
            <key>name</key>
            <string>meta.typedef.class.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#base-grammar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-binding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.systemverilog</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.systemverilog</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.systemverilog</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#fixme-todo</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.systemverilog</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.systemverilog</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#fixme-todo</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>compiler-directives</key>
      <dict>
        <key>name</key>
        <string>meta.preprocessor.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.regexp.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(`)(else|endif|endcelldefine|celldefine|nounconnected_drive|resetall|undefineall|end_keywords|__FILE__|__LINE__)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.regexp.systemverilog</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.preprocessor.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(`)(ifdef|ifndef|elsif|define|undef|pragma)[\t\n\r ]+([A-Z_a-z][$0-9A-Z_a-z]*)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.regexp.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(`)(include|timescale|default_nettype|unconnected_drive|line|begin_keywords)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(`)(protected)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.regexp.systemverilog</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(`)(endprotected)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.regexp.systemverilog</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.crypto.systemverilog</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.directive.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.preprocessor.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(`)([A-Z_a-z][$0-9A-Z_a-z]*)\b</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b[1-9][0-9_]*)?'([Ss]?[Bb][\t\n\r ]*[01?XZxz][01?XZ_xz]*|[Ss]?[Oo][\t\n\r ]*[0-7?XZxz][0-7?XZ_xz]*|[Ss]?[Dd][\t\n\r ]*[0-9?XZxz][0-9?XZ_xz]*|[Ss]?[Hh][\t\n\r ]*[?XZxz\h][?XZ_xz\h]*)(([Ee])([-+])?[0-9]+)?(?!['\w])</string>
            <key>name</key>
            <string>constant.numeric.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>'[01XZxz]</string>
            <key>name</key>
            <string>constant.numeric.bit.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d[._\d]*(?&lt;!\.)[Ee][-+]?[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric.exp.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d[._\d]*(?![.\d]|[\t\n\r ]*(?:[Ee]|fs|ps|ns|us|ms|s))\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d[.\d]*[\t\n\r ]*(?:[fnpu]|m?)s\b</string>
            <key>name</key>
            <string>constant.numeric.time.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#compiler-directives</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:this|super|null)\b</string>
            <key>name</key>
            <string>constant.language.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z][0-9A-Z_]*)\b</string>
            <key>name</key>
            <string>constant.other.net.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)([0-9A-Z_]+)(?!\.)\b</string>
            <key>name</key>
            <string>constant.numeric.parameter.uppercase.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\*</string>
            <key>name</key>
            <string>keyword.operator.quantifier.regexp</string>
          </dict>
        </array>
      </dict>
      <key>enum-struct-union</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(enum|struct|union(?:[\t\n\r ]+tagged)?|class|interface[\t\n\r ]+class)(?:[\t\n\r ]+(?!(?:pack|sign|unsign)ed)([A-Z_a-z][$0-9A-Z_a-z]*)?[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?)?(?:[\t\n\r ]+(packed))?(?:[\t\n\r ]+((?:|un)signed))?(?=[\t\n\r ]*(?:\{|$))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#built-ins</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})[\t\n\r ]*([A-Z_a-z][$0-9A-Z_a-z]*|(?&lt;=^|[\t\n\r ])\\[!-~]+(?=$|[\t\n\r ]))[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?[\t\n\r ]*[,;]</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#identifiers</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.enum-struct-union.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#base-grammar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>fixme-todo</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?i:fixme)</string>
            <key>name</key>
            <string>invalid.broken.fixme.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?i:todo)</string>
            <key>name</key>
            <string>invalid.unimplemented.todo.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>function-task</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*(?:\b(virtual)[\t\n\r ]+)?\b(function|task)\b(?:[\t\n\r ]+\b((?:st|autom)atic)\b)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.function.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.function.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.scope.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.scope.systemverilog</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#built-ins</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>[A-Z_a-z][$0-9A-Z_a-z]*</string>
                    <key>name</key>
                    <string>storage.type.user-defined.systemverilog</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#modifiers</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#selects</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\t\n\r ]*(?:\b([A-Z_a-z][$0-9A-Z_a-z]*)(::))?([A-Z_a-z][$0-9A-Z_a-z]*\b[\t\n\r ]+)?(?:\b((?:|un)signed)\b[\t\n\r ]*)?(?:(\[[]\t\n\r $%'-+\--:A-\[_-z]*])[\t\n\r ]*)?\b([A-Z_a-z][$0-9A-Z_a-z]*)\b[\t\n\r ]*(?=[(;])</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#base-grammar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(?!while|for|iff??|else|casex??|casez)([A-Z_a-z][$0-9A-Z_a-z]*)(?=[\t\n\r ]*\()</string>
        <key>name</key>
        <string>entity.name.function.systemverilog</string>
      </dict>
      <key>identifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z_a-z][$0-9A-Z_a-z]*\b</string>
            <key>name</key>
            <string>variable.other.identifier.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|[\t\n\r ])\\[!-~]+(?=$|[\t\n\r ])</string>
            <key>name</key>
            <string>string.regexp.identifier.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>imports</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.type.scope.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.scope.systemverilog</string>
          </dict>
          <key>4</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#identifiers</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b((?:im|ex)port)[\t\n\r ]+([A-Z_a-z][$0-9A-Z_a-z]*|\*)[\t\n\r ]*(::)[\t\n\r ]*([A-Z_a-z][$0-9A-Z_a-z]*|\*)[\t\n\r ]*([,;])</string>
        <key>name</key>
        <string>meta.import.systemverilog</string>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\t\n\r ]*\b(edge|negedge|posedge|cell|config|defparam|design|disable|endgenerate|endspecify|event|generate|ifnone|incdir|instance|liblist|library|noshowcancelled|pulsestyle_onevent|pulsestyle_ondetect|scalared|showcancelled|specify|specparam|use|vectored)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-control</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-control-begin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-control-end</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-definition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-cover-cross</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-std</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-option</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-local</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#sv-rand</string>
          </dict>
        </array>
      </dict>
      <key>modifiers</key>
      <dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(?:(?:un)?signed|packed|small|medium|large|supply[01]|strong[01]|pull[01]|weak[01]|highz[01])\b</string>
        <key>name</key>
        <string>storage.modifier.systemverilog</string>
      </dict>
      <key>module-binding</key>
      <dict>
        <key>begin</key>
        <string>\.([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]*\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.port.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\),?</string>
        <key>name</key>
        <string>meta.port.binding.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-scope</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cast-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#system-tf</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bvirtual\b</string>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>module-declaration</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b((?:macro)?module|interface|program|package|modport)[\t\n\r ]+(?:((?:st|autom)atic)[\t\n\r ]+)?([A-Z_a-z][$0-9A-Z_a-z]*)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.module.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.module.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#imports</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#base-grammar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#system-tf</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>module-no-parameters</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(?:(bind|pullup|pulldown)[\t\n\r ]+(?:([A-Z_a-z][$.0-9A-Z_a-z]*)[\t\n\r ]+)?)?(\b(?:and|nand|or|nor|xor|xnor|buf|not|bufif[01]|notif[01]|r?[cnp]mos|r?tran|r?tranif[01])\b|[A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]+(?!intersect|and|or|throughout|within)([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?[\t\n\r ]*(?=\(|$)(?!;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.module.systemverilog</string>
          </dict>
          <key>5</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>\)(?:[\t\n\r ]*(;))?</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.module.instantiation.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.module.no_parameters.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#module-binding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z_a-z][$0-9A-Z_a-z]*)\b(?=[\t\n\r ]*(\(|$))</string>
            <key>name</key>
            <string>variable.other.module.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>module-parameters</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(?:(bind)[\t\n\r ]+([A-Z_a-z][$.0-9A-Z_a-z]*)[\t\n\r ]+)?([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]+(?!intersect|and|or|throughout|within)(?=#[^#])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.module.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)(?:[\t\n\r ]*(;))?</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.module.instantiation.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.module.parameters.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([A-Z_a-z][$0-9A-Z_a-z]*)\b(?=[\t\n\r ]*\()</string>
            <key>name</key>
            <string>variable.other.module.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-binding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z_a-z][$0-9A-Z_a-z]*)\b(?=[\t\n\r ]*$)</string>
            <key>name</key>
            <string>variable.other.module.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:dist|inside|with|intersect|and|or|throughout|within|first_match)\b|:=|:/|\|-&gt;|\|=&gt;|-&gt;&gt;|\*&gt;|#-#|#=#|&amp;&amp;&amp;</string>
            <key>name</key>
            <string>keyword.operator.logical.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>@|##?|-&gt;|&lt;-&gt;</string>
            <key>name</key>
            <string>keyword.operator.channel.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:[-%\&amp;*+/^|]|&gt;&gt;&gt;?|&lt;&lt;&lt;?|&lt;?)=</string>
            <key>name</key>
            <string>keyword.operator.assignment.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+\+</string>
            <key>name</key>
            <string>keyword.operator.increment.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>--</string>
            <key>name</key>
            <string>keyword.operator.decrement.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-+]|\*\*|[%*/]</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!|&amp;&amp;|\|\|</string>
            <key>name</key>
            <string>keyword.operator.logical.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&lt;&lt;?|&gt;&gt;&gt;?</string>
            <key>name</key>
            <string>keyword.operator.bitwise.shift.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>~&amp;|~\|?|\^~|~\^|[\&amp;^{|]|'\{|[:?}]</string>
            <key>name</key>
            <string>keyword.operator.bitwise.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=?|&gt;=?|==\?|!=\?|===|!==|==|!=</string>
            <key>name</key>
            <string>keyword.operator.comparison.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*(#)[\t\n\r ]*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.channel.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parameters.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))[\t\n\r ]*(?=[(;A-Z\\_a-z]|$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parameters.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.parameters.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#system-tf</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bvirtual\b</string>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#module-binding</string>
          </dict>
        </array>
      </dict>
      <key>port-net-parameter</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.direction.systemverilog</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.net.systemverilog</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.type.scope.systemverilog</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.scope.systemverilog</string>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#built-ins</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>[A-Z_a-z][$0-9A-Z_a-z]*</string>
                    <key>name</key>
                    <string>storage.type.user-defined.systemverilog</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#modifiers</string>
                  </dict>
                </array>
              </dict>
              <key>7</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#selects</string>
                  </dict>
                </array>
              </dict>
              <key>8</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#constants</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#identifiers</string>
                  </dict>
                </array>
              </dict>
              <key>9</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#selects</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>match</key>
            <string>,?[\t\n\r ]*(?:\b(output|input|inout|ref)\b[\t\n\r ]*)?(?:\b(localparam|parameter|var|supply[01]|tri|triand|trior|trireg|tri[01]|uwire|wire|wand|wor)\b[\t\n\r ]*)?(?:\b([A-Z_a-z][$0-9A-Z_a-z]*)(::))?(?:([A-Z_a-z][$0-9A-Z_a-z]*)\b[\t\n\r ]*)?(?:\b((?:|un)signed)\b[\t\n\r ]*)?(?:(\[[]\t\n\r $%'-+\--:A-\[_-z]*])[\t\n\r ]*)?(?&lt;!(?&lt;!#)[-!%\&amp;(*+/:&lt;-?^|~][\t\n\r ]*)\b([A-Z_a-z][$0-9A-Z_a-z]*)\b[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?[\t\n\r ]*(?=[),/;=]|$)</string>
            <key>name</key>
            <string>meta.port-net-parameter.declaration.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>selects</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.slice.brackets.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.slice.brackets.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.brackets.select.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\$(?![a-z])</string>
            <key>name</key>
            <string>constant.language.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#system-tf</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cast-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-scope</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z_a-z][$0-9A-Z_a-z]*</string>
            <key>name</key>
            <string>variable.other.identifier.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>sequence</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(sequence)[\t\n\r ]+([A-Z_a-z][$0-9A-Z_a-z]*)\b</string>
        <key>name</key>
        <string>meta.sequence.systemverilog</string>
      </dict>
      <key>storage-scope</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.scope.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.scope.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b([A-Z_a-z][$0-9A-Z_a-z]*)(::)</string>
        <key>name</key>
        <string>meta.scope.systemverilog</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>`?"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.systemverilog</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"`?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.systemverilog</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.systemverilog</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(?:["\\afntv]|[0-7]{3}|x\h{2})</string>
                <key>name</key>
                <string>constant.character.escape.systemverilog</string>
              </dict>
              <dict>
                <key>match</key>
                <string>%(\d+\$)?[- #'+0]*[,:;_]?((-?\d+)|\*(-?\d+\$)?)?(\.((-?\d+)|\*(-?\d+\$)?)?)?(hh?|ll|[Ljltz])?[%B-HLMOPS-VXZb-hlmops-vxz]</string>
                <key>name</key>
                <string>constant.character.format.placeholder.systemverilog</string>
              </dict>
              <dict>
                <key>match</key>
                <string>%</string>
                <key>name</key>
                <string>invalid.illegal.placeholder.systemverilog</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#fixme-todo</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=include)[\t\n\r ]*(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.systemverilog</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.systemverilog</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.lt-gt.include.systemverilog</string>
          </dict>
        </array>
      </dict>
      <key>sv-control</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(initial|always|always_comb|always_ff|always_latch|final|assign|deassign|force|release|wait|forever|repeat|alias|while|for|iff??|else|casex??|casez|default|endcase|return|break|continue|do|foreach|clocking|coverpoint|property|bins|binsof|illegal_bins|ignore_bins|randcase|matches|solve|before|expect|cross|ref|srandom|struct|chandle|tagged|extern|throughout|timeprecision|timeunit|priority|type|union|wait_order|triggered|randsequence|context|pure|wildcard|new|forkjoin|unique0??|priority)\b</string>
      </dict>
      <key>sv-control-begin</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.label.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.section.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(begin|fork)\b(?:[\t\n\r ]*(:)[\t\n\r ]*([A-Z_a-z][$0-9A-Z_a-z]*))?</string>
        <key>name</key>
        <string>meta.item.begin.systemverilog</string>
      </dict>
      <key>sv-control-end</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.label.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.section.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(end|endmodule|endinterface|endprogram|endchecker|endclass|endpackage|endconfig|endfunction|endtask|endproperty|endsequence|endgroup|endprimitive|endclocking|endgenerate|join|join_any|join_none)\b(?:[\t\n\r ]*(:)[\t\n\r ]*([A-Z_a-z][$0-9A-Z_a-z]*))?</string>
        <key>name</key>
        <string>meta.item.end.systemverilog</string>
      </dict>
      <key>sv-cover-cross</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.other.systemverilog</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(([A-Z_a-z][$0-9A-Z_a-z]*)[\t\n\r ]*(:))?[\t\n\r ]*(c(?:overpoint|ross))[\t\n\r ]+([A-Z_a-z][$0-9A-Z_a-z]*)</string>
        <key>name</key>
        <string>meta.definition.systemverilog</string>
      </dict>
      <key>sv-definition</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(primitive|package|constraint|interface|covergroup|program)[\t\n\r ]+\b([A-Z_a-z][$0-9A-Z_a-z]*)\b</string>
        <key>name</key>
        <string>meta.definition.systemverilog</string>
      </dict>
      <key>sv-local</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(const|static|protected|virtual|localparam|parameter|local)\b</string>
      </dict>
      <key>sv-option</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.cover.systemverilog</string>
          </dict>
        </dict>
        <key>match</key>
        <string>[\t\n\r ]*\b(option)\.</string>
      </dict>
      <key>sv-rand</key>
      <dict>
        <key>match</key>
        <string>[\t\n\r ]*\brandc??\b</string>
        <key>name</key>
        <string>storage.type.rand.systemverilog</string>
      </dict>
      <key>sv-std</key>
      <dict>
        <key>match</key>
        <string>\b(std)\b::</string>
        <key>name</key>
        <string>support.class.systemverilog</string>
      </dict>
      <key>system-tf</key>
      <dict>
        <key>match</key>
        <string>\$[$0-9A-Z_a-z][$0-9A-Z_a-z]*\b</string>
        <key>name</key>
        <string>support.function.systemverilog</string>
      </dict>
      <key>tables</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(table)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.table.systemverilog.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>[\t\n\r ]*\b(endtable)\b</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.table.systemverilog.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.table.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[01BFNPRXbfnprx]\b</string>
            <key>name</key>
            <string>constant.language.systemverilog</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[-*?]</string>
            <key>name</key>
            <string>constant.language.systemverilog</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.systemverilog</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\(([01?Xx]{2})\)</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>punctuation.definition.label.systemverilog</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
      <key>typedef</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(typedef)[\t\n\r ]+(?:([A-Z_a-z][$0-9A-Z_a-z]*)(?:[\t\n\r ]+\b((?:|un)signed)\b)?[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?)?(?=[\t\n\r ]*[A-Z\\_a-z])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#built-ins</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\bvirtual\b</string>
                <key>name</key>
                <string>storage.modifier.systemverilog</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#modifiers</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typedef.end.systemverilog</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.typedef.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#selects</string>
          </dict>
        </array>
      </dict>
      <key>typedef-enum-struct-union</key>
      <dict>
        <key>begin</key>
        <string>[\t\n\r ]*\b(typedef)[\t\n\r ]+(enum|struct|union(?:[\t\n\r ]+tagged)?|class|interface[\t\n\r ]+class)(?:[\t\n\r ]+(?!(?:pack|sign|unsign)ed)([A-Z_a-z][$0-9A-Z_a-z]*)?[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?)?(?:[\t\n\r ]+(packed))?(?:[\t\n\r ]+((?:|un)signed))?(?=[\t\n\r ]*(?:\{|$))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.systemverilog</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#built-ins</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.systemverilog</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})[\t\n\r ]*([A-Z_a-z][$0-9A-Z_a-z]*|(?&lt;=^|[\t\n\r ])\\[!-~]+(?=$|[\t\n\r ]))[\t\n\r ]*(\[[]\t\n\r $%'-+\--:A-\[_-z]*])?[\t\n\r ]*[,;]</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.systemverilog</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selects</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.typedef-enum-struct-union.systemverilog</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#port-net-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#base-grammar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.systemverilog</string>
  </dict>
</plist>