<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>tasl</string>
    </array>
    <key>name</key>
    <string>tasl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#class</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#edge</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>class</key>
      <dict>
        <key>begin</key>
        <string>^\s*(class)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.tasl.class</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#export</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.tasl</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(#).*$</string>
        <key>name</key>
        <string>comment.line.number-sign.tasl</string>
      </dict>
      <key>component</key>
      <dict>
        <key>begin</key>
        <string>-&gt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.tasl.component</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>coproduct</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tasl.coproduct</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tasl.coproduct</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#option</string>
          </dict>
        </array>
      </dict>
      <key>datatype</key>
      <dict>
        <key>match</key>
        <string>[A-Za-z][0-9A-Za-z]*:(?:[!$\&amp;-;=?-Z_a-z~]|%\h{2})+</string>
        <key>name</key>
        <string>string.regexp</string>
      </dict>
      <key>edge</key>
      <dict>
        <key>begin</key>
        <string>^\s*(edge)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.tasl.edge</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#export</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=/</string>
            <key>name</key>
            <string>punctuation.separator.tasl.edge.source</string>
          </dict>
          <dict>
            <key>match</key>
            <string>/=&gt;</string>
            <key>name</key>
            <string>punctuation.separator.tasl.edge.target</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>punctuation.separator.tasl.edge</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>export</key>
      <dict>
        <key>match</key>
        <string>::</string>
        <key>name</key>
        <string>keyword.operator.tasl.export</string>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#uri</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#product</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#coproduct</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#reference</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optional</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([A-Za-z][0-9A-Za-z]*)\b</string>
      </dict>
      <key>key</key>
      <dict>
        <key>match</key>
        <string>[A-Za-z][0-9A-Za-z]*:(?:[!$\&amp;-;=?-Z_a-z~]|%\h{2})+</string>
        <key>name</key>
        <string>markup.bold entity.name.class</string>
      </dict>
      <key>literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#datatype</string>
          </dict>
        </array>
      </dict>
      <key>namespace</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.tasl.namespace</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#namespaceURI</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[A-Za-z][0-9A-Za-z]*\b</string>
                <key>name</key>
                <string>entity.name</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(namespace)\b(.*)</string>
      </dict>
      <key>namespaceURI</key>
      <dict>
        <key>match</key>
        <string>[a-z]+:[]!#-;=?-\[_a-z~]+</string>
        <key>name</key>
        <string>markup.underline.link</string>
      </dict>
      <key>option</key>
      <dict>
        <key>begin</key>
        <string>&lt;-</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.tasl.option</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>optional</key>
      <dict>
        <key>begin</key>
        <string>\?</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>product</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tasl.product</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tasl.product</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#component</string>
          </dict>
        </array>
      </dict>
      <key>reference</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.bold keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#key</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>match</key>
        <string>(\*)\s*(.*)</string>
      </dict>
      <key>term</key>
      <dict>
        <key>match</key>
        <string>[A-Za-z][0-9A-Za-z]*:(?:[!$\&amp;-;=?-Z_a-z~]|%\h{2})+</string>
        <key>name</key>
        <string>entity.other.tasl.key</string>
      </dict>
      <key>type</key>
      <dict>
        <key>begin</key>
        <string>^\s*(type)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.tasl.type</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>uri</key>
      <dict>
        <key>match</key>
        <string>&lt;&gt;</string>
        <key>name</key>
        <string>variable.other.constant</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.tasl</string>
  </dict>
</plist>