<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>tsv</string>
      <string>tab</string>
    </array>
    <key>name</key>
    <string>tsv</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>rainbow1</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.rainbow2</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.rainbow3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>comment.rainbow4</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.rainbow5</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.rainbow6</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.rainbow7</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.rainbow8</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>markup.bold.rainbow9</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>invalid.rainbow10</string>
          </dict>
        </dict>
        <key>match</key>
        <string>([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)([^\t]*\t?)</string>
        <key>name</key>
        <string>rainbowgroup</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>text.tsv</string>
  </dict>
</plist>