<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>turtle</string>
      <string>ttl</string>
      <string>acl</string>
    </array>
    <key>name</key>
    <string>turtle</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#rule-constraint</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#iriref</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#prefix</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#prefixed-name</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#special-predicate</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#language-tag</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>boolean</key>
      <dict>
        <key>match</key>
        <string>\b(?i:true|false)\b</string>
        <key>name</key>
        <string>constant.language.sparql</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>match</key>
        <string>#.*$</string>
        <key>name</key>
        <string>comment.line.number-sign.turtle</string>
      </dict>
      <key>integer</key>
      <dict>
        <key>match</key>
        <string>[-+]?(?:\d+|[0-9]+\.[0-9]*|\.[0-9]+(?:[Ee][-+]?\d+)?)</string>
        <key>name</key>
        <string>constant.numeric.turtle</string>
      </dict>
      <key>iriref</key>
      <dict>
        <key>match</key>
        <string>&lt;[^ "&lt;&gt;\\^`{|}]*&gt;</string>
        <key>name</key>
        <string>entity.name.type.iriref.turtle</string>
      </dict>
      <key>language-tag</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.turtle</string>
          </dict>
        </dict>
        <key>match</key>
        <string>@(\w+)</string>
        <key>name</key>
        <string>meta.string-literal-language-tag.turtle</string>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#integer</string>
          </dict>
        </array>
      </dict>
      <key>prefix</key>
      <dict>
        <key>match</key>
        <string>(?i:@?base|@?prefix)\s</string>
        <key>name</key>
        <string>keyword.operator.turtle</string>
      </dict>
      <key>prefixed-name</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.PNAME_NS.turtle</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.variable.PN_LOCAL.turtle</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\w*:)(\w*)</string>
        <key>name</key>
        <string>constant.complex.turtle</string>
      </dict>
      <key>rule-constraint</key>
      <dict>
        <key>begin</key>
        <string>(rule:content) (""")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#prefixed-name</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.triple.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.triple.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.rule-constraint.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.srs</string>
          </dict>
        </array>
      </dict>
      <key>single-dquote-string-literal</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>single-squote-string-literal</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.turtle</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>special-predicate</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.turtle</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\s(a)\s</string>
        <key>name</key>
        <string>meta.specialPredicate.turtle</string>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#triple-squote-string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#triple-dquote-string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-squote-string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-dquote-string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#triple-tick-string-literal</string>
          </dict>
        </array>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>match</key>
        <string>\\(x\h{2}|[012][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
        <key>name</key>
        <string>constant.character.escape.turtle</string>
      </dict>
      <key>triple-dquote-string-literal</key>
      <dict>
        <key>begin</key>
        <string>"""</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"""</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>triple-squote-string-literal</key>
      <dict>
        <key>begin</key>
        <string>'''</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'''</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>triple-tick-string-literal</key>
      <dict>
        <key>begin</key>
        <string>```</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.turtle</string>
          </dict>
        </dict>
        <key>end</key>
        <string>```</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.turtle</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.triple.turtle</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.turtle</string>
  </dict>
</plist>