<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>typst</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#markup</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>arguments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[_[:alpha:]][-_[:alnum:]]*(?=:)</string>
            <key>name</key>
            <string>variable.parameter.typst</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code</string>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#common</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.code.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.block.code.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.content.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>]</string>
            <key>name</key>
            <string>meta.block.content.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#markup</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.double-slash.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>punctuation.separator.colon.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;|\.\.</string>
            <key>name</key>
            <string>keyword.operator.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>==|!=|&lt;=?|&gt;=?</string>
            <key>name</key>
            <string>keyword.operator.relational.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:[-*+]|/?)=</string>
            <key>name</key>
            <string>keyword.operator.assignment.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[*+/]|(?&lt;![_[:alpha:]][-_[:alnum:]]*)-(?![:almnu]_-]*[_[:alpha:]])</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(and|or|not)\b</string>
            <key>name</key>
            <string>keyword.operator.word.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(let|as|in|set|show)\b</string>
            <key>name</key>
            <string>keyword.other.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|else)\b</string>
            <key>name</key>
            <string>keyword.control.conditional.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(for|while|break|continue)\b</string>
            <key>name</key>
            <string>keyword.control.loop.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(import|include|export)\b</string>
            <key>name</key>
            <string>keyword.control.import.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(return)\b</string>
            <key>name</key>
            <string>keyword.control.flow.typst</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[_[:alpha:]][-_[:alnum:]]*!?(?=[(\[])</string>
            <key>name</key>
            <string>entity.name.function.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\bshow\s*)\b[_[:alpha:]][-_[:alnum:]]*(?=\s*[.:])</string>
            <key>name</key>
            <string>entity.name.function.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=\b[_[:alpha:]][-_[:alnum:]]*!?)\(</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#arguments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b[_[:alpha:]][-_[:alnum:]]*\b</string>
            <key>name</key>
            <string>variable.other.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)|(?=;)</string>
            <key>name</key>
            <string>meta.group.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!:)//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.double-slash.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>common</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bnone\b</string>
            <key>name</key>
            <string>constant.language.none.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bauto\b</string>
            <key>name</key>
            <string>constant.language.auto.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d*)?\.?\d+([Ee][-+]?\d+)?(mm|pt|cm|in|em)\b</string>
            <key>name</key>
            <string>constant.numeric.length.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d*)?\.?\d+([Ee][-+]?\d+)?(rad|deg)\b</string>
            <key>name</key>
            <string>constant.numeric.angle.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d*)?\.?\d+([Ee][-+]?\d+)?%</string>
            <key>name</key>
            <string>constant.numeric.percentage.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d*)?\.?\d+([Ee][-+]?\d+)?fr</string>
            <key>name</key>
            <string>constant.numeric.fr.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b\d+\b</string>
            <key>name</key>
            <string>constant.numeric.integer.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d*)?\.?\d+([Ee][-+]?\d+)?\b</string>
            <key>name</key>
            <string>constant.numeric.float.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(["\\nrt]|u\{?[0-9A-Za-z]*}?)</string>
                <key>name</key>
                <string>constant.character.escape.string.typst</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.math.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\$</string>
            <key>name</key>
            <string>string.other.math.typst</string>
          </dict>
        </array>
      </dict>
      <key>markup</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#common</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\([]#-/=\[\\_`{}~]|u\{[0-9A-Za-z]*}?)</string>
            <key>name</key>
            <string>constant.character.escape.content.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\</string>
            <key>name</key>
            <string>punctuation.definition.linebreak.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>~</string>
            <key>name</key>
            <string>punctuation.definition.nonbreaking-space.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-\?</string>
            <key>name</key>
            <string>punctuation.definition.shy.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>---</string>
            <key>name</key>
            <string>punctuation.definition.em-dash.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>--</string>
            <key>name</key>
            <string>punctuation.definition.en-dash.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.\.</string>
            <key>name</key>
            <string>punctuation.definition.ellipsis.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:([0-9A-Za-z]+:)+</string>
            <key>name</key>
            <string>constant.symbol.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^\*|\*$|((?&lt;=[_\W])\*)|(\*(?=[_\W])))</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.bold.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(^\*|\*$|((?&lt;=[_\W])\*)|(\*(?=[_\W])))|\n|(?=])</string>
            <key>name</key>
            <string>markup.bold.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#markup</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^_|_$|((?&lt;=[_\W])_)|(_(?=[_\W])))</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.italic.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(^_|_$|((?&lt;=[_\W])_)|(_(?=[_\W])))|\n|(?=])</string>
            <key>name</key>
            <string>markup.italic.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#markup</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>https?://[#%\&amp;'+,.-9;=?A-Za-z~]*</string>
            <key>name</key>
            <string>markup.underline.link.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>`{3,}</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.raw.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\x00</string>
            <key>name</key>
            <string>markup.raw.block.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>`</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.raw.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>name</key>
            <string>markup.raw.inline.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.math.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\$</string>
            <key>name</key>
            <string>string.other.math.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s*=+\s+</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.heading.typst</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>entity.name.section.typst</string>
            <key>end</key>
            <string>\n|(?=&lt;)</string>
            <key>name</key>
            <string>markup.heading.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#markup</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*-\s+</string>
            <key>name</key>
            <string>punctuation.definition.list.unnumbered.typst</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*([0-9]*\.|\+)\s+</string>
            <key>name</key>
            <string>punctuation.definition.list.numbered.typst</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.list.description.typst</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.list.term.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*(/)\s+([^:]*:)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.label.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>&lt;[_[:alpha:]][-_[:alnum:]]*&gt;</string>
            <key>name</key>
            <string>entity.other.label.typst</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.reference.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(@)[_[:alpha:]][-_[:alnum:]]*</string>
            <key>name</key>
            <string>entity.other.reference.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(#)(let|set|show)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.typst</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n|(;)|(?=])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.terminator.statement.typst</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#)(as|in)\b</string>
            <key>name</key>
            <string>keyword.other.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>((#)if|(?&lt;=([]}])\s*)else)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.typst</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n|(?=])|(?&lt;=[]}])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(#)(for|while)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.loop.typst</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n|(?=])|(?&lt;=[]}])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#)(break|continue)\b</string>
            <key>name</key>
            <string>keyword.control.loop.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(#)(import|include|export)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.import.typst</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\n|(;)|(?=])</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.terminator.statement.typst</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#)(return)\b</string>
            <key>name</key>
            <string>keyword.control.flow.typst</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.function.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>((#)[_[:alpha:]][-_[:alnum:]]*!?)(?=[(\[])</string>
            <key>name</key>
            <string>entity.name.function.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=#[_[:alpha:]][-_[:alnum:]]*!?)\(</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.typst</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#arguments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.typst</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#)[_[:alpha:]][-._[:alnum:]]*</string>
            <key>name</key>
            <string>entity.other.interpolated.typst</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>#</string>
            <key>end</key>
            <string>\s</string>
            <key>name</key>
            <string>meta.block.content.typst</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.typst</string>
  </dict>
</plist>