<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array/>
    <key>injectTo</key>
    <array>
      <string>source.vue</string>
    </array>
    <key>injectionSelector</key>
    <string>L:source.css -comment, L:source.postcss -comment, L:source.sass -comment, L:source.stylus -comment</string>
    <key>name</key>
    <string>vue-sfc-style-variable-injection</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#vue-sfc-style-variable-injection</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>vue-sfc-style-variable-injection</key>
      <dict>
        <key>begin</key>
        <string>\b(v-bind)\s*\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>vue.sfc.style.variable.injection.v-bind</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(["'])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\1)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html</string>
              </dict>
            </dict>
            <key>name</key>
            <string>source.ts.embedded.html.vue</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>vue.sfc.style.variable.injection</string>
  </dict>
</plist>