<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>vue</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#vue-comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#self-closing-tag</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(&lt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)md\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>text.html.markdown</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>text.html.markdown</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!template(?![-0-:A-Za-z]))([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)html\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.html.derivative</string>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-stuff</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)pug\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>text.pug</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>text.pug</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)stylus\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.stylus</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.stylus</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)postcss\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.postcss</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.postcss</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)sass\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.sass</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.sass</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)css\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.css</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)scss\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.css.scss</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css.scss</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)less\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.css.less</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css.less</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)js\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.js</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.js</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)ts\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)(?=[^\n]*&lt;/script[&gt;\s])</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>name</key>
                <string>source.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
                <key>while</key>
                <string>^(?!\s*&lt;/script[&gt;\s])</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)jsx\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.js.jsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.js.jsx</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)tsx\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)(?=[^\n]*&lt;/script[&gt;\s])</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.tsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.tsx</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>name</key>
                <string>source.tsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.tsx</string>
                  </dict>
                </array>
                <key>while</key>
                <string>^(?!\s*&lt;/script[&gt;\s])</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)coffee\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.coffee</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.coffee</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)json\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.json</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.json</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)jsonc\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.json.comments</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.json.comments</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)json5\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.json5</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.json5</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)yaml\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.yaml</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.yaml</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)toml\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.toml</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.toml</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)(g(?:ql|raphql))\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>source.graphql</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.graphql</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)\b(?=[^&gt;]*\blang\s*=\s*(["']?)vue\b\2)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>text.html.vue</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>text.html.vue</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(template)(?=\s|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/template[&gt;\s])</string>
                <key>name</key>
                <string>text.html.derivative</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#html-stuff</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(script)(?=\s|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#multi-line-script-tag-stuff</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(style)(?=\s|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#multi-line-style-tag-stuff</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([-0-:A-Za-z]+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$1.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)(\1)\s*(?=&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$2.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/)</string>
                <key>name</key>
                <string>text</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>html-stuff</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#template-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.derivative</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic</string>
          </dict>
        </array>
      </dict>
      <key>multi-line-script-tag-stuff</key>
      <dict>
        <key>begin</key>
        <string>\G</string>
        <key>end</key>
        <string>(?=&lt;/script[&gt;\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G(?!\blang\s*=\s*["']?(?:tsx??|jsx|coffee)\b)</string>
            <key>end</key>
            <string>(?=\blang\s*=\s*["']?(?:tsx??|jsx|coffee)\b)|(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.tag-stuff</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#vue-directives</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic#attribute</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?ts\b)</string>
            <key>end</key>
            <string>(?=&lt;/script[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)(?=[^\n]*&lt;/script[&gt;\s])</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>name</key>
                <string>source.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
                <key>while</key>
                <string>^(?!\s*&lt;/script[&gt;\s])</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?tsx\b)</string>
            <key>end</key>
            <string>(?=&lt;/script[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)(?=[^\n]*&lt;/script[&gt;\s])</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.tsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.tsx</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>name</key>
                <string>source.tsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.tsx</string>
                  </dict>
                </array>
                <key>while</key>
                <string>^(?!\s*&lt;/script[&gt;\s])</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?jsx\b)</string>
            <key>end</key>
            <string>(?=&lt;/script[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.js.jsx</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.js.jsx</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?coffee\b)</string>
            <key>end</key>
            <string>(?=&lt;/script[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/script[&gt;\s])</string>
                <key>name</key>
                <string>source.coffee</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.coffee</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=&gt;)</string>
            <key>end</key>
            <string>(?=&lt;/script[&gt;\s])</string>
            <key>name</key>
            <string>source.js</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>multi-line-style-tag-stuff</key>
      <dict>
        <key>begin</key>
        <string>\G</string>
        <key>end</key>
        <string>(?=&lt;/style[&gt;\s])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G(?!\blang\s*=\s*["']?(?:scss|stylus|less|postcss)\b)</string>
            <key>end</key>
            <string>(?=\blang\s*=\s*["']?(?:scss|stylus|less|postcss)\b)|(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.tag-stuff</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#vue-directives</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic#attribute</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?scss\b)</string>
            <key>end</key>
            <string>(?=&lt;/style[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/style[&gt;\s])</string>
                <key>name</key>
                <string>source.css.scss</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css.scss</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?stylus\b)</string>
            <key>end</key>
            <string>(?=&lt;/style[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/style[&gt;\s])</string>
                <key>name</key>
                <string>source.stylus</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.stylus</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?less\b)</string>
            <key>end</key>
            <string>(?=&lt;/style[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/style[&gt;\s])</string>
                <key>name</key>
                <string>source.css.less</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css.less</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\blang\s*=\s*["']?postcss\b)</string>
            <key>end</key>
            <string>(?=&lt;/style[&gt;\s])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;=&gt;)</string>
                <key>end</key>
                <string>(?=&lt;/style[&gt;\s])</string>
                <key>name</key>
                <string>source.postcss</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.postcss</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;=&gt;)</string>
            <key>end</key>
            <string>(?=&lt;/style[&gt;\s])</string>
            <key>name</key>
            <string>source.css</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.css</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>self-closing-tag</key>
      <dict>
        <key>begin</key>
        <string>(&lt;)([-0-:A-Za-z]+)(?=([^&gt;]+/&gt;))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.$2.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(/&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>name</key>
        <string>self-closing-tag</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-stuff</string>
          </dict>
        </array>
      </dict>
      <key>tag-stuff</key>
      <dict>
        <key>begin</key>
        <string>\G</string>
        <key>end</key>
        <string>(?=/&gt;)|(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag-stuff</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#vue-directives</string>
          </dict>
          <dict>
            <key>include</key>
            <string>text.html.basic#attribute</string>
          </dict>
        </array>
      </dict>
      <key>template-tag</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#template-tag-1</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#template-tag-2</string>
          </dict>
        </array>
      </dict>
      <key>template-tag-1</key>
      <dict>
        <key>begin</key>
        <string>(&lt;)(template)\b(&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.$2.html.vue</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(/?&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.template-tag.start</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G</string>
            <key>end</key>
            <string>(?=/&gt;)|((&lt;/)(template)(?=[&gt;\s]))</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$3.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template-tag.end</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#html-stuff</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>template-tag-2</key>
      <dict>
        <key>begin</key>
        <string>(&lt;)(template)(?=\s|/?&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.$2.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(/?&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.html.vue</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.template-tag.start</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G</string>
            <key>end</key>
            <string>(?=/&gt;)|((&lt;/)(template)(?=[&gt;\s]))</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.html.vue</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.$3.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.template-tag.end</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-stuff</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-stuff</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>vue-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#vue-comments-key-value</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;!--</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>--&gt;</string>
            <key>name</key>
            <string>comment.block.vue</string>
          </dict>
        </array>
      </dict>
      <key>vue-comments-key-value</key>
      <dict>
        <key>begin</key>
        <string>(&lt;!--)\s*(@)([$\w]+)(?=\s)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.tag.comment.vue</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.comment.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(--&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.vue</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.vue</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.json#value</string>
          </dict>
        </array>
      </dict>
      <key>vue-directives</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#vue-directives-control</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vue-directives-generic-attr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vue-directives-style-attr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vue-directives-original</string>
          </dict>
        </array>
      </dict>
      <key>vue-directives-control</key>
      <dict>
        <key>begin</key>
        <string>(?:(v-for)|(v-(?:if|else-if|else)))(?=[)/=&gt;\s])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\s*[^=\s])</string>
        <key>name</key>
        <string>meta.attribute.directive.control.vue</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#vue-directives-expression</string>
          </dict>
        </array>
      </dict>
      <key>vue-directives-expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(=)\s*(["'`])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.html.vue</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\2)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.html.vue</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?&lt;=(["'`]))</string>
                <key>end</key>
                <string>(?=\1)</string>
                <key>name</key>
                <string>source.ts.embedded.html.vue</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#expression</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(=)\s*(?=[^"'`])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=([&gt;\s]|/&gt;))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(?=[^"'`])</string>
                <key>end</key>
                <string>(?=([&gt;\s]|/&gt;))</string>
                <key>name</key>
                <string>source.ts.embedded.html.vue</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#expression</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>vue-directives-generic-attr</key>
      <dict>
        <key>begin</key>
        <string>\b(generic)\s*(=)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=["'])</string>
        <key>name</key>
        <string>meta.attribute.generic.vue</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(["'])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\1)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.type.parameters.vue</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#comment</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;![$_[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))(extends|in|out)(?![$_[:alnum:]])(?:(?=\.\.\.)|(?!\.))</string>
                <key>name</key>
                <string>storage.modifier.ts</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#type</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#punctuation-comma</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(=)(?!&gt;)</string>
                <key>name</key>
                <string>keyword.operator.assignment.ts</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>vue-directives-original</key>
      <dict>
        <key>begin</key>
        <string>(?:(v-[-\w]+)(:)?|([.:])|(@)|(#))(?:(\[)([^]]*)(])|([-\w]+))?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.vue</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.attribute-shorthand.bind.html.vue</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.attribute-shorthand.event.html.vue</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.attribute-shorthand.slot.html.vue</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.vue</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>source.ts.embedded.html.vue</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#expression</string>
              </dict>
            </array>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.vue</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=\s*[^=\s])</string>
        <key>name</key>
        <string>meta.attribute.directive.vue</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.key-value.html.vue</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.other.attribute-name.html.vue</string>
            </dict>
            <key>match</key>
            <string>(\.)([-\w]*)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vue-directives-expression</string>
          </dict>
        </array>
      </dict>
      <key>vue-directives-style-attr</key>
      <dict>
        <key>begin</key>
        <string>\b(style)\s*(=)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.html.vue</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value.html.vue</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=["'])</string>
        <key>name</key>
        <string>meta.attribute.style.vue</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(["'])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\1)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>source.css.embedded.html.vue</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.css#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.css#escapes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.css#font-features</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?&lt;![-\w])--[-A-Z_a-z[^\x00-\x7F]](?:[-0-9A-Z_a-z[^\x00-\x7F]]|\\(?:\h{1,6}|.))*</string>
                <key>name</key>
                <string>variable.css</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?&lt;![-A-Za-z])(?=[-A-Za-z])</string>
                <key>end</key>
                <string>$|(?![-A-Za-z])</string>
                <key>name</key>
                <string>meta.property-name.css</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css#property-names</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(:)\s*</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.css</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>meta.property-value.css</string>
                <key>end</key>
                <string>\s*(;)|\s*(?=["'])</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.terminator.rule.css</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css#comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>source.css#property-values</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>;</string>
                <key>name</key>
                <string>punctuation.terminator.rule.css</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>vue-interpolations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.interpolation.begin.html.vue</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(}})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.interpolation.end.html.vue</string>
              </dict>
            </dict>
            <key>name</key>
            <string>expression.embedded.vue</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\G</string>
                <key>end</key>
                <string>(?=}})</string>
                <key>name</key>
                <string>source.ts.embedded.html.vue</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#expression</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.vue</string>
  </dict>
</plist>