<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>wgsl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#line_comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#block_comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function_calls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.attribute.at</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.attribute.wgsl</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(@)([A-Z_a-z]+)</string>
            <key>name</key>
            <string>meta.attribute.wgsl</string>
          </dict>
        </array>
      </dict>
      <key>block_comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.wgsl</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.wgsl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block_comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*(?!\*)</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.wgsl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#block_comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(-?\b[0-9][0-9]*\.[0-9][0-9]*)([Ee][-+]?[0-9]+)?\b</string>
            <key>name</key>
            <string>constant.numeric.float.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:-?\b0x\h+|\b0|-?\b[1-9][0-9]*)\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:0x\h+|0|[1-9][0-9]*)u\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.wgsl</string>
          </dict>
        </array>
      </dict>
      <key>function_calls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([0-9A-Z_a-z]+)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.wgsl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.wgsl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.wgsl</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.call.wgsl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#line_comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#block_comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function_calls</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(fn)\s+([0-9A-Z_a-z]+)((\()|(&lt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.fn.wgsl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.wgsl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.round.wgsl</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\{</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.brackets.curly.wgsl</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function.definition.wgsl</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#line_comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#block_comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function_calls</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(bitcast|block|break|case|continue|continuing|default|discard|else|elseif|enable|fallthrough|for|function|if|loop|private|read|read_write|return|storage|switch|uniform|while|workgroup|write)\b</string>
            <key>name</key>
            <string>keyword.control.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(asm|const|do|enum|handle|mat|premerge|regardless|typedef|unless|using|vec|void)\b</string>
            <key>name</key>
            <string>keyword.control.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(let|var)\b</string>
            <key>name</key>
            <string>keyword.other.wgsl storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(type)\b</string>
            <key>name</key>
            <string>keyword.declaration.type.wgsl storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(enum)\b</string>
            <key>name</key>
            <string>keyword.declaration.enum.wgsl storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(struct)\b</string>
            <key>name</key>
            <string>keyword.declaration.struct.wgsl storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bfn\b</string>
            <key>name</key>
            <string>keyword.other.fn.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\^|]|\|\||&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
            <key>name</key>
            <string>keyword.operator.logical.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;(?![\&amp;=])</string>
            <key>name</key>
            <string>keyword.operator.borrow.and.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:[-%\&amp;*+/^|]|&lt;&lt;|&gt;&gt;)=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![&lt;&gt;])=(?![=&gt;])</string>
            <key>name</key>
            <string>keyword.operator.assignment.equal.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
            <key>name</key>
            <string>keyword.operator.comparison.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(([%+]|(\*(?!\w)))(?!=))|(-(?!&gt;))|(/(?!/))</string>
            <key>name</key>
            <string>keyword.operator.math.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.(?!\.)</string>
            <key>name</key>
            <string>keyword.operator.access.dot.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.skinny.wgsl</string>
          </dict>
        </array>
      </dict>
      <key>line_comments</key>
      <dict>
        <key>match</key>
        <string>\s*//.*</string>
        <key>name</key>
        <string>comment.line.double-slash.wgsl</string>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.comma.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[{}]</string>
            <key>name</key>
            <string>punctuation.brackets.curly.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[()]</string>
            <key>name</key>
            <string>punctuation.brackets.round.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.semi.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[]\[]</string>
            <key>name</key>
            <string>punctuation.brackets.square.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![-=])[&lt;&gt;]</string>
            <key>name</key>
            <string>punctuation.brackets.angle.wgsl</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>name</key>
        <string>storage.type.wgsl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(bool|i32|u32|f32)\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([fiu]64)\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(vec(?:2i|3i|4i|2u|3u|4u|2f|3f|4f|2h|3h|4h))\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(mat(?:2x2f|2x3f|2x4f|3x2f|3x3f|3x4f|4x2f|4x3f|4x4f|2x2h|2x3h|2x4h|3x2h|3x3h|3x4h|4x2h|4x3h|4x4h))\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(vec[234]|mat[234]x[234])\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(atomic)\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(array)\b</string>
            <key>name</key>
            <string>storage.type.wgsl</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z][0-9A-Za-z]*)\b</string>
            <key>name</key>
            <string>entity.name.type.wgsl</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?&lt;!(?&lt;!\.)\.)(?:r#(?!(crate|[Ss]elf|super)))?[0-9_a-z]+\b</string>
            <key>name</key>
            <string>variable.other.wgsl</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.wgsl</string>
  </dict>
</plist>