<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>xml</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(&lt;\?)\s*([-0-9A-Z_a-z]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\?&gt;)</string>
        <key>name</key>
        <string>meta.tag.preprocessor.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string> ([-A-Za-z]+)</string>
            <key>name</key>
            <string>entity.other.attribute-name.xml</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doublequotedString</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#singlequotedString</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(&lt;!)(DOCTYPE)\s+([:A-Z_a-z][-.0-:A-Z_a-z]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.doctype.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.language.documentroot.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(&gt;)</string>
        <key>name</key>
        <string>meta.tag.sgml.doctype.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internalSubset</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(&lt;)((?:([-0-9A-Z_a-z]+)(:))?([-0-:A-Z_a-z]+))(?=(\s[^&gt;]*)?&gt;&lt;/\2&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.namespace.xml</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.namespace.xml</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.localname.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&gt;)(&lt;/)((?:([-0-9A-Z_a-z]+)(:))?([-0-:A-Z_a-z]+))(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.xml</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.namespace.xml</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.namespace.xml</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.localname.xml</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.tag.no-content.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tagStuff</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(&lt;/?)(?:([-.\w]+)((:)))?([-.:\w]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.namespace.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.xml</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.namespace.xml</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.localname.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(/?&gt;)</string>
        <key>name</key>
        <string>meta.tag.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tagStuff</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#entity</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bare-ampersand</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>&lt;%@</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>%&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>source.java-props.embedded.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>page|include|taglib</string>
            <key>name</key>
            <string>keyword.other.page-props.xml</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>&lt;%[!=]?(?!--)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?!--)%&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>source.java.embedded.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.java</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>&lt;!\[CDATA\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>]]&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.unquoted.cdata.xml</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>EntityDecl</key>
      <dict>
        <key>begin</key>
        <string>(&lt;!)(ENTITY)\s+(%\s+)?([:A-Z_a-z][-.0-:A-Z_a-z]*)(\s+(?:SYSTEM|PUBLIC)\s+)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.xml</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.entity.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.entity.xml</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.language.entity.xml</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.other.entitytype.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&gt;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#doublequotedString</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#singlequotedString</string>
          </dict>
        </array>
      </dict>
      <key>bare-ampersand</key>
      <dict>
        <key>match</key>
        <string>&amp;</string>
        <key>name</key>
        <string>invalid.illegal.bad-ampersand.xml</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>&lt;%--</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.xml</string>
              </dict>
              <key>end</key>
              <string>--%&gt;</string>
              <key>name</key>
              <string>comment.block.xml</string>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;!--</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.xml</string>
              </dict>
            </dict>
            <key>end</key>
            <string>--&gt;</string>
            <key>name</key>
            <string>comment.block.xml</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>--(?!&gt;)</string>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>invalid.illegal.bad-comments-or-CDATA.xml</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>doublequotedString</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bare-ampersand</string>
          </dict>
        </array>
      </dict>
      <key>entity</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(&amp;)([:A-Z_a-z][-.0-:A-Z_a-z]*|#[0-9]+|#x\h+)(;)</string>
        <key>name</key>
        <string>constant.character.entity.xml</string>
      </dict>
      <key>internalSubset</key>
      <dict>
        <key>begin</key>
        <string>(\[)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(])</string>
        <key>name</key>
        <string>meta.internalsubset.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#EntityDecl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameterEntity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>parameterEntity</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.constant.xml</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(%)([:A-Z_a-z][-.0-:A-Z_a-z]*)(;)</string>
        <key>name</key>
        <string>constant.character.parameter-entity.xml</string>
      </dict>
      <key>singlequotedString</key>
      <dict>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.xml</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.xml</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single.xml</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bare-ampersand</string>
          </dict>
        </array>
      </dict>
      <key>tagStuff</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.namespace.xml</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.xml</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.xml</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.localname.xml</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?:^|\s+)(?:([-.\w]+)((:)))?([-.:\w]+)\s*=</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doublequotedString</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#singlequotedString</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>text.xml</string>
  </dict>
</plist>