import { useMemo, useState } from 'react'
// generated by `cargo run -p duck-md-core --bin duck-md -- build`
// shape matches velite's `.velite/docs.json` exactly
import docs from '../.gentleduck/docs.json'
import { MdxContent } from './MdxContent'
import { Callout } from './components/Callout'

type DocRecord = (typeof docs)[number]

const components = { Callout }

export function App() {
  const [slug, setSlug] = useState<string>(docs[0]?.permalink ?? '')
  const doc = useMemo<DocRecord | undefined>(
    () => docs.find((d) => d.permalink === slug),
    [slug],
  )

  return (
    <div className="layout">
      <aside>
        <h2>docs</h2>
        <ul>
          {docs.map((d) => (
            <li key={d.permalink}>
              <button
                className={d.permalink === slug ? 'active' : ''}
                onClick={() => setSlug(d.permalink)}
              >
                {(d as { title?: string }).title ?? d.permalink}
              </button>
            </li>
          ))}
        </ul>
      </aside>
      <main>{doc ? <DocView doc={doc} /> : <p>no doc</p>}</main>
    </div>
  )
}

function DocView({ doc }: { doc: DocRecord }) {
  // velite shape: frontmatter fields are hoisted to the record root
  const fm = doc as DocRecord & {
    title?: string
    description?: string
    tags?: string[]
  }
  return (
    <article>
      <header>
        <h1>{fm.title ?? doc.permalink}</h1>
        {fm.description && <p className="lede">{fm.description}</p>}
        {fm.tags && (
          <ul className="tags">
            {fm.tags.map((t) => (
              <li key={t}>{t}</li>
            ))}
          </ul>
        )}
        <p className="meta">
          {doc.metadata.wordCount} words · {doc.metadata.readingTime} min read
        </p>
      </header>

      {doc.toc.length > 0 && (
        <nav className="toc">
          <strong>On this page</strong>
          <Toc items={doc.toc} />
        </nav>
      )}

      <MdxContent code={doc.body} components={components} />
    </article>
  )
}

function Toc({ items }: { items: DocRecord['toc'] }) {
  return (
    <ul>
      {items.map((it) => (
        <li key={it.url}>
          <a href={it.url}>{it.title}</a>
          {it.items.length > 0 && <Toc items={it.items} />}
        </li>
      ))}
    </ul>
  )
}
